### ISSUE TITLE
LINUX crash: TMPE_GlobalConfig.xml does not exist

### ISSUE THREAD

**Issue by FuJa0815** [CitiesSkylinesMods/TMPE#1002]
### Describe the problem
When loading the game, the mod crashed.
This leads to massive routing problems (as you can see with my bus stop at the train station. Without mods it works fine)

### Steps to reproduce

1. Start a game with the mod
2. Mod crashes

### Log files

[Player.log](https://github.com/CitiesSkylinesMods/TMPE/files/5183467/Player.log)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/5183473/TMPE.log)

### Savegame?

[My savegame](https://steamcommunity.com/sharedfiles/filedetails/?id=2222344338)

**Comment by FuJa0815** [comment]
PS: Crashes on stable and lab version

**Comment by krzychu124** [comment]
It's CitiesSkylinesMultiplayer breaking other mods from loading XML files. 
Fix that mod first, probably game needs to be run with elevated privileges (at least helps on Windows) or disable/unsubscribe it.

**Comment by FuJa0815** [comment]
I've tried root access, didn't work.
I thought the mod wouldn't be a problem, because it was disabled

**Comment by krzychu124** [comment]
> I thought the mod wouldn't be a problem, because it was disabled
Disabled mod is still loaded to memory so there is still possibility to break other things

**Comment by krzychu124** [comment]
Since there was no response, I assume that problem was solved. I'm closing the issue.
