### ISSUE TITLE
traffic rules not persistent when spliting segments

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1010]
![image](https://user-images.githubusercontent.com/26344691/93693265-4ab56980-fb06-11ea-822e-be53043eaa4b.png)

### Situation
when a new segment is created splitting another segment or even when a new segment is created on an existing node CS releases and recreates up to 2 segments on each side to move the nodes to a new balanced position. this is done by calling `SpitSegment()` and `MoveMiddleNode()`. all TMPE data are lost on such segments. I have added a new segment in the screenshot above to create the screenshot below:
![image](https://user-images.githubusercontent.com/26344691/93693319-e34be980-fb06-11ea-9d74-95f6747ed409.png)
note that some TMPE rules are lost. 

### some technical notes:
`SpitSegment()` and `MoveMiddleNode()` are weird and complicated. if you attach a segment to an already existing node for example as I have done in the screenshot above, `SpitSegment()`  calls `MoveMiddleNode()` to deal with one side and directly deals with the other side. as you can see in the image above only the node to one side has moved.

### Need:
TMPE data should persist when CS moves middle nodes/splits segment.

### Action:
Patch `SpitSegment()` and `MoveMiddleNode()` to copy-paste TMPE data to newly created segments. this is going to be more difficult than move it because unlike moveit, CS does not preserve invert flag or start/end nodes. Another challenge is the concept of split/merge that we might need to deal with.
This might require us to change the way data is stored which in turn might pose some backward compatibility issues.

### Plan:
in order to avoid backward compatibility issues, we might want to get it done. before the next release.
We should first conduct some tests in order to figure out all possible behavioral combinations with `SpitSegment()` and `MoveMiddleNode()` . Then plan how to persist data in such situations.

**Comment by kianzarrin** [comment]
closing as duplicate of #1228

**Comment by aubergine10** [comment]
actually closing :)
