### ISSUE TITLE
Different startup crash between linux and windows

### ISSUE THREAD

**Issue by lindesbs** [CitiesSkylinesMods/TMPE#1025]
### Describe the problem

I have build a city on my LinuxMachine. Works like a charme. Saved in cloudspace of steam. Opened next day and the game hangs immediatly after unpause the game.
When uninstalling TMPE everything works fine. It makes no difference if i install TMPE stable or labs version. On linux this savegame is not working anymore.

Starting on windows this same savegame and same mods are working.

No notifications in log file. It just hangs

**Comment by krzychu124** [comment]
Hi, this issue was already reported and it's the other variant of issue described in #817

**Comment by krzychu124** [comment]
Solved along with #817
