### ISSUE TITLE
TMPE.log Invalid segment direction detected: Turn for segments

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#103]
I've noticed that error inside TMPE.log

I think it's related with fences around industry buildings.
I don't know if it can cause bugs, but it's worth checking.

**Comment by aubergine10** [comment]
I suspect this may have been due to decorative networks showing up in default speed limits UI, which was fixed by #513.

Can this be closed or is the error still appearing?

**Comment by krzychu124** [comment]
Since then I haven't spotted any errors in the mod log file. Closing.
