### ISSUE TITLE
wrong direction of traffic at intersections

### ISSUE THREAD

**Issue by atroxactor** [CitiesSkylinesMods/TMPE#1030]
Describe the problem
incorrect directions of traffic arrows are indicated at the intersection (see the screenshot). I've seen on steam that other users have similar problems. There was no solution.. I don't have a multiple subscription.

Log files
https://drive.google.com/file/d/1Wp4Cr--cAZZmBJgtamQ9WaQ15JVqcqcA/view?usp=sharing

Savegame?
https://steamcommunity.com/sharedfiles/filedetails/?id=2277972168

Screenshots?
https://drive.google.com/file/d/1bxNaqX78U9wiQN3mD7ohItbC-KAGRxIN/view?usp=sharing
![image](https://user-images.githubusercontent.com/26344691/99072284-67c56080-25bc-11eb-93da-df92e5877397.png)

**Comment by aubergine10** [comment]
Hi - could you elaborate what the problem is? It looks like those lane connectors are correcly linking the incoming lanes to outgoing lanes. Or is it the lane arrow decals which are the issue?

**Comment by krzychu124** [comment]
Lack of response, reopen if necessary. Closing.
