### ISSUE TITLE
Service building vehicles flickering 0/1

### ISSUE THREAD

**Issue by Haxov** [CitiesSkylinesMods/TMPE#1042]
Have a city that was working fine until recently. Most of my services are not sending out their vehicles, and when selecting the building it just flickers from 0 to 1 and back. Disabling the mod fixes the issue. To my knowledge, there are no incompatible mods. 

link to map: https://steamcommunity.com/sharedfiles/filedetails/?id=2320288677
link to mods (minus TM:PE): https://steamcommunity.com/sharedfiles/filedetails/?id=2320290503

**Comment by krzychu124** [comment]
There is no single solution for this. Check out this guide: [Vehicles-not-spawning](https://github.com/CitiesSkylinesMods/TMPE/wiki/Vehicles-not-spawning)

**Comment by aubergine10** [comment]
Dedicated troubleshooting article for vehicle count flickering: https://github.com/CitiesSkylinesMods/TMPE/wiki/Vehicle-Count-Flickering-Between-1-and-0
