### ISSUE TITLE
Mod is not working

### ISSUE THREAD

**Issue by TourBinD** [CitiesSkylinesMods/TMPE#1043]
### Describe the problem
I have installed Cities: Skylines a few days ago. I want to install it but when I put its folders in CitiesSkylines -> Files -> Mods it isn't showing in game. Am I doing something wrong? I have non-steam but original version of game.

### Screenshots?

https://prnt.sc/w6zer7

**Comment by krzychu124** [comment]
Follow steps decribed here: https://github.com/CitiesSkylinesMods/TMPE/wiki/Installing-on-Origin

**Comment by TourBinD** [comment]
Thanks a lot, it works now :)
