### ISSUE TITLE
"Array index out of range" error

### ISSUE THREAD

**Issue by Klaksix** [CitiesSkylinesMods/TMPE#1050]
I repeatedly get this error and I can't understand where it is coming from... Can you help me?

_Simulation error: Array index is out of range.
at NodeController.Patches.VehicleSuperElevation.SuperElevationCommons.GetLaneInfo (PathUnit/Position&) <0x00056>
at NodeController.Patches.VehicleSuperElevation.SuperElevationCommons.GetCurrentSE (PathUnit/Position,single,Vehicle&) <0x00263>
at NodeController.Patches.VehicleSuperElevation.SuperElevationCommons.Postfix (Vehicle&,Vehicle/Frame&) <0x000b6>
at NodeController.Patches.VehicleSuperElevation.CarAI_SimulationStepPatch.Postfix (Vehicle&,Vehicle/Frame&) <0x0003d>
at (wrapper dynamic-method) CarAI.CarAI.SimulationStep_Patch1 (CarAI,uint16,Vehicle&,Vehicle/Frame&,uint16,Vehicle&,int) <0x0365d>
at PassengerCarAI.SimulationStep (uint16,Vehicle&,Vehicle/Frame&,uint16,Vehicle&,int) <0x000a9>
at VehicleAI.SimulationStep (uint16,Vehicle&,uint16,Vehicle&,int) <0x003b9>
at TrafficManager.Custom.AI.CustomCarAI.CustomSimulationStep (uint16,Vehicle&,UnityEngine.Vector3) <0x005cf>
at TrafficManager.Custom.AI.CustomPassengerCarAI.CustomSimulationStep (uint16,Vehicle&,UnityEngine.Vector3) <0x000cb>
at VehicleManager.SimulationStepImpl (int) <0x00511>
at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at VehicleManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.SimulationStep () <0x00693>
at SimulationManager.SimulationThread () <0x0018a>
  [Core]_

**Comment by krzychu124** [comment]
@kianzarrin ? 🙃

**Comment by DaEgi01** [comment]
@Klaksix you see where its coming from if you just read the text.
hint:
at **NodeController**.Patches.VehicleSuperElevation.SuperElevationCommons.GetLaneInfo

**Comment by Klaksix** [comment]
@DaEgi01 I know it's probably from the node controller mod, but can you tell me how I should fix it?
Sorry if I messed up here but I am new...

**Comment by DaEgi01** [comment]
Nah, you did not "messed up", everything is fine. You posted your mc donald's complaint to the burger king board ;D
But since @kianzarrin is here too, it does not matter that much. He is the one who will probably fix that issue.

**Comment by kianzarrin** [comment]
@Klaksix

**Comment by kianzarrin** [comment]
Does anyone know what is `<0x00056>` in the stack trace? maybe it can help me to find the line or instruction or something?

**Comment by chameleon-tbn** [comment]
Do you use skip prefab from Loading Screen mod @Klaksix ?

**Comment by Klaksix** [comment]
> 
> 
> Do you use skip prefab from Loading Screen mod @Klaksix ?

No I am not using it. Most of the mods I have are with default setting.
I do get some missing assets warning in the loading screen but they seem not related

**Comment by chameleon-tbn** [comment]
Can you please send me the output_log.txt? Please directly after the Error Message appears

**Comment by Klaksix** [comment]
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/5905257/output_log.txt)
@chameleon-tbn here it is, right after the error message popped out

**Comment by chameleon-tbn** [comment]
First subscribe all dependencies... 

**Harmony 2.0.4** is a dependency for Node controller V2.1 and Lifecycle Rebalance Revisited 1.5.2
https://steamcommunity.com/workshop/filedetails/?id=2040656402

**Hide TMPE crosswalks V3.0** is a dependency for Node controller V2.1
https://steamcommunity.com/workshop/filedetails/?id=1934023593

and second clean up your mod list....

**Topographic Lines Toggle**
Comment by creator of the mod: [OBSOLETE / PROBABLY BROKEN] Please consider using "Toggle It! by Keallu" instead. Thank you ;)
https://steamcommunity.com/sharedfiles/filedetails/?id=1764637396
And you are already subbed to Toggle It. Never use two mods doing the same

**Precision Engineering**
This mod has noticeable issues to some players, but unseen issues (behind the scenes) for all players.
It is recommended you unsubscribe from this mod and use Precision Engineering 2
https://steamcommunity.com/sharedfiles/filedetails/?id=2083188521

*RM Crossings*
several players have massve issues with it. Use Node controller instead, that you are already subscribed to.

**No Radioactive Desert And More!**
Several players have issues with it. maybe use Hide It instead
https://steamcommunity.com/sharedfiles/filedetails/?id=1591417160

**Network Extensions 2**
Causing massive issues for a lot of players. Totally outdated and there are better free available options like Vanilla+ Roads... You can't simply unsubscribe if you already have placed roads of it. You must either exchange them manually ingame oder they will be removed if you load your save after unsubscribing

**Automatic Bulldoze v3** 
Several players reported it as not working

**Touch This! Tool 4**
Not needed as you have Move it... Marque Tool - Segments - Alt+click - Del - Ctrl+Z ...

**Comment by kianzarrin** [comment]
@Klaksix do you get this bug when you load the game again?
Have you tried removing ghost nodes or broken nodes

**Comment by Klaksix** [comment]
@kianzarrin I got this error mostly during the game, when I was hovering around the city and not really doing anything. I can't remember if I also got the error right after the game was loaded, but in any case it was not the most common appearence.
I used the mod that looks for broken nodes but none was found.

Now I haven't got it again after 3 more hours of play... I was already subbed to the 2 dependencies that @chameleon-tbn indicated. I removed topographic line toggle, precision engineering and RM crossings (not the others).
Additionally I have realised that in the roundabouts (made with the popular mod) which had Radius=20 and "three-lanes one-way roads" (not highways), the arrows were not correctly displayed and i could not change them even with TMPE. I have downgraded them to two-lanes and they look fine now.

I will keep you posted if the error comes out again.

**Comment by kianzarrin** [comment]
I will soon update NC to put more info on the log file and do not bother you when this error occurs.
if you do see this error on the log file then you should use a mod called network detective to find the segment that is faulty and give me a screenshot.
then I may be able to understand what is going on
