### ISSUE TITLE
Asset Color Expander: Building color set in ACE are ignored in TMPE CustomGetColor

### ISSUE THREAD

**Issue by klyte45** [CitiesSkylinesMods/TMPE#1063]
### Describe the problem

Hi Guys! I got back to work in Skylines and I found a incompatibility issue: The color was set in the Asset Color Expander mod is being ignore in a custom GetColor method implemented in TMPE. I pointed the code conflict below.

### Steps to reproduce

1. Subscribe and activate the [Asset Color Expander](https://steamcommunity.com/sharedfiles/filedetails/?id=2140866327)
2. Load a game
3. Go to <K> button, select the ACE tab and add a new rule
4. Type of rule filter = By Service
5. Allowed service = <Any Service>
6. Then go to second inner tab (Color settings) and change the coloring mode to Color List
7. Add a color in the list by clicking "+" button
8. It should change the color of all buildings of the city to that, but it have no effect

### Log files

N/A

### Extra appointments

I took a look in the TMPE code and found where possibly is the incompatibility source: [at TMPE/TLM/TLM/Custom/AI/CustomBuildingAI](https://github.com/CitiesSkylinesMods/TMPE/blob/3ba1f2f48ab76fc8d86f93d45c8873f345a82aac/TLM/TLM/Custom/AI/CustomBuildingAI.cs#L40)

It's applying the code of the default BuildingAI behaviour, instead of call the original method. ACE uses a pre-method patch to apply the color selection: [BuildingAIOverrides at ACE repo](https://github.com/klyte45/AssetColorExpander/blob/fecdd3a7f2629c7437224fe16c6041035fc9d77f/Overrides/ACEBuildingOverrides.cs#L24)

If there's a reason for it and I need to change ACE code to add this support, let me know and I will apply it. 

Thanks!

**Comment by krzychu124** [comment]
Like we've talk on discord, it won't be an issue once #1060 gets merged. I'll add this issue to autoclose on merge 😉

**Comment by kianzarrin** [comment]
@krzychu124 is this fixed?

**Comment by krzychu124** [comment]
Weird, I thought I added this issue to autoclose after merge... (PR had closes keyword but didn't work 🤷‍♂️ )

**Comment by klyte45** [comment]
May you wrote them in list (ex: `Closes #00A, #00B, #00C`) instead of creating a entry to each? 
(ex: `Closes #00A; Closes #00B; Closes #00C`)
