### ISSUE TITLE
patcher to continue on error

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1074]
Harmony.PatchAll stops as soon as it faces the first exception.
but I think it should continue to the next patch.
I have done this in my KianCommons. I can copy this code to TMPE
https://github.com/kianzarrin/KianCommons/blob/59e0574d7433e14e667daf0680af4dce61657c96/KianCommons/Patches/HarmonyUtil.cs#L105

**Comment by krzychu124** [comment]
Hmm, I doubt is a good idea to continue patching, especially without prioritizing which patches are necessary and which optional (does not break anything when not patched)

BTW, how you handle transpiler exceptions (if you have patch with yield return)?

**Comment by DaEgi01** [comment]
I'd rather have it break if buggy than habe it continue "working" in a broken state corrupting save games in the worst case.

**Comment by kianzarrin** [comment]
@krzychu124 @DaEgi01 when there is patching error:
currently: it stops all future patches on failure and continues to the game. in-game it shows that something failed and the game might not work properly.
in PR #1076 : it continues patching on failure and continues to the game. in-game it shows that something failed and the game might not work properly.

**Comment by kianzarrin** [comment]
Sometimes there is a patch that is not so important and if it fails, the user will not be able to play the game.
so I think showing the warning dialog is a good compromise.

**Comment by kianzarrin** [comment]
> BTW, how you handle transpiler exceptions (if you have patch with yield return)?
well, my code does not manage that and I don't think that would be useful in any practical application of TMPE.
but if you really want to do that you can use Cleanup in the patch

**Comment by krzychu124** [comment]
> I am assuming this is a patch with multiple target methods.

No, a patch which does not return modified collection of code instructions but uses yield return to emit new instructions

**Comment by kianzarrin** [comment]
> @krzychu124 No, a patch which does not return modified collection of code instructions but uses yield return to emit new instructions

I don't need to know about that in patcher. harmony has a wrapper for all of those. my code will catch the exception and will continue to the next patch. harmony will not apply patch if there is error by transpiler even if it yield return instructions.

**Comment by kianzarrin** [comment]
In any case since the warning dialog tells the player that "they can continue playing but it might not work" , I think we should not have an aggressive break on failure policy.

**Comment by kianzarrin** [comment]
one good example where my code would be useful is:
```
HarmonyLib.HarmonyException: IL Compile Error ---> System.FormatException: Method System.Void LoadAssetPanel::OnLoad() cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) LoadAssetPanel:LoadAssetPanel.OnLoad_Patch2 (LoadAssetPanel): IL_0805: call      0x000001fd
```
we only need this in asset editor so there is no reason why the player cannot play the game because of this.

**Comment by krzychu124** [comment]
> we only need this in asset editor so there is no reason why the player cannot play the game because of this.

We could also skip patching that method if user is not using asset editor 🙂
