### ISSUE TITLE
"argument out of range" on different PC

### ISSUE THREAD

**Issue by Viklamvia** [CitiesSkylinesMods/TMPE#1084]
### Describe the problem
I received a savegame from others running normally on his PC. But now it got an "argument out of range" error on my both 2 PCs and failed to enter the game even with safe mode of Loading Screen Mod on. I have turned all the mods needed on.

### Steps to reproduce

1. 
2. 
3. 

### Log files
https://ufile.io/p4f3v3s9

### Savegame?
https://ufile.io/p4f3v3s9

**Comment by krzychu124** [comment]
Why reporting here? `TrafficManager` is not mentioned in the log, even better, you don't even subscribe it.
Anyways. I suspect you forgot to subscribe and enable **More Vehicles** mod

**Comment by Viklamvia** [comment]
Thanks.

**Comment by Viklamvia** [comment]
And I am sorry, I thought every bug could be reported here before
