### ISSUE TITLE
Master Branch Version Unpause Constant Error

### ISSUE THREAD

**Issue by TianQiBuTian** [CitiesSkylinesMods/TMPE#1092]
### Describe the problem
I usally building and using master branch version. But in this weekend, i used 040a5efc9dbc662d4a3857e3d8be52df968fec4a version and loaded my savegame. It had a Error. And created a new savegame, also had this Error. I turn off this version. no this Error.
### Steps to reproduce
1. Building 040a5efc9dbc662d4a3857e3d8be52df968fec4a version
2. Open the game and load OR create a new savegame
=====IN GAME=====
3. Unpause this game
=====ERROR=====
### Log files
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/6330656/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/6330657/TMPE.log)
### Savegame?
Also Had New Savegame
### Screenshots?
![20210418143632_1](https://user-images.githubusercontent.com/26628474/115137743-6829c200-a05a-11eb-91c6-82bd52d8518e.jpg)

**Comment by krzychu124** [comment]
Ok, might be `More Vehicles` compatibility regression. Need to check. Thanks!

**Comment by krzychu124** [comment]
compiled build available in #1093 should work 😉
