### ISSUE TITLE
Change language Doesn't Apply changed icon language

### ISSUE THREAD

**Issue by TianQiBuTian** [CitiesSkylinesMods/TMPE#1099]
### Describe the problem
See title.
### Steps to reproduce
=== Default is SChinese ===
![20210503174158_1](https://user-images.githubusercontent.com/26628474/116972429-93184500-aced-11eb-8168-516086cce51e.jpg)
=== Change to English ===
![20210503174251_1](https://user-images.githubusercontent.com/26628474/116972545-bd6a0280-aced-11eb-88de-e4c79152f239.jpg)
### Notes or questions?
TMPE Version: 24a7b158832b2709d312606452bcde4938eeb6dc

**Comment by krzychu124** [comment]
Thanks for reporting the issue. I'll take a look later today. 👍
