### ISSUE TITLE
No overlay

### ISSUE THREAD

**Issue by Death-Blade-RSX** [CitiesSkylinesMods/TMPE#1107]
I have played with the same dlcs and mods from the workshop and all of a sudden I booted the game up to day and the overlay has disappeared. I have tried removing and reinstalling. Any suggestions or is it a bug?

Screenshot: https://drive.google.com/file/d/1Gq9uZi5idhk2cQJcUPVh84u0W9gszrdY/view?usp=sharing

**Comment by krzychu124** [comment]
Maybe you forgot to enable the mod (_Content Manager -> Mods -> TM:PE 11.5.2_)? Share [output_log.txt and TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/wiki/Share-your-Cities-Skylines-log-file)

**Comment by Death-Blade-RSX** [comment]
The mod comes up under Workshop but not under mods. 
Output log: https://drive.google.com/file/d/1DmYMZmkPPKp8yRSa57tILQ9v3S4q_laV/view?usp=sharing
TMPE Log: https://drive.google.com/file/d/1s-9RFgAVAe4BptJ_YucWsZbJ4yDw109u/view?usp=sharing

**Comment by krzychu124** [comment]
Ok, it means that Steam didn't download it. There was mod update yesterday.
Try changing download region in the Steam client, it should trigger downloading.

**Comment by Death-Blade-RSX** [comment]
That has fixed it. Thank you for your help.
