### ISSUE TITLE
Stuck pedestrians at intersections impacting simulation speed/game performance with TM:PE.

### ISSUE THREAD

**Issue by Devieth** [CitiesSkylinesMods/TMPE#1110]
### Describe the problem
When a mass number pedestrians get stuck at intersections it can cause the simulation rate of the game to surge/slow and not function as intended.

### Steps to reproduce

1. Create and overpass with custom assets (roads, may work with normal assets.)
2. Enable TM:PE Policy that allows vehicles to turn right on red.
*2b. __(optional, makes it more consistent to re-produce)__ . Edit at least 3 individual roads connecting to the node and then the node itself with Node Controller. (Video below.)*
3. Wait for a mass number of peds to get stuck trying to cross the street.
4. Simulation speed settings will no longer work (game only runs at one speed) or simulation speed with surge at higher settings.

### Log files

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/6519997/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/6520000/output_log.txt)

### Savegame?

N/A

### Screenshots?

![Skylines - Clogged](https://user-images.githubusercontent.com/5672855/119082989-c1bc3e00-b9c4-11eb-96bf-e42d605bdffd.png)
![Skylines - Clear](https://user-images.githubusercontent.com/5672855/119082991-c3860180-b9c4-11eb-93a1-e9183971ae65.png)

### Video

https://youtu.be/tS6lbHk0Ozo

### Notes or questions?

Can be mitigated by adding elevated crosswalks, having alternate paths for the peds, and or disabling crossing at intersections like these.  

Additionally disabling the TM:PE policy that allows vehicles to turn right on red should stop this from happening entirely.

**Comment by krzychu124** [comment]
Hi,
there are two problems.
1. Citizens and cyclist cannot cross gaps between pedestrian lanes wider than 64f units (game limitation)  - 12 lanes(with 2 pedestrian lanes) road is almost 64f wide but pedestrian lane gap where highway road is connected is definitely wider than 64f.
2. Pathfinder and TM:PE should not even consider crossing those highway roads. Vanilla game does not allow citizens to cross highway roads because highway roads don't have pedestrian lanes/pavements.

**Comment by Devieth** [comment]
After noticing this one and fixing it, there were multiple other instances of it happening in my city (on a much smaller scale.) Other instances were not as bad, but were also on much smaller roads that were not connected to highway roads (bridges at angled intersections) so maybe hitting that distance limit?  

After disabling TM:PE peds will still cross at those points.

**Comment by krzychu124** [comment]
That limit can be patched, but... I'm not sure what other bugs may show up - game devs probably set that limit for a reason.

Yes, if TM:PE would work correctly in those intersections there wouldn't be an option to change pedestrian crossing setting.
I'll try to investigate why TM:PE didn't detect a "not crossable" road there.

Thanks for reporting that issue!

**Comment by aubergine10** [comment]
Added a troubleshooting guide with some interim solutions and link to this issue should others encounter same issue: https://github.com/CitiesSkylinesMods/TMPE/wiki/Cims-stuck-at-crosswalks

@krzychu124 Maybe "Broken Nodes Detector" could scan for junctions `>= 64f` in size?

**Comment by krzychu124** [comment]
Hmm, I haven't thought about that from Broken Nodes Detector 🤔 I think it shouldn't be too hard. I'll add that to my TODO list.
This version of [Node Controller Reneval](https://steamcommunity.com/sharedfiles/filedetails/?id=2462845270) fixes the problem (might be worth adding to wiki) and I think that @kianzarrin also tried to implement similar feature into his **NC** (don't remember if succeeded)

**Comment by aubergine10** [comment]
I linked the non-beta version of NC Renewal to wiki, assuming it will get updated with that fix; in interim it can still be used to shrink junction size manually.

**Comment by Devieth** [comment]
> Added a troubleshooting guide with some interim solutions and link to this issue should others encounter same issue: https://github.com/CitiesSkylinesMods/TMPE/wiki/Cims-stuck-at-crosswalks
> 
> @krzychu124 Maybe "Broken Nodes Detector" could scan for junctions `>= 64f` in size?

This only seemed to affect pedestrians, traffic is unaffected (the screenshot was captured during a light cycle.)  Large roads with diagonals trigger it (in conjunction with changes made with node controller, but only with TM:PE present.)  Road type does not, highways not having crosswalks don't seem to be an issue (in the city I reported this on), pedestrians cross anyway at non-broken intersections.

Another solution for users is to disable crosswalks at offending intersections and provide alternative paths for pedestrians.

**Comment by aTadnMad** [comment]
all of this requires you know the problem exists; generally, you just stumble upon it.  i have a city of 800,000 cims.  Vast city.  I've literally spent hours searching the map, looking for these stuck cims.  I know they're somewhere.  Reset Stuck Cims makes the game run normal ... for a little while.  but, i can't find the damn node causing the issue!  i know exactly why it's happening, too - the node is too large.  broken node detector does not appear to account for over-sized nodes (over-sized for pedestrians to cross).  once you find this node, and using node controller, make it smaller by dragging the coloured circles.  but, when you have a city this size, searching for that elusive node is tedious.  There needs to be a way to detect these nodes.

**Comment by krzychu124** [comment]
Solved by #1610, will be released with the [**v. 11.6.6.0**](https://github.com/CitiesSkylinesMods/TMPE/milestone/65)
