### ISSUE TITLE
Speed & Red Light Cameras

### ISSUE THREAD

**Issue by vtomic85** [CitiesSkylinesMods/TMPE#1119]
### Describe your idea

I propose introducing speed cameras and/or red light cameras which will detect the law breakers and generate additional income for the city.

### Screenshots?

None

### Notes or questions?

Possibly some additional development would be needed to make the AI cars drive against the law.

**Comment by krzychu124** [comment]
Requires a lot of work. maybe in the future.

Similar to #1045

**Comment by aubergine10** [comment]
Tracked in: #67
