### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by 2winners** [CitiesSkylinesMods/TMPE#1123]
A Mod caused an error [ModException]

Details:
System.IndexOutOfRangeException: Array index is out of range.
  at OptionsMainPanel.AddUserMods () [0x00000] in <filename unknown>:0 

when placing the .DLL files in the mods folder when i open the game i get the above error message oke after turning off other mods. no error.

when entering new game new error shows up
Traffic Manager: President Edition failed to load. You can continue playing but it's NOT recommended. Traffic Manager will not work as expected.

Field '.PathUnit.m_vehicleTypes' not found. [System.MissingFieldException]

Details:
No details

bastiaan

**Comment by krzychu124** [comment]
Buy the game.

**Comment by DaEgi01** [comment]
You could make it a in your face popup you know? ;D

**Comment by krzychu124** [comment]
That error breaks the game, might be enough 😉
