### ISSUE TITLE
Lane arrow and lane connector assignments not workign after save load

### ISSUE THREAD

**Issue by Karnor** [CitiesSkylinesMods/TMPE#1146]
### Describe the problem

I've only just noticed this happening in the last day but may have been going on much longer.

All of the lane arrow assignments I make using TM:PE are reset when I load a save game. So for example where I set a 6L arterial road to have dedicated lanes for left, straight and right, when I load the save they have reverted to left/straight, straight and right/straight on every road. Similarly a 4L I set to left/right, and right, are reset to left/straight and right/straight when I load the game.

Also the lane connector assignments are acting weird. They still have the coloured lane connectors laid out how I set them up, but the actual lane arrows which they should be controlling do not comply.

So for example, I have a junction connecting a 4L avenue with a 6L avenue and a 1L1W road connecting to the left and right sides of the junction, essentially mimicking a standard highway intersection with on/off ramps. There is a lane connector linking the right lane of the left carriageway on the 4L avenue to the right lane in left carriageway of the 6L avenue, which is how I set it up before the save.
But the lane arrow in the right lane of the 4L avenue is right/straight, allowing the traffic to go straight on to the 6L arterial road, but also turn right across the 4L avenue into the 1L1W road on the right side of the junction, which is wrong, the lane arrow should be just straight ahead.

### Steps to reproduce

**How to trigger lane arrow problem**
1. Assign any lane arrows on a junction to whatever you want
2. Save game
3. Exit game
4. Restart game
5. Reload save game
6. Observe that the lane arrow assignments are not how you set them in step 1

**How to trigger lane connector problem**
1. Connect a 4L road to a 6L road with 1L roads joining the junction on the side of the 4L (i.e. standard intersection employing lane maths)
2. Assign lane connectors on the 4L road to ensure that the lanes can only go straight ahead to the 6L road
3. Save game
4. Exit game
5. Restart game
6. Reload save game
7. Observe that the lane connectors are still as you set them in step 2
7. Observe that the lanes on the 4L road can now turn right/left across the 4L road to the 1L off ramp on the side of the junction

### Log files
Please find the log files in the same google drive folder that contains the screenshots

### Savegame?
[Save game](https://steamcommunity.com/sharedfiles/filedetails/?id=2572724942)

### Screenshots?
[screenshots showing both the lane connector and lane arrow bugs](https://drive.google.com/drive/folders/1j8YPepyyTxXidop6NNqR_I0AsIimgIhm?usp=sharing)

### Notes or questions?
The junction where the savegame opens is a prime example of the lane connector bug, check either side of the sunken 4L avenue where it joins the 6L avenue. You'll see the lane connectors and lane arrows for the 4L avenue do not match.

An example of the lane arrows bug can be found quickly if you follow the 6L road on that same junction back towards the Harlesden district. Go to the 4 road junction, and you'll see the 6L roads on the junction do not have dedicated turn lanes, but they should do because I set them up as such, and then saved the game.

As it stands, this bug is making the game tedious to play, and as the city gets larger it will become unplayable as there will be far too many junctions to constantly check and reset every time I load the game.

**Comment by krzychu124** [comment]
Hello, I can reproduce the issue. I loaded your savegame and here is the result

![image](https://user-images.githubusercontent.com/19638970/129409819-f19b126d-a23a-437f-ba92-eb824e39ca49.png)

same for lane connector 😕 

![image](https://user-images.githubusercontent.com/19638970/129410008-9a877e76-bd6e-4245-b85b-e7af404d5c25.png)

**Comment by Karnor** [comment]
It was happening all the time, then yesterday I loaded the game and no problem. But today I loaded the new save game, and again it happened.
However I only had to nudge one junction to fix the problem across the whole map which makes no sense, so I'm wondering now if it's just a really really slow update process going on.
I'll check again tonight and get back to you.

**Comment by Karnor** [comment]
Right I've sussed it, and can't believe I've never seen it before. So when I load the savegame, I have my system default to paused.

Because this time I was specifically looking for it, having waited a few minutes with no updates happening, I took the game of pause to see if that changed things, and sure enough the junctions all updated instantly in front of my eyes.

I never realised that was the behaviour before, so I'm sorry for wasting your time, I'll close the bug.

**Comment by krzychu124** [comment]
That behaviour depends on mods you use. 
TM:PE in combination with mods like IntersectionMarkingTool or NodeController requires the game to simulate at least one frame to reapply modifications, because they request update nodes/segments where custom settings were applied (intersection markings or node corner adjustments) - probably minor load/processing order issue.

**Comment by aubergine10** [comment]
Added troubleshooting guide: https://github.com/CitiesSkylinesMods/TMPE/wiki/Lane-arrow-and-connector-not-loading
