### ISSUE TITLE
What's new!

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#118]
I think it would be nice to show dialog after mod update (One time only like similar to that after game dlc release).

Currently user has no idea which workshop item was updated(or I am wrong 😄 )

I'm thinking about creating something like this to point main issues which where resolved and notify user about new content and other things.

What do you think?

**Comment by aubergine10** [comment]
When the TAM mod was being developed there was a feature that could pop-up a window (complete with those stars as seen on the milestone unlock window) and it would list new features.

However, it would be a chore keeping it up-to-date and might become irritating for users, especially on bugfix-only releases.

That being said, I'd certainly be interested to see it in action - this new TM:PE is becoming increasingly professional (eg. incompatible mod checker) and with the huge list of features we've got planned there will be plenty to celebrate as the mod develops.

**Comment by krzychu124** [comment]
Good point with that it might become irritating for users but on the other hand we won't release patches every day.
I've an idea how to 'pop-up' a window only when important changes has been made and skip those with minor bug fixes 😉

**Comment by aubergine10** [comment]
Just make sure it has those sparkly star things when the window pops up :)

Can probably find them by looking at the code responsible for ```UnlockingPanel``` (easy to show that by enabling the "unlock all" vanilla mod then start a new game).

**Comment by aubergine10** [comment]
muust have sparkly stars....

:D

**Comment by krzychu124** [comment]
I will spam whole screen at first release 🤣

**Comment by ntoff** [comment]
>Currently user has no idea which workshop item was updated(or I am wrong 😄 )

Yeah, that bugs me, I'll see "cities skylines workshop content updated" in steam and be like "ok, well? what updated?" I wish steam in general would give more info.

>However, it would be a chore keeping it up-to-date and might become irritating for users, especially on bugfix-only releases.

Make a user setting "never show update news" and a user can opt out of seeing the updates if they want.

**Comment by aubergine10** [comment]
BTW, you can find out what's been updated in Steam:

1. Go to workshop tab
2. Under **Your Workshop Files** choose **Your Files > Subscribed Items**
3. In the right sidebar change **Date Subscribed** to **Date Updated**

> Make a user setting "never show update news" and a user can opt out of seeing the updates if they want.

Yes, good idea!

Although... the current settings system seems hardwired to only save to savegames, not global (which always confused me). The options screen needs updating to not render options that are save-game specific (or, better, allow global defaults to be set).

The options system used in RealTime mod provides that capability if memory serves.

**Comment by aubergine10** [comment]
Tagging #420

**Comment by krzychu124** [comment]
@aubergine10 how we are going to populate version log? 
 - internal file like for incompatible mods (txt), 
 - parsing CHANGELOG.md (doable) and automated deployment to releases via Appveyor?
 - other? 
 Should we divide it per Stable - Test? Group by type (added/fixed/updated/other...)? I need tiny, ugly mockup if possible 😄

**Comment by aubergine10** [comment]
IMO it should be hand-crafted per release, and the focus should be on stable releases (can be done for test too, but only if not too much work). We don't want a massive list of all the atomic changes; users just want a _summary_.

An example for 11.6 release might be something like:

> * New speed limits panel and icon themes
> * Default speeds massively improved
> * New roundabout policies in settings
> * New dedicated turning lanes policy in settings
> * Map/Asset editor support
> * Accurate lane connector lines
> * Move It! mod integration
> * New languages: Arabic, Indonesian, Slovak, Thai
> * Pathfinder can use more threads on modern CPUs
> * 100+ bug fixes and performance improvements

And it needs to be as super-simple to maintain as possible.

**Comment by aubergine10** [comment]
BTW, I think this should be implemented and introduced with the 11.6 release, if possible. (I know we're in code freeze, but it's so long overdue and 11.6 is a big release...)

**Comment by krzychu124** [comment]
Thanks. Yes, I'm working on it so we could test it before 11.6, eg. on TEST

**Comment by kvakvs** [comment]
Corporate client i'm working with, require a CHANGES line with a closed ticket. The CHANGES line goes into the CHANGES file which is then released to the customers. It should be a 1-3 line description of what changed from the end user point of view.
