### ISSUE TITLE
TMPE connections is not restablished after removing lane connection

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1198]
> Milestone update: This was partially fixed in v11.6.2 as shown in changelog, but [additional issue was identified](https://github.com/CitiesSkylinesMods/TMPE/issues/1198#issuecomment-1127964194) which will be fixed by #1550 in v11.6.6.0. As such the milestone for this issue has been updated to 11.6.6.0.

I tested TMPE lane connections on Train Network using AR(Adaptive roads) mod and HUT mod(Hide unconnected tracks).
AR gets connections from Routing Manger
HUT gets connections from Lane Connection Manager.

when I create remove the red connection
![image](https://user-images.githubusercontent.com/26344691/142949610-eac965fe-21a9-41e8-9273-23dc62cbcfb5.png)
AR shows this : tracks not reconnected which is indicates a bug:
![image](https://user-images.githubusercontent.com/26344691/142949631-63e9d978-d9c7-44b9-9301-f0cd65642084.png)
HUT shows this : tracks VISUALLY (But not really) reconnected as expected:
![image](https://user-images.githubusercontent.com/26344691/142949631-63e9d978-d9c7-44b9-9301-f0cd65642084.png)

This means Lane Connection manager rightfully removes the lane connection data but routing manager does not.

To prove that the problem is with TMPE and not with AR I tested it with train stops:
![image](https://user-images.githubusercontent.com/26344691/142949805-32d27fd6-1c23-4b06-85e7-4577f83efe34.png)
in the picture above I cannot make a stop which means even though I removed the lane connection, The tracks did not get reconnected.

Note: If I force node update using MoveIT or if I create another lane connection on another segment, the track data will update correctly.

Note2: when I add lane connection on train tracks, I notice in the log that LaneArrowManger is updated. but when I remove tracks LaneArrowManager is not updated. I am not sure if LaneArrowManager is relevant for train networks or if this is somehow relevant.

Need: routing manager should reconnect tracks after I remove lane connection

**Comment by krzychu124** [comment]
Did you post 3 exact same screenshots? I don't see any difference 🤔

**Comment by kianzarrin** [comment]
oops bad image!!! I must have made a mistake when I pressed Control+C . in any case it is fixed

**Comment by kianzarrin** [comment]
This is still not resolved. we need to update lane connections for all the segments in the node not just source/target segment.
