### ISSUE TITLE
set dead ends for lanes using lane connector

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1213]
There should be a mechanism in lane connector to set a lane connected to nothing. This is particularly useful for station tracks or other bidirectional lanes.

I suggest if we connect the lane to itself, it will act as a dead end.

This is also useful for AR tracks to look nice.

**Comment by aubergine10** [comment]
Is this an alternate to the directional lane connectors for `both` direction lanes, or some other purpose? Could you elaborate on the use cases?

**Comment by kianzarrin** [comment]
@aubergine10 So in the train station bellow there are 2 unnecessary tracks which I have marked with blue arrows:
![image](https://user-images.githubusercontent.com/26344691/144687603-28c5991c-d991-4b35-9fd3-d82c3e2b3f7c.png)
I created the network using Adaptive-Network mod.

**Comment by aubergine10** [comment]
I see. When you say "connect lane to itself" is that from a user-interface perspective or back-end data perspective? If user-interface, I think I'd find that confusing and also suspect it would be accident prone (eg. if user accidentally creates dead end and doesn't realise how to un-do that).

Maybe if user has selected the outgoing lane (visually: wire being dragged by mouse) they could press a shortcut key and the 'source' circle would turn in to a stop / no-entry sign? To remove stop sign either, while lane is selected: a) press key again, or, b) connect it to another lane.

**Comment by aubergine10** [comment]
Thinking further, if we had a stop/no-entry icon to indicate when unconnected lane is prevented from connecting to anything, could we also have a `*` icon to indicate that an unconnected lane will follow vanilla connection rules? That would illustrate to user a) which outgoing lanes don't have connection and b) what will happen as a result (either no-entry or vanilla routing, as applicable).

**Comment by kianzarrin** [comment]
![image](https://user-images.githubusercontent.com/26344691/169640261-ce0efc2e-d251-4145-ac93-b34863b32736.png)
what should happen if lane has no arrows?
should it be a dead end? currently it is as if it is forward.

**Comment by aubergine10** [comment]
I assume the current implementation defaults to 'forward' when no arrows primarily because we had no concept of 'dead end' when it was implemented.

However, if we add concept of 'dead end', that would be a better default. We'd ideally need additional visual cue to user to illustrate that, eg. a red bar (rectangle) overlay at the end of the lane?

**Comment by kianzarrin** [comment]
there are 2 ways to create dead end:
1- user connects a lane to itself (specially useful for tracks)
2- user removes lane arrows.
That second part might conflict with NC that removes lane arrow flags if all lanes go forward.
