### ISSUE TITLE
tranaparency option works inconsistently

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1216]
these don't respect overlay when selected:
![image](https://cdn.discordapp.com/attachments/545066674605391882/916954805430280212/unknown.png)

they respect overlay transparency only if the node is not selected:
![](https://cdn.discordapp.com/attachments/545066674605391882/916955878865903666/unknown.png)

but in other tools even when the node segment is selected they are still transparent:
![](https://media.discordapp.net/attachments/545066674605391882/916955878865903666/unknown.png)
![](https://cdn.discordapp.com/attachments/545066674605391882/916956384619266068/unknown.png)

**Comment by kianzarrin** [comment]
in my specific use case I want to create a tutorial about how changing TMPE rules changes props. but since these signs are blocking my view it is harder to do so.

**Comment by krzychu124** [comment]
I was done like this because at high transparency values signs you will have no idea what is editable and what's not.
