### ISSUE TITLE
Can't vert scroll keybinds tab

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1222]
Noticed while testing in PR #1168 ( https://github.com/CitiesSkylinesMods/TMPE/pull/1168#issuecomment-987510170 )

![image](https://user-images.githubusercontent.com/1386719/144956993-195175e9-4807-461d-9c68-8d2fa30f95d7.png)

The reference branch where this problem appears is here: https://github.com/kvakvs/TMPE/tree/u-speedlimits-tool-feature-creep

**Comment by kianzarrin** [comment]
yeah when I designed the Scroll I ignored this tab as it was so complicated.
its just a matter of setting that page size though

**Comment by krzychu124** [comment]
Already fixed in https://github.com/CitiesSkylinesMods/TMPE/pull/1576/commits/80bbd4c27ecd2430694c7cb22ee8b5c2e1df9d16 and released in the `11.6.5.3`
