### ISSUE TITLE
Speed tool - reset to default setting wrong speed

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1226]
Note: I'm using current build from PR #1215

### Describe the problem

I've customised default speed for a road, then set custom speed overrides for that road. When I reset to default, the resulting speed is shows an override speed which is slower than the customised default speed.

### Steps to reproduce

1. Set default speed of a road to something other than that defined in prefab - in my case, 30 mph
2. Set override speed to, say 10 mph faster - in my case, 40 mph
3. Use the reset to default tool to try and put road back to the speed set in 1 above
4. It's not giving me that speed - in my case, 20 mph

### Log files

can provide on request

### Savegame?

can provide on request (crazy number of assets + mods)

### Screenshots?

The road is has custom override speed of 40 mph:

![image](https://user-images.githubusercontent.com/1386719/145538474-2101b290-a34c-437c-8aa9-2001445fc0aa.png)

It's customised default speed is 30 mph:

![image](https://user-images.githubusercontent.com/1386719/145538424-7bfed502-356f-4d9e-a91b-b85dd441866d.png)

When I reset to default:

![image](https://user-images.githubusercontent.com/1386719/145538674-c4b7fbde-c091-40c7-8cb2-2454719e1649.png)

The resulting speed is showing as customised 20 mph.

![image](https://user-images.githubusercontent.com/1386719/145538787-5920e024-6b0e-49d0-b6a9-97f926afdebb.png)

### Notes or questions?

IIRC the workshop asset speed for this road is 20 mph. Maybe "reset to default" is setting to prefab speed rather than my modified default speed?

Road I'm using is "2 Lane, 2 Way, 15m: No Parking with Bike Lanes" from [UK Small Roads](https://steamcommunity.com/sharedfiles/filedetails/?id=1601040013)

**Comment by kvakvs** [comment]
Its a bug
Reason: I believed that entire road including slopes and other parts of the same netinfo all have same name. They don't all have same name. Setting default speed limit correctly sets override for all affected netnames. Deleting default speed limit override only does it for the clicked road netinfo name.
Example: "Small rural highway" and "Small rural highway slope" are same road but different netinfo names.
I'll come up with a reasonable good fix.
