### ISSUE TITLE
Test compatibility with Airports DLC

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1230]
https://store.steampowered.com/app/1726380/Cities_Skylines__Airports/

> The Airports expansion allows you to build your own airport areas, set up gates and connect them via concourse networks. Design your dream airports, from small airfields to large international hubs.

**Comment by krzychu124** [comment]
TMPE will require an update because of a breaking change in one of vanilla methods we are patching.

**Comment by aubergine10** [comment]
Fixed in #1305
