### ISSUE TITLE
Clarification on some mod options

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1234]
I'm updating all the wiki pages, and am currently going through the various options screens - there's a few things that I'm unsure about...

## Policies tab

At junctions:

* ~~**Vehicles may turn at red traffic lights** - what kind of traffic lights? does it work with TTL? (so far I've only tested with vanilla TL)~~
    * Works on both
* **Also apply to left & right turns between one-way streets**:
    * I assume this is automatically applied to all junction road that have enabled "turn on red"?
    * As such, is its effect limited to allowing, in addition, a far-side turn in to a one-way road? (a near-side turn in to a one way road would already be covered by the main "turn at red traffic lights" option, given that needs to be enabled for the one-way policy to have any effect)
* **Vehicles follow priority rules at junctions with timed traffic lights**:
    *  What specifically does this do / how does it change traffic a the junction?
    * [Old docs](https://tmpe.viathinksoft.com/wiki/index.php?title=Vehicles_follow_priority_rules_at_junctions_with_timed_traffic_lights) state that it can be used to "realise unprotected turns" - but isn't that what newer **Turn on Red** does?
*  ~~**Dedicated turning lanes** - what does this do/affect?~~

On roads:

* **at a segment to segment transition, only the smaller segment gets crossings**:
    * Is this automatically applied to all transition nodes?
    * What happens if both roads are same size? Does it still remove one crossing?

Roundabouts:

* **Put parking ban inside roundabouts**:
    * I assume "inside roundabouts" refers to the actual roundabout itself (the one-way roads)?
    * If so, would it be better named: "Ban parking on the roundabout"

## Overlays tab

* **Connected Lanes** - could this option be renamed **Lane connectors** ?

**Comment by kianzarrin** [comment]
> at a segment to segment transition, only the smaller segment gets crossings:  Is this automatically applied to all transition/stretch nodes?

stretch nodes is not a vanilla concept. only for node controller. and in node controller stretch nodes do not have crossings enabled/configurable.

>What happens if both roads are same size? Does it still remove one crossing?

I am not sure about normal node when both segments have same size (forgot my code!). might randomly turn off one segment.


>  Put parking ban inside roundabouts:
I assume "inside roundabouts" refers to the actual roundabout itself (the one-way roads)?
If so, would it be better named: "Ban parking on the roundabout"

yes

**Comment by aubergine10** [comment]
closing - got all the info now; wiki updated
