### ISSUE TITLE
Regression: Auto TTL sets-up dedicated turning lanes improperly

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1241]
Auto-TTL allocates dedicated far turn. but the way it is setup, it needs dedicated near turn.

**Comment by kianzarrin** [comment]
I have am testing a short fix for this:
dedicated turning lanes to be setup based on "ban traffic on bus lanes" policy when setting up TTL or when using the dedicated turning lanes shortcut in Lane Arrow Tool.

**Comment by kianzarrin** [comment]
related #1106

**Comment by kianzarrin** [comment]
![image](https://user-images.githubusercontent.com/26344691/146798014-633af9e3-e0c5-42f6-a9ff-c7499f2e384c.png)

here is my test setup (i added lane arrows to some of the bus lanes hence the assets): 
[test-bus-lanes.zip](https://github.com/CitiesSkylinesMods/TMPE/files/7746559/test-bus-lanes.zip)

**Comment by krzychu124** [comment]
@kianzarrin Have you seen that report? Maybe you could fit a bugfix in the PR (it looks like tiny bug somewhere in auto-tl code)? https://steamcommunity.com/workshop/filedetails/discussion/1637663252/3200368477539744008/
