### ISSUE TITLE
Imrpove detecting elevations when setting "per road type" speed limits.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1245]
Topic: what is considered a road type when changing default speed limits per "road type". 

Definitions:
- Elevations: when you select a road, you can use page-up/page-down to use ground/elevated/bridge/tunnel/slope. each one of these is called an elevation of the road.
- Basic Road: almost always the ground elevation. some custom assets have only one bridge elevation (can't remember from top of my mind) in which case that single elevation is considered the basic elevation.
- Road type: open for discussion! But loosely speaking the basic road and all its elevations (although the Note bellow makes this a bit more complicated)

Note: some vanilla roads share elevations. for example "Large Road with parking" and "Large road with trees" share the same elevation which does not have parking or trees. Asset editor does not provide any mechanism for asset creators to do this so currently WS assets always have a 1:1 correspondents between basic elevation and other elevations.

Situation:
Currently Speed limit manger uses name comparison as the criteria to match different elevations together. this method is flawed. We need a better way of doing this. I have written a code to get the elevations from member fields of the `NetAI` such as `m_elevatedInfo`, ... .

What is considered a road type?
in [my current code](https://github.com/CitiesSkylinesMods/TMPE/tree/RoadFamily): If two roads share the same elevation then I consider them the same road type. (see note above), then they are considered the same road type.  fore example  changing the speed limit of "Large Road with Parking" also changes the speed limit of "Large road with grass/trees" in addition to all the elevations. i think this is the only way that we can consistently change speed limits. 

Does everyone agree with this?

**Comment by aubergine10** [comment]
The new default speeds stuff @kvakvs has done is such a massive improvement on the old UI that I doubt anyone would be annoyed if it didn't apply the default speed to all elevations. It's so much easier now to _see_ and _set_ default speeds that user is only a couple of clicks away from changing default sfor any prefab.

If trying to link in the elevations is going to take time, just comment that code out for now and get 11.6 released. We can always add a mod option later "Default speed limits apply to all elevations" (and explain how that might affect shared elevations).

**Comment by kvakvs** [comment]
I already have cherry-picked Kian's suggested change, we should be fine for now. This needs a quick test in #1233

**Comment by aubergine10** [comment]
About to test, will report back on the PR if I find any issues

**Comment by aubergine10** [comment]
Can this be closed now that #1233 is merged?

**Comment by aubergine10** [comment]
> What is considered a road type?  
> in my current code: If two roads share the same elevation then I consider them the same road type. (see note above), then they are considered the same road type. fore example changing the speed limit of "Large Road with Parking" also changes the speed limit of "Large road with grass/trees" in addition to all the elevations. i think this is the only way that we can consistently change speed limits.

This has been implemented via #1233 - closing.
