### ISSUE TITLE
Localised "give way" (yield) and "priority" signs for `gb`

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1251]
### Language name or ISO code

* `gb` (or `en`?) - England
* `cy` - Wales (Cymru)

### Localization file

SVG's in attached zips. They aren't 200x200 px - I'm not sure how you want to resize/export them for best quality.

* [gb.zip](https://github.com/CitiesSkylinesMods/TMPE/files/7759636/gb.zip)
* [cy.zip](https://github.com/CitiesSkylinesMods/TMPE/files/7759635/cy.zip)

Contents:

* Give Way (yield)
* Priority over oncoming traffic (priority - or closest thing we have to it) - identical for `gb` and `cy`

The existing Stop sign icon is practically identical to those used in UK.

### Notes or questions?

The files are both from UK government agency under Open Government License 1.0:

* Give way (TSRGDNO 602) - author: TSRGD - license: OGL 1.0 - source https://commons.wikimedia.org/wiki/File:UK_traffic_sign_602.svg
* Priority over oncoming traffic (TSRGDNO 811) - author TSRGD - license: OGL 1.0 - source https://commons.wikimedia.org/wiki/File:UK_traffic_sign_811.svg

I've also added a page to the wiki (and linked from the various other localisation pages) for priority sign themes: https://github.com/CitiesSkylinesMods/TMPE/wiki/Priority-Signs-Icon-Themes

**Comment by kvakvs** [comment]
Added right of way sign to PR 1260

**Comment by aubergine10** [comment]
Yeah, I removed the `cy` from title, if someone wants to add Welsh langauge at later date we can easily create a welsh icon theme at that point.

As for "Priority over oncoming vehicles" sign.... I'm having second thoughts on using it to denote "priority route" because it's actual purpose is to help traffic decide who is safest to navigate around an obstacle/choke point (narrow bridge, traffic calming, roadworks, etc) _within_ a road, for example:

![image](https://user-images.githubusercontent.com/1386719/147864096-32f78d48-f3cd-4130-b8d8-ac0c748772a0.png)

It's _never_ used at junctions. I was just scrambing for a UK-ish sign to represent "Priority", but there isn't one... In UK signage parlance, we wouldn't give one group special privileges (ie. dominance) at a junction. Instead, we'd just ask the other groups to temporarily wait (ie. be polite) to help reduce traffic congestion, and even then our first choice would be a humble "Passing Place" sign in many cases. There are other similar things, such as Urban Clearway, double red lines at edge of road, etc., but those are more about "no stopping" (ie. be polite; don't cause congestion) rather than "Priority" (ie. dominance).

So the correct sign for "Priority" in UK is actually.... no sign. But "no sign" doesn't really work from a UI perspective heh. I think that's why we inveted traffic lights.

> The world's first traffic light was a manually operated gas-lit signal installed in London in December 1868.

Wiki article should note that it was to prevent recursive civil wars over who has right of way at junctions at the weekly parish council meeting.

Maybe we could use some complete random sign instead?

![image](https://user-images.githubusercontent.com/1386719/147864292-33930bc7-7d22-46fe-b659-4a58d3e2c8a0.png)

**Comment by kvakvs** [comment]
Missing sign will be rendered as default 🔶🔻🛑
I wouldn't want to localise it to every language like in Japan/Canada/France, the EU signs are quite universally understood
Indonesia doesn\t have right of way, but they have a diamond yellow sign with very close meaning, so i used that

**Comment by aubergine10** [comment]
Just use the default yellow diamond for UK theme in that case.
