### ISSUE TITLE
Can you please release this mod on cities-mods.com

### ISSUE THREAD

**Issue by bolandnick18** [CitiesSkylinesMods/TMPE#1257]
Can you please release this mod on https://cities-mods.com/xlex/categories/cities-skyline.53/ so others users can enjoy it as well

**Comment by aubergine10** [comment]
People can always get latest released versions from this URL: https://github.com/CitiesSkylinesMods/TMPE/releases

**Comment by krzychu124** [comment]
I've never seen that side before and also why on the site with a typo in game name 🤣
Follow the link posted by @aubergine10 😉

**Comment by bolandnick18** [comment]
I don’t thing people will download the link from GitHub and also the game name is current as I am aware!

**Comment by aubergine10** [comment]
@bolandnick18 It would be better for you to automate it on your end - GitHub has an API so you can use that to check for releases and download the files (see `browser_download_url` in the API examples) then upload to your site: https://docs.github.com/en/rest/reference/releases
