### ISSUE TITLE
Compatibility with Extended Managers Library `81 Tiles` implementation

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1259]
Quistar has started work on an EML implementation of 81 Tiles:

https://steamcommunity.com/sharedfiles/filedetails/changelog/2696146165

I notice in merged PR #1112 that there were some changes for 81 Tiles, and assume the EML mod will have same area, but flagging just in case any additional changes required.

**Comment by krzychu124** [comment]
Honestly I think we can completely remove that patch, because BP updated `81 tiles` with the values - changes are no required if <= 25 tiles.

**Comment by krzychu124** [comment]
No changes required.
