### ISSUE TITLE
Auto-select speed limit icon theme based on chosen language?

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1261]
### Describe your idea

After PR #1260 is merged, we'll have enough speed sign themes to give a rough match to the style used by most countries.

Could we auto-select theme based on mod language? But only while in-game _if_:

* current theme is `null` or invalid
* mod language changes (either by mod settings or, if user selected Game Language, when game language changes)

> Doing it in-game reduces chances of language mods kicking in post-TMPE activation during cities.exe startup thus causing repeat language change events.

While not perfect, it increases liklihood of users getting a theme that they are familiar with and of course they can manually override it at any time via the theme setting.

Based on what I've seen of the available themes so far, I've concoted this first attempt at mapping language codes to country-specific themes:

```
                Dictionary<string, string> {
                    { "ar", KMPH_GERMANY_THEME }, // Arabic
                    { "en", MPH_US_THEME }, // English / DEFAULT_LANGUAGE_CODE
                    { "zh", KMPH_GERMANY_THEME }, // Chinese Simplified
                    { "zh-tw", KMPH_GERMANY_THEME }, // Chinese Traditional
                    { "cz", KMPH_GERMANY_THEME }, // Czech
                    { "nl", KMPH_FRANCE_THEME }, // Dutch
                    { "en-gb", MPH_UK_THEME }, // English, United Kingdom
                    { "fr", KMPH_FRANCE_THEME }, // French
                    { "de", KMPH_GERMANY_THEME }, // German
                    { "hu", KMPH_GERMANY_THEME }, // Hungarian
                    { "id", KMPH_INDONESIA_THEME }, // Indonesian
                    { "it", KMPH_FRANCE_THEME }, // Italian
                    { "ja", KMPH_JAPAN_THEME }, // Japanese
                    { "ko", KMPH_KOREA_THEME }, // Korean
                    { "oc", KMPH_FRANCE_THEME }, // Occitan
                    { "pl", KMPH_FRANCE_THEME }, // Polish
                    { "pt", KMPH_GERMANY_THEME }, // Portuguese
                    { "ro", KMPH_FRANCE_THEME }, // Romanian
                    { "ru", KMPH_FRANCE_THEME }, // Russian
                    { "sk", KMPH_FRANCE_THEME }, // Slovak
                    { "es", KMPH_FRANCE_THEME }, // Spanish
                    { "th", KMPH_FRANCE_THEME }, // Thai
                    { "tr", KMPH_FRANCE_THEME }, // Turkish
                    { "uk", KMPH_FRANCE_THEME }, // Ukrainian
                };
```

EDIT: I know, like, a French-speaking Canadian is going to get the completely wrong theme, but...

**Comment by kvakvs** [comment]
Users might be building a map in a different country than theirs. But on language change we could provide a non-modal popup, which would look like
![bild](https://user-images.githubusercontent.com/288724/147849494-c94869fb-98f9-45f3-aca4-47615e768aff.png)

**Comment by aubergine10** [comment]
yup, it's a flawed idea - closing
