### ISSUE TITLE
when toggling a road lane connections are only visual

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1270]
when we invert segment, lane connections stay there but I don't think they actually work
before VS after invert:
![image](https://user-images.githubusercontent.com/26344691/147991173-597af27f-a7b4-43f8-a07c-472bf00b89e8.png)
![image](https://user-images.githubusercontent.com/26344691/147991183-4da18fd0-2262-44be-a6ff-429df32220b1.png)
Adaptive Networks mod uses TMPE lane transitions to determine U-turn on lane. so this indicates that TMPE lane transitions have ignored the lane connection.

the u-turn overlay might also be misleading:
![image](https://user-images.githubusercontent.com/26344691/147991186-f7b6f77d-ad14-4988-934a-382e00b0a156.png)

**Comment by aubergine10** [comment]
Maybe nuke the affected customisations but play "bulldozer dust" effect over the junction to let user know their change just nuked some customisations?

**Comment by kianzarrin** [comment]
Wait this only happens if I toggle with Network detective. it won't happen if I toggle with the Vanilla toggle tool.
therefore I am closing this issue.
