### ISSUE TITLE
Array index is out of range. [System.IndexOutOfRangeException]

### ISSUE THREAD

**Issue by lemuelmpranoto** [CitiesSkylinesMods/TMPE#1271]
Hello,

I am building my city on a custom map called Seahorse Islands Archipelago (https://steamcommunity.com/sharedfiles/filedetails/?id=2238464694&searchtext=) and I have downloaded all the required assets and items to load the map properly. Everything was fine and I was able to load the game properly during startup until one day, I loaded the game and the array index error popped up. I tracked down which mod/mods caused the error and turns out TM:PE is the one solely causing the error. I have the latest stable version of TM:PE and my game is purchased from Epic Games. I was suspicious of any broken assets so I tried to remove all assets I downloaded from the Steam workshop but the error still retain. Any help would be much appreciated. Thank you!

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/7808563/output_log.txt)
![Screenshot (681)](https://user-images.githubusercontent.com/43080048/148082329-ec344e98-f87a-4f3a-bddf-4f43fc72808a.png)

**Comment by lemuelmpranoto** [comment]
[UPDATE]
I managed to find the errors inside the log file but I can't seem to understand where the problem lies, do anyone mind interpreting it for me? Thank you
![image](https://user-images.githubusercontent.com/43080048/148088447-16363415-066d-4c2d-970e-b291fe37e143.png)

**Comment by aubergine10** [comment]
Probably caused by one of the mods on this page:

https://github.com/CitiesSkylinesMods/TMPE/wiki/Array-Index---Symptom-10

Try the Compatibility Report mod as it will help track down outdated mods and suggest newer alternatives: https://steamcommunity.com/sharedfiles/filedetails/?id=2633433869

**Comment by Leni-Vienne** [comment]
I had the same issue a while ago and only managed to fix it by reverting to an older save. From what I remember, this problem is related to a huge amount of citizen getting stuck and thus a massive decrease in FPS. In TMPE settings > Maintenance, could you enable "show pathfind count" ? The value in TMPE UI should over between 0 and 1, yours may be way higher than that.

**Comment by aubergine10** [comment]
TM:PE doesn't alter the terrain. That error is not TM:PE.

There are many other causes of Array Index error listed in our wiki: https://github.com/CitiesSkylinesMods/TMPE/wiki/Simulation-error-Array-index-is-out-of-range

**Comment by Leni-Vienne** [comment]
Yeah I don't think it's TMPE either, it's quite bug-proof. But In my memory clearing stuck cims and vehicle had an effect on FPS, so if that can help identify the root cause it would be great news

**Comment by aubergine10** [comment]
The issue in OP is certainly caused by **Building Anarchy mod**.

```
Loading C:\Users\user\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\building_anarchy\BuildingAnarchy.dll  [Mods - Internal]
```

As for the issue with stuck sims, there's a bunch of improvements coming in v11.6 release, but in mean time see if anything in the wiki helps: https://github.com/CitiesSkylinesMods/TMPE/wiki/Troubleshooting

**Comment by lemuelmpranoto** [comment]
Hello, thank you for the help. I ended up browsing on the error and someone said it was indeed the Building Anarchy mod as mentioned by @aubergine10. I don't know why when I removed TM:PE the error disappeared but maybe the mod was not compatible with TM:PE. Anyways consider this issue resolved. Thank you so much :)
