### ISSUE TITLE
Cache `LHT` and `RHT` shortcut values?

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1274]
In `Shorcuts.cs` we have the following:

https://github.com/CitiesSkylinesMods/TMPE/blob/83a7ca3f3285b1eaef271c14540879c0de674cfd/TLM/TLM/Util/Shortcuts.cs#L197-L198

After PR #1273 is merged (assuming it is), the entire codebase will be using those shortcuts, rather than the cumbersome:

```csharp
Singleton<SimulationManager>.instance.m_metaData.m_invertTraffic == SimulationMetaData.MetaBool.True; // or .False
```

However, it seems we're going to be calling `LHT` and `RHT` huge numbers of times, particularly when overlays are active ...I think?

Would there be any merit to caching the value?

```
LHT => _lht;
RHT => _rht;
```

The value can be changed in-game via mods - currently TM:PE is completely unaware of such change.... To keep the cached value fresh, we could maybe detect changes to `.m_invertTraffic `. Benefit here is that TM:PE will now know if user or a mod changes which side traffic drives on in-game.

That could further develop in to handling such change:

1. Pause simulation
2. Clear all traffic (rather than lengthy repath)
3. Clear any broken traffic customisations
4. Let user know they should save under new filename, exit to desktop, then reload city, and that most of their customsiations are toast

**Comment by aubergine10** [comment]
Ok, I agree about no need to cache.

But if there's change between LHT/RHT are there adverse effects if user doesn't manually clear down the customisations?

If we start seeing proliferation of TMPE customised assets/maps in workshop, and user has their traffic on other side of road, what's going to happen?

**Comment by kianzarrin** [comment]
I suspect it will not work out very well! in any case this is another issue.

**Comment by aubergine10** [comment]
Pls create another issue that describes the LHT/RHT issue in better detail. At the very least we need to make asset/map creators aware of the potential issues should user play with traffic driving on other side.

**Comment by kianzarrin** [comment]
maybe it should be part of the persistency issue?

**Comment by aubergine10** [comment]
yup, if possible that would be awesome!
