### ISSUE TITLE
Despawn vehicle button missing

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1289]
### Describe the problem

The red 'Despawn vehicle' button that appears on vehicle info panels is missing in 11.6.2 TEST.

I'm using build from PR #1284 if that makes any difference?

### Steps to reproduce

1. Click a vehicle to show it's info panel
2. The red despawn vehicle button is missing

### Log files

* [output_log.zip](https://github.com/CitiesSkylinesMods/TMPE/files/7885217/output_log.zip)
* [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/7885218/TMPE.log)

### Savegame?

n/a

### Screenshots?

![image](https://user-images.githubusercontent.com/1386719/149849224-129c4ac4-4b79-429c-9fd5-0b154a458293.png)
![image](https://user-images.githubusercontent.com/1386719/149849261-13152b85-4362-417f-b429-5df2418ea41c.png)

**Comment by krzychu124** [comment]
Hmm, so not fixed by #1281?

**Comment by krzychu124** [comment]
Ok it seems to be an issue with PlayMode fix #1286
