### ISSUE TITLE
Allow `CheckboxOption` to handle locale strings from other tables

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1299]
Due to way `CheckboxOption.AddUI()` works, it can only pull localisation strings from `Options.csv` (which is fine).

However, `Checkbox:Display speed limits mph` locale string is currently residing in `SpeedLimits.csv`.

**Comment by kianzarrin** [comment]
either we should decide to put all translations in `options.csv` or allow to modify translation delegate. either way its easy fix. changing translations can be annoying though!

**Comment by aubergine10** [comment]
@kianzarrin I've just noticed the mod checker has it's own translation file (`Translation.ModConflicts` ie. contents of `ModConflicts.csv`). So yeah, would be useful to be able to define which translation file we're dealing with (should default to `Translation.Options` as that's what most things currently use).

I was unsure of how best to reference a list - eg. if I just pass in the list and store that, what happens on hotload? Should it use `nameof(Translation.Whatever)` and then use `GetField()` to grab it as necessary? If you know of a good way to do that send a PR or just dump code in comment below. I'm currently working on updating all the checkboxes in General options to use `CheckboxOption`.

**Comment by kianzarrin** [comment]
> @kianzarrin I've just noticed the mod checker has it's own translation file (`Translation.ModConflicts` ie. contents of `ModConflicts.csv`). So yeah, would be useful to be able to define which translation file we're dealing with (should default to `Translation.Options` as that's what most things currently use).
> 
> I was unsure of how best to reference a list - eg. if I just pass in the list and store that, what happens on hotload? Should it use `nameof(Translation.Whatever)` and then use `GetField()` to grab it as necessary? If you know of a good way to do that send a PR or just dump code in comment below. I'm currently working on updating all the checkboxes in General options to use `CheckboxOption`.

For translations override we can pass delegate

**Comment by aubergine10** [comment]
Good call - works like a charm!
