### ISSUE TITLE
Speed limits - possibly not working for some/all metro tracks.

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1322]
Multiple users stating that speed limits tool isn't showing up for metro tracks (note: v11.6.4.1 release):

![image](https://user-images.githubusercontent.com/1386719/151326680-58c4707f-2b4d-4159-a4b8-e3c9bcd8302a.png)

**Comment by krzychu124** [comment]
... not good 😕 I'll test later today

**Comment by krzychu124** [comment]
And bridges...

![image](https://user-images.githubusercontent.com/19638970/151376104-70d76f65-7ec3-4f47-803f-45b33544aecf.png)

**Comment by aubergine10** [comment]
Do we need to list separate AIs?

![image](https://user-images.githubusercontent.com/1386719/151416106-ddd958ba-fbf2-4c12-9c22-670b1263af4d.png)
![image](https://user-images.githubusercontent.com/1386719/151416547-9ee58417-d923-4b1a-87f5-44487fc4f2bf.png)

```csharp
            if (!(netinfo.m_netAI is RoadBaseAI or TrainTrackBaseAI or MetroTrackAI)) {
```

Also, should we add `MonorailTrackAI` ?

**Comment by krzychu124** [comment]
Probably but I'm curious how that thing worked before as we didn't remove anything (i think)...

**Comment by aubergine10** [comment]
If it's affecting workshop assets primarily, is it possible the asset author got their flags wrong?

```csharp
            if (!netinfo.m_vehicleTypes.IsFlagSet(VEHICLE_TYPES) || !netinfo.m_laneTypes.IsFlagSet(LANE_TYPES)) {
```

**Comment by krzychu124** [comment]
Works for monorail (derives from `TrainTrackBaseAI`) although overlay should be one "level" higher (where 80)
![image](https://user-images.githubusercontent.com/19638970/151434786-11e363b9-aefc-4269-a6bf-96904e0aabe0.png)


Train Tracks works too but for underground it requires switching with PageDown to show signs. They probably forget about that, maybe add tiny sign or `v` so notify that something is there or another toggle to always show everything

![image](https://user-images.githubusercontent.com/19638970/151435313-dc26dc05-2393-4e1f-8468-78604a856965.png)

![image](https://user-images.githubusercontent.com/19638970/151435260-a23ba9fb-cb7f-405d-b85b-d30ebc9238e9.png)


For metro.. _I'll push tiny fix_
