### ISSUE TITLE
Switch to under/overground should be read from the game keybinds

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#1326]
### Describe the problem

Some users report (MacOS) they don't have easy access to those keys.
Switching between underground and normal mode should be the same as one set in the vanilla game keybinds.

OSD texts might require an update 😕

**Comment by aubergine10** [comment]
As far as I can tell these are the game-defined keys.

```csharp
// page up
SavedInputKey m_buildElevationUp = new SavedInputKey(Settings.buildElevationUp, Settings.gameSettingsFile, DefaultSettings.buildElevationUp, autoUpdate: true);

// page down
SavedInputKey m_buildElevationDown = new SavedInputKey(Settings.buildElevationDown, Settings.gameSettingsFile, DefaultSettings.buildElevationDown, autoUpdate: true);
```

**Comment by krzychu124** [comment]
Yup, I didn't have energy to implement it... Translations also require change since probably in all languages PageUp/PageDown key is mentioned

**Comment by aubergine10** [comment]
Yeah, it looks like each tool has it's own hard-coded `PageUp/Down` OSD text so that will need centralising too.

**Comment by krzychu124** [comment]
@aubergine10 I'm working on it and hope to squeeze it into **11.6.5.1**, but we will see 😅

**Comment by aubergine10** [comment]
Awesome!
