### ISSUE TITLE
Aircraft DLC: Aircrafts sometimes stuck at taxiway junction

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#1329]
### Describe the problem
User reports that TM:PE sometimes cause vehicles to stuck at taxiway junctions. Removing TM:PE fixes the problem.

### Steps to reproduce

Not clear how to setup taxiways unfortunately, I'm waiting for savegame to start debugging the problem.

### Screenshots?
![image](https://user-images.githubusercontent.com/19638970/151445936-be4f9244-ff44-4732-aad5-09f033d74324.png)

**Comment by krzychu124** [comment]
Good question, I'll ask!

**Comment by krzychu124** [comment]
Nope, Multitool not used on taxiway or runway

**Comment by aubergine10** [comment]
try broken node detector (I assume it tests all nodes, not just roads/paths)?

**Comment by aubergine10** [comment]
It's probably a good thing that they don't take off from a fuel depot.

Afterburners + huge vats of jet fuel = ...let's just turn the engines off for a bit.

**Comment by aubergine10** [comment]
It's a shame you can't connect the After Dark aviation club to the Airports DLC runways :(

**Comment by krzychu124** [comment]
I found they stuck because they can't take off (aircraft path is occupied, not enough space to reserve), related to #1327 😄
