### ISSUE TITLE
Issues with station tracks

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1337]
### Describe the problem

Had a few people on TMPE workshop page mention that speed limit overlay isn't appearing on station tracks.

Not sure if this is just related to underground stations, will need some testing.

![image](https://user-images.githubusercontent.com/1386719/151679803-753bcca8-0734-4b28-9023-64b56965ddba.png)

![image](https://user-images.githubusercontent.com/1386719/151679816-9c499a59-322c-499e-ae80-29b479396f75.png)

**Comment by aubergine10** [comment]
Confirmed bug with train station tracks - the speed icon appears, and interacts (eg. changes color on hover, and lanes highlight), but clicking has no effect:

![image](https://user-images.githubusercontent.com/1386719/151680164-5499c0d4-1d0b-4b80-aecb-ea4111625f9b.png)

There are no errors in the logs.

I suspect whatever handles the "click" is doing some extra checks on the segment and for some reason deciding it's not applicable for speed limits - I'll dig through the code shortly.

![image](https://user-images.githubusercontent.com/1386719/151680205-d5b87d3f-cb98-4f44-a334-a362dfa98833.png)

![image](https://user-images.githubusercontent.com/1386719/151680213-8ddc4f9a-9863-4141-9cdd-255808c81d00.png)

![image](https://user-images.githubusercontent.com/1386719/151680223-8271b6d5-6cfc-4916-8503-0b82b8f0fb3c.png)

**Comment by aubergine10** [comment]
What are these new directions `AvoidForward` and `AvoidBackward`??

**Comment by aubergine10** [comment]
Ok, I'm sure I've not seen these before, but looks like we have bunch of new directions to deal with:
```diff
[Flags]
public enum Direction : byte
{
	None = 0,
	Forward = 1,
	Backward = 2,
	Both = 3,
+	Avoid = 0xC,
+	AvoidBackward = 7,
+	AvoidForward = 0xB,
+	AvoidBoth = 0xF
}
```

**Comment by aubergine10** [comment]
Note: Still push out 11.6.4.3 to workshop today if poss.

I think this update to directions flags is going to take a bit of time to deal with.

For example, `AvoidBackward` = `7`, which in binary is: `0000000000000111`

If my understanding of how flags work in C# is correct, that means TM:PE will be seeing that track as `Both`, `Forward`, and `Backward` but not `Avoid`.

ffs, what did CO do here lol

In any case, station tracks are going to need to deal with what is effectively `Both` in oldspeak. As far as I know TM:PE speed limits isn't built to deal with `Both` direction lanes...

**Comment by aubergine10** [comment]
`Avoid` should surely have value `4` and then it would be a case of just mixing the existing flags with `Avoid` to get the other variants of avoid directions.

**Comment by aubergine10** [comment]
Updated comments above; Both = `11` so it does seem like `Avoid` is `4` (`100`) but also with an additional bit (`1000`) set for some weird reason?

**Comment by krzychu124** [comment]
> Avoid should surely have been value 4 and then it would be a case of just mixing the existing flags with Avoid to get the other variants of avoid directions.

No, no... I think the case here is that `Avoid` something should be something completely different that `Forward`, `Backward` or `Both` (`Forward | Backward`), If `Avoid` is 12 then `AvoidBoth` is also "ok" (`Both | Avoid`) but the other two does not make sense

**Comment by aubergine10** [comment]
Yeh, it's set like this:

|`Direction`| | | | | |
|:---|:---:|:---:|:---:|:---:|:---:|
|`None`|0|0|0|0|0|
|`Forward`|0|0|0|0|1|
|`Backward`|0|0|0|1|0|
|`Both`|0|0|0|1|1|
|`Avoid`|0|1|1|0|0|
|`AvoidForward`|0|1|0|1|1|
|`AvoidBackward`|0|0|1|1|1|
|`AvoidBoth`|0|1|1|1|1|

**Comment by krzychu124** [comment]
oh.. I see that now:
AvoidBackward 7 -> `0111` and AvoidForward 11 -> `1011` so it looks like they see it not as flags in group of 4 bits `0000` but two groups of 2bits `00 00` so flags contains `Both` use 4 bits `0011` or `1111` but `Avoids` must contain both so either `01 11`(7) or `1011`(11)

**Comment by aubergine10** [comment]
Even if that is the case, AvoidForward and AvoidBackward are reversed?

**Comment by krzychu124** [comment]
If you divide that table on two groups it will make a bit more sense (normal - 4 flags, avoids - 4 flags)

> Even if that is the case, AvoidForward and AvoidBackward are reversed?


Yes because you are avoiding 
![image](https://user-images.githubusercontent.com/19638970/151681346-2caaf9d0-a76b-43e4-a4c4-6d427f4143d0.png)

**Comment by krzychu124** [comment]
I think it is related to the situation you can enter and exit segment in both ways but spawning on the segment allows moving only one direction

**Comment by aubergine10** [comment]
Table above updated headings.

**Comment by aubergine10** [comment]
That would be useful on central turning lanes to control "preferred" direction of traffic at segment ends

Might also possibly have some use for tidal lanes (#122) and virtual bus lanes (#123).

**Comment by krzychu124** [comment]
Yes but code must check `Avoids` because `flag & Forward != 0` will be true for `Forward`, `Both`, and other Avoids excluding `Avoid`

**Comment by aubergine10** [comment]
This is a freaking nightmare for any mod that interacts with `NetInfo.Direction` lol

**Comment by aubergine10** [comment]
![heycsl](https://user-images.githubusercontent.com/1386719/151682357-253dff57-a746-49cf-b1b9-9048af7f5885.png)

**Comment by aubergine10** [comment]
```csharp
public NetInfo.Direction SimplifyDirection(NetInfo.Direction dir) =>
    dir < 4 ? dir : ~(dir >> 2);
```

**Comment by aubergine10** [comment]
algernon provided some additional detail: 

>  It's allocated as part of the base prefab deserialization (including post-deserialization where it's allocated to lane.m_finalDirection) and isn't otherwise touched during gameplay.

**Comment by kianzarrin** [comment]
Oh damn I missed all the fun. I have been using avoid flags for a while and am quite familiar with them.
in this PR I have copied code from my mods into TMPE extensions regarding directions: https://github.com/CitiesSkylinesMods/TMPE/pull/1487

CS has code to deal with avoid flags so I got my code from there :)

At train station:
Forward/Backward : for trains stopping at station
AvoidBackward = 4 + Forward+Backward where 4 means bypass forward (or avoid bypassing backward)
AvoidForward = 8 + Forward+Backward where 8 means bypass backward (or avoid bypassing forward)
