### ISSUE TITLE
Is TM:PE speed constant wrong?

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1340]
Found this whilst browsing game code:

![image](https://user-images.githubusercontent.com/1386719/151713116-5785a534-b861-4d3e-b365-268d7f245c7b.png)

Note `num` - looks like `km/h = game speed * 13.5f` ?

In `Constants.cs` we've got:

```csharp
        /// <summary>
        /// Conversion rate from km/h to game speed (also exists in TrafficManager.API.Constants)
        /// </summary>
        public const float SPEED_TO_KMPH = 50.0f; // 1.0f equals 50 km/h
```

**Comment by chameleon-tbn** [comment]
What would be the effect of this? I have several players complaining about very long stop / unloading times. Would that value also have an impact on this?

**Comment by krzychu124** [comment]
Frame velocity is not the same as the game speed set in the asset (road or vehicle

> What would be the effect of this? I have several players complaining about very long stop / unloading times. Would that value also have an impact on this?

I doubt, but keep in mind if you slow down the game with speed slider everything will be slower, including unloading time (it's probably calculated based on simulation steps passed)
