### ISSUE TITLE
Something is wrong with speed limits tool

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1346]
### Describe the problem

I slapped down a bunch of roads while testing airport stuff:

![image](https://user-images.githubusercontent.com/1386719/152114047-3f2c1b13-641c-48fa-b044-2735dd43d688.png)

Note how they all have 'custom override' speeds 20 mph.

However, I didn't set those overrides. I've done nothing to those roads other than splat them down on the map.

The default speeds of those roads are 30 mph.

![image](https://user-images.githubusercontent.com/1386719/152114153-63388b64-81de-41e6-8a25-125b382e115a.png)

Where did the 20 mph come from?

**Comment by kvakvs** [comment]
The number comes from SpeedLimitManager API returning the numbers. As that's a dictionary with segmentId as a key, it should not return anything for a new segment that did not exist before. But then also this code was touched by @kianzarrin should get his opinion too.

**Comment by aubergine10** [comment]
Lane flags etc for image in previous comment, lanes ordered from left to right:

Road on the left:

![image](https://user-images.githubusercontent.com/1386719/152659597-5fbe8aa7-c10e-4e56-ad26-a8612bb2c23e.png)

![image](https://user-images.githubusercontent.com/1386719/152659601-503f05a5-2012-446e-bda0-34f626df5ac8.png)

Road on the right:

![image](https://user-images.githubusercontent.com/1386719/152659576-749cdb6e-f639-49c6-8398-fe446e7d8f16.png)

![image](https://user-images.githubusercontent.com/1386719/152659565-065097e5-a969-4606-a6e7-275ca2936ac1.png)

**Comment by aubergine10** [comment]
![image](https://user-images.githubusercontent.com/1386719/152659659-32d15e1b-a0bc-464a-850f-fb06ab643cd7.png)

**Comment by aubergine10** [comment]
Added some debugging to the `DrawSpeedLimitHandles_SegmentCenter()` method:

```csharp
if (isHoveredHandle) {
    try {
        Log.Info(
            $"overrideSpeedlimitForward = {overrideSpeedlimitForward}, " + 
            $"overrideSpeedlimitBack = {overrideSpeedlimitBack}, " + 
            $"drawSpeedlimit = {drawSpeedlimit}, " + 
            $"defaultSpeedLimit = {defaultSpeedLimit}");
    }
    catch (Exception ex) {
        ex.LogException();
    }
}
```

Here's what came up when hovering over one of the speed icons (note: log is in km/h whereas images earlier in this issue are showing MPH):

```
overrideSpeedlimitForward = ,
overrideSpeedlimitBack = 30 km/h,
drawSpeedlimit = 30 km/h,
defaultSpeedLimit = 50 km/h
```

* 30 MPH = 47 km/h (I assume this gets rounded to 50 km/h)
* 20 MPH = 31 km/h (I assume this gets rounded to 30 km/h)

So it seems `defaultSpeedLimit` is correct, but for some reason I'm getting back invlaid speeds from `CalculateCustomSpeedLimit()` in the lines below:

```csharp
SpeedValue? overrideSpeedlimitForward =
    SpeedLimitManager.Instance.CalculateCustomSpeedLimit(segmentId, finalDir: NetInfo.Direction.Forward);
SpeedValue? overrideSpeedlimitBack =
    SpeedLimitManager.Instance.CalculateCustomSpeedLimit(segmentId, finalDir: NetInfo.Direction.Backward);
SpeedValue? drawSpeedlimit = GetAverageSpeedlimit(
    forward: overrideSpeedlimitForward,
    back: overrideSpeedlimitBack);
```

Will now start digging in to those to find out where the error creeps in.

**Comment by aubergine10** [comment]
Results of extended logging:

```
Info 440.9290207: CalculateCustomSpeedLimit Forward
Info 440.9297678: CalculateCustomSpeedLimit Backward
Info 440.9310367: laneInfo.m_speedLimit = 0.6, as SpeedValue = 30 km/h
Info 440.9317807: GetDefaultSpeedLimit = 30 km/h
Info 440.9325512: validLanes = 1, meanSpeedLimit = 30 km/h
Info 440.9333117: laneInfo.m_speedLimit = 0.6, as SpeedValue = 30 km/h
Info 440.9339923: GetDefaultSpeedLimit = 30 km/h
Info 440.9346849: validLanes = 2, meanSpeedLimit = 60 km/h
Info 440.9355180: overrideSpeedlimitForward = , overrideSpeedlimitBack = 30 km/h, drawSpeedlimit = 30 km/h, defaultSpeedLimit = 50 km/h
```

The `Info 440.9310367: laneInfo.m_speedLimit = 0.6, as SpeedValue = 30 km/h` is coming from this code:

```csharp
        public SpeedValue GetDefaultSpeedLimit(NetInfo netinfo, NetInfo.Lane laneInfo, bool db = false) {
            if (customNetinfoSpeedLimits_.TryGetValue(netinfo, out float speedLimit)) {
                if (db) {
                    Log.Info($"customNetinfoSpeedLimits_ = {speedLimit}");
                }
                return new SpeedValue(speedLimit);
            } else {
                if (db) {
                    Log.Info($"laneInfo.m_speedLimit = {laneInfo.m_speedLimit}, as SpeedValue = {new SpeedValue(laneInfo.m_speedLimit)}");
                }
                return new SpeedValue(laneInfo.m_speedLimit);
            }
        }
```

So 20 MPH (30 km/h) is the actual prefab speed of the road.... But why is it not getting the 30 MPH (50 km/h) custom default speed for the road if that value is shown when viewing/editing default speeds?

Now I need to dig in to how `defaultSpeedLimit` (mentioned in previous comment) is being determined...

**Comment by aubergine10** [comment]
```csharp
var defaultSpeedLimit = new SpeedValue(
    gameUnits: SpeedLimitManager.Instance.CalculateCustomNetinfoSpeedLimit(info: neti));
```

Calls (some code trimmed for brevity)....

```csharp
        public float CalculateCustomNetinfoSpeedLimit(NetInfo info) {
            return !customNetinfoSpeedLimits_.TryGetValue(info, out float speedLimit)
                       ? GetVanillaNetInfoSpeedLimit(info)
                       : speedLimit;
        }
```

Which is recognisable from previous comment...

```csharp
if (customNetinfoSpeedLimits_.TryGetValue(netinfo, out float speedLimit)) { ...
```

So assuming there isn't an entry in `customNetinfoSpeedLimits`, it must be calling `GetVanillaNetInfoSpeedLimit()` (some code removed for brevity)...

```csharp
        private float GetVanillaNetInfoSpeedLimit(NetInfo info) {
            float? maxSpeedLimit = null;

            if (info.m_lanes != null) {
                foreach (var laneInfo in info.m_lanes) {
                    float speedLimit = laneInfo.m_speedLimit;
                    if (maxSpeedLimit == null || speedLimit > maxSpeedLimit) {
                        maxSpeedLimit = speedLimit;
                    }
                }
            }

            return maxSpeedLimit ?? 0f;
        }
```

So, that's not checking lane types or vehicle types... Example, if there was a `None, None` lane but with highest speed, it would be returned as the netinfo speed. I suspect that may be the case with some of the UK road assets (and potentially any network asset from workshop).... time to add more logging/trace....

**Comment by aubergine10** [comment]
Annnnd there's the culprit....

```diff
- Info 440.2720848: m_vehicleType = None, laneInfo.m_laneType = None, speedLimit = 1
- Info 440.2727466: m_vehicleType = None, laneInfo.m_laneType = None, speedLimit = 1
- Info 440.2734355: m_vehicleType = None, laneInfo.m_laneType = None, speedLimit = 1
- Info 440.2740341: m_vehicleType = None, laneInfo.m_laneType = None, speedLimit = 1
- Info 440.2746089: m_vehicleType = None, laneInfo.m_laneType = None, speedLimit = 1
+ Info 440.2752129: m_vehicleType = Car, laneInfo.m_laneType = Vehicle, speedLimit = 0.6
+ Info 440.2757840: m_vehicleType = Car, laneInfo.m_laneType = Vehicle, speedLimit = 0.6
Info 440.2763682: m_vehicleType = None, laneInfo.m_laneType = Pedestrian, speedLimit = 0.1
Info 440.2769400: m_vehicleType = None, laneInfo.m_laneType = Pedestrian, speedLimit = 0.1
```

This would also explain all the weirdness I was getting with speed overlays a while back - and why changing default speed for a network was solving those issues.

Should be easy to fix, will send PR shortly.

**Comment by aubergine10** [comment]
Code that calls `GetVanillaNetInfoSpeedLimit()` for future reference:

![image](https://user-images.githubusercontent.com/1386719/152663938-35051866-3867-4da8-91e4-4e2e1717b5f8.png)

**Comment by aubergine10** [comment]
```csharp
if (laneInfo.MayHaveCustomSpeedLimits()) { ...
```

:)
