### ISSUE TITLE
Game dosent work

### ISSUE THREAD

**Issue by demitri4** [CitiesSkylinesMods/TMPE#1349]
### Steps to reproduce

1.  Open Cities Skylines
2. Click "Continue"
3. Have Loading screen https://user-images.githubusercontent.com/60064953/152205139-1f3bfc39-0f21-4142-b2d3-fbcb2955f9c9.png

### Log files

https://we.tl/t-fxe9s6XzDW

### Screenshots?

![image](https://user-images.githubusercontent.com/60064953/152205139-1f3bfc39-0f21-4142-b2d3-fbcb2955f9c9.png)

(Linux KDE Neon 8 GB RAM (without TMPE game work)

**Comment by aubergine10** [comment]
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/7988798/TMPE.4.log)

@demitri4 Could you also upload your output_log.txt (or is it Player.log on Linux?) - just drag the file on to a comment box here on github like you did with the screenshot. Note that the logs reset each time game starts so collect them after error occurs.

@krzychu124 any idea what's causing this?

```diff
Info 8.6539550: Expected C:SL v1.14.0-f4 - Actual C:SL v1.14.0-f4
Info 15.9635023: Preloading Managers
Info 15.9642642: CustomPathManager.Initialize() called.
Info 15.9643835: CustomPathManager.Initialize() CustomPathManager not found, creating new instance.
- Info 160.8462414: TMPELifecycle.OnDestroy()
Info 160.8466239: Unloading CustomPathManager
Info 160.8469262: CustomPathManager.WaitForAllPaths()
```

**Comment by demitri4** [comment]
@aubergine10 I did not find this file player.log

**Comment by aubergine10** [comment]
try `~/.config/unity3d/Colossal Order/Cities: Skylines/Player.log`

**Comment by krzychu124** [comment]
> 



> [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/7988798/TMPE.4.log)
> 
> @demitri4 Could you also upload your output_log.txt (or is it Player.log on Linux?) - just drag the file on to a comment box here on github like you did with the screenshot. Note that the logs reset each time game starts so collect them after error occurs.
> 
> @krzychu124 any idea what's causing this?
> 
> ```diff
> Info 8.6539550: Expected C:SL v1.14.0-f4 - Actual C:SL v1.14.0-f4
> Info 15.9635023: Preloading Managers
> Info 15.9642642: CustomPathManager.Initialize() called.
> Info 15.9643835: CustomPathManager.Initialize() CustomPathManager not found, creating new instance.
> - Info 160.8462414: TMPELifecycle.OnDestroy()
> Info 160.8466239: Unloading CustomPathManager
> Info 160.8469262: CustomPathManager.WaitForAllPaths()
> ```

It might be just indicator that game was closed or forced to close. `Player.log` is required to say anything more

**Comment by demitri4** [comment]
I didn't find this file, version cities skylines 1.14.0-f4

**Comment by demitri4** [comment]
The game does not crash for me, I forcibly close it because nothing happens

**Comment by demitri4** [comment]
what should I do to get this file ? , my game is still hanging on loading (for more than an hour)

**Comment by krzychu124** [comment]
Find that file, it must be somewhere on your hdd/ssd. It's super important. Without that file we won't help you or say where the problem could be. I'm going to switch to Ubuntu for additional tests on our side.

**Comment by demitri4** [comment]
I have an endless download of the game, just loads and nothing more (more than one and a half hours), the only file that I have this TMPE.log

**Comment by krzychu124** [comment]
@demitri4 I missed one thing looking into your log. What is this?
>   * (local)      Harmony 2.0.0.9

It doesn't look like correct Harmony mod. Remove it completely and subscribe to [Harmony 2.0.4-4 (Mod Dependency, Airports DLC compatible)](https://steamcommunity.com/workshop/filedetails/?id=2040656402)
Without Cities Harmony **TM:PE** won't work

**Comment by demitri4** [comment]
![image](https://user-images.githubusercontent.com/60064953/152227588-498e3f8e-b131-4648-8dcf-a9564b3ee1e8.png)

**Comment by demitri4** [comment]
Mod work , thank you!

**Comment by krzychu124** [comment]
That's ok, if it's the only warning/info you see then everything is working correctly
