### ISSUE TITLE
Vehicles that turn to a building must follow priority rules

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#135]
see https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/32

copied from https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/57

---

Summary: If vehicles can cross oncoming traffic to enter a building, they should wait until there is a gap in that traffic before doing so.

**Comment by aubergine10** [comment]
Related: #19 , #89

**Comment by aubergine10** [comment]
Closing this old ticket; the issue is now being tracked in #1223
