### ISSUE TITLE
Aircraft not spawning from outside connections/airport

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1352]
Not sure if this is a bug or not, or even if it's caused by TM:PE. I suspect it's the age-old problem of editing aircraft paths (using More Network Stuff / Move It) in-game resulting in Aircraft AI breaking. Also, the airport is well outside the central 25 tile area so it could be 81 Tiles issue.

I created a new DLC airport; as soon as it was powered/watered a bunch of aircraft spawned at its stands and took off - so no problem there. But after that... nothing. Not only are no aircraft spawning from the stands of the airport, but no aircraft are spawning from outside connections either.

The key issue at present is I have no idea if or where something is breaking, so I'm creating this issue to ask for assistance in implementing something that can shed light on what's happening under the hood.

It would be super-useful if there was some way to attach a logging harness to anything that involves aircraft spawning:

- Whatever sends a request to transfer manager
- Whatever bit of transfer manager decides to use air travel
- Anything in the Aircraft AI that handles that
- Pathfinding attempts for aircraft

**Comment by krzychu124** [comment]
Where is Airplane path located in relation to your airport? Does your runway touch it?

**Comment by aubergine10** [comment]
![image](https://user-images.githubusercontent.com/1386719/152249411-af41a543-3b29-45b7-bfcb-9c6c511ac8f3.png)

**Comment by krzychu124** [comment]
How did you connect aircraft stands with taxiways? 

![image](https://user-images.githubusercontent.com/19638970/153075980-9e42f4c5-e562-43b2-88e5-e6f5b77aff38.png)

**Comment by aubergine10** [comment]
Now fixed, airplanes are arriving at the airport. Which is currently on fire, but fire engines are on the way.

![image](https://user-images.githubusercontent.com/1386719/153120925-a025ffa8-5561-4913-be6d-8fe869057562.png)

![image](https://user-images.githubusercontent.com/1386719/153121042-efcaef68-e6d8-4c57-be31-162dfb7432d3.png)

CO should use their new direction types `both + avoid backward` on the taxiways!

**Comment by aubergine10** [comment]
Oh, btw, I noticed if runway is too short, big planes take off almost vertical. And for some reason I can't bulldoze the runway lol. (move it mod is able to destroy it).
