### ISSUE TITLE
Mod compatibility with Reversible Tram AI

### ISSUE THREAD

**Issue by sway2020** [CitiesSkylinesMods/TMPE#1353]
I made a reversible tram AI mod prototype. I am still testing it with vanilla traffic and the next thing I plan to work on is to make it compatible with TMPE.

https://steamcommunity.com/sharedfiles/filedetails/?id=2740907672

It creates a new tram AI, modified from the vanilla tram AI, with some ported functions from the vanilla train AI and some additional tweaks. It'll take some time for me to study the TMPE codebase, and then I'll send a pull request later. Is there any suggestion where I should look at first? I think two main tasks are:

1. Let TMPE detect the new tram AI

2. Apply the same or similar TMPE tram AI patches to the new tram AI

There are probably better ways to do things as I only have limited experience in modding vehicle AI. Krzychu already has access to my mod repo and I'll send an invitation to aubergine

**Comment by krzychu124** [comment]
Awesome! I haven't had a chance to look into latest version. I only tested previous from `main` branch yesterday, with those weird bugs with collision check and lane reservation issues. It shouldn't be too hard to add support.

**Comment by sway2020** [comment]
I am working on it already. One problem is the game complains about assembly resolution failure when the reversible AI mod is not present, and I don't know a better way to eliminate this error message. Also in my testing I noticed that the collision check became worse when the reversible tram AI was used together with TMPE (vehicle overlapping increased). I don't know the cause yet

https://github.com/sway2020/TMPE/commit/1fe884482c0b0c70ea7d2d0bb59eecea5acbc9b0
![Screenshot 1](https://user-images.githubusercontent.com/65274619/152638801-6654cfd0-7bcf-43be-91c0-de3d76359d6a.png)

**Comment by krzychu124** [comment]
Probably the easiest way would be writing manual patch. Remove `[HarmonyPatch]` and add few lines for manual patching in the Patcher (conditionally called)

**Comment by sway2020** [comment]
I used manual patching in my other mods. I'll check out TMPE's Patcher
