### ISSUE TITLE
CSUR Lane connector - missing connectors

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#1355]
### Describe the problem

Missing outgoing connectors on transition segments of CSUR roads. e.g.: 3 to 2, 3 to 2 and lane shifts (12)->(23)

### Steps to reproduce

https://user-images.githubusercontent.com/19638970/152610560-41fd2dca-c04e-4ee3-bcf3-9c36f241941d.mp4

I've hit shift-s to check stay-on-lane at last node, so that's expected behavior

**Comment by aubergine10** [comment]
Does this issue affect other node-related tools? Notably junction restrictions, lane arrows, and priority signs?

**Comment by krzychu124** [comment]
I doubt. It's specific case where we use average segment length to calculate offset from node to render lane connectors with a little distance from each other and in this case node is a joined junction so has 0 width, just like nodes connecting segments with the same number of lanes.

**Comment by aubergine10** [comment]
Possibly related?

![image](https://user-images.githubusercontent.com/1386719/152629788-eb002840-2b87-4c94-bbd5-8d991faffc6b.png)

https://steamcommunity.com/workshop/filedetails/?id=1219936022

**Comment by bjoernelson** [comment]
Hi, seems to be working all fine again. I built a local version from the fix branch and it worked with all CSUR segments i tried. 
Thanks a lot for the quick solution and this mod in general, lane connectors are kind of important to have with CSUR roads ;)

**Comment by krzychu124** [comment]
> Possibly related?
> 
> ![image](https://user-images.githubusercontent.com/1386719/152629788-eb002840-2b87-4c94-bbd5-8d991faffc6b.png)
> 
> https://steamcommunity.com/workshop/filedetails/?id=1219936022

yes, and all other CSUR variants
