### ISSUE TITLE
Some users report language defaulting to Arabic

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1379]
### Describe the problem

We've had a couple of users report that TM:PE was defaulting to Arabic language. Possibly a buglet in the options loading or code that updates the dropdown?

### Steps to reproduce

Unknown - waiting for more info from users.

### Log files

If only `*sigh*`

I'll dig through the code to see if I can spot anything.

**Comment by aubergine10** [comment]
Language setting stored in `GlobalConfig.Instance.LanguageCode` and defaults to `null`.

References:

![image](https://user-images.githubusercontent.com/1386719/152892276-096face4-09b2-49eb-9918-4b02a0716483.png)

**Comment by aubergine10** [comment]
`HandleGameLocaleChange`:

![image](https://user-images.githubusercontent.com/1386719/152892371-f5870072-8128-48ab-89ad-7dfccb33eadc.png)

**Comment by aubergine10** [comment]
```csharp
        public static void SetCurrentLanguageToGameLanguage() {
            string code = LocaleManager.instance.language;

            // language mods can add their own codes, so deal with those if necessary
            switch (code) {
                case "jaex": {
                    code = "ja";
                    break;
                }

                case "zh-cn": {
                    code = "zh";
                    break;
                }

                case "kr": {
                    code = "ko";
                    break;
                }
            }

            CurrentLanguage = GetValidLanguageCode(code);
        }
```

**Comment by krzychu124** [comment]
Maybe that issues with untoggled Timed Traffic lights feature is also related (some users reported)?

**Comment by aubergine10** [comment]
```csharp
        private static string GetValidLanguageCode(string code) {
            return AvailableLanguageCodes.Contains(code)
                ? code
                : DEFAULT_LANGUAGE_CODE;
        }
```

`DEFAULT_LANGUAGE_CODE` = `"en"`

**Comment by aubergine10** [comment]
@krzychu124 I think the toggled lights feature was from that earlier bug with the wrong array size, and users just haven't realised there was issue with the mod option.

**Comment by aubergine10** [comment]
Issue is possibly here (general options tab):

```csharp
            string[] languageLabels = new string[Translation.AvailableLanguageCodes.Count + 1];
            languageLabels[0] = T("General.Dropdown.Option:Game language");

            for (int i = 0; i < Translation.AvailableLanguageCodes.Count; ++i) {
                languageLabels[i + 1] = Translation.Options.Get(
                    lang: Translation.AvailableLanguageCodes[i],
                    key: "General.Dropdown.Option:Language Name");
            }

            int languageIndex = 0;
            string curLangCode = GlobalConfig.Instance.LanguageCode;

            if (curLangCode != null) {
                languageIndex = Translation.AvailableLanguageCodes.IndexOf(curLangCode);
                if (languageIndex < 0) {
                    languageIndex = 0;
                } else {
                    ++languageIndex;
                }
            }

            _languageDropdown = group.AddDropdown(
                                    text: T("General.Dropdown:Select language") + ":",
                                    options: languageLabels,
                                    defaultSelection: languageIndex,
                                    eventCallback: OnLanguageChanged) as UIDropDown;
```

Notably this bit:

```csharp
            int languageIndex = 0;
            string curLangCode = GlobalConfig.Instance.LanguageCode;

            if (curLangCode != null) {
```

It's possible that for new users the `GlobalConfig.Instance.LanguageCode` is `null`, which means `languageIndex` will remain at `0`.

And there we go:

```csharp
            CsvColumnsToLocales
                = new Dictionary<string, string> {
                    { "Arabic", "ar"},
                    { "English", "en" }, // DEFAULT_LANGUAGE_CODE
                    { "Chinese Simplified", "zh" },
                    { "Chinese Traditional", "zh-tw" },
                    { "Czech", "cz" },
                    { "Dutch", "nl" },
                    { "English, United Kingdom", "en-gb" },
                    { "French", "fr" },
                    { "German", "de" },
                    { "Hungarian", "hu" },
                    { "Indonesian", "id" },
                    { "Italian", "it" },
                    { "Japanese", "ja" },
                    { "Korean", "ko" },
                    { "Occitan", "oc"},
                    { "Polish", "pl" },
                    { "Portuguese", "pt" },
                    { "Romanian", "ro" },
                    { "Russian", "ru" },
                    { "Slovak", "sk"},
                    { "Spanish", "es" },
                    { "Thai", "th"},
                    { "Turkish", "tr"},
                    { "Ukrainian", "uk"},
                };
            AvailableLanguageCodes = CsvColumnsToLocales.Values.ToList();
            AvailableLanguageCodes.Sort();
```

**Comment by aubergine10** [comment]
That was added recently to ensure list was alphabetical order, which is correct.

However, because all our testers already had the mod, they already had non-`null` language code set in global config, so none of us noticed that new users would be getting Arabic by default.

Should be relatively easy to fix, will send PR shortly.

**Comment by aubergine10** [comment]
Oh, wait, index `0` is `Game Language`.... hrm...

**Comment by aubergine10** [comment]
Added loads of logging, here's trace if a non-default but valid language is already set:

```
Info 32.8618286: Options.MakeSettings: Adding UI to mod options tabs
Info 32.8675167: Translation.SetCurrentLanguageToTMPELanguage(): GlobalConfig.Instance.LanguageCode = en-gb
Info 32.8684354: - not null, CurrentLanguage = GetValidLanguageCode(en-gb)
Info 32.8693916: Translation.GetValidLanguageCode result: en-gb
...
Info 34.0901708: languageLabels (0 indexed) = Game language, ﺔﻴﺑﺮﻌﻟﺍ, Čeština, Deutsch, English, English (UK), Español, Français, Magyar, Bahasa Indonesia, Italiano, 日本語, 한국어, Nederlands, Occitan, Polski, Português, Română, Русский язык, Slovenčina, ภาษาไทย, Türkçe, Українська, 简体中文, 繁體中文
Info 32.8877581: OptionsGeneralTab: curLangCode = en-gb; languageIndex = 0
Info 32.8886599: OptionsGeneralTab: languageIndex b4 increment = 4
Info 32.8894072: OptionsGeneralTab: languageIndex final = 5
```

All good so far.

**Comment by aubergine10** [comment]
Uh, what's that blank line?

![image](https://user-images.githubusercontent.com/1386719/152897533-d6b02dff-7438-444a-908a-aec8c74e3661.png)

And more blank lines:

![image](https://user-images.githubusercontent.com/1386719/152897609-6193b6c1-0acd-4ba4-9f17-33f36e46583f.png)

And more...

![image](https://user-images.githubusercontent.com/1386719/152897631-12e7ed84-28f5-41c2-8ada-6beeed8694a3.png)

This is debug build so it's not affected by that tweak I made to STABLE builds where unknown key returns pruned string (will still double check that).

@kvakvs You seen anything like this before?

**Comment by aubergine10** [comment]
Anyway, now set to game language, here's log trace for that...

```
Info 274.6501531: OptionsGeneralTab.OnLanguageChanged(0)
Info 274.6509347: - setting: GlobalConfig.Instance.LanguageCode = null
Info 274.6518150: Writing global config to file 'TMPE_GlobalConfig.xml'...
Info 274.6604167: Translation.SetCurrentLanguageToGameLanguage(): CurrentLanguage = GetValidLanguageCode(en)
Info 274.6612540: Translation.GetValidLanguageCode result: en
Debug 274.6626881: Rebuilding the TM:PE menu: ignored, ModUI is null
Debug 274.6637050: Informing the main OptionsPanel about the locale change...
Info 282.9337695: Options.MakeSettings: Adding UI to mod options tabs
Info 282.9434034: languageLabels (0 indexed) = Game language, ﺔﻴﺑﺮﻌﻟﺍ, Čeština, Deutsch, English, English (UK), Español, Français, Magyar, Bahasa Indonesia, Italiano, 日本語, 한국어, Nederlands, Occitan, Polski, Português, Română, Русский язык, Slovenčina, ภาษาไทย, Türkçe, Українська, 简体中文, 繁體中文
Info 282.9441029: OptionsGeneralTab: curLangCode = ; languageIndex = 0
```

**Comment by krzychu124** [comment]
> Uh, what's that blank line?
> 
> ![image](https://user-images.githubusercontent.com/1386719/152897533-d6b02dff-7438-444a-908a-aec8c74e3661.png)
> 
> And more blank lines:
> 
> ![image](https://user-images.githubusercontent.com/1386719/152897609-6193b6c1-0acd-4ba4-9f17-33f36e46583f.png)
> 
> And more...
> 
> ![image](https://user-images.githubusercontent.com/1386719/152897631-12e7ed84-28f5-41c2-8ada-6beeed8694a3.png)
> 
> This is debug build so it's not affected by that tweak I made to STABLE builds where unknown key returns pruned string (will still double check that).

FPS Booster - not cached characters - should fix itself after few frames/sec.

**Comment by aubergine10** [comment]
Loading up game again, this time with game language having been set:

```
Info 34.8168968: Options.MakeSettings: Adding UI to mod options tabs
Info 34.8222352: Translation.SetCurrentLanguageToTMPELanguage(): GlobalConfig.Instance.LanguageCode = 
Info 34.8229562: - was null, setting to game language...
Info 34.8239492: Translation.SetCurrentLanguageToGameLanguage(): CurrentLanguage = GetValidLanguageCode(en)
Info 34.8248607: Translation.GetValidLanguageCode result: en
...
Info 34.8430663: languageLabels (0 indexed) = Game language, ﺔﻴﺑﺮﻌﻟﺍ, Čeština, Deutsch, English, English (UK), Español, Français, Magyar, Bahasa Indonesia, Italiano, 日本語, 한국어, Nederlands, Occitan, Polski, Português, Română, Русский язык, Slovenčina, ภาษาไทย, Türkçe, Українська, 简体中文, 繁體中文
Info 34.8438620: OptionsGeneralTab: curLangCode = ; languageIndex = 0
```

It's in English as I'd expect:
![image](https://user-images.githubusercontent.com/1386719/152898330-e81dcf35-70ba-44cf-8ec3-6970a292c0c6.png)

The drop down still has loads of blank lines in it.

@krzychu124 Is there anything weird about text labels in the drop-down list UI component? It seems to not handle unicode...

**Comment by aubergine10** [comment]
> FPS Booster - not cached characters - should fix itself after few frames/sec.

@krzychu124 Been waiting over a minute now - still blank lines in the dropdown

**Comment by krzychu124** [comment]
Turn off FPS Booster Custom font manager and just hover over options - it will update text

**Comment by aubergine10** [comment]
Recently a user described the green 'default speed' icons as 'UK signs' and I'm wondering if it similar thing here with users misreporting 'alien text' (due to font update) as 'arabic'?

**Comment by kvakvs** [comment]
It's better to see a screenshot once than hear it many times over.
