### ISSUE TITLE
Changes to long roads with lots of junctions

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#138]
"I want to impose a vehicle restriction to an entire length of road. If I do this before adding any junctions I have the '....between two juctions' option, which is great. I want that for roads that already have junctions. I also want the same for speed limits (that doesn't even appear to have the between junctions option). Is this already possible and I'm missing something?

Love the mod! I'm in the process of creating a city with no private vehicles and it seems to be working :) It's just making changes is fiddly. "

see http://steamcommunity.com/workshop/filedetails/discussion/583429740/133256959375747518/

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/60

**Comment by VictorPhilipp** [comment]
Similar (but not identical) to #103.

**Comment by aubergine10** [comment]
`Shift` has been added as common modifier key for "apply to route" to all applicable tools. In addition, lane highlighting visually depicts which segments/lanes will be updated.

#721, #709, #708
