### ISSUE TITLE
Vehicles not spawning while "trucks and cars ban on bus lanes" is on

### ISSUE THREAD

**Issue by grtrd** [CitiesSkylinesMods/TMPE#1380]
### Describe the problem

As it is said in "Vehicles not spawning" site on your Wiki I report a bug when trucks are not spawning when bus lanes restrictions are on.

### Steps to reproduce

1. Unique factory doesn't send out any trucks (those trucks probably want to commute via train or ship).
2. Disabling bus lane restriction they start to spawn and drive to ship harbor/ cargo train station.
3. Turning the restriction on blocks spawning again.
4. Destination of these trucks, as far as I looked, are shops located next to bus lane, although other trucks don't have problem with delivering goods.

### Log files

not necessary I believe

### Savegame?

not necessary I believe

### Screenshots?

not necessary I believe

### Notes or questions?

Compatibility Report is not showing any conflicts with TM:PE.

**Comment by aubergine10** [comment]
This will be fixed by PR #1382 which will be released in TM:PE 11.6.4.8 hopefully within next 24 hours.
