### ISSUE TITLE
Settings not saving/loading in test build

### ISSUE THREAD

**Issue by Adreos** [CitiesSkylinesMods/TMPE#1384]
### Describe the problem
In the Test build of Presidents edition the settings for the mod are not saving and/or loading.

### Steps to reproduce

1.  Use TEST build instead of Stable build.
2. Make any setting change like a lane connection
3. Save game
4. Load game
5. The mod changes will be removed.

### Log files

http://adreos.adreos.com/output_log.txt
http://adreos.adreos.com/TMPE.log

### Savegame?

This happened across multiple different saves

### Screenshots?

https://www.youtube.com/watch?v=2mnZREGbtQI

### Notes or questions?
This is only happening in the TEST build. The STABLE build is working just fine. I am subscribed to both version of TMPE but I keep the one I'm not using disabled.

**Comment by aubergine10** [comment]
Looks like you have two versions of TMPE subscribed at same time, which will always cause settings to fail.

Try unsubscribe one of them (disabling is not enough, due to zombie assembly issue with Mono framework that the game runs in) and see if that fixes it?

**Comment by aubergine10** [comment]
@Adreos did removing the other TM:PE mod solve the issue?

**Comment by aubergine10** [comment]
Good, glad it's fixed :)
