### ISSUE TITLE
Mod features do not work as expected

### ISSUE THREAD

**Issue by CNColorful** [CitiesSkylinesMods/TMPE#1388]
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/8043034/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/8043036/TMPE.log)

**Comment by krzychu124** [comment]
@CNColorful unsubscribe this https://steamcommunity.com/sharedfiles/filedetails/?id=2399343344 and Traffic Manager will start working correctly. You already have this https://steamcommunity.com/sharedfiles/filedetails/?id=2040656402 which is pretty much the same thing and you can't have/use both installed/subscribed at the same time

**Comment by krzychu124** [comment]
You **have to unsubscribe** the first one, Disabling it won't work. Only one version can be subscribed.

**Comment by CNColorful** [comment]
I don't have the first one。I tried to re-download the game and it still works发自我的手机-------- 原始邮件 --------发件人： Krzysztof ***@***.***>日期： 2022年2月11日周五 02:17收件人： CitiesSkylinesMods/TMPE ***@***.***>抄送： CNColorful ***@***.***>, Mention ***@***.***>主    题： Re: [CitiesSkylinesMods/TMPE] Mod features do not work as expected (Issue #1388)
You have to unsubscribe the first one, Disabling it won't work. Only one version can be subscribed.

**Comment by krzychu124** [comment]
The thing is that TMPE.log you've posted is listing that mod. Check again on "Mods" tab and then "Steam workshop". If Traffic manager still does not work as expected upload **output_log.txt** and **TMPE.log** again

**Comment by CNColorful** [comment]
Thank you ，I'll probably send it to you around 4pm Beijing time-------- 原始邮件 --------发件人： Krzysztof ***@***.***>日期： 2022年2月11日周五 02:30收件人： CitiesSkylinesMods/TMPE ***@***.***>抄送： CNColorful ***@***.***>, Mention ***@***.***>主    题： Re: [CitiesSkylinesMods/TMPE] Mod features do not work as expected (Issue #1388)
The thing is that TMPE.log you've posted is listing that mod. Check again on "Mods" tab and then "Steam workshop". If Traffic manager still does not work as expected upload output_log.txt and TMPE.log again

**Comment by krzychu124** [comment]
No feedback but provided solution should solve the problem completely.
