### ISSUE TITLE
Possible issue with 'Dark Asphalt' Big Parking Lot assets

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1394]
### Describe the problem

A user on Steam has reported that the `Dark Asphalt` versions of Big Parking Lots aren't being used.

![image](https://user-images.githubusercontent.com/1386719/153737812-e422a240-df8d-4a9c-adfb-a4302f87046f.png)

I'm already using the normal BPL assets so I'll do some testing tomorrow to see if I can reproduce the issue.

EDIT: Link to assets in workshop https://steamcommunity.com/sharedfiles/filedetails/?id=2132447662

**Comment by krzychu124** [comment]
From the asset description 
> This pack contains the same roads as the Basic Version and the Dark Asphalt Expansion with a dark road color. You could do the same with Network Skins 2 but if you like you can subscribe here!

**Comment by krzychu124** [comment]
Also... keep in mind that Parking AI is slightly bugged, so don't expect miracles 😂 
It's number 2 on my list things to improve, number 1 - vehicle priority behavior is in progress so it might take some time till I switch to next thing especially if I discovered new things (turn signals, right hand priority rule if moving off priority road) - deserve to be 1a, 1b etc.🤣
