### ISSUE TITLE
Road intersection control, editing lane connection, roadside parking control and other related functions are hidden in road intersection editing

### ISSUE THREAD

**Issue by KHY-afk** [CitiesSkylinesMods/TMPE#1409]
After turning on the intersection control, the control switch icons such as sidewalk and U-turn seem to be hidden, only the mouse arrow moves to the hidden ones. I can only see the corresponding control switch icon at the switch, and I did not report a MOD conflict when I entered the game. Only road speed control and lane change guidance arrows now display properly. I've also tried troubleshooting with the compatibility report mod, but it still doesn't work. Find out what's wrong. All intersections now have this proble
screenshot:https://steamcommunity.com/sharedfiles/filedetails/?id=2753232272
log:[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/8067721/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/8067722/output_log.txt)
m

**Comment by krzychu124** [comment]
Could you list assets used on that intersection?
Is it elevated (doesn't look like it is)?

Have you tried creating similar intersection to check if it's asset issue or placement, height, terrain? 🤔

**Comment by KHY-afk** [comment]
All roads and road intersections have this problem. I checked MOD, assets and game integrity, but I can't solve this problem. This problem has appeared since the release of the airport DLC. It didn't have this problem before, and I am also the first Encountered this issue once.

**Comment by KHY-afk** [comment]
All roads and road intersections have this problem. I checked MOD, assets and game integrity, but I can't solve this problem. This problem has appeared since the release of the airport DLC. It didn't have this problem before, and I am also the first Encountered this issue once.

**Comment by KHY-afk** [comment]
> 您能列出在该交叉点上使用的资产吗？它是否升高（看起来不像）？
> 
> 您是否尝试过创建类似的交叉点来检查是资产问题还是位置，高度，地形？🤔

All roads and road intersections have this problem. I checked MOD, assets and game integrity, but I can't solve this problem. This problem has appeared since the release of the airport DLC. It didn't have this problem before, and I am also the first Encountered this issue once.

**Comment by krzychu124** [comment]
Have you tried starting new game and original, vanilla assets? 

The main problem is: it seems that you are the only one with that problem and TrafficManager has 1.5Million subscriptions.

Does the `Lane Connector` tool works on that or any other intersection?
Is the `Junction Restrictions` tool the only tool that doesn't work?

It would be awesome if you could record short clip showing the problem.

**Comment by KHY-afk** [comment]
> 你有没有试过开始新游戏和原创的香草资产？
> 
> 主要问题是：似乎您是唯一一个有这个问题的人，而TrafficManager拥有150万订阅。
> 
> 该工具是否适用于该交叉点或任何其他交叉点？该工具是唯一不起作用的工具吗？`Lane Connector``Junction Restrictions`
> 
> 如果您可以录制显示问题的短片，那就太棒了。
I am also helpless. I've tried countless ways but still can't find the cause of the problem. I recorded a video. I demonstrate the general situation in the video. The MOD function is normal and does not affect the use, but some of the control switch icons are hidden. In the whole game, only this MOD has problems at present. I also consulted the players who have backed it up, and none of them have this problem.

https://user-images.githubusercontent.com/64994772/154275281-5f6f5217-628a-4104-9397-a042932e9560.mp4

**Comment by aubergine10** [comment]
If you disable these two mods does it make a difference:

  * 572888650    Remove Need For Power Lines
  * 576997275    Remove Need For Pipes

**Comment by krzychu124** [comment]
@aubergine10 to me it does not make sense that gui overlays which are rendered on top of everything using UI camera (after rendering 3d worlds) are not visible if you don't hover on them... It looks more like incorrect order of rendering but... we can't change it

**Comment by KHY-afk** [comment]
> @aubergine10对我来说，如果您不将鼠标悬停在使用UI相机（渲染3D世界之后）在所有东西之上渲染的GUI叠加层是不可见的，这是没有意义的......它看起来更像是不正确的渲染顺序，但是...我们无法改变它

The problem has been solved, I reset all the settings of TMPE, then it is normal, thanks

**Comment by krzychu124** [comment]
Did you set overlay transparency to... 100% (means invisible)?
![Blinking white guy: The three stages of incredulity](https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif)

--
@aubergine10 I think we should adjust min. setting when you will be changing those options 😄

**Comment by krzychu124** [comment]
Ok, thank you for confirmation it was the issue with transparency values. I'm closing the issue, we will improve that. 🙂

**Comment by aubergine10** [comment]
I'll be fixing that as part of the mod options overhaul stuff.
