### ISSUE TITLE
If savegame data fails to load, we should not attempt to persist defaults later

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1412]
This arises from discussion here:

https://github.com/CitiesSkylinesMods/TMPE/pull/1378#discussion_r807382870

> **krzychu:** I think we shouldn't try to save anything if failed to load, that won't overwrite old data, so in case of a bug in load code it could be loaded after applying hotfix - IIRC game is cloning mod data container so even if you not longer have a mod, data will be migrated to new saves.

> **aubergine:** If the data fails to load, the `LoadData()` method will still `return false` just like it previously did, which results in `loadingSucceeded = false` at the call site - that currently has no effect on whether `SaveData()` gets invoked later.

We'd need to store value of `loadingSucceeded`, ideally more granular (eg. which chunk of loading failed - all of it, just mod options, something else?) - and then prevent associated `SaveData()` calls later on?

**Comment by krzychu124** [comment]
That won't solve that problem but it can greatly help in case of #1426 which we can't reproduce.

**Comment by aubergine10** [comment]
I could probably add something to same code paths being tweaked in https://github.com/CitiesSkylinesMods/TMPE/pull/1425 ?

We just need to remember success/fail of the load data and then have save data behave accordingly. But, what happens if user alters their options between failed load and next save? I'm not sure which is more frustrating for the user :/

**Comment by krzychu124** [comment]
I think the key here is to inform the user about the problem with loading settings and suggest to reload the same savegame (if not bloated with fragile mods it will work) or restart game and try again. I've got report from the user with mentioned issue that it somehow loaded at 3rd attempt. The exception is triggered in the internals of binary serialization, dll that is running serialization on MacOS is exactly the same as on Windows so... no idea that is going on 🤷‍♂️

**Comment by aubergine10** [comment]
> I think the key here is to inform the user about the problem with loading settings

There's already some code in there to display a message, but it's commented out (and the message text is somewhat confusing I think).

https://github.com/CitiesSkylinesMods/TMPE/blob/59e4e20a0bc2c5a06b667ec6ed97037ec96de755/TLM/TLM/Lifecycle/SerializableDataExtension.cs#L93-L99

Same sort of thing for save data - message is commented out.
