### ISSUE TITLE
Multiple users report roundabout quick-setup not working

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1429]
![image](https://user-images.githubusercontent.com/1386719/154869315-d65d34c5-2c3d-42f4-a405-f0231324b305.png)
![image](https://user-images.githubusercontent.com/1386719/154869327-c35e7271-656d-413d-9478-323dfd8e6469.png)

I've asked for more info about what specifically does "not working" mean.

**Comment by krzychu124** [comment]
If they ignore signs - increase simulation accuracy to high+
I feel like adding that options only increased number of reports. I'll recheck conditions, but currently anything below "high" makes priority signs useless and will be even worse when I push fix for issue with segment length.

For roundabouts.. hard to say what is wrong since we didn't really change anything. I'll try to test that later today

**Comment by aagavin** [comment]
Also. Seeing this. Let me know if I can help.

**Comment by aubergine10** [comment]
@aagavin Yup, please give a detailed explanation of what "not working" means :)

**Comment by aagavin** [comment]
For me the roundabout setting don't apply at all. Here is a video https://youtu.be/84nm0kF__7s

**Comment by krzychu124** [comment]
Wait.. didn't you actually show it works, at the end of the clip?😂 You need to hover the segment, not the node.

**Comment by aagavin** [comment]
I can show it again, none of the roundabout rules are being applied.

**Comment by krzychu124** [comment]
@aagavin we'd got another similar reports but it turned you that user did not enable any roundabout-specific settings in the mod options screen. Could you check if all settings you want to apply are enabled after loading the savegame and if so, which of them does not work for you? 
I've tested that feature yesterday and didn't notice any issues, everything seem to be working as advertised, but... if you disable all of them, it will do literally nothing after click.

**Comment by aagavin** [comment]
@krzychu124 ok can confirm! That was the issue. This is not a new install, so maybe this got wiped somehow. 

Thanks!

**Comment by krzychu124** [comment]
Yes, one of hotfixes to the Stable version accidentally introduced a bug which prevented saving of the options so they were reset after loading that savegame. We've fixed it quickly but... who saved game using that faulty version has lost mod options configuration by overwriting everything with default settings 😕 

Thank you for confirmation that was the problem. Have a nice day, I'm closing this issue 😉

**Comment by aubergine10** [comment]
Will be fixed by PR #1455 which ensures pre-requisite features are enabled for any roundabout / priority road setup options.
