### ISSUE TITLE
Disable despawning by vehicle type

### ISSUE THREAD

**Issue by Marconius6** [CitiesSkylinesMods/TMPE#1434]
### Describe your idea
I like to play with despawning disabled, for a more realistic and challenging experience. However, I've been noticing more and more that trains are... kind of terrible; their AI seems limited at best, and unlike road traffic, you have relatively few options to do deal with them (no lights, and they ignore yield signs half the time).

So I would like to be able to play with despawning disabled for most things, but trains still despawning as in vanilla, if they get stuck. I think this would be a good compromise, and seems relatively easy to implement as well.

Specifically, I would put a list in the options menu under the "disable despawning" setting, that would allow you to choose exactly which vehicles you want to disable despawning for. A similar list already exists under the Maintenance options for one-time despawning.

**Comment by lokpro** [comment]
I think so.
I thought the Maintenance options one-time despawning was also for the (!🚗) icon and found it isn't.

**Comment by aubergine10** [comment]
Just checked the despawn code (notably it all routes through `VehicleBehaviorManager.MayDespawn(Vehicle)`) and there is currently no distinction of vehicle type in that method.

```csharp
public bool MayDespawn(ref Vehicle vehicleData) {
    return !Options.disableDespawning
        || ((vehicleData.m_flags2 & (Vehicle.Flags2.Blown | Vehicle.Flags2.Floating)) != 0)
        || (vehicleData.m_flags & Vehicle.Flags.Parking) != 0;
}
```

Call sites would either need updating to pass in `ExtVehicleType`, or the method itself would need udpating to determine that (if possible).

![image](https://user-images.githubusercontent.com/1386719/155438908-76aa3b2d-86db-446b-8b9c-26b3c7df20a4.png)

**Comment by krzychu124** [comment]
@aubergine10 we just need to pass vehicle id. It shouldn't be too hard. I'll try to create PR with changes later today.
