### ISSUE TITLE
Blank TM:PE toolbar buttons in Scenario Editor

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1449]
> _Originally posted by @kianzarrin in https://github.com/CitiesSkylinesMods/TMPE/issues/1422#issuecomment-1056996064_ :
>  
> ![blank-buttons](https://user-images.githubusercontent.com/1386719/156434065-939ef372-7b20-4f45-84d9-a5bc7841ef69.png)
> ![image](https://user-images.githubusercontent.com/26344691/156381729-13b8881e-0b26-4bc6-b3a1-9ff6a53d0fa7.png)
red arrow is bad green arrow is good

**Comment by aubergine10** [comment]
@kianzarrin I'm unable to reproduce the issue - here's what I see in-game:
![Screenshot 2022-03-02 192427](https://user-images.githubusercontent.com/1386719/156434296-b180b33c-6ff7-497a-b130-2612e8df3185.png)

**Comment by aubergine10** [comment]
@kianzarrin At a guess it might need a call to `RebuildMenu()` adding to `OptionsManager.OnAfterLoadData()` - can you try that and see if it solves the blank button issue for you?

**Comment by krzychu124** [comment]
Try Scenario editor but instead of savegame select map. All TM:PE features are disabled and then enable them (no idea why there is no TTL) you will see this:

![image](https://user-images.githubusercontent.com/19638970/156448400-8e143bec-e697-42bb-8699-40316eed8d05.png)

I think it affects `New Game` mode in general, but I haven't check regular new game yet.

**Comment by krzychu124** [comment]
Btw, some textures from atlas are not available in Scenario editor so backgrounds are blank.

**Comment by aubergine10** [comment]
TTL is disabled in all editors currently as per details in #959

**Comment by krzychu124** [comment]
There is nothing about Map/Scenario editor... We need to test it, but now I'm 99/5% sure that all features will work properly in the Map and Scenario editor. It should be limited in Asset Editor and disabled for Theme Editor

**Comment by aubergine10** [comment]
What's the best way to identify the context (eg. which editor is active) - `TMPELifecycle.Mode` ?

**Comment by krzychu124** [comment]
> What's the best way to identify the context (eg. which editor is active) - `TMPELifecycle.Mode` ?

hmm, why not `TMPELifecycle.AppMode`?

**Comment by aubergine10** [comment]
> hmm, why not `TMPELifecycle.AppMode`?

Ok, will use that.

BTW, if features aren't getting enabled it's likely because `OptionsManager.LoadData()` isn't being called, as that's what's setting defaults.

What's the best way to apply `-NoWorkshop` launch option these days? I'll need to do some testing in editors and don't want to manaully disable 140+ mods / 5600+ assets.

**Comment by krzychu124** [comment]
> What's the best way to apply -NoWorkshop launch option these days? I'll need to do some testing in editors and don't want to manaully disable 140+ mods / 5600+ assets.

Hmm you can use Load Order mod + profiles. It's pretty powerful, right @kianzarrin 😄

**Comment by krzychu124** [comment]
It looks like there is something wrong or different than before because reading the log it should load defaults but does not at all

**Comment by aubergine10** [comment]
Yeah, I'm testing it now.

**Comment by krzychu124** [comment]
I almost finished fixing UI/textures etc.

**Comment by aubergine10** [comment]
Ah, I think I know what's causing it - if config is `null` (eg. due to new game)... it's not going to call `OptionsManager.LoadData()` = no defaults get set.

As for enabling the options resulting in blank buttons, that's likely a fubar on my part in recent PR - pretty sure I know what's causing it but just need to do some extra checking.

Both these things should be relatively easy to fix; will send PR shortly.

> I almost finished fixing UI/textures etc.

Ah, I just created issue to track that hehe https://github.com/CitiesSkylinesMods/TMPE/issues/1450

Does your fix include missing button textures?

**Comment by krzychu124** [comment]
> Does your fix include missing button textures?

Everything what I found and it probably has nothing to your recent changes 😉

**Comment by aubergine10** [comment]
The missing defaults are due to my recent changes. Need to ponder how to better handle the default option values (have some ideas. just not sure which is best approach).

**Comment by krzychu124** [comment]
> The missing defaults are due to my recent changes. Need to ponder how to better handle the default option values (have some ideas. just not sure which is best approach).

Yeah, I leave fixing missing defaults for you 😄

**Comment by krzychu124** [comment]
> The missing defaults are due to my recent changes. Need to ponder how to better handle the default option values (have some ideas. just not sure which is best approach).

@aubergine10 I think you can also revive and improve that commented out error message when loading save data fails so at least user will know that something went wrong, since now is not even aware of. 🤞

**Comment by aubergine10** [comment]
Yup - will do.

**Comment by kianzarrin** [comment]
I tried with new game.

**Comment by kianzarrin** [comment]
https://cdn.discordapp.com/attachments/948480860670291968/948541891555774534/output_log.txt
https://cdn.discordapp.com/attachments/948480860670291968/948541891752898570/TMPE.log
These are logs just in case

**Comment by aubergine10** [comment]
Note that #1425 will also need merging to fix the default values for mod options.
