### ISSUE TITLE
Background textures missing in Scenario Editor (and others?)

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1450]
As mentioned by @krzychu124 in https://github.com/CitiesSkylinesMods/TMPE/issues/1449#issuecomment-1057372799 :

> some textures from vanilla atlas are not available in Scenario editor so backgrounds are blank.

Example (from a winter map hence snow in bg):

![image](https://user-images.githubusercontent.com/1386719/156466286-3bd10380-343e-46e2-9a50-209205618326.png)

**Comment by aubergine10** [comment]
Also affects mod option tabs, keybind buttons, etc:

![image](https://user-images.githubusercontent.com/1386719/156467524-f5de6b85-8e4f-49ce-8dd4-39bc46769a83.png)

And the debug panel:

![image](https://user-images.githubusercontent.com/1386719/156467582-6ccf8f65-3659-440c-8713-d0f694a987dd.png)

**Comment by krzychu124** [comment]
yeah, what's new panel, speed limits window, lane arrows tool window, menu background, and so on. It takes `InScenarioEditor` atlas instead of `Ingame`
