### ISSUE TITLE
Cyclists levetating without their bikes

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1472]
Anyone seen anything like this? (I'm currently testing PR #1471 although it's unlikely to be the case).

My cyclists are all floating down streets with no bikes - no idea if it's TM:PE or some other mod.

![image](https://user-images.githubusercontent.com/1386719/158746929-2d97201b-09cf-4465-8f95-5d562abed1e7.png)

They seem to be leaving their bikes at the point where they'd normally spawn them:

![image](https://user-images.githubusercontent.com/1386719/158747056-013833b5-c327-4016-a997-047baa017621.png)

![image](https://user-images.githubusercontent.com/1386719/158747077-30160a0e-9b6f-4592-bcbc-2dde9b9989f0.png)

Recently updated mods:

![image](https://user-images.githubusercontent.com/1386719/158747209-1e3f8f56-9e6a-4d8f-b6ac-615f2b2262bf.png)

Recently subscribed mods:

![image](https://user-images.githubusercontent.com/1386719/158747258-5d02c7b9-00bb-49a0-be54-954207af3bad.png)

**Comment by aubergine10** [comment]
When cyclist would normally "pocket car" their bike (eg. arriving at work or a train station) the stranded bike will disappear from outside whatever building they spawned from.

It's happening to all cyclists in the city - this is scene outside one building:

![image](https://user-images.githubusercontent.com/1386719/158747972-797d1706-1176-400d-93ab-16d08bf7432e.png)

**Comment by chameleon-tbn** [comment]
Yes, have the same, not figured out which mod causing it

**Comment by aubergine10** [comment]
my mods list, excluding vanilla.

green = confirmed OK

```diff
  * 1552053911   Trailer Variation Loader
  * 724382534    One-Way Train Tracks
  * 2474585115   CSL Music Mod
  * 1934023593   RM Crossings 3.0 
  * 940299505    AnimUV Params
  * 2496034669   Movable Bridge Mod
  * 818641631    Ambient Sounds Tuner
  * 1420955187   Real Time
  * 954067599    PropRotating Params
    2107292536   Pink Shrimp Harbor Theme Mix
    2069725167   San Minato 2
  * 2172948371   Emergency Vehicle Priority 0.0.1
  * 2170999920   HDRI Haven Cubemap Pack 3
  * 2126881996   Shadow Distance Fix
  * 2494660480   Fish Warehousing
  * 2559042012   Better HealthCare Toolbar Mod
  * 1777173984   Broken Node Detector 0.6
  * 2139035212   Garbage Bin Manager 0.3
  * 1771841274   HDRI Haven Cubemap Pack 2
  * 973512634    Sort Mod Settings
  * 2247089222   MetroSoundDefinition_SH
  * 1999271351   OxylonSoundPackUSA
  * 2513657277   Hide it, Bobby! 1.32
  * 2152013104   Network detective1.0
  * 793176674    Sharp Textures
  * 1806759255   Customize It! Extended
  * 1412844620   Realistic Walking Speed
  * 672248733    Ultimate Eyecandy 1.5.2
  * 2502526929   Better Road Toolbar
  * 2041457644   Patch Loader Mod v2.1.2
  * 1209581656   Relight
  * 2101551127   Repaint 1.4.2
  * 1969432061   OxylonEuroSoundpackNED
  * 2220870813   TramSoundAddON
  * 2008325200   TrainPackDBAG
  * 1969428208   OxylonEuroSoundpackAUT
  * 928103306    Ship Converter
  * 1886877404   Custom Effect Loader
  * 903347963    Transparent Selectors
  * 1530376523   Railway Replacer
  * 1274199764   Network Tiling
  * 515489008    Extra Train Station Tracks
  * 650436109    Quay Anarchy
  * 1551413082   Sunless Radio
  * 1394468624   Advanced Stop Selection
  * 1183931915   Cubemap Replacer
  * 707497031    Tram Station Track
  * 1591584836   HDRI 2K Cubempap Pack
  * 1585691173   HDRI Haven Cubemap Pack
  * 1801953480   Natural Disasters Overhaul
  * 820157360    Spawn Points Fix
  * 899063611    UKSoundPack
  * 476141470    Craft_Inc's Synthwave & 80s-Retro-Music pack
  * 1289991722   Music pack: Vault Archives Music Pack
  * 2077102792   AD Cloud Enabler
  * 2053661585   Emergency Lights Manager V2
  * 793346248    Decal Hover Area
  * 883332136    Any Road Outside Connections
  * 2037888659   Instant Return To Desktop
  * 1348627392   Tides
  * 1568910950   ZONE Radio 
  * 1562650024   Rebalanced Industries
    812713438    Dynamic Resolution
  * 1844442251   Klyte's Fine Road Tool 2.0.4
  * 608517757    Sub-Buildings Tabs
    1393820309   Ticket Price Customizer
  * 530771650    Prefab Hook
  * 1776052533   Stops and Stations
  * 2085018096   Node Spacer
  * 530871278    Daylight Classic
  * 1435741602   Snooper
  * 2065332413   Crash FM
  * 1556715327   Show It!
  * 2133885971   Find It! 2.8.0
  * 2027161563   Lifecycle Rebalance Revisited 1.6.2 
  * 2755226186   Crash FM: Burnout 3
  * 1764637396   Toggle It!
  * 2483920668   Fog Controller
+  * 2499771767   Intercity Bus Control
  * 2674842365   Curb Height Adjuster 1.3
  * 2405917899   RON - the network replacer 0.9.2.3
  * 1658679290   Forest Brush
  * 2654110611   Transit Vehicle Spawn Delay 1.2.2
  * 611254368    Environment Changer
  * 2487213155   UI Resolution 1.1.2.3
  * 2511258910   Building Spawn Points 1.2.3.2
  * 2723628116   Control It!
  * 2755228228   Crash FM: Burnout Revenge
  * 2197863850   BOB - the tree and prop replacer 0.9.1
  * 2448824112   Load Order Mod 1.3
  * 1094334744   Procedural Objects 1.7.6
  * 870291141    Random Train Trailers 2.3.3
  * (local)      TM:PE 11.6.5.1 STABLE - PR #1471
  * 2016920607   RICO Revisited 2.4.12 
  * 2025147082   Realistic Population 2 2.0.2
  * 2019097300   RM Unconnected Tracks 
  * 2255219025   Unified UI 2.2
  * 2698595602   Network Skins
  * 2472062376   Node Controller Renewal 3.1.3.2
  * 780720853    Vehicle Effects 1.9.2
  * 1664509314   Custom Animation Loader (CAL)
  * 502750307    Extra Landscaping Tools
  * 512314255    More Network Stuff
  * 689937287    Surface Painter
  * 576327847    81 Tiles (Fixed for C:S 1.2+)
  * 2527486462   Tree Anarchy 1.3.5
  * 497033453    UnlimitedOutsideConnections
  * 1899640536   Theme Mixer 2
  * 1656549865   Rebuild It!
  * 2133705267   Advanced Building Level Control 1.0.5
  * 1619685021   Move It 2.9.5
  * 1567569285   Achieve It!
  * 1661072176   Empty It!
  * 1548831935   Advanced Vehicle Options 1.9.7
  * 2105755179   FPS Booster 0.7.0
  * 815103125    Extra Vehicle Effects
    625608461    Adaptive Prop Visibility Distance
  * 2696146165   Extended Managers 1.0.3
  * 2159934925   Intersection Marking Tool 1.8.0.762 [BETA]
  * 618536610    AST: KRA Sound Pack
  * 1844440354   Klyte's Fine Road Anarchy 2.0.2
  * 2556133736   Network Multitool 1.3.0.92 [BETA]
  * 2633433869   Compatibility Report v0.7.5
  * 2069057130   No Big Truck 1.2.4.2
  * 591137516    Redcomet's Municipal Sound Pack
  * 2731207699   Loading Screen Mod for Airports DLC (Temporary Updated)
  * 2399204842   Harmony 2.2-0 (EXPERIMENTAL)
  * 2389414419   Zoning Adjuster 1.5.1 
  * 533958715    Real London Sound Pack
  * 1721492498   Optimised Outside Connections
  * 1393452031   Parkify r1.0.6
  * 2696146766   Prop Anarchy 0.7.5
  * 1433003062   Rotors FlipXZ
+  * 2746241436   SingleTrainTrackAI
  * 2778750497   ACME 0.1
```

**Comment by krzychu124** [comment]
@aubergine10 could you generate Harmony report and then post output_log.txt? It might be new or old mod that added a patch to `CitizenAI/ResidentAI/TouristAI SimulationStep()` - maybe overwritten TMPE one?

**Comment by aubergine10** [comment]
@krzychu124 :

* [harmony_report.txt](https://github.com/CitiesSkylinesMods/TMPE/files/8405031/harmony_report.txt) - trimmed output_log with just the harmony report bits
* [output_log.zip](https://github.com/CitiesSkylinesMods/TMPE/files/8405032/output_log.zip) - full output_log file

**Comment by aubergine10** [comment]
@chameleon-tbn which ver of TMPE are you using?

**Comment by chameleon-tbn** [comment]
> @chameleon-tbn which ver of TMPE are you using?

I'm atm using local 11.6.5.27308 ... imho i've not seen it with that version any more... but i'll keep an eye on it

**Comment by aubergine10** [comment]
I was able to reproduce issue from current `master` build last night so it still seems to be there. Pretty sure it's issue with some other mod.

**Comment by krzychu124** [comment]
Thanks for harmony report. Hard to say what is it, I only noticed there might be a compatibility issue with Movable bridge mod (we are skipping its transpiler) but nothing special about bikes 🤷‍♂️

**Comment by krzychu124** [comment]
hmm, does it affect only workshop bikes or all?

**Comment by aubergine10** [comment]
> hmm, does it affect only workshop bikes or all?

Not sure as I've disabled vanilla bicycles via LSM `skip.txt`:

![image](https://user-images.githubusercontent.com/1386719/161589676-27cac92b-bb50-4cd5-86ef-497f89e2e28c.png)

These are the workshop bicycles I'm using: https://steamcommunity.com/sharedfiles/filedetails/?id=1343983364

**Comment by krzychu124** [comment]
I would try with vanilla, probably won't make any difference but may give us a tiny hint if they'll actually work 😂

**Comment by krzychu124** [comment]
@aubergine10 could you check with ModTools if floating citizen has `m_vehicle` field set to some number? It should be the id of bike otherwise bike simulation won't work at all.

**Comment by aubergine10** [comment]
I don't seem to be able to get the citizen to open in the scene explorer - only the bicycle vehicle:

![image](https://user-images.githubusercontent.com/1386719/161807433-2c9d1da5-fcd5-45cf-a100-5c3e9c060e84.png)

![image](https://user-images.githubusercontent.com/1386719/161807636-c884d979-5ffa-44c2-ba37-9138ea8b8312.png)

vehicle.Info:

![image](https://user-images.githubusercontent.com/1386719/161807897-0bf82160-dcd1-4036-8ee0-e5f5135167fc.png)

![image](https://user-images.githubusercontent.com/1386719/161808077-931fca2c-a16a-4539-af8c-61af6a38c537.png)

**Comment by krzychu124** [comment]
> I don't seem to be able to get the citizen to open in the scene explorer - only the bicycle vehicle:

So when you click owner it won't move camera to that cim?

Check `m_citizenUnits` of bike, it should contain ref to `Citizen` (aka driver) and then check `m_instance` of the `Citizen` (flags etc.)

**Comment by aubergine10** [comment]
![image](https://user-images.githubusercontent.com/1386719/161814570-3838fc1b-30c3-4fc9-97fc-fd412df2f1dd.png)

citizen:

![image](https://user-images.githubusercontent.com/1386719/161814654-85f6af99-da1f-4e69-a254-28d4566b6fdf.png)

instance:

![image](https://user-images.githubusercontent.com/1386719/161814745-98c9eeb2-3a50-404b-a8ec-bedfbdc20bb9.png)

flags:

![image](https://user-images.githubusercontent.com/1386719/161814860-6d1714e3-0739-4ab8-aaff-c3404d88c244.png)

![image](https://user-images.githubusercontent.com/1386719/161814917-9327cb15-9b27-42a2-9aef-c64eebf4f4b1.png)

CitizenInfo:

![image](https://user-images.githubusercontent.com/1386719/161814998-1a1a2fcc-4352-4712-8457-d87c7dd228a7.png)
![image](https://user-images.githubusercontent.com/1386719/161815042-0788e9ca-c03e-48f4-a54e-de23a4ad5bf0.png)

**Comment by aubergine10** [comment]
Ok, it's a mod - just disabled a batch of mods and bicycles now working again... just need to enable one  by one to work out which is causing the issue....

**Comment by krzychu124** [comment]
Try _Optimized Outside Connections_. I did tests with vanilla and without that mod, then another test with that mod and also bike assets so it must be either that mod alone or combination with Realistic Walking Speed -> they both patch the same method.

**Comment by aubergine10** [comment]
Cyclists are OK with `Optimised Outside Connections` mod, but I currently have `Realistic Walking Speed` mod unsubbed so I will try that next.

**Comment by aubergine10** [comment]
`OOC` + `RWS` = still working

continuing to test other recently unsubbed mods....

**Comment by krzychu124** [comment]
hehe, for me it didn't work - it's either `OOC` + RWS` or one of them with TM:PE... I don't use any other mods touching simulation code 🤔 

> EDIT: It could possibly be due to load order issue?

Hmm, could be. I installed OOC after playing some time and immediately noticed missing bikes but now after shuffling enabled/disabled I can't find any 🤷‍♂️ I'm testing Parking AI now, maybe something is broken there when combined with other mods.

**Comment by aubergine10** [comment]
I've re-enabled most mods now so it certainly looks like a load order issue, most likely between `OOC` and something else, probably `RWS`.

@kianzarrin Here's my logs for working load order - as mentioned above the issue is likely caused by load order of `Optimised Outisde Connections` and `Realistic Walking Speeds` mods so whatever order they are in these logs seems to work (and the reverse order likely breaks cyclists). Is it possible to update LOM so that it ensures this order?

* [LoadOrder logs.zip](https://github.com/CitiesSkylinesMods/TMPE/files/8421350/LoadOrder.zip)
* [other logs.zip](https://github.com/CitiesSkylinesMods/TMPE/files/8421356/other.logs.zip) - output_log and tmpe

**Comment by svnolte** [comment]
If I remember correctly, CO wrote that they optimised outside connections in the Airports DLC release. Fewer trains with less than 10 passengers, and the like...

**Comment by kianzarrin** [comment]
Does the default load order work?

**Comment by kianzarrin** [comment]
@chameleon-tbn

**Comment by chameleon-tbn** [comment]
> Does the default load order work?

Yes. I have now 130 mods and Not this issue any more. But i must say, that i use from all mods where available Beta/Alpha/pre-release Versions.

**Comment by aubergine10** [comment]
Closing this as issue resolved.

Wiki guide: https://github.com/CitiesSkylinesMods/TMPE/wiki/Floating-cyclists-and-discarded-bicycles
