### ISSUE TITLE
ICustomSegmentLights overhaul

### ISSUE THREAD

**Issue by Elesbaan70** [CitiesSkylinesMods/TMPE#1474]
The `ICustomSegmentLights` API needs an overhaul to support several features under consideration or active development. These features include:

1. Displaced lanes (in development)
2. Traffic Lights per lane (planned)
3. Custom lane grouping (under consideration)

Here is my proposal:

1. Instead of `ExtVehicleGroup`, lights would be grouped on an object which can take on new properties in the future:

```cs
public struct SegmentLightGroup {

    public ExtVehicleType VehicleType { get; set; }
}
```

4. The API-level exposure of the various collections that make lane grouping work would be deprecated.
5. Indexer properties would be used for accessing each `ICustomSegmentLight` by group or by lane index.
6. Most or all methods and properties that rely on `ExtVehicleGroup` would be deprecated and replaced with equivalents based on `SegmentLightGroup`.

**Comment by Elesbaan70** [comment]
@krzychu124 is having way too much fun watching me discover the horrors of the TMPE code. 🤣

**Comment by t1a2l** [comment]
@Elesbaan70 why did you close this?

**Comment by Elesbaan70** [comment]
The changes described here will not be implemented. The API for traffic lights is fundamentally flawed and cannot be maintained in a backward-compatible way. @krzychu124 had warned me, but I didn't believe him. 😆

https://github.com/CitiesSkylinesMods/TMPE/issues/967#issuecomment-1073163111

The functional changes this describes are still in progress for displaced lanes, but not as an API.

**Comment by t1a2l** [comment]
I see...
