### ISSUE TITLE
[EPIC] UI design of Lane connector tool for new features.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1479]
- [x] #784
- [x] #354
- [x] #654
- [x] #1213
- [x] #1214
- [x] #1485 
- #670
- #1500
- #1498

The UI design for issues above can influence/conflict one another. So I created this issues to discuss solutions.

summary:
1- Hotkeys (https://github.com/CitiesSkylinesMods/TMPE/issues/1479#issuecomment-1074476891 will be adopted for hotkeys/modifiers. thought we might need a new one for creating dead ends.)
2- how should lane connections differentiate between 
      - making new connection VS removing older connection (#1485) 
      - unidirectional VS bidirectional 
      - dead ends (#1213) : use :X: icon
3- how should we differentiate between car/track/mixed lanes: 
      - for tracked vehicles we can use 🔺 🔻 🔶 to indicate the direction of the lane (it tells us if the lane is bidirectional, it does not tell us if the lane connection is bidirectional).
      - for car lanes we can just use 🟠 because they are always uni-directional anyways. 
      - for mixed lane we can put 🔺 over 🟠 to create a pointy circle ![image](https://user-images.githubusercontent.com/26344691/159484271-6195e946-299a-4ade-8026-6e273da787d2.png)

# Problems:

Bidirectional lane connections:
- If we use arrow heads :left_right_arrow: to show the direction of the lanes there is two problems:
    - if a lane lane multiple connections then the arrow heads can overlap each other.
    - also the arrow heads can overlap with the lane end icons 🔺 🔻 🔶
    - if we use ❌ for #1213 then it can overlap with the lane end symbols above
- @aubergine10 suggested to use dashed line for bi-directional:
    - if we use dashed line then it might conflict with when we want to remove lane connection if we decide to use dashed line for that too. 
    - Also using solid line for uni-directional and dashed line for bi-directional does not seem logical. bidirectional has more connections why should we make it dashed? if anything it should be thickened.

**Comment by kianzarrin** [comment]
How about this modifier key configuration?
 - click: both car/tram/..., bidirectional if possible
 - Control+click: unidirectional
 - Alt+key: cars only
 - shift+click: tram only

**Comment by kianzarrin** [comment]
shift usually means multiple things are selected so maybe we can do it like this:
- no modifier: 
     - always unidirectional lane connection 
     - car on car-only or mixed lanes 
     - tracked vehicle (tram/metro/monorail/train) otherwise
- alt: tracked vehicle only - solves #354 and #654.
- shift:  bidirectional on bidirectional lanes | both car tram on mixed lanes
     - bidirectional lane connection on bidirectional lanes
     - both car/tram on mixed lanes

this also helps to reduce number of modifier keys we use and the shift modifier key makes more sense now.

**Comment by kianzarrin** [comment]
@aubergine10 what do you think we should do with modifier key assignments?

**Comment by aubergine10** [comment]
> The downside with this is that I think by default we should make bi-directional lane connections on bi-directional lanes so that more novice users will not get confused.

Users - both new and existing - will need to learn new stuff whichever way it works. As long as the UI (tracked via https://github.com/CitiesSkylinesMods/TMPE/issues/1214) makes it clear what's going on, there shouldn't be too much of a problem.

IMO having one-directional by default makes more sense than bidirectional; we're routing _from_ lane A _to_ lane B, and additionaly the vast majority of lanes are one-way.

The visualisation should clearly indicate:

* Default lane routings in cases where user hasn't specified custom lane routing (feint/thin dotted white lines?)
* Which lanes are bidirectional (could we overlay a double-ended arrow ↔ on the lane?)
* The direction of a lane connector (pointed triangle at ends? only show where applicable to declutter UI?)

**Comment by aubergine10** [comment]
As for modifier keys, this approach is best IMO: https://github.com/CitiesSkylinesMods/TMPE/issues/1479#issuecomment-1074476891

**Comment by kianzarrin** [comment]
@aubergine10 @kvakvs @chameleon-tbn I updated the issue. We need some brainstorming here!

**Comment by aubergine10** [comment]
>  for car lanes we can just use 🟠 because they are always uni-directional anyways

Are you sure car lanes are always unidirectional? I'm pretty sure some NExt roads that have central "turning lanes" were bidirectional lanes.

> - @aubergine10 suggested to use dashed line for bi-directional:
>     - if we use dashed line then it might conflict with when we want to remove lane connection if we decide to use dashed line for that too.
>     - Also using solid line for uni-directional and dashed line for bi-directional does not seem logical. bidirectional has more connections why should we make it dashed? if anything it should be thickened.

Yeah, this needs more thought either way. Still pondering that and the other stuff in OP.

**Comment by aubergine10** [comment]
Random idea: When an incoming lane is selected, fade (reduce opacity of) connection lines from other lanes so connections from the selected lane are more obvious in comparison to them?

**Comment by kianzarrin** [comment]
> Random idea: When an incoming lane is selected, fade (reduce opacity of) connection lines from other lanes so connections from the selected lane are more obvious in comparison to them?

don't we already make such lane connections thicker and on the top?

**Comment by aubergine10** [comment]
> I personally can't remember where we ever had a dual-direction lane. Any good example?

Bi-directional train tracks are somewhat common, and there's also some 'turning lanes' on roads that are bidirectional.

Prior implementation of lane connectors were always bi-directional. However, that caused limitations in cases where a uni-directional connector was required, so Kian change to using unidirectional connectors. But that now causes the issue of how to indicate to users a) which lanes are bidirectional and b) which connectors are bidirectional (where applicable).

**Comment by kianzarrin** [comment]
cool only dead end is remaining

**Comment by kianzarrin** [comment]
All required tasks are completed.
there are a few optional tasks to improve ascetics.
