### ISSUE TITLE
Feature Request: Hold [ALT;CTRL;SHIFT;whatever] during street/crossing creation to disable left turn

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#148]
Hi there,

awesome mod, i mainly use it's arrow tool to disallow left turns on highway mergers. I think it would be an awesome addition to have that feature on a (configurable) hotkey. 

What do you guys think?

PS: Sorry, I am not (yet) able to provide a PR. Although i do have modding expirience with unity (Kerbal Space Program), i never did a C:S mod.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/84

**Comment by VictorPhilipp** [comment]
+1 Here in Brazil you can't turn left at almost every junction with traffic lights.

**Comment by VictorPhilipp** [comment]
Would this be better as a mod option instead of modifying the build tool?

So you could default all new junctions to prevent left or right turn (depending on game RHD or LHD setting), with the option to override on junction-by-junction basis using the lane connector or lane arrow tools...?

**Comment by kianzarrin** [comment]
This is related to #537

**Comment by aubergine10** [comment]
I think this could potentially be viable for automation via a setting in mod options.

However, we'd need some way to detect medians - see #504 

For example, small roads would usually allow far-side turns ("left turn in context of conversation above), but this small 2-lane 2-way road has a median:

![image](https://user-images.githubusercontent.com/1386719/69386064-61f2b300-0cb9-11ea-90e6-a2352ea88e90.png)

The `m_canCrossLanes` flag (I think that's what it's called?) could be checked by default, but can't be relied upon - especially for workshop roads.

**Comment by aubergine10** [comment]
> VictorPhilipp Does that satisfy your needs?

Victor didn't raise the original issue, he just copied it here when we changed github repos (there wasn't a bulk move feature on github at the time).

You can find original issue here: https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/84

**Comment by kianzarrin** [comment]
duplicates #541

**Comment by aubergine10** [comment]
#148 is about applying the customisation during road placement.

#541 is about applying customisations to existing roads.

That being said, I'm not sure what is proposed in #148 is viable - all potential modifiers (Shift/Ctrl/Alt) are already consumed during road placement by mods such as Precision Engineering.

![image](https://user-images.githubusercontent.com/1386719/81728950-20321080-9483-11ea-9421-c4fab178c6b1.png)
