### ISSUE TITLE
Ctrl+Shift+Click Auto TTL w/ Dedicated Left Turns

### ISSUE THREAD

**Issue by Fireboyd78** [CitiesSkylinesMods/TMPE#1482]
### Describe your idea
- When the user holds Ctrl+Shift and clicks to setup a timed traffic light, it should attempt to add a few extra cycles that are simply dedicated left turns.

- If possible, it should take into account any existing lane arrows ~~and use those to determine~~ when determining if that particular road can have a dedicated left turn light. Roads with multiple left-turn lanes should not cause any issues or be messed with. 

- In cases where a lane goes straight & left, and there is a lane to the right of it; the left-turning lane should be for left-turns only, and the other lane should have a straight arrow added to any existing directions.

- Intersections made up entirely of one-lane roads is probably a case that should be discussed further.

- Pedestrian crossings during left turn cycles should be disabled completely. Normal crossing rules apply otherwise.

- [Optional] Priority roads with a higher speed limit (for example, a freeway exit) could have an extra cycle after the left turn cycle where they may continue turning left, as well as continue straight on - but the opposing side must wait during this cycle before going straight. Is this realistic? Not sure. But I use it often to alleviate traffic congestion on busy roads.

### Screenshots?
None (for now). Can be provided later if needed for examples.

### Notes or questions?
If possible, maybe the existing Ctrl+Click setup can simply toggle through different modes instead of forcing one type? Most of the time, using the auto setup on my intersections is a waste of time and I'm better off manually creating them by hand. Since there's no ability to save templates, this would probably be easier to implement instead.

**Comment by kianzarrin** [comment]
> When the user holds Ctrl+Shift and clicks to setup a timed traffic light, it should attempt to add a few extra cycles that are simply dedicated left turns.

How is this different from alt+click ?

**Comment by Fireboyd78** [comment]
> > When the user holds Ctrl+Shift and clicks to setup a timed traffic light, it should attempt to add a few extra cycles that are simply dedicated left turns.
> 
> How is this different from alt+click ?

Is this behavior already implemented? I could've sworn I tried different combinations and didn't notice anything.

**Comment by kianzarrin** [comment]
@Fireboyd78 you must read the hintbox!!! press that `?` and read what options is available.

**Comment by kianzarrin** [comment]
already implemented.
