### ISSUE TITLE
Quick set-up for high priority roundabout does not work. (CTRL+SHIFT+CLICK)

### ISSUE THREAD

**Issue by SkillzGamingYT** [CitiesSkylinesMods/TMPE#1494]
> # How to fix
> In mod options > TM:PE > Policies tab, make sure you set up your roundabout options as desired.
> Note: In TM:PE 11.6.5.1 and later (currently available on the TEST workshop page) some of the options are enabled by default.

### Describe the problem
Quick set-up for high priority roundabout does not work.
- Give way signs are not setup
- Intersection tools are not set up correctly.

### Log files
[CompatibilityReport.txt](https://github.com/CitiesSkylinesMods/TMPE/files/8356578/CompatibilityReport.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/8356579/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/8356580/output_log.txt)

### Screenshots
![image](https://user-images.githubusercontent.com/26197169/160261878-9aad615f-0772-40c7-b127-346bb1e8bd38.png)
![image](https://user-images.githubusercontent.com/26197169/160261879-1eb3ca88-6e1b-482a-906a-df13c315440c.png)

### Notes or questions?
- I used Roundabout builder to build the roundabout. Although TM:PE auto-setup options are disabled.

**Comment by krzychu124** [comment]
Did you enable any roundabout rule in the mod Policies settings?

**Comment by aubergine10** [comment]
Also, are the features enabled in mod options > TMPE > Maintenance tab?

**Comment by BenOniKenobi** [comment]
Hi!
Just wanted to say that I have the same issue with a new city I just started. My old city worked just fine, but now I cant set up roundabouts anymore. 
Benjamin

**Comment by krzychu124** [comment]
@BenOniKenobi 
https://github.com/CitiesSkylinesMods/TMPE/issues/1494#issuecomment-1079804215

**Comment by BenOniKenobi** [comment]
No policies are checked under ”roundabouts”. Is it suppose to be for it to work?

**Comment by aubergine10** [comment]
@BenOniKenobi Yes, you'll need to specify how the roundabout should be set-up with those options.

**Comment by krzychu124** [comment]
@aubergine10  it's probably like that because of that tiny bug introduced to the Stable version so when you start new game all are loaded as disabled - normally some of them are enabled by default. That problem was fixed in TEST but Stable version still required an update (along with fixes of other things we've found in the mean time).

**Comment by aubergine10** [comment]
@krzychu124 Yes, it's fixed in 11.6.5 TEST workshop.

**Comment by aubergine10** [comment]
fixed by 11.6.5.1
