### ISSUE TITLE
Texture atlas breaks when changing option involving menu rebuild

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#1514]
### Describe the problem
See steps below. Investigating... (TM:PE workshop TEST also affected so probably a bug introduced in texture rebuild fix)

### Steps to reproduce

1. start new game
2. enter options and change PF counter visibility at Maintenance tab
3. close options modal and open TM:PE main menu
4. observe missing textures

Now the fun part
1. enter options once again and revert PF counter visibility setting 
2. close options modal and open TM:PE main menu
3. observe working textures

Now the weird part
1. break textures like in the first step
2. disable one of the features like _Lane Connector_
3. close options and observe menu (working)
4. enable the feature that was changed in step 2.
5. main menu breaks again...

### Screenshots?
![image](https://user-images.githubusercontent.com/19638970/161601560-db414a02-df48-401c-bc84-96686cda69a9.png)

### Notes or questions?
It looks like every **second** rebuild of _menu, texture source or whatever is happening there_ fixes the problem 🤷‍♂️ 
Everything works, just textures are missing.

**Comment by krzychu124** [comment]
Looks like TM:PE is setting wrong atlas when recalculates buttons. After next rebuild atlas is correct so must be a race condition or a bug in code that decides which atlas it should take

**Comment by aubergine10** [comment]
The menu rebuild is triggered by checkbox event handlers which call `OptionsManager.RebuildMenu();`

```csharp
        internal static void RebuildMenu() {
            if (TMPELifecycle.Instance.Deserializing || ModUI.Instance == null) {
                Log._Debug("OptionsManager.RebuildMenu() - Ignoring; Deserialising or ModUI.Instance is null");
                return;
            }

            Log.Info("OptionsManager.RebuildMenu()");
            ModUI.Instance.RebuildMenu();

            // TM:PE main button also needs to be updated
            if (ModUI.Instance.MainMenuButton != null) {
                ModUI.Instance.MainMenuButton.UpdateButtonSkinAndTooltip();
            }

            RoadUI.Instance.ReloadTexturesWithTranslation();
            TrafficLightTextures.Instance.ReloadTexturesWithTranslation();
            TMPELifecycle.Instance.TranslationDatabase.ReloadTutorialTranslations();
            TMPELifecycle.Instance.TranslationDatabase.ReloadGuideTranslations();
        }
```

**Comment by krzychu124** [comment]
Yeah that second part should be called when language changes - I don't see why it's now/was every time 🤷‍♂️ 
I'll check that code 😉

**Comment by aubergine10** [comment]
IIRC it was doing that originally so I just kind of left it.

Here's the original code before I stared changing stuff (it used to live in `Options.cs`):

https://github.com/CitiesSkylinesMods/TMPE/blob/768fe7f578b0124f9b33d4866960fa8221d49f69/TLM/TLM/State/Options.cs#L127-L144

**Comment by krzychu124** [comment]
Yeah, I've checked original code. All good, but I'll test if it's really necessary. No need to waste time if not needed.

Anyways.... it's a race condition when it comes to issue with UI texture. I need to figure out a better solution

**Comment by aubergine10** [comment]
I think the original `RebuildMenu()` (and thus my slightly tweaked version) was just a blunt "make sure everything gets updated".

The only 2 times I'm aware of that locales and textures should get updated:

1. When road sign theme changes (except during deserialization)
2. When language changes (except during deserialization)
3. `OnAfterLoadData()` to ensure textures are updated post-deserialization (the textures should _not_ be loaded prior to deserialisation IMO)

So we could put the texture reload in to a method and only call it when required - vague mockup (needs improvement):

```csharp
internal static void ReloadLocalisations(bool languageChanged = false) {
    if (TMPELifecycle.Instance.Deserializing || ModUI.Instance == null) {
        Log._Debug("OptionsManager.ReloadTextures() - Ignoring; Deserialising or ModUI.Instance is null");
        return;
    }

    // relaod whenever locale or road them changes
    RoadUI.Instance.ReloadTexturesWithTranslation();
    TrafficLightTextures.Instance.ReloadTexturesWithTranslation();

    // only reload if language code changed
    if (languageChanged) {
        TMPELifecycle.Instance.TranslationDatabase.ReloadTutorialTranslations();
        TMPELifecycle.Instance.TranslationDatabase.ReloadGuideTranslations();
    }
}
```

**Comment by krzychu124** [comment]
I'm testing this one:

![image](https://user-images.githubusercontent.com/19638970/161613239-8e943345-4f33-434d-80d8-e0df48fabcb5.png)

**Comment by krzychu124** [comment]
Ok, above code works good enough but there is a regression with regards to priority signs textures. 
I think we'll need new issue 😕 
@aubergine10 @kvakvs 
I noticed that Chinese version of priority signs is never displayed despite we load textures when changing language. When we should display those modified version if we also have themes (but no Chinese one)?

**Comment by kvakvs** [comment]
> I noticed that Chinese version of priority signs is never displayed despite we load textures when changing language. When we should display those modified version if we also have themes (but no Chinese one)?

I do not understand, there is no special handling of chinese signs in my theme code. But there is special handling of chinese TTL icons, where special versions of TTL icons for Chinese are loaded. Please make an issue with a screenshot.

**Comment by aubergine10** [comment]
Note also that there's two variants of Chinese - `zh-cn` and `zh-tw` IIRC? Simplified, and Traditional.

**Comment by kvakvs** [comment]
Locale is a combination of ISO language code (ZH for chinese) and country code where it is used (CN is for mainland China and TW for Taiwan, there's also SG for Singapore and HK for Hong Kong which we do not see in the game). Don't ask me how ZH means Chinese, probably some hieroglyph meaning China or Chinese transliterates to that and it became accepted by the ISO.

**Comment by aubergine10** [comment]
If lang is `zh-cn` (for example) but the filename is just `zh` would that cause issue? Maybe there's some code that trims anything from `-` so `zh-cn` becomes `zh`? 
![image](https://user-images.githubusercontent.com/1386719/161649418-f5f11da0-6ba9-489c-953e-d679b41054e5.png)

**Comment by krzychu124** [comment]
Files are loaded correctly, we just don't use them anymore because of introduced themes. There is even [Obsolete] label above both fields holding refs to loaded textures. Everything was "working" before introducing Speed limit themes but now we just need either do an exception for the rule we have or better build a basic theme for Chinese.

**Comment by kvakvs** [comment]
Function doing the magic of appending ZH to the filename is here: `Translation:GetTranslatedFileName/2` and it is called from `Translation:GetTranslatedFileName/1` and it is called from `UI.Textures` namespace from multiple texture loaders. If you're changing some reloading code, make sure that these special textures are reloaded using this call and not a simple `LoadDllResource` with a string name.

**Comment by krzychu124** [comment]
I already explained. Yield and Stop signs as localized Chinese version -> https://github.com/CitiesSkylinesMods/TMPE/pull/1081 
I was pretty simple implementation -> when selected Chinese lang, swap signs. Now it does not work since we only have themes and there is no Chinese one.
Part for localized Traffic Lights buttons from mentioned PR still works since we didn't touch that.

**Comment by kvakvs** [comment]
I don't mind adding Chinese signs or several themes for different lands speaking Chinese. What you think?

**Comment by krzychu124** [comment]
If we find textures why not. The more complete set of textures the better.
