### ISSUE TITLE
TM:PE doesn't recognise crossings made with Node Controller mod

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1524]
![image](https://user-images.githubusercontent.com/1386719/162327056-f8f30457-0d83-440f-b0ce-5f8551c6c37e.png)

Image link: https://imgur.com/gallery/iOaPTaj

Mods link: https://steamcommunity.com/sharedfiles/filedetails/?id=2595470859

![image](https://user-images.githubusercontent.com/1386719/162327160-63da2364-5baf-4a1a-8f4d-dad7226a0134.png)

![image](https://user-images.githubusercontent.com/1386719/162327191-2352b167-b532-49eb-96bd-f3b7252f3b7b.png)

![image](https://user-images.githubusercontent.com/1386719/162327216-4f102274-8647-4d40-a1d3-6c8717bd0c5e.png)

Mod link: https://steamcommunity.com/sharedfiles/filedetails/?id=2472062376

Roads link: https://steamcommunity.com/sharedfiles/filedetails/?id=2365944326

Youtube link: https://www.youtube.com/watch?v=m6Yy3qFe8G0

As can be seen near end of youtube vid, TM:PE junction restrictions tool isn't recognising the crossing node as having crossings.

In turn, that means Hide TMPE Crossings mod, when it asks TM:PE if there's crossings at that node, is likely getting a negative response and thus not showing striped crossing decals of the road network.

@kianzarrin does above sound correct?

**Comment by kianzarrin** [comment]
these are two different things:
1- hide node markings (to make them with IMT later)
2- banning pedestrian crossings.

![image](https://user-images.githubusercontent.com/26344691/162334801-3ca64982-82ef-408c-af02-0089ac76fd6f.png)
Also pay attention to my hintbox

The NC's TMPE overlay does not work anymore.

**Comment by kianzarrin** [comment]
> As can be seen near end of youtube vid, TM:PE junction restrictions tool isn't recognising the crossing node as having crossings.

As I told @macsurgey, he needs to show TMPE signs as a sort of documentation. otherwise ppl get confused. but he doesn't like to cover the road with TMPE signs so that ppl can see what they are doing.

**Comment by kianzarrin** [comment]
OK I updated the TMPE for NC2
![image](https://user-images.githubusercontent.com/26344691/162336864-24578c31-d74e-4670-84ac-59e07f2972d5.png)
Now the user can hide markings or ban crossings.

**Comment by kianzarrin** [comment]
> As can be seen near end of youtube vid, TM:PE junction restrictions tool isn't recognizing the crossing node as having crossings.

This is how a crossing node looks like with NC2

The crossing signs are transparent because they are not configurable on a crossing node. This is the same reason why TMPE does not show the sign handles.

I show the sign handles to clarify what is going on.

**Comment by kianzarrin** [comment]
now everyone is going to complain they cannot see the junction under the NC2 TMPE signs again!

**Comment by kianzarrin** [comment]
OK now that everything is clear I am closing this issue.
