### ISSUE TITLE
settings for verbose log

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1538]
```xml
  <Debug>
    <Switches>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
      <boolean>false</boolean>
    </Switches>
    <ExtVehicleType>None</ExtVehicleType>
    <ExtPathMode>None</ExtPathMode>
  </Debug>
  ```
Its hard to set the specific debug switch. I have to read the code and then count the lines to turn on the switch.
  it would be nice to be able to set these in the maintenance tab. that way I don't have to reload config all the time either :)

```cs
    public class DebugSettings {
        private int nodeId_ = 0;
        public static int NodeId => GlobalConfig.Instance.Debug.nodeId_;
        private int segmentId_ = 0;
        public static int SegmentId => GlobalConfig.Instance.Debug.segmentId_;
        private int startSegmentId_ = 0;
        ...
```
Also I have no way of setting debug log for specific segment/node/... even from the global config file. so we need these options too

**Comment by kianzarrin** [comment]
@aubergine10 @krzychu124 is there anyway of setting the `segmentId_` for verbose logs that I am not aware of?

**Comment by krzychu124** [comment]
afaik it was used only for specific testing, like you have got a problematic savegame, know the segment or node and want to log only data related to that segment or node (so you are compiling the mod with hardcoded values). If you could expose instance somewhere (Lifecycle object via property then you could use mod tools to set it). 
Anyways I see much better way, just require a basic tool to read id of entity(segment/node) you clicked

**Comment by kianzarrin** [comment]
it can help a lot with routings and path finding.

**Comment by krzychu124** [comment]
I'll try to refactor my experiment from my other mod and include it into TM:PE as a debug tool
