### ISSUE TITLE
Yield/Giveway is not adhered to on master branch

### ISSUE THREAD

**Issue by winxuser** [CitiesSkylinesMods/TMPE#1554]
### Describe the problem
Using Steam stable Traffic Manager, everything works fine with priority signage. With a self compiled version from master branch, all priority/yield is not adhered to, turning on and off give-way does nothing.

This could be an issue from my compiling but i have tried to reinstall VS a couple times with .net framework 4.8 and 3.5 and issue still persists.
 

### Log files

https://drive.google.com/drive/folders/1Fvu2WERDM28w5mUfIZ5otCXF8SJh4I6u?usp=sharing

this folder contains output and tmpe logs from both steam downloaded tmpe and self compiled. if link doesnt work please comment

**Comment by krzychu124** [comment]
![image](https://user-images.githubusercontent.com/19638970/166122191-b3e34fc7-49bf-4637-9ea9-dc2e99e0f0d0.png)

Why do you ignore Incompatibility message??

**Comment by winxuser** [comment]
its made no difference, i have unsubscribed from the steam version and its made no difference

**Comment by krzychu124** [comment]
Unsubscribe, **restart game** if unsubscribed from in-game, try again, upload new TMPE.log. It's near impossible that won't work.

**Comment by winxuser** [comment]
new tpme log added, still had the same issue, just not as bad, i had recompiled it again before this log

**Comment by krzychu124** [comment]
What `Simulation accuracy` value you've set in game? Is it the same? Test _Very High_, anything lower will result in lower accuracy (obviously) so more vehicles may ignore the sign (may not see other vehicles approaching the intersection)

**Comment by winxuser** [comment]
set on very high, aggression is on strict, cars coming up to round about still try to enter blocked junction, even though that policy is turned off and giveway sign added

**Comment by krzychu124** [comment]
Could you record short clip showing the problem?

**Comment by winxuser** [comment]
https://user-images.githubusercontent.com/2645165/166123556-13753857-1cc1-43e3-87da-0a49eb5b879c.mp4

thats only a small clip, but if i was to record longer you would be able to see more of it

**Comment by krzychu124** [comment]
That behaviour you see (car entering roundabout if should yield) is pretty normal considering all possible options in those condition. 
The main problem here is congested roundabout which forces vehicles with priority to stop. Yielding vehicle is allowed to enter junction if:
- there is enough space 
- and is able to finish maneuver without slowing down traffic (vehicle with priority won't move so entering yielding will manage to join).

I suggest enabling enter blocked junction inside of roundabout so vehicle with priority won't stop before intersection.

The code for priority behavior was not touched in past year or so, it's exactly the same as in Stable version (yet). 
I'm working on accuracy improvements to eliminate such situations. -> https://github.com/CitiesSkylinesMods/TMPE/issues/1229#issuecomment-1030912846
