### ISSUE TITLE
hidden redundant lane transitions

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1564]
![image](https://user-images.githubusercontent.com/26344691/167312588-84310fa4-f580-4666-8291-4d2a72fd2d0e.png)
in the image above routing detector displays a redundant track transition (in addition to  a useful road transition) from `car+tram` lane to `tram only ` lane.
We don't need that.

**Comment by kianzarrin** [comment]
fixed in https://github.com/CitiesSkylinesMods/TMPE/tree/1564-redundant-transitions

**Comment by aubergine10** [comment]
What do  you mean by "redundant"? Should the car+tram lane not be able to reach the tram-only lane?

**Comment by krzychu124** [comment]
Question is: what vehicle type the selection represents. If 'both' (car + rail) then it is correct, not redundant

**Comment by kianzarrin** [comment]
I think redundant is not strong enough. its a bug in routing manager. but path find recovers because it checks the source/target lanes' vehicle types.

**Comment by aubergine10** [comment]
There should be no tracked connection to a non-tracked lane. Agreed.

IIRC you added some modifier key shortcuts to toggle between car vs. tracked, and I assume you're holding that key on your keybaord when image is taken? If so, _we can't see your keyboard in the image_. There's literally nothing in that image that conveys "this is filtered to tracked connections".

So in addition to the identified bug in routing manager, maybe also some enhancecments to the routing diagnostic tool to help illustrate what we're looking at in current view. Either square connectors for tracks, or yellow-text highlight relevant content in the hint panel, or change button icon between road and track...?

**Comment by kianzarrin** [comment]
> you added some modifier key shortcuts to toggle between car vs. tracked

@aubergine10 those modifiers are for lane connection. the tool above is Routing detector. It does not have track/road shortcuts. 

>  enhancecments to the routing diagnostic tool to help illustrate what we're looking

to understand what you are looking at you need to read the text in the hint box (I have pointed to with green and red arrow in https://github.com/CitiesSkylinesMods/TMPE/issues/1564#issuecomment-1121389265).

Its hard to talk about abstract topics. go to the tool and play with it!
