### ISSUE TITLE
What's New panel - support for hotfix version

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#1566]
### Describe the problem
Recently pushed `What's New` update #1563 broke the changelog parsing _(I hotfixed the hotfix and uploaded working solution to the workshop 😅 )_. `Version` accepts only up to 4 comma separated numbers and fails on reading other text characters.

### Notes or questions?
Should be introduce `TMPEVersion` type in replacement of C# `Version` and implement additional parser + comparer?
How hotfix releases should be displayed in the `What's New` panel? 
I think we should display hotfix(es) on top and then below the version that was hotfixed so the user will see all changes regards to specific version instead of changelog just from the hotfix(panel stops loading anything older than last shown version).

@aubergine10 ideas?

**Comment by aubergine10** [comment]
> @aubergine10 ideas?

https://github.com/CitiesSkylinesMods/TMPE/pull/1563#issuecomment-1120444985
