### ISSUE TITLE
trams/trains are blocked by their own trailer.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1572]
This is also a vanilla problem:
when segment is updated or TMPE rules are updated, the leading vehicle will go a little bit backwards (because it will reset simulation speed data) while the trailers will not (they will stop immediately). if the vehicle is going fast enough it can get behind its own trailer and get blocked by it.

https://user-images.githubusercontent.com/26344691/168418804-592f2b8c-1d33-4079-a765-a7cde4bcc51c.mp4

https://cdn.discordapp.com/attachments/545066674605391882/965713435935506512/2022-04-18_23-39-26.mkv

Solutions:
- leading vehicle must ignore its own trailer in collision checks.
- trailers must also reset their simulation frame data.

**Comment by kianzarrin** [comment]
Collision check takes place in `CarAI.CheckOtherVehicles()`.

**Comment by krzychu124** [comment]
@kianzarrin watch carefully the clip. Trailers stop immediately, they don't collide with the leading vehicle. It's the leading vehicle moving back and forth

**Comment by kianzarrin** [comment]
yes. but if I disable collision with its own trailer then the tram can get un-stuck.

**Comment by kianzarrin** [comment]
it had nothing to do with collision. train/tram was going backward because targetpos was updated.
