### ISSUE TITLE
Where are custom traffic lights?, and what does broken plane means?

### ISSUE THREAD

**Issue by ZZuma** [CitiesSkylinesMods/TMPE#1587]
### Describe the problem

When I start the game, warning(some vehicles (plane) had broken paths due to a bug in an earlier version of pathfinder) appear.
there is not custom traffic lights button so that I can't use it

### Log files

https://drive.google.com/file/d/16A7xEz4KxBVp1dhWxtb5mNT0tZNK5KRU/view?usp=sharing

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2815500415

### Screenshots?

~~https://drive.google.com/drive/folders/1hzuUA1qPgHLdF8rVkhxMM--d92FohH_A?usp=sharing~~
![image](https://user-images.githubusercontent.com/26344691/171402575-10263496-742b-45d1-ae59-9d05d368d727.png)
![image](https://user-images.githubusercontent.com/26344691/171402518-0f35288f-58b1-4d3b-82f4-a3dc74886cee.png)

### Notes or questions?

I'm sorry that I'm not good at English

**Comment by kianzarrin** [comment]
custom traffic lights can be enabled in TMPE options from the settings. it works in game not asset editor. (due to disable it at some point?)

**Comment by kianzarrin** [comment]
BTW it is better to drag and drop images here.

**Comment by kianzarrin** [comment]
>  That message is just warning/info to the user that previous version of mod was used (had a bug) and planes will get removed from the map to be spawned automatically again after some time with correct paths. Older version of the mod could cause planes to stuck at taxiway or takeoff using only tiny part of runway. Just save game and it won't be shown again.

is that why I see that message all the time? because I switch between different versions of TMPE?

**Comment by krzychu124** [comment]
It's corelated with version of TM:PE stored in the savegame while saving. if you see it all the time then make sure TM:PE is actually loading anything without errors - I noticed that error/exception while loading data will also trigger that modal (load process is setting last used version which is used to determine if modal should be shown or not)

**Comment by krzychu124** [comment]
Fixed in **STABLE/TEST 11.6.5.3**
