### ISSUE TITLE
NEW GAME OR LOAD GAME not loading with TM:PE on.

### ISSUE THREAD

**Issue by SDBetelgeuse** [CitiesSkylinesMods/TMPE#1588]
### Describe the problem
I have bought the game and its Addons via Epic Games (not Steam). So I was playing the game for about a week now on my brand new computer without any issues at all. Once I saw that TM:PE is a must-have Mod for the game I downloaded it but when I have TM:PE turned on, the map I'm trying to play (either New game or Saved files) won't load. It just goes into a never ending loading screen. I have tried deleted and re-downloading the Mod but there's still the same issue. Also, when I turn it off, the game plays and loads normally. I haven't found any helpful thread for this issue. Please help! (FYI i'm no computer expert so I don't really now much about logs, pc requirements etc.)

### Steps to reproduce

1. Turn on TM:PE via CONTENT MANAGER
2. Press NEW GAME or LOAD GAME (if trying to play a saved map file)
3. 

### Screenshots?

![Screenshot_1](https://user-images.githubusercontent.com/106821339/171868346-c89f3232-4761-410d-8d1c-ed8f31c5f880.png)
![Screenshot_2](https://user-images.githubusercontent.com/106821339/171868407-7077b4bd-dc8e-4ece-bb24-536984c8ef30.png)
![Screenshot_3](https://user-images.githubusercontent.com/106821339/171868425-d5de7712-a9d6-4914-9454-520a7f1a8607.png)

**Comment by krzychu124** [comment]
Did you also have **required mod dependency**? I doubt.

**Comment by SDBetelgeuse** [comment]
Hi.
I have the Harmony mod which I read somewhere that is also required.

Στις Παρ 3 Ιουν 2022 στις 4:58 μ.μ., ο/η Krzysztof ***@***.***>
έγραψε:

**Comment by krzychu124** [comment]
You are using completely wrong version. It's outdated and incompatible with all mods. Use version that is listed in _required mods_ section at TM:PE Steam workshop page.

**Comment by zawr77** [comment]
Same problem here. Let's just say I've played this game for over a month flawlessly. Until a few hours ago I decided to add several mods. 

So I added these mods (attached) all at once and come to a looping loading screen as said. I then remove everything and install them one by one. Everything seems to keep me start a new game without any problem. The second last addition was Harmony (stated as 2.2 in the workshop but the in-game mods setting is reflected 2.0.0.9 as this fella's here). It opens a new game no problem. 

My last addition just now was the TMPE that got me stuck in the new game loading screen. I've been searching for the similar issue and this one seems to be the first post I found. 

Is this a new bug or something? 

![Capture](https://user-images.githubusercontent.com/106825568/171880794-cba26fe8-b6f2-4814-a21f-289587a077cc.PNG)

**Comment by SDBetelgeuse** [comment]
Yeah same.
So I tried re-downloading Harmony from Steam via Steam workshop downloader. The file is Harmony 2.0.0.9 although it says 2.2.
I found Harmony 2.2 from here https://smods.ru/archives/62430 and now everything works properly.

**Comment by zawr77** [comment]
> Yeah same. So I tried re-downloading Harmony from Steam via Steam workshop downloader. The file is Harmony 2.0.0.9 although it says 2.2. I found Harmony 2.2 from here https://smods.ru/archives/62430 and now everything works properly.

That is actually the v2.2. Thank you!

**Comment by krzychu124** [comment]
No need to post link to external untrusted source. Use this version instead: https://github.com/boformer/CitiesHarmony/releases/tag/v2.2-0
