### ISSUE TITLE
Public Transport - Take Ticket Price into Pathfinding Cost

### ISSUE THREAD

**Issue by thomaschow19** [CitiesSkylinesMods/TMPE#1591]
The Pathfinding of Public Transport Users do not seem to take ticket prices into consideration. Would be a nice addition if the citizens will take ticket prices into consideration (ie they might prefer a cheaper but slower bus route if possible)

**Comment by kianzarrin** [comment]
you can't change bus ticket prices can you?

**Comment by krzychu124** [comment]
Pathfinding already does that, even more than vanilla. If you have districts with free transport then.. obviously won't work in those areas.

One of the examples:
https://github.com/CitiesSkylinesMods/TMPE/blob/bfeccac39577e02418e7143022e418a48c8ee73c/TLM/TLM/Custom/PathFinding/CustomPathFind.cs#L2100-L2106
