### ISSUE TITLE
incorporate crazy tourist fix

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1595]
This mod is 2 simple patches only. we should and easily can bring it to TMPE:
https://steamcommunity.com/sharedfiles/filedetails/?id=1759269367
https://github.com/chronofanz/CrazyTouristFix/blob/3132af53f4aa30e45302cc1a3a8166a4f37cd8b4/CrazyTouristFixMod.cs#L58

EDIT: I need to run some tests though to prove its needed and works.

**Comment by krzychu124** [comment]
It describes the issue occurs for roads without sidewalks, but... default highway road neither has a sidewalk 🤷‍♂️ 
It may not be needed by looking at the code, I think 🤔 See #1543

**Comment by kianzarrin** [comment]
This is a draft because I have not tested this yet. I'll add test plan to description.

> It describes the issue occurs for roads without sidewalks,
>  but... default highway road neither has a sidewalk 

is there a contradiction in the statement above?

I have seen that ppl spawn at highway outside connections at jump on a vehicle IIRC.

**Comment by kianzarrin** [comment]
In any case I do need to run some tests.

**Comment by kianzarrin** [comment]
@krzychu124 did you read the description completely? he is aware that this problem does not happen with one-way highways that don't have sidewalk.

> This behavior also happens at ALL outside connections. Most outside connections are one way out, however, and also these outside connections have no sidewalk either ...  Path Manager FAILS (because the road segment is one-way or there's no sidewalk or whatever), and then the citizen then goes away.

**Comment by kianzarrin** [comment]
reproduced problem:
[image](https://user-images.githubusercontent.com/26344691/174489270-a0f65be7-8fbb-47a7-bd09-200a5c2a7370.png)

**Comment by kianzarrin** [comment]
This is with the crazy tourist fix mod enabled:
![image](https://user-images.githubusercontent.com/26344691/174490351-33c323df-bfe8-4965-aa5a-db938f96e5d4.png)
The mod does not work

**Comment by kianzarrin** [comment]
since the original mod does not fix the problem I close this.
