### ISSUE TITLE
"C:S Stopped Responding" prompt when placing Aircraft Stands

### ISSUE THREAD

**Issue by deFFo** [CitiesSkylinesMods/TMPE#1597]
### Describe the problem
When placing Airport DLC Aircraft stands, the game freezes right after the stands are visually set and Windows gives the "Cities: Skylines Stopped Responding" Windows prompt. Issue only present when TMPE is enabled.

### Steps to reproduce

1. Open any save / new game (with TMPE running)
2. Place Airport Terminal (any kind)
3. Place Airports DLC aircraft stand (any size)

### Log files

- This line from output_log bugs my eye the most.

> Assembly resolution failure. No assembly named 'NetworkSkins, Version=1.0.7319.2601, Culture=neutral, PublicKeyToken=null' was found.  [Serialization]

- [output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/8865210/output_log.txt)

- [CompatibilityReport.txt](https://github.com/CitiesSkylinesMods/TMPE/files/8865217/CompatibilityReport.txt)

- [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/8871051/TMPE.log)

### Notes or questions?

**System:** 
(I'm aware that the system, in particular, is massively underpowered for the vanilla game already, not to mention mods, but every other use case works just fine, even without any memory overload errors)

**OS:** Windows 10
**RAM:** 4GB
**GPU:** AMD Radeon HD5670
**CPU:** Intel Core i3 550

### Tested

**Issue not present when:**
- All mods disabled [No issues]
- TMPE disabled (other mods loaded)[No Issue]

**Issue still present when:**
- New Save started (with TMPE enabled)
- Loaded Save used (with TMPE enabled)
- Different Map(s) selected (with TMPE enabled)
- Only TMPE is enabled, no other mods running, previous scenarios applied.

I'm somewhat certain that there is a hardware performance issue at hand, but it'd be great to get a second opinion from someone more broadly educated in this than I am.

**Comment by krzychu124** [comment]
Try without FPS Booster (unsubscribe, disable may not work), leave TM:PE enabled + attach TMPE.log

**Comment by deFFo** [comment]
> Try without FPS Booster (unsubscribe, disable may not work), leave TM:PE enabled + attach TMPE.log

Did, the scenario changed!

Now, placing the aircraft stand creates **no issues**, **but** as soon as I start to move the camera around or I pause-unpause the game, it still gives the prompt and freezes.


- [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/8871037/TMPE.log)  as requested.

**Comment by deFFo** [comment]
**UPDATE**

As I've suspected, hardware issue.
Increasing the page file size solved the issue indefinetly.

**Comment by krzychu124** [comment]
Closing.
