### ISSUE TITLE
Crashing on CSUR elements

### ISSUE THREAD

**Issue by Xeenon77** [CitiesSkylinesMods/TMPE#1612]
### Describe the problem
While changing the speed on a CSUR-Element (that merges lines for example 4 to 3 lines) and using shift+left click the game softlocks.

### Steps to reproduce

1.  Have a CSUR Road that merges Lines ( as an example 4 to 3)
2. change the speed of this road segement by using shift+left click
3. 

### Notes or questions?
https://youtu.be/jiFvG3d3XUE

**Comment by krzychu124** [comment]
@kianzarrin could you test that since we've had some issues in infinite loop in "apply between junctions" feature in the past and you know the code better than me?

**Comment by kianzarrin** [comment]
what is CSUR element?

**Comment by Xeenon77** [comment]
> what is CSUR element?

A road piece from the CSUR mod. This mod is used to create highway interchanges.
https://www.csur.fun/en/

**Comment by krzychu124** [comment]
> what is CSUR element?

I'm 99% sure we can reproduce that issue with just standard CSUR road collection, most likely "minimal" is pinned in CSUR toolbox mod

**Comment by krzychu124** [comment]
@kianzarrin it might be related to #1439
