### ISSUE TITLE
Non steam player error

### ISSUE THREAD

**Issue by troner14** [CitiesSkylinesMods/TMPE#1616]
### Describe the problem

hi, I have a problem with mod when try to install in a non steam player

### Steps to reproduce

1. install de mod in C:\Users\[UserName]\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods
2. enter a game
3. show error and mod not working

### Screenshots?

![image](https://user-images.githubusercontent.com/73949396/179418839-a9d7fb30-d8cf-4ceb-b5ea-2b2de467bf72.png)
![image](https://user-images.githubusercontent.com/73949396/179418866-f93acafe-fd00-4e68-9d6b-7a3b11827e36.png)
![image](https://user-images.githubusercontent.com/73949396/179418875-9e76d8c5-c80c-47c0-b3fa-5235b0136f36.png)

**Comment by krzychu124** [comment]
Hi,
Screenshot of error is not useful in this case. Provide full log https://github.com/CitiesSkylinesMods/TMPE/wiki/Share-your-Cities-Skylines-log-file

**Comment by troner14** [comment]
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/9128401/output_log.txt)

**Comment by krzychu124** [comment]
https://github.com/CitiesSkylinesMods/TMPE/wiki/Installation

https://github.com/CitiesSkylinesMods/TMPE#support-policy
