### ISSUE TITLE
TM : PE Pathfinder Updated Some vehicles 

### ISSUE THREAD

**Issue by mykytaMedko** [CitiesSkylinesMods/TMPE#1640]
### Describe the problem

The "Policies" menu is no longer displayed

### Steps to reproduce

1. game mod installed
2. enable the mod in the Content Manager
3. made a second load of my save
4. trying to open the policy menu
5.  (after resetting the game parameters (in the settings), such buildings disappeared - polyclinics, some schools, all police stations)

### Savegame?

I don't play through steam

### Screenshots?

![image](https://user-images.githubusercontent.com/59159014/189479605-f0e2f977-74e0-4506-a395-1ef764e01e6f.png)

**Comment by krzychu124** [comment]
Ignore that warning about Pathfinder Update, especially if you started new game or loaded old savegame with the mod for the first time. 
Issue with policies panel is an old game bug (no one know why it happens sometimes, it's rare).
Use **Loading Screen Mod** which helps with loading time and fixes Policies panel problem.

**Comment by mykytaMedko** [comment]
Fine. I realized about mod . Thank you!

сб, 10 вер. 2022, 16:50 користувач Krzysztof ***@***.***>
пише:
