### ISSUE TITLE
TM:PE doesn't load on Cities: Skylines 1.15+

### ISSUE THREAD

**Issue by osfanbuff63** [CitiesSkylinesMods/TMPE#1643]
### Describe the problem
TM:PE will not load on version 1.15+ of Cities: Skylines, despite using the latest v11 TEST (v11.7.0.0).

### Steps to reproduce

1. Open a Cities: Skylines instance with TM:PE
2. Load up any savegame (including the one I linked below)
3. Click on any road and notice TM:PE is not loaded.

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/9575040/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/9575042/TMPE.log)

### Savegame?

Shouldn't be too relevant, but https://steamcommunity.com/sharedfiles/filedetails/?id=2863220820

### Screenshots?
![Screenshot 2022-09-15 081456](https://user-images.githubusercontent.com/91388253/190401152-8d9779e3-1542-4c85-a315-267fcad775a0.png)
![Screenshot 2022-09-15 081441](https://user-images.githubusercontent.com/91388253/190401155-c00d5f4e-aa8c-4411-8166-5736944cdacb.png)

### Notes or questions?

I am using the Steam version of Cities: Skylines.

**Comment by krzychu124** [comment]
log reports that savegame has no TM:PE data. DId you made any changes using some mod features and **saved the game**? I doubt. It does not even have a version number so savegame file was not created with the mod enabled

**Comment by osfanbuff63** [comment]
I've uploaded a save file I just loaded that has been saved many times with TM:PE settings changed, and still nothing. Here's the savefile if you want it, and updated logs:
[Savefile](https://steamcommunity.com/sharedfiles/filedetails/?id=2864068445)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/9591634/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/9591636/output_log.txt)

I've also noticed: Even though it shows up in Harmony's menu:
![image](https://user-images.githubusercontent.com/91388253/190856447-ad9cf595-8c01-418e-87b8-73215ed54e28.png)

There's no area for configuring the mod, which is strange.
![image](https://user-images.githubusercontent.com/91388253/190856467-ab875ef8-7513-4004-a5a4-6238d16f9d93.png)

**Comment by krzychu124** [comment]
Wait.. Is the mod even enabled? Check that in Main Menu -> Content Manager -> Mods.

**Comment by osfanbuff63** [comment]
Yep, that did it. I wonder why it disabled when I updated...?
