### ISSUE TITLE
Parked disaster recovery vans should block road and cause repathing

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#165]
Opposite of #19...

I'd like an option to mark roads as blocked if there's a disaster recovery vehicle parked on them.

I've been using tiny 1u NeXT roads for my mountain villages - a building had burnt down, and disaster team was searching rubble for survivors. Their parked disaster van (the one that makes that weird beeping sound) caused a massive traffic queue as there was no room for other vehicles to pass. Vehicles in the queue started despawning; it would be nice if they rerouted instead (even if that means u-turns).

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/132

**Comment by VictorPhilipp** [comment]
This issue might be more related to problems with disaster recovery never being able to "recover" on sites of destroyed Ploppable RICO buildings...

EDIT: Logged associated issue: https://github.com/AJ3D/Ploppable-RICO/issues/19

**Comment by VictorPhilipp** [comment]
Did some more testing on this. The never-ending rescue operation is caused by RICO buildings, however the fact the lane does not seem to be marked as "blocked" is still a separate issue that TM:PE could potentially fix?

I created extra roads so there was definitely alternate route for traffic to take going up the mountain; after 2 game months, traffic was still not rerouting to use the alternate route.

In the end I had to manually "block" the affected segment of road using the lane connector tool (routing connections away to the newly created alternate route) to get traffic to bypass the blockage.

See also: #133

**Comment by aubergine10** [comment]
I think the RICO buildings bug has since been fixed. Will to some testing when time permits.

As there is a `collapsed` flag on segments (I think) we could potentially treat `collapsed` like `blocked` in the pathfinder? Would obviously need some investigations to see what exactly happens with those flags.

**Comment by aubergine10** [comment]
Closing this - the [RICO Revisited](https://steamcommunity.com/sharedfiles/filedetails/?id=2016920607) mod fixed the issue with never-ending searches at disaster sites.
