### ISSUE TITLE
For non-STEAM users, the entry interface is gray, and the loaded map can’t enter in infinite circles。

### ISSUE THREAD

**Issue by WSXTE** [CitiesSkylinesMods/TMPE#1659]
### Steps to reproduce

1. 
2. 
3. 

### Savegame?
![Cities Skylines Screenshot 2022 09 27 - 19 25 23 34](https://user-images.githubusercontent.com/114486903/192513293-38c10be7-e0b3-46d6-96a7-dd24750f4b97.png)

**Comment by krzychu124** [comment]
https://github.com/CitiesSkylinesMods/TMPE/wiki/Installation !

**Comment by WSXTE** [comment]
Thank you very much for solving my problem perfectly！！！ @krzychu124
