### ISSUE TITLE
Garbage trucks not finding path since Park & Plazas update

### ISSUE THREAD

**Issue by XtraMorganary** [CitiesSkylinesMods/TMPE#1662]
### Describe the problem

Garbage trucks have stopped spawning in at Recycling Centres. The number of trucks in use flickers between 0 and 1.
I ran the city without TMPE (other mods were left on) and the trucks began spawning.
I then ran the city with TMPE on, without adjusting any settings or applying any lane arrows/conectors and the problem reappeared.

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/9678103/output_log.txt)

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/9678113/TMPE.log)

### Savegame
https://steamcommunity.com/sharedfiles/filedetails/?id=2869175509

### Notes or questions?
Hopefully there's something in the settings that I haven't spotted/tried that'll fix it.
Thanks in advance for your help, Cities Skylines wouldn't be the same without TMPE!

**Comment by krzychu124** [comment]
I can't reproduce the problem on your savegame but I see two junctions that create huge traffic jams, basically killing whole garbage collection. In your setup where you have all recycling center in one spot - traffic jam can cause a lot of troubles, shifting priorities in garbage collection etc. Some distant buildings will start demanding garbage collection at higher and higher priority causing problems in garbage collection for closer buildings.

Also... decrease Dynamic Lane Selection. Having it on 100% will favor egoistic behavior in lane selection over keeping good traffic flow - you will see way more dumb drivers trying to change lane for no reason (there is actually, but objectively not worth), sometimes even multiple at a time completely blocking multilane roads within few seconds.

**Comment by krzychu124** [comment]
You are also using `More Effective Transfer Manager` which might be incompatible with the latest game update (may not throw errors) - Pedestrian districts where garbage and other services are handled by special service point buildings. 
I've been testing your savegame **without** that mod (will try with it later).

**Comment by krzychu124** [comment]
Reopen or create new issue if needed, latest game update and also recently released mod enhancements to lane arrows validation should reduce a chance for pathfinding issues to minimum.
