### ISSUE TITLE
Infinite Loading Problem

### ISSUE THREAD

**Issue by GustavoAguiar01** [CitiesSkylinesMods/TMPE#1669]
180 / 5.000

Game installed by Epic Games, when activating this mod the game is in infinite loading, even with Hamony installed without any other mod installed or active.

Thank you for your help.

Jogo instalado pela Epic Games, ao ativar este mod o jogo fica em carregamento infinito, mesmo com Hamony instalado sem qualquer outro mod instalado ou ativo.

Obrigado pela ajuda.

**Comment by kianzarrin** [comment]
Follow Epic installation instructions. https://github.com/CitiesSkylinesMods/TMPE/wiki/Installing-on-Epic-Games

**Comment by GustavoAguiar01** [comment]
Thanks for the help, I changed the mod installation folder, when activating the mod a warning screen about using mod, but the infinite loading continues.

Only with Harmony active the game load.
With Harmony and TMPE active game does not load
TMPE active the game does not load

Thank you for your help.

Obrigado pela ajuda, mudei a pasta de instalação de mod, ao ativar o mod uma tela de aviso sobre utilização de mod, mas o carregamento infinito continua.

Somente com Harmony ativo o jogo carrega.
Com Harmony e TMPE ativos jogo não carrega
TMPE ativo o jogo não carrega

Obrigado pela ajuda.

**Comment by krzychu124** [comment]
Delete both mods completely (Harmony and TM:PE) and install again using files linked in the guide. It still does not work for you because you didn't use specific version of mods. That's all.
