### ISSUE TITLE
tri-state toggle in options

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1671]
a toggle that can store `bool?` value. would look like something like this: 
<img height="100px" src="https://user-images.githubusercontent.com/26344691/194746000-c74ea1b2-2987-4c68-a7c1-ad8d154eeaa8.png" /><img height="100px" src="https://user-images.githubusercontent.com/26344691/194746006-6f9b2946-26fa-48fc-b95d-bc2a8cca74d5.png" />

can help with bulk edit options.

**Comment by kvakvs** [comment]
I suggest making ON state colored (some contrast color)
OFF state having no color, like gray?
And indeterminate maybe X or - or ? or just middle position and no color or half color of the ON state?
Or look at the images.google.com search for "ui design tri-state checkbox" for more ideas

**Comment by krzychu124** [comment]
Or instead of ON AUTO OFF, a bit shorter version
![image](https://user-images.githubusercontent.com/19638970/194773055-5a2cdf32-db08-4569-8b32-e7d97dc11a5d.png)

**Comment by kianzarrin** [comment]
also this 
![image](https://user-images.githubusercontent.com/26344691/194774028-fe0b24e0-6d3f-4377-8937-cb71643d73c8.png)

**Comment by kianzarrin** [comment]
![image](https://user-images.githubusercontent.com/26344691/195158054-b1d448af-08ba-4c56-8fa4-c09f3d9f057a.png)

**Comment by kvakvs** [comment]
If you want it on the left side, i can quickly make on/off/? images styled in line with the other game UI
That is black background, thick gray outline and blue highlights.

**Comment by kvakvs** [comment]
![bild](https://user-images.githubusercontent.com/288724/195171709-fed50f23-5212-4690-971d-1b948ca4de5b.png)
![Indeterminate](https://user-images.githubusercontent.com/288724/195171747-57dfcd22-566e-44b1-87b5-5905f926c73a.png)
![Off](https://user-images.githubusercontent.com/288724/195171752-69665566-54f5-467c-8434-2b7661a81c9f.png)
![On](https://user-images.githubusercontent.com/288724/195171758-81d74ea4-100f-4269-bce6-ae16e47cb8c5.png)

**Comment by kvakvs** [comment]
Oh let me try the blue highlight too

**Comment by kvakvs** [comment]
![On2](https://user-images.githubusercontent.com/288724/195172323-ce081ceb-ad99-47a1-aa38-abde5384ff39.png)
![Indeterminate2](https://user-images.githubusercontent.com/288724/195172327-0c4f4ad3-9191-4e5a-96b0-9b0ff268ceba.png)
![Off2](https://user-images.githubusercontent.com/288724/195172328-b5ead4c0-3fbb-4018-8638-7ecb06417fd3.png)
