### ISSUE TITLE
Mod not loading System.IndexOutOfRangeException: Array index is out of range.

### ISSUE THREAD

**Issue by alkolodziej** [CitiesSkylinesMods/TMPE#1683]
### Describe the problem
Error:
`A Mod caused an error [ModException]

Details:
System.IndexOutOfRangeException: Array index is out of range.
  at OptionsMainPanel.AddUserMods () [0x00000] in <filename unknown>:0 `

### Steps to reproduce

1.  just launch game
2. 
3. 

### Log files

`ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetExportedTypes () [0x00000] in <filename unknown>:0 
  at ColossalFramework.Plugins.PluginManager+PluginInfo.GetInstances[IUserMod] () [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
ColossalFramework.Plugins.PluginInfo:GetInstances()
EntryData:GenerateData()
EntryData:.ctor(PluginInfo)
CategoryContentPanel:RefreshAssetsModImpl()
CategoryContentPanel:RefreshAssets()
CategoryContentPanel:Refresh()
ContentManagerPanel:RefreshCategory(UIComponent)
ContentManagerPanel:Initialize()
MenuPanel:Start()
 
(Filename:  Line: -1)

ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetExportedTypes () [0x00000] in <filename unknown>:0 
  at ColossalFramework.Plugins.PluginManager+PluginInfo.GetInstances[IUserMod] () [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
ColossalFramework.Plugins.PluginInfo:GetInstances()
EntryData:GenerateData()
EntryData:.ctor(PluginInfo)
CategoryContentPanel:RefreshAssetsModImpl()
CategoryContentPanel:RefreshAssets()
CategoryContentPanel:Refresh()
ContentManagerPanel:RefreshCategory(UIComponent)
ContentManagerPanel:Initialize()
MenuPanel:Start()
 
(Filename:  Line: -1)

GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
Paradox Account not linked to current Steam user account.  [HTTP]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)`

### Savegame?

its in main screen

**Comment by krzychu124** [comment]
https://github.com/CitiesSkylinesMods/TMPE/wiki/Share-your-Cities-Skylines-log-file

**Comment by alkolodziej** [comment]
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/9955258/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/9955259/TMPE.log)

**Comment by krzychu124** [comment]
![image](https://user-images.githubusercontent.com/19638970/200417440-d7c86412-60f2-491e-81e3-d88c4dc1ef2b.png)
