### ISSUE TITLE
Integrate Mass Transit's stop sign into TMPE's traffic sign menu

### ISSUE THREAD

**Issue by Leo512bit** [CitiesSkylinesMods/TMPE#1716]
### Integrate Mass Transit's Stop Sign
Integrate Mass Transit's stop sign into TMPE's traffic sign menu.

### Screenshots?
Maybe later

### Notes or questions?
Made add asset signs for yield and priority?

**Comment by kianzarrin** [comment]
duplicates #28
this was a bit of an obstacle : https://github.com/CitiesSkylinesMods/TMPE/issues/28#issuecomment-460268053
