### ISSUE TITLE
Cargo Trains bugging into each other from stations

### ISSUE THREAD

**Issue by cbweiland** [CitiesSkylinesMods/TMPE#1721]
Cargo trains are bugging into each other.  I have tried playing with the settings with TMPE but can't figure out what is causing it.  Does work fine in Vanilla.  Let me know what other info you need.

![image](https://user-images.githubusercontent.com/25651156/216402878-3b170bac-2148-4ac1-9ed4-60417a9aaeeb.png)

**Comment by krzychu124** [comment]
Have you tested it without other mods, just with TM:PE, e.g.: on new map? Cargo and Passenger trains have the same handling so you can try reproducing it on new map. As for today no one reported such issue so I don't thinks it's something wrong with TM:PE, more like some kind of mod conflict.

**Comment by cbweiland** [comment]
Pretty sure the issue was the custom train asset!

**Comment by galtobellojr** [comment]
I'm looking at that junction to the left of the arrow, which I presume shows two trains' head-on crash.  I've solved a number of rail junction problems by using Node Controller on the node, which I see has two catenaries overlapping.  Nodes seem to come up "collapsed", like in "middle", at times, and I've seen simply clicking on them with Node Controller cause a normal-looking node to collapse.
The solution I use is to select the rail intersection with Node Controller, then increase All/Offset (mouse-wheel) until the node's, um, "edges/segments/boundaries?" are far enough apart to keep e.g. trains on the mainline from getting stuck with trains "waiting" on the siding (yielding but blocking the junction).
In this particular case, I expect if you widen the node, you'll see switch tracks appear, which would allow the train on the right to switch to the unoccupied lane without colliding with the train on the left, as both would pause at the boundaries, and whichever one went first could pass freely.
