### ISSUE TITLE
Vehicles keep changing lines only on nodes

### ISSUE THREAD

**Issue by pnazim96** [CitiesSkylinesMods/TMPE#1722]
Hi, I experience a strange behavior of vehicles, that always insist on changing lanes only on nodes. They all wait in huge lines until the specific point in the road when they change the line, instead of smoothly switching between lanes. I got advanced AI enabled, with the dynamic lanes selection set around 35%, but this doesn't help much.
I can stitch nodes manually to ban cars from switching lanes, but it only moves a problem a bit further or causes cars to calculate a completely weird path across the city, because they don't know how to switch lanes in the long sections of the highway, always looking for nodes. I don't remember them doing this before. Is it something related to the new version?

KR

**Comment by Deeheks** [comment]
Isn't this nor al game behavior??

**Comment by qjlu404** [comment]
This is normal game behavior.

**Comment by lokpro** [comment]
This is a sign that the world is a simulation.

**Comment by krzychu124** [comment]
That's exactly how the game works. Vehicles are changing lanes on nodes, if they're moving fast then transition is smooth if they need to stop they do what you see. 
Most likely the source of problem is when vehicle is trying to change lane it has no space so has to move slower and slower until it stops, stopping all traffic behind.  _Dynamic lane selection_ feature can react in situations where vehicle sees blocked lane but it also instructs the vehicle to change lane on node. It would be a way too expensive to allow changing lanes at any place.
_Simulation Accuracy_ affects how many other vehicles are tested to calculate if vehicle has priority or not (also applies to lane change)

**Comment by galtobellojr** [comment]
That's normal behavior, but I found that using Node Controller to set the node type from "Middle" to "Bend" seems to allow for smoother lane transitions, especially in heavy traffic, by widening the node and reducing those "jump into the other lane" tie-ups.  Mainly I use this in busy freeway exits/entrances, and vehicles seem to get "stuck together" less often.
