### ISSUE TITLE
LaneChangeManager issue

### ISSUE THREAD

**Issue by pote2639** [CitiesSkylinesMods/TMPE#1726]
### Describe the problem

it throws these errors coming from TMPE on the LaneChangeManager, and if I'm trying to unpause the simulation I will also get the "System.NullReferenceException" error and the city disappears when zooming in and the simulation is stuck.

### Steps to reproduce

By just loading this save game I will provide
### Log files

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/10851357/TMPE.log)
[CompatibilityReport.txt](https://github.com/CitiesSkylinesMods/TMPE/files/10851360/CompatibilityReport.txt)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/10851362/output_log.txt)

### Savegame?

(https://steamcommunity.com/sharedfiles/filedetails/?id=2940307115)

### Screenshots?

![image](https://user-images.githubusercontent.com/41198794/221887776-938b5e59-18bc-4e9e-bf4d-88bea580cc53.png)

![image](https://user-images.githubusercontent.com/41198794/221888081-63bec8d3-7ad8-44a1-93f5-3f5670b245b6.png)

**Comment by krzychu124** [comment]
Did you remove some roads assets that were used before in the savegame/city?

**Comment by pote2639** [comment]
> Did you remove some roads assets that were used before in the savegame/city?

Nope I didn’t.

**Comment by pote2639** [comment]
> Did you remove some roads assets that were used before in the savegame/city?

Nope I didn’t

**Comment by krzychu124** [comment]
Could you post output_log.txt after run without the mod subscribed? I don't believe there are no errors. 
It's in a place which shouldn't ever throw an error if all networks were loaded without issues - just check the log, it's full of errors, mostly because you probably forgot to enable/install Vehicle effects or effects plugin, but at the end there are Adaptive Networks errors because of the same reason like in TM:PE - missing/broken network asset.

**Comment by krzychu124** [comment]
Another problem is I can't load your savegame with all mods and assets subscribed because of unrecoverable Simulation error which then breaks a lot of stuff 😕

**Comment by pote2639** [comment]
The game wwon't absolutely load at all if I disable this mod, it will stuck on loading screen forever.

So do you think there is no way to find which missing mods are causing the issue right :\

also here is the output_log with TMPE unsubscribed
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/10883347/output_log.txt)

**Comment by pote2639** [comment]
The game wwon't absolutely load at all if I disable this mod, it will stuck on loading screen forever.

So do you think there is no way to find which missing mods are causing the issue right :\

also here is the output_log with TMPE unsubscribed
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/10883347/output_log.txt)

**Comment by pote2639** [comment]
it was the KL Residential Props that broke everything it seems, I unsubscribe it and now everything works!

**Comment by krzychu124** [comment]
> The game won't absolutely load at all if I disable this mod, it will stuck on loading screen forever.

I can only add that in addition to unsubscribing the mod you should disable all mods which require TM:PE to work. In that case it failed because _Adaptive Networks_ requires TM:PE API dll which was not available, obviously, since you unsubscribed the mod. 

I'm glad you found the solution.
