### ISSUE TITLE
Problem with arrows and line connectors

### ISSUE THREAD

**Issue by igorrychert** [CitiesSkylinesMods/TMPE#1736]
### Describe the problem
Hi, I have a problem with lane arrows and lane connectors. When I build a new road, I can't change the lane arrows, supposedly through the intersection settings. I can adjust the lane connectors but they don't work as they should.

### Steps to reproduce

1.  You need to add new road to intersection.

### Log files
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/11114714/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/11114715/TMPE.log)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2955008745

### Screenshots?
![Test](https://user-images.githubusercontent.com/129429973/228932244-dd0d73f0-8f7b-41a9-8911-8b6911f39f5f.png)

**Comment by krzychu124** [comment]
> I can adjust the lane connectors but they don't work as they should.

What do you mean by that?

**Comment by igorrychert** [comment]
> > I can adjust the lane connectors but they don't work as they should.
> 
> What do you mean by that?

Even though the lanes are connected, the vehicles do not comply with these rules.

**Comment by keeperagb** [comment]
I'm having the same problem, did you manage to solve it?
