### ISSUE TITLE
BUG STRET intersection 

### ISSUE THREAD

**Issue by keeperagb** [CitiesSkylinesMods/TMPE#1743]
### Steps to reproduce

1. create an intersection on any street, or upgrade
2. cars do not travel through the site
3. I have to access the mod settings and reset
4. the vehicles start to travel but very slowly

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/11512678/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/11512679/TMPE.log)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2977603985

### Screenshots?

https://youtu.be/V2s9LLWlX7Y

### Notes or questions?
Compatibility Report no have problem

**Comment by krzychu124** [comment]
From the mod description:
![image](https://github.com/CitiesSkylinesMods/TMPE/assets/19638970/b11da060-d222-4386-afd6-cc5bf26e7aff)

**Comment by keeperagb** [comment]
hell, thank you very much, already corrected what was wrong, you can close
