### ISSUE TITLE
Epic Games

### ISSUE THREAD

**Issue by PierrunoYT** [CitiesSkylinesMods/TMPE#1750]
How can I use it on Epic Games?

**Comment by krzychu124** [comment]
So, you found github page of the mod, **_but you didn't notice this on the front page:_**

![image](https://github.com/CitiesSkylinesMods/TMPE/assets/19638970/c211926f-51d2-4055-9dd3-f9fe45afd5f6)

**_and then this on the linked wiki page:_**

![image](https://github.com/CitiesSkylinesMods/TMPE/assets/19638970/5ab4be7f-2782-4652-9cc8-92faefb85cb4)

Interesting 🤔

**Comment by PierrunoYT** [comment]
I'm dumb
