### ISSUE TITLE
Method not found: 'PathManager.FindPathPosition'. [System.MissingMethodException]  Details: No details

### ISSUE THREAD

**Issue by Tapes** [CitiesSkylinesMods/TMPE#1752]
### Describe the problem

I can't place roads, even the first one to unlock the other ones.

The error pop up when i start a new game.

### Steps to reproduce

1.  Just start a new city
2. 
3. 

### Screenshots?

https://i.imgur.com/pCEgm18.png

**Comment by krzychu124** [comment]
Update the game and the mod.
