### ISSUE TITLE
monorail road speed not showing right value

### ISSUE THREAD

**Issue by hellas2000** [CitiesSkylinesMods/TMPE#1754]
### Describe the problem
monorail road speed not showing right value, as shown in:
https://steamcommunity.com/sharedfiles/filedetails/?id=3017886125

it should be 50, like in this picture:
https://steamcommunity.com/sharedfiles/filedetails/?id=3017886151

### Steps to reproduce

build a segment of "monorail tracks on four-lane road",
click on TMPE icon, will show the wrong speed 70, but it should be 50.

Thank you.

**Comment by krzychu124** [comment]
It's because general speed limit view (single icon per segment) shows average speed based on all lanes. Use per-lane mode to see more accurate value

**Comment by hellas2000** [comment]
> 

Ok I understand now, thanks a lot.
