### ISSUE TITLE
I keep getting the error pathmanager.find path position

### ISSUE THREAD

**Issue by Goyrilla123** [CitiesSkylinesMods/TMPE#1764]
### Describe the problem

 I'm having some issues with the mod, i can't play with it, i keep getting the error pathmanager.find path position, i don't know why because i was playing a day before and everything was ok, but now i keep getting this error, i get this even when i start a new save so i think my save is not corrupted, and when i close the tab and hit play the game keep showing this

### Steps to reproduce

1. I just openned the map
2. The tab shows up, i close it.
3. When i hit play the tab keep showing up

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/14335426/output_log.txt)

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/14335427/TMPE.log)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=3164245525

### Screenshots?

![image](https://github.com/CitiesSkylinesMods/TMPE/assets/160529480/582e2a7d-e6af-47a0-aaea-30b539c231cb)

**Comment by krzychu124** [comment]
Update the game to the latest version.

**Comment by krzychu124** [comment]
Closing, since the issue is not present when using the latest version of the game

**Comment by HH5921** [comment]
I'd like to ask if you've solved it.
