### ISSUE TITLE
Report an error

### ISSUE THREAD

**Issue by HH5921** [CitiesSkylinesMods/TMPE#1769]
I checked the mod, anyway, when I only open two front mods and tmpe will report the following error, and keep popping up when running the game, resulting in a menu that cannot be opened.Thank you for your trouble.

Method not found: 'PathManager.FindPathPosition'. [System.MissingMethodException]

Details:
No details

**Comment by krzychu124** [comment]
Make sure you run **the latest version of the game (1.17.1f4)** and **the latest version of the mod (11.8.0.0)**. 
Any other combination will not work correctly.

https://github.com/CitiesSkylinesMods/TMPE?tab=readme-ov-file#support-policy

**Comment by HH5921** [comment]
> 确保运行**最新版本的游戏 （1.17.1f4）** 和**最新版本的 mod （11.8.0.0）。**任何其他组合都无法正常工作。
> 
> https://github.com/CitiesSkylinesMods/TMPE?tab=readme-ov-file#support-policy

Both versions are correct. Is it possible that I don't have enough memory? I'm 16 gigabytes, and there's one more mistake.

Broken assets:

Commercial Low: Game Store 3x3 Level 1: Object reference not set to an instance of an object
Commercial Low: Game Store 3x3 Level 2: Object reference not set to an instance of an object
Commercial Low: Game Store 3x3 Level 3: Object reference not set to an instance of an object
Commercial High: Future Store 4x4 Level 1: Object reference not set to an instance of an object
Commercial High: Future Store 4x4 Level 2: Object reference not set to an instance of an object
Commercial High: Future Store 4x4 Level 3: Object reference not set to an instance of an object
Monument: Countdown Clock: Object reference not set to an instance of an object [BrokenAssetException]

Details:
No details

**Comment by krzychu124** [comment]
There are only two reasons for that error: 
- outdated version of the game or mod
- or completely different mod is incompatible.

You didn't share the log file (output_log.txt) so how can I know what you have installed?
And no, the error about missing method is only caused when trying to run incompatible version of the game or mod.

Broken assets are broken assets, completely unrelated.

**Comment by HH5921** [comment]
[output_log.txt](https://github.com/user-attachments/files/16720496/output_log.txt)
Is this it? I always subscribe to the latest in the creative Workshop, and just a few essential mods. Please take another look at it for me, and I'll change the hardware if I have to. Thank you.

**Comment by krzychu124** [comment]
> [output_log.txt](https://github.com/user-attachments/files/16720496/output_log.txt) Is this it? I always subscribe to the latest in the creative Workshop, and just a few essential mods. Please take another look at it for me, and I'll change the hardware if I have to. Thank you.

Yes, file is correct. 
From the log you sent: `Game Version: 1.17.0-f3-epic-win`
You said: 
> "Both versions are correct." 

which is clearly not true!

I told you what's the correct version so **update the game.**
> Make sure you run **the latest version of the game (1.17.1f4)**

**Comment by HH5921** [comment]
> > [output_log.txt](https://github.com/user-attachments/files/16720496/output_log.txt)就这样吗？我总是订阅创意工坊中的最新版本，以及一些基本的 Mod。请帮我再看一眼，如果需要的话，我会更换硬件。谢谢。
> 
> 是的，文件是正确的。从你发送的日志中：你说：`Game Version: 1.17.0-f3-epic-win`
> 
> > “两个版本都是正确的。”
> 
> 这显然不是真的！
> 
> 我告诉过你什么是正确的版本，所以**更新游戏。**
> 
> > 确保您运行**最新版本的游戏 （1.17.1f4）**

Thank you so much. I figured out the problem, too. Since I'm epic, I had to import the mod myself, so the game version was automatically lowered. Thank you for your answer.
