### ISSUE TITLE
error "references to null instance"

### ISSUE THREAD

**Issue by samjoe16** [CitiesSkylinesMods/TMPE#1772]
### Steps to reproduce

1. Unlock all the areas using areas 81 mod. 
2. Running the game with advanced parking on. 
3. Let the game running for about 1-2 hours.
4. The error "references to null instance" will pops up with all the water and electricity and water connection disabled. 

### Log files

[TMPE.log](https://github.com/user-attachments/files/17750795/TMPE.log)
[output_log.txt](https://github.com/user-attachments/files/17750796/output_log.txt)
backup linked if above files doesn't work:
https://drive.google.com/file/d/1ozjtcNPSseDaio8_-fro3SHOTcJqrSNp/view?usp=sharing
https://drive.google.com/file/d/1z5XDhHTHNQlkwp32tAv8SgYOKXNXEd3l/view?usp=sharing

### Savegame?

N/A

### Screenshots?

N/A

### Notes or questions?
N/A

**Comment by krzychu124** [comment]
Did you use any custom citizens workshop assets? If so, make sure all are working correctly

**Comment by samjoe16** [comment]
> Did you use any custom citizens workshop assets? If so, make sure all are working correctly
Ok, I use a bunch of them. I will unsub to all of them and testing them out. Skyvee didn't give me any warning tho

**Comment by samjoe16** [comment]
> Did you use any custom citizens workshop assets? If so, make sure all are working correctly

Ok, I unsub from all the citizen mod and tested the game for 12 hours. No errors pops up. the issue is fixed. Thank You very much!!
