### ISSUE TITLE
Option to allow cars to cross road for parking

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#189]
I'm seeing lots of cars drive down a road, turn at the end of that road, and then drive most of the way along the road again to get to a parking space that they'd already driven past (albeit on the other side of the road).

Time for another of my crummy ascii diagrams:

```
Start
  ↓
  →--X-------
             |
     ←-------
     P
     ↑
     Parking spot
```

Could the mod be configured to allow cars to cross the road if they drive past the building where they want to park (on the requirement that it has available parking spot)? In the diagram above, the car would cross at point `X` to get to `P` rather than driving to the end of the road and back again.

This would only be viable on small roads (2 lane roads, optionally with bus/bike lane).

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/184

**Comment by VictorPhilipp** [comment]
I think this is possible but wouldn't that look pretty weird?

**Comment by VictorPhilipp** [comment]
It's ubiquitously common where I live in UK. I've never seen anyone drive past the place they want to park just because it's on other side of road. The parking space is treated like a road segment at a T-junction node, and it doesn't matter how much traffic backs up behind them, the driver is determined to get that parking :)

Driver logic seems to be:

> * Ignoring service vehicle lanes (usually a bus lane), if I only need to cross a single lane then just cross the road to get to parking.
>     * ...unless the lanes to be crossed are really busy
> * Otherwise, keep driving and find somewhere safe to turn and enter parking from correct side of road.

While this creates transient traffic delays, getting vehicles off the road sooner rather than later generally reduces congestion (assuming the logic above is adhered to).

**Comment by VictorPhilipp** [comment]
Cars would obviously not cross medians, including the more elaborate designs discussed in #196

**Comment by aubergine10** [comment]
This seems closely related to #19?

**Comment by aubergine10** [comment]
Closing this as it's now tracked by #1223
