### ISSUE TITLE
Dummy traffic only entering via one outside connection

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#199]
I have a city with 2 outside road connections (south and west sides of the map, with a path between them).

The dummy traffic in my city is only entering via a single outside connection.

Will upload a save illustrating the issue some time in next 24 hours.

Was something modified in relation to https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/175 ?

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/215

**Comment by VictorPhilipp** [comment]
No, I have not changed anything for #175.

**Comment by aubergine10** [comment]
Not seen any other reports of this issue, was likely a broken outside connection (eg. only highways work as outside connections, unless user has [Any Road Outside Connections](https://steamcommunity.com/sharedfiles/filedetails/?id=883332136) mod).
