### ISSUE TITLE
Add a new step to the load process

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#228]
_As a developer I want to be able to initialize the program state before the level is loaded in order to avoid errors when users switch between different savegames._

**Assumptions/Preconditions**
- The level loading procedure currently consists of the following steps:
    1. {Flags|NodeGeometry|SegmentGeometry}.OnBeforeLoadData
    2. ICustomManager.OnBeforeLoadData *(for every manager)*
    3. (SerializableDataExtension loads custom game data)
    4. ICustomManager.OnAfterLoadData *(for every manager)*
    5. (LoadingManager sets up detours)
    6. ICustomManager.OnLevelLoading *(for every manager)*
- It is currently impossible for managers to reset their fields before geometries are calculated.

**Tasks**
- Add a new `OnInit` step that is called before geometries are calculated.
- Update the documentation of `AbstractCustomManager`.
  - OR for bonus points: Move the documentation to the wiki.

**Technical notes**
- The step needs to be added to `ICustomManager`, `AbstractCustomManager`
- Log calls to `OnInit` to TMPE.log
- check whether existing code from constructors/`OnBeforeLoadData` code should be moved to `OnInit`

**Acceptance criteria**
- The new step is implemented and is executed before calculating geometries
- TMPE still works when the user switches to another game level

**Comment by aubergine10** [comment]
@kianzarrin have the various hotswap updates effectively resolved this issue?

**Comment by kianzarrin** [comment]
yes
