### ISSUE TITLE
Highways: Hard shoulder / emergency lane

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#26]
In mod options, there's a setting to make **Heavy trucks prefer outer lanes on highways**.

However, many highways will have an outside lane that's used as an emergency 'hard shoulder' (eg. where broken down cars try and get to so they're not blocking traffic while they wait for service van).

Would it be possible to add an additional option (Policies tab in mod settings), something like:

--[ ] **Outermost highway lanes are emergency lanes**

The effect would be to restrict all but emergency traffic (police/ambulance/fire/disaster) from using the outermost lane via 'virtual vehicle restrictions' (in much the same way that the **Ban private cars and trucks on bus lanes**  option does.

Doing it this way would allow users to optionally allow vehicles back on to outermost lane for _some_ highways, eg. those that don't have an emergency lane.

One problem might be what happens if user doesn't have TM:PE installed but uses a highway asset that has hard shoulder? I was thinking if the hard shoulder was a bus lane in the road asset, that users without TM:PE would get an "almost hard shoulder" (busses, taxis, etc, would still use it, but it would be mostly clear of traffic).

What  do you think?

**Comment by krzychu124** [comment]
I am not sure if I understand what you want to do :confused: . Do you want to somehow unlock these currently disabled outer lanes and restrict usage to all but emergency vehicles? I am thinking about 3 lane highway and its white continuous lines on both sides. Could you add some images with roads with that 'hard shoulder'?

**Comment by aubergine10** [comment]
First, to clarify what I mean by emergency hard shoulder: https://en.wikipedia.org/wiki/Shoulder_(road)

Example from England:

![lane-on-mw](https://user-images.githubusercontent.com/1386719/52210307-94dccf00-287e-11e9-85d9-5cce1bfa6916.jpg)

Note: 'Central reservation' lane is often omitted (it's usually found near junctions); but the outer 'hard shoulder' is almost always present on UK highways.

In England they are sometimes given a red texture (especially on older highways):

![2169423_9aa3c4e0](https://user-images.githubusercontent.com/1386719/52210717-bdb19400-287f-11e9-8445-2210aa849c2b.jpg)

In Ireland they usually have a solid yellow line:

![m4_heading_west_at_j11_ start_of_the_n6_near_kinnegad](https://user-images.githubusercontent.com/1386719/52210733-c609cf00-287f-11e9-9515-c7271aa33982.jpg)

The wikipedia article above shows other examples.

Next comment will explain how option would work...

**Comment by aubergine10** [comment]
The outer lane is converted to emergency lane by adding virtual vehicle restrictions

It's same approach as the **Ban private cars and trucks on bus lanes** option; only in this case it's detecting outermost vehicle lane and restricting so that only emergency vehicles can use it.

**Comment by aubergine10** [comment]
Asset authors, who want to produce assets which take advantage of the new option, but also want to make it 'kind of work' for players without TM:PE, could optionally designate their outer lane as a bus lane (like normal roads can have bus lanes, only this would be a bus lane on a highway).

While not perfect, players without TMPE would see far less traffic on the outer lane due to it being flagged as a bus lane.

However, players with TMPE will get the full 'emergency lane experience' via the new option (the new option doesn't care whether the outer lane is a bus lane or normal road lane).

**Comment by aubergine10** [comment]
Note: Without the option, players could just manually vehicle restrict their existing outside lane to emergency vehicles, but it would be tedious. Also it would add lots of data to save games which can already be problematic due to https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/160

With the dedicated option, players get a nice way to quickly give their highways a hard shoulder. There are some other benefits, for example if there is single lane ramp joining a highway, it would need lane connecting to both outside lanes (the hard shoulder and the 'normal traffic' outside lane).

Hope that clarifies everything.

**Comment by krzychu124** [comment]
Yup, now I understand everything, thank you for your explanation :wink:

**Comment by aubergine10** [comment]
Closing this as it's now tracked by #515
