### ISSUE TITLE
Button to despawn just trains

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#270]
Steam user CanePlayz:

> For me, a feature to only delete trains and not the whole traffic is absolutely necessary, because if I have problems with my trains, there is always an unbelievable backup of trains that cant get out of my city and I can`t delete them all because that would take so much time. But of course a great mod. Keep on working!

I've also experienced this pain; not wanting to despawn all vehicles, I ended up manually despawning about 50 trains which was a PITA.

Hopefully it will be relatively easy to implement, as it's subset of existing 'despawn all' feature. A button in mod options (maintenance tab) would be suitable.

**Comment by aubergine10** [comment]
I guess this could be extended to "Just boats", "Just _whatever_" at some point (eg. if we implement #51 the despawn stuff could get its own tab with icons for various despawns)

**Comment by pallamf** [comment]
Funny, I'm looking for this, too and came across this post.  I separated my train lines, etc.  All the routes are clogged, and when a train leaves a cargo hub, new trains are spawned, instead of letting in other trains.  What a mess.  There are about 100+ trains on my map, so I would love to clear them all and let the engine regenerate what it thinks it needs.

**Comment by aubergine10** [comment]
We could make it so the Clear Traffic button opens a list of checkboxes of what should be cleared. 

The checkbox selections could be saved to global config perhaps? Would be useful for dev too if we're regularly clearing certain type of traffic during testing something.

**Comment by kvakvs** [comment]
Idea:
Despawn button pops up a choice of transport type or [All] checkbox.
Also with an [Apply] button.

**Comment by kvakvs** [comment]
This is two parts job
1. Create that panel mentioned above
2. Refactor despawning call into an intent with bit options per traffic type.

**Comment by aubergine10** [comment]
PR #1341

![image](https://user-images.githubusercontent.com/1386719/151744086-0149bb96-ccc5-499a-8d6e-ce6d5efc5a08.png)
