### ISSUE TITLE
Option to allow fire trucks to use pedestrian paths in park areas

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#300]
Currently parklike park areas prevent access to fire trucks due to lack of roads.

In addition, fire helicopters seem preoccupied with putting out tree fires, not building fires (makes sense, as fire trucks are pretty much useless against forest fires).

Would be nice if there was option to allow fire trucks to drive _in_ to parks via their ped paths. Only in park areas would ped paths be considered 'roads' (and only to fire trucks).

**Comment by aubergine10** [comment]
Same way park buildings know if they can be placed by a path? But somehow cached.

I suspect the game will already have a cache of which paths are park paths.

**Comment by aubergine10** [comment]
This probably isn't required any more due to this change in Campus free update:

> ## Fire behavior update
>  
> In the free update we also provide the players the possibility to turn off the spreading of fire. This applies to all kinds of fires from forest fire to building fire. When this option is turned on, it prevents large scale forest fires by not allowing fire to spread from one tree to another. It also prevents fire from spreading from trees to buildings and from buildings to buildings and so on. However, if the player turns on random disasters, this option is disabled. Also, setting random disaster probability to more than zero or playing a scenario turns the option off.
>  
> The fire behavior update also brings change to how fire behaves with Parklife and Campus buildings placed on paths. Normally these buildings can catch on fire only if they are placed on roadside. However, **buildings placed alongside paths can also catch fire if the player has Natural Disasters installed and has unlocked helicopters and has turned random disasters on or is playing a scenario**.

**Comment by krzychu124** [comment]
Closing due to changes in base game which satisfies requirements of this feature
