### ISSUE TITLE
Strange vehicle/unit count bug

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#317]
> # Solution:
> This bug is not caused by TM:PE; it's caused by broken vehicle assets.
>  
> * Solution: Unsubscribe [broken vehicle assets](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Broken-Vehicle-Assets#breaks-vehicle-spawning)
> * Workaround: For broken boat assets, reducing their speed with AVO seems to help
> * Workaround: In TM:PE, despawning all vehicles, etc., temporarily resolves the issue, or...

----

There is a bug somewhere (likely not caused by TM:PE) that's hogging unit count and subsequently causing vehicles not to spawn, even on small/medium cities. Users commonly report that their industries are not working or, in severe cases, their city starts to depopulate due to multiple notification issues.

I did some digging and found three links that contain save games:

* [#297 - TM:PE user](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/297#issuecomment-487746550)
* [#267 - TM:PE user](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/267#issuecomment-480559607)
* [Steam forum - Non-TM:PE user](https://steamcommunity.com/app/255710/discussions/0/1648792788228491150/)

Interestingly, in the latter link (non-TM:PE) it was discovered, by another Steam user, that removing two workshop vehicle assets resolved the situation:

* [Red Fishing Boat](https://steamcommunity.com/sharedfiles/filedetails/?id=1107521505) (cargo ship)
    * Asset comments indicate it is too fast which freaks the AI and blocks shipping lanes
    * Apparently, slowing it down using AVO resolves the issue (based on comment on asset workshop page)
* ~~[Mack CH603 w/ Tanker](https://steamcommunity.com/sharedfiles/filedetails/?id=1424507440) (oil truck)~~
    * ~~Asset comments do not mention any issues, but could do with testing if anyone has time~~
    * ~~EDIT: Likely to be a false-positive as it is now confirmed the Red Fishing Boat is known to be broken~~
    * EDIT 2: Multiple confirmations on Steam that the truck does not cause any problems.

There were two other vehicles I know of that cause similar issues, but it was years ago (~2016) - they've since been removed from workshop, however it seems workshop sometimes fails to delete removed assets. Their workshop ids are: 450619803 and 450652597.

Some of the vehicles are listed on our [Broken Vehicle Assets](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Broken-Vehicle-Assets#breaks-vehicle-spawning) wiki page.

If we could potentially isolate such a vehicle and confirm it causes the unit count problem, someone in the modding community might be able to do further digging and create a small mod that fixes that issue (or we could build it in to TM:PE).

Note: Another possible cause of unit count issue is the crazy tourist bug on bi-directional highway outside connections. For more info on that, see: #273

**Comment by aubergine10** [comment]
More on the non-TM:PE user - looks like the boat is known to cause the problem:

> **aubergine18:**
> BucketBrain: How did you determine that those two vehicles were causing the vehicle limit problem?

> **BucketBrain:**
> [Active vehicle limit at 35000 pop ? (Screenshot)](https://steamcommunity.com/sharedfiles/filedetails/?id=1742106480)
>  
> l use the extended info panel that listed the vehicle count in game and his city was too empty for 16000 cars + he told about his custom vehicles . l took the AVO and searched unusual vehicles - not my usual content , found the oil trucks and the boat and disabled them + removed them from the map . All in game on pause.
>  
> Unpause and the av count dropped in a second to 3500 + the deblocked outside ship routes send some hundred ships with goods 
>  
> Later on l had a talk with 1JasonBradly . He knew about that bugged boat . lt seems the asset creator removed negative comments about his shtt
>  
> l didn´t test the Oil trucks again , but think they are ok .

**Comment by aubergine10** [comment]
Another two assets with this problem:

* [Blue fishing boat](https://steamcommunity.com/sharedfiles/filedetails/?id=1107517568)
* [Tugboat](https://steamcommunity.com/sharedfiles/filedetails/?id=1107513981)

**Comment by krzychu124** [comment]
_Out of scope - broken assets_
