### ISSUE TITLE
UI: Highlight lane when hovering over icons associated with lane

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#33]
- [x] Lane connectors #635
- [x] Speed limits #709
- [x] Parking restrictions #708
- [x] Vehicle Restrictions #721

Sometimes, particularly if various persistent overlays are enabled in mod settings, it's difficult to see which lane a row of vehicle restriction icons belong to. Short rail segments (especially when using 1-lane tracks next to each other) are also sometimes difficult as icons might overlap with infoview icons of adjacent rails.

So, I was wondering if it wold be possible to highlight associated lane when mouse is over an icon, that way it's very clear which lane is being affected when the mouse clicks.

A similar thing could benefit speed restrictions when the individual lane mode is active.

**Comment by aubergine10** [comment]
I'd take a more agile approach if possible; push improvements out as they are completed, rather than trying to waterfall it in to big patch. Bu doing incremental updates, if any bugs creep in, there's less code changes to dig through to find them.

That being said, I can spend some time this week doing visual mockups of what the changes might look like; so far they've been described as words but it might be a good ideal to put them in to pixel as a sanity-check that the UI would be viable before making changes to code?

**Comment by krzychu124** [comment]
No problem :wink: I've had a plan to release 1.10.15 later this week(maybe even on Friday) after merging with Turn on red feature if I'll find time to check if everything works with that.

Great idea with mockups, would be nice to look how it could look like. Its always easier to make changes on image than in code.

**Comment by aubergine10** [comment]
Is the 'turn on red' feature optional? a) because some countries don't allow it (eg. UK), and b) if it causes problems users should be able to turn it off while it gets bugfixed.

**Comment by krzychu124** [comment]
Yup, I've started testing it yesterday and it's disabled by default IIRC :wink:

**Comment by aubergine10** [comment]
Let me know which mod settings screen (I assume "Maintenance") its on as the docs will need updating. I've added a bunch of stuff to the "Wiki" tab (still lots of stuff missing, broken links, etc) but expect to have bulk of docs finished in a week or two.

**Comment by krzychu124** [comment]
'Turn on red' feature toggle is currently located on 'Gameplay' tab under 'Vehicle behavior'. I think that 'Maintenance' could be better but the best would be on 'Policies & Restrictions' under 'At junctions' because its strictly related to this.

What do you think? I can add request to change location to my review of feature pull request :wink:

Generally wiki section looks amazing. As you said it still needs some work but besides that I think there are all information they need. In addition I can see you are experienced player and you know this game and mod better than me. Great work!

**Comment by aubergine10** [comment]
Policies & Restrictions seems best tab IMO. It's a traffic rule (policies & restrictions), rather than a traffic modifier (gameplay) or major feature (maintenance).

**Comment by aubergine10** [comment]
Ancient image from Traffic++ showing how lanes can be highlighted.

So far, I can see this sort of highlighting being useful for:

* Parking restrictions
* Vehicle restrictions
* Lane arrows / Lane connector
* Timed traffic lights
* Speed limits

![b01d7a64-ffcc-11e4-93df-d220047e19dc](https://user-images.githubusercontent.com/1386719/52449528-94b72a80-2b2f-11e9-9e60-caa1ce97063a.png)

It could even be useful for junction restrictions and priority signs...

Although it could get annoying so possibly some setting in global config or mod settings to choose which tools it applies to?

**Comment by krzychu124** [comment]
Moar settings and options 🤣 
I've had similar image in my mind when I saw topic of this issue. Could you post again link to source of Traffic++. I can't find it because you've added too many issues 😆

**Comment by aubergine10** [comment]
When using with timed traffic lights, or when using with 'all segments between two junctions' key modifiers on other tools, it would need ability to highlight one or more lanes along multiple segments.

T++ source: https://github.com/joaofarias/csl-traffic

**Comment by aubergine10** [comment]
Closing this as it's basically complete but via several issues:

- Lane connectors #635
- Speed limits #709
- Parking restrictions #708
- Vehicle Restrictions #721

The traffic lights lane highlighting is tracked by at least one separate issue already so no need to keep this #33 open.
