### ISSUE TITLE
Question or bug: Bus ignoring lane arrows policy

### ISSUE THREAD

**Issue by SubaruSVX** [CitiesSkylinesMods/TMPE#330]
I'm not sure if this is a bug, but if it is, then this can be placed in the right category.

How are buses supposed to ignore lane arrows?

<img width="498" alt="Screen Shot 2019-05-23 at 6 05 50 PM" src="https://user-images.githubusercontent.com/50699460/58244606-7cd58080-7d85-11e9-98b1-0b157d6d188a.png">

Because, from my understanding of what it says on the tin, it means that if, in this case, a bus were to go straight, it would use the turn right lane to join the four lane road.

**Comment by SubaruSVX** [comment]
Picture of the junction in question:

Now, my bus route goes straight, as per the diagram. There is a standalone lane to turn left, and a standalone lane to turn right.
![Screenshot 4](https://user-images.githubusercontent.com/50699460/58245248-f15cef00-7d86-11e9-9319-5fa5c8b57d1e.png)

But with the policy turned on, for some reason, this happens.
![Screenshot 5](https://user-images.githubusercontent.com/50699460/58245250-f15cef00-7d86-11e9-9c17-4468e88a17dd.png)

**Comment by aubergine10** [comment]
The policy allows them to ignore lane arrows if it helps them achieve a better route.

More info here: https://tmpe.viathinksoft.com/wiki/index.php?title=Busses_may_ignore_lane_arrows

**Comment by SubaruSVX** [comment]
So, in this case, the computer would have thought that the right lane wouldn't make it better?

**Comment by SubaruSVX** [comment]
Hmm.
![Screenshot 6](https://user-images.githubusercontent.com/50699460/58246661-3df5f980-7d8a-11e9-94e0-6c06a28495dc.png)


![Screenshot 7](https://user-images.githubusercontent.com/50699460/58246662-3e8e9000-7d8a-11e9-9657-ac78a939b923.png)
![Screenshot 8](https://user-images.githubusercontent.com/50699460/58246664-3e8e9000-7d8a-11e9-973f-1cc31d1e9610.png)

**Comment by krzychu124** [comment]
As far as I know, lane connection has precedence over lane arrow (arrows are chosen based on lane connections) so bus has to choose second lane (go straight).

**Comment by SubaruSVX** [comment]
So, if one were to, for example, make connections that don't directly affect the lanes that aren't selected, the buses will follow what's on the road?

**Comment by aubergine10** [comment]
> As far as I know, lane connection has precedence over lane arrow (arrows are chosen based on lane connections) so bus has to choose second lane (go straight).

I'm not sure if this is entirely correct.

Reasoning: Reckless drivers can ignore lane arrows, but cannot ignore user-defined lane connectors. So there must be some degree of separation between the two. I'm not sure how that works, maybe @VictorPhilipp can advise?

**Comment by VictorPhilipp** [comment]
Yes, lane connections and lane arrows are seperate systems.

**Lane arrows** can be thought to be kind of an advice for vehicles: All kind of road vehicles should follow them. But for example reckless drivers and emergency vehicles on duty may ignore them. As you know there is also an option that also allows buses to ignore them.

Also, important to know is that ignoring a lane arrow comes with a higher path-finding cost. That means buses will ignore them if it is really necessary but otherwise they stick to regular traffic rules. The reason behind this is because at junctions with standalone lanes for each directions that also have standalone timed traffic lights for each direction, vehicles that ignore lane arrows cause traffic jams when they use a turn lane to go straight. (https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/206)

**Lane connections** on the other hand are super strict: Neither can reckless drivers, emergency vehicles nor busses ignore them.

**Comment by VictorPhilipp** [comment]
https://tmpe.viathinksoft.com/wiki/index.php?title=Lane_connector

**Comment by Phoenix616** [comment]
> Lane connections on the other hand are super strict: Neither can reckless drivers nor busses ignore them. But emergency vehicles on duty can!

Any chance to get an option for buses ignoring lane connectors similar to the ignore lane arrows policy? 

I realise that lane connectors probably modify the pathfinding on a deeper level (by actually changing the connections of the nodes or something like that?) but it really hurts your bus lines if all you want is proper traffic flow but your buses to still take a short route e.g. in a situation like this where the bus stop is directly at the intersection on a two-lane, one-way stree and the bus will not be able to reach the left turning lane from the stop:

![image](https://user-images.githubusercontent.com/5768781/61228178-aa9fcb80-a71d-11e9-9913-da02fa8843a0.png)
.
(This would work fine with lane-arrows though)

**Comment by aubergine10** [comment]
Lane Connectors are "hard-wired" links between lanes; their sole purpose is to create a lane linkage that _all_ vehiclesd must follow (including reckless drivers and emergency vehicles). See: #1219

Closing this as `wontfix` as it's simply not possible with current implementation.
