### ISSUE TITLE
T Junctions don't seem to have u-turns occur

### ISSUE THREAD

**Issue by SubaruSVX** [CitiesSkylinesMods/TMPE#347]
### Description
Perhaps I can use better words, but when I put in a metro station with several parking garages, all the cars seem to have a rather peculiar habit of doing a loop, even when the u-turns policy is enabled. 

### Reproduction Steps
Add more steps as nessecary.
1. Select any T-Junction on the game (preferably with the six-lane roads)
2. Allow the policy for u-turns to be enabled
3. Watch.

### Mod List
Please list the mods enabled when you noticed the bug.

[config SubaruSVX.docx](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3239814/config.SubaruSVX.docx)

### Output Log
[Player.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3239789/Player.log)

### Savegame (Optional)
https://steamcommunity.com/sharedfiles/filedetails/?id=1736078702

### Screenshots (Optional)
![Screenshot 11](https://user-images.githubusercontent.com/50699460/58683343-b1a98f00-83a6-11e9-848c-4e29c484c4fd.png)
![Screenshot 12](https://user-images.githubusercontent.com/50699460/58683344-b2422580-83a6-11e9-826d-d9a1d5167357.png)
![Screenshot 13](https://user-images.githubusercontent.com/50699460/58683346-b2422580-83a6-11e9-8461-7e4a5e1301e4.png)
![Screenshot 14](https://user-images.githubusercontent.com/50699460/58683347-b2422580-83a6-11e9-912a-3487dce77245.png)
![Screenshot 15](https://user-images.githubusercontent.com/50699460/58683348-b2dabc00-83a6-11e9-957f-09d4cacbbe14.png)

**Comment by aubergine10** [comment]
Plain text mods list:

```
config SubaruSVX's Mod List

### mods list ###

Hard Mode (ID=18446744073709551615)                         deactivated
Unlimited Money (ID=18446744073709551615)                   activated
Unlimited Oil And Ore (ID=18446744073709551615)             activated
Unlimited Soil (ID=18446744073709551615)                    activated
Unlock All (ID=18446744073709551615)                        deactivated
Employ Overeducated Workers V2 (ID=1674732053)              activated
Network Skins (ID=543722850)                                activated
Prop Snapping (ID=787611845)                                activated
Los Santos Rock Radio (ID=1564632871)                       activated
Metro Overhaul (ID=816260433)                               activated
Train Converter (ID=795514116)                              activated
Prefab Hook (ID=530771650)                                  activated
Advanced Stop Selection (ID=1394468624)                     activated
Non Stop Pop FM (ID=1563236161)                             activated
Ambient Sounds Tuner (ID=818641631)                         activated
Rebalanced Industries (ID=1562650024)                       activated
Tiny Segments 2.0 (ID=1586027591)                           activated
Plop The Growables (ID=924884948)                           activated
BigCity (ID=1270675750)                                     activated
Vehicle Wealthizer 1 (ID=1633580257)                        deactivated
Klyte Commons 1.1.6 (ID=1312735149)                         deactivated
First Person Camera (ID=650805785)                          activated
CSL Music Mod (ID=422934383)                                activated
Pollution Solution (ID=1263262833)                          activated
Airport Roads 1.3.7 (ID=465127441)                          activated
Unlock All + Wonders & Landmarks (ID=458519223)             activated
Better bulldoze Tool (ID=417965096)                         activated
Surface Painter (ID=689937287)                              activated
Automatic Bulldoze v2 (ID=639486063)                        activated
Find It! 1.5.4 (ID=837734529)                               activated
Network Extensions 2 (ID=812125426)                         activated
Prop & Tree Anarchy (ID=593588108)                          activated
Extra Landscaping Tools (ID=502750307)                      activated
Fine Road Anarchy 1.3.5 (ID=802066100)                      activated
Fine Road Tool 1.3.7 (ID=651322972)                         activated
Precision Engineering (ID=445589127)                        activated
More Effective Transfer Manager (ID=1680840913)             activated
Favorite Cims v0.3.1b (ID=426460372)                        activated
Move It 2.4.1 (ID=1619685021)                               activated
No Park Building Fires (ID=1718245521)                      activated
AST: KRA Sound Pack (ID=618536610)                          activated
TM:PE 10.20 (ID=1637663252)                                 activated
Empty It! (ID=1661072176)                                   activated
Achieve It! (ID=1567569285)                                 activated
Real Time (ID=1420955187)                                   activated
Advanced Vehicle Options 1.8.5 (ID=1548831935)              activated
Cargo Hold Fix (ID=1721492498)                              activated
WG Citizen Lifecycle Rebalance v2.6 (ID=654707599)          activated
WG Realistic Population v8.4.0 (ID=426163185)               activated
Show It! (ID=1556715327)                                    activated
Hide It! (ID=1591417160)                                    activated
Service Vehicle Selector 2 (r4.0.2) (ID=934994075)          activated
Improved Public Transport 2 [r4.3.1] (ID=928128676)         activated
Loading Screen Mod (ID=667342976)                           activated
```

**Comment by VictorPhilipp** [comment]
Some ideas:
- U-turns are treated as 2 lane changes. So cars might prefer to take a small detour instead of performing a u-turn. (You can change the number of accounted lane changes in the TMPE_GlobalConfig.xml file:
![grafik](https://user-images.githubusercontent.com/4333935/58735080-9d42b200-83f9-11e9-847d-1404c01ade1e.png)
- U-turns can only happen if there is a left-pointing (RHD) / right-pointing (LHD) lane arrow

**Comment by aubergine10** [comment]
@VictorPhilipp Is that `UTurnLaneDistance` used for all u-turns, regardless of node type?

Maybe it should be:

* Terminal node: `0` (cul-de-sac)
* Junction node: `UTurnLaneDistance`
* Transition node: `1 + UTurnLaneDistance`

**Comment by kianzarrin** [comment]
2 relevant lines of code (I have simplified the code in my branch but its effectively the same):

1- here U-turn routing of type `LaneEndTransitionType.Default` happens if it is a junction with 2 segments  but not when it is a junction with 3 segments.

https://github.com/CitiesSkylinesMods/TMPE/blob/a7d644629bd2b5ceeff5b5e61b4dca9e07550e8d/TLM/TLM/Manager/Impl/RoutingManager.cs#L907
note `nextIsRealJunction = nextNode.CountSegments() >= 3`

2- this line is reached for T junction with right turn. only relaxed vehicles can do u-turn.
https://github.com/CitiesSkylinesMods/TMPE/blob/a7d644629bd2b5ceeff5b5e61b4dca9e07550e8d/TLM/TLM/Manager/Impl/RoutingManager.cs#L1970
