### ISSUE TITLE
Lane connector: Separate road vs. tracked connections

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#354]
### Description

Using lane connector tool, tram track lanes can only be connected to other tram track lanes.

However, in most cases the tram track lane is also a road or bus lane. It would be nice if we could connect the non-tram traffic to any other traffic lane.

Maybe we could have two shapes on incoming lanes:

* Circle = the connector for road vehicles
* Rectangle = connector for tracked vehicles

This way we could still allow road vehicles to connect to any outgoing road lane, and the tracked (eg. tram, usually) vehicle would be limited to outgoing lanes containing same type of track.

### Screenshots (Optional)

Example of a road that has tram+bus lanes - it's not possible to connect those bus lanes to the bus lanes on adjoining road.

![255710_screenshots_20190601215741_1](https://user-images.githubusercontent.com/1386719/58762230-08010400-8546-11e9-9762-9af3b65496db.jpg)

tasks:
- [x] separate routing for car/track vehicles in routing manager #1501 #1493 #1477 
- [x] sub lane connection manager #1545 #1546 
- [ ] use different sub managers for road/track vehicles
- [ ] (optional) handle trolleybuses

**Comment by aubergine10** [comment]
In addition to different shape, we'd also need to offset (closer or further from junction) the track shapes from where the road shapes usually appear.

Also there is possibility of a "lane area" containing two tracks, for example a monorail lane over tram lane over road lane. So possibly offset and shape would be based on network type?

Some ideas on shapes (no idea if these are feasible):

* Circle = road
* Square = tram
* Triangle = monorail / train / metro (assumption: we'll never have more than one of those networks in the same position on a road)

**Comment by kianzarrin** [comment]
We should use the alt modifier to hide road circle markers. This helps to select rectangular tracks. road selection takes priority.

**Comment by aubergine10** [comment]
That will also solve #353 and would possibly remove the need to differentiate between lane types too #295

**Comment by kianzarrin** [comment]
@aubergine10 @krzychu124 so far I have laid the foundation of the code such that trolleybuses use the same lane connection as cars vehicles and not track vehicles. That means trolleybuses will use the same lane connections as cars. is that OK?

**Comment by kianzarrin** [comment]
I don't think it would be too hard to implement. we need a new transition group: bus. 
Routing manager needs a dedicated code-path to route buses but the rest of the code needs minimal changes.
