### ISSUE TITLE
Multiple Set speed limit calls when holding mouse button while changing speed limit

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#388]
### Description
Speed limits tool - multiple `set speed limit of lane` calls if user holds mouse button while changing speed limit.

Noticeable only in debug build log.

### Reproduction Steps
Add more steps as nessecary.
1. Open speed limits tool
2. Select any speed limit
3. Try to change speed limit of lane by 'click and hold' mouse button.

The longer you hold mouse button the more updates will be triggered.

### Mod List
Please list the mods enabled when you noticed the bug.
- TM:PE [STABLE]

### Output Log

Log fragment
```cs
[Debug] @ 2859127769 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2859636774 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2859644023 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2859656160 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2859662617 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2860226599 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2860233278 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2860247125 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2860253805 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2860843788 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2860851551 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2860864291 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2860870559 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2861411122 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2861419469 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2861432819 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2861439275 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2861988519 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2861995261 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2862009132 SpeedLimitManager: Setting speed limit of lane 95423 to 40
[Debug] @ 2862015323 SpeedLimitManager: Setting speed limit of lane 138206 to 40
[Debug] @ 2862482250 SpeedLimitManager: Setting speed limit of lane 95423 to 40
```

**Comment by aubergine10** [comment]
Is this something to do with the fact that it's designed to allow "dragging" a speed down a road? I think that feature was added about a year or two ago prior to some shortcuts being added for similar effect.

**Comment by kvakvs** [comment]
We can probably improve this by not setting and not logging if the value is already the same. For this we need to propagate success boolean from the deepest setSpeedLimit function.

**Comment by aubergine10** [comment]
btw: Does the code check if new speed is different to current speed before taking any action?

**Comment by aubergine10** [comment]
Just been reading the old wiki, [which states](https://tmpe.viathinksoft.com/wiki/index.php?title=Speed_limits#Setup):

> To apply the selected speed limit to multiple (nearby) road segments, hold the mouse button down and then move it over the road segments you want to apply the speed limit to.

So it's definitely a "feature" rather than a "bug".

**Comment by kvakvs** [comment]
It should not log "changed speed limit" if it was actually set to the same value. Then it will work as intended.

**Comment by aubergine10** [comment]
Could we also despam it based on either mouse move delta or skip every _n_ frames?

**Comment by aubergine10** [comment]
This feature was removed by #709
