### ISSUE TITLE
Replace 'default speeds' UI with 'rubber stamp' on the main speeds panel

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#389]
The new UI being developed by @kvakvs and @FireController1847  in #384 has uneven number of icons for both km/h and mph.

![example](https://user-images.githubusercontent.com/288724/59883457-743c8e00-93b5-11e9-8ab8-9f742b283cad.png)

We could use the remaining space to add a new "Rubber Stamp" (or whatever) button that allows player to set default speeds for a road.

Process would be as follows:

1. User sets the speeds of a road segment on the map in usual manner
2. User clicks the 'rubber stamp' button and then clicks the road:
    * This takes the speeds set for that segment and sets them as default for that _prefab_
    * A keyboard modifier could apply the speeds as default for _related prefabs_ of same road...
    * Example: Ctrl+Rubber Stamp click = use speed settings for _clicked prefab_ as defaults for _ground, elevated, bridge, slope and tunnel prefabs_ of associated road _asset_

This would allow us to completely eradicate the current default speeds UI, so no more clickathon scrolling through prefabs one by one. It's also much more intuitive as user can see on the map what the speeds are, and they can now have lane-wise default speeds rather than just one speed for entire road. This also overcomes issues with current UI such as inability to set default speed of monorail in a road.

Original comment describing this feature: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/384#issuecomment-503996621

Tagging #84

**Comment by FireController1847** [comment]
@aubergine10 We're not developing a new UI, you realize this right? The point of #384 is to add MPH speed limits, not redesign the entire UI. But yes, I think this needs to be done and added to the UI overhaul. Although I'd love to debate this implementation when the time comes.

**Comment by aubergine10** [comment]
I referenced #384 as that's where it was discussed, but as requested in that PR created this new #389 issue for it so it can be treated as separate task.

**Comment by aubergine10** [comment]
This issue resolved by #1168 .
