### ISSUE TITLE
Allow parking lanes to be used as filter lanes

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#39]
UPDATE: Bus stops can't be used, but we could probably use parking lanes.

----

On most roads, adding bus stop creates a cut-out...  So, I was thinking, what if there was a way to 'trigger' these pavement cut-outs, say, near junctions... In other words, the cut out becomes a filter lane for turning left or right.

* Would need some way to identify whether a road has the pavement cut-out feature or not
* Would need some way to make it extend all the way up to junction
* Would need a way to add a virtual lane to it (and then have traffic lights, lane connector, etc, all working with it)

In theory it would be possible to run a 'fake bus stop' all the way along a stretch of road to add an extra lane to an existing road lol.

> On tram stops, it's often the reverse - they'll cause the pavement to extend out towards the tram, often wiping out some parking spaces or bike lane or something. Not sure what that could be used for, but something to ponder if the bus stop idea above turns out to be feasible.

**Comment by FireController1847** [comment]
That is a really, really good idea. I hate not having turning lanes and being forced to use NeXT to add an asymmetrical road which is bigger than my current road so I have to move eight of my buildings because of this one road and it turns out the turning lane didn't help very much anyways... What was I talking about again? Oh yeah. Great idea. Would love the idea of turning lanes.

**Comment by aubergine10** [comment]
Just learnt: Adding a ```Stop``` flag to a road segment creates the bus stop indentation (if the road supports that kind of thing). Problem might be how to get the game to stop clearing such flags (and also how to prevent actual bus stops from being added to roads where the flag is set).

**Comment by aubergine10** [comment]
Speaking to author of UK Roads assets, and he mentioned that a bus stop only exists in single segment. So if applied to multiple segments, you'd get multiple bus stops but with bits of pavement jutting out between each one. So probably not viable for our needs.

**Comment by aubergine10** [comment]
Was discussing with asset creator recently and it's certain we cannot use this technique. The bus stops basically cause the asset to switch between two meshes and unless the asset is specifically designed to not have any curb at either end of bus stop (which would result in a rectangular bus bay) this approach won't work.

An alternative might be to re-purpose parking lanes.

**Comment by aubergine10** [comment]
Tagging #515 - lane customiser

**Comment by aubergine10** [comment]
Closing this as approach described in OP was infeasible, and alternatives are covered by #515
