### ISSUE TITLE
Polish translation on Gameplay mod options tab too long?

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#401]
Noticed while testing keybinds PR, the last option on Gameplay tab looks like it might be too long in Polish translation?

![image](https://user-images.githubusercontent.com/1386719/60533564-d1123f80-9cf7-11e9-8f96-7c46609eec64.png)

**Comment by aubergine10** [comment]
Wait, there's more...

![image](https://user-images.githubusercontent.com/1386719/60533626-f8690c80-9cf7-11e9-86b2-246702dfa362.png)

**Comment by kvakvs** [comment]
I have made GUI helper for building keybinds UI in #382 , and i suggest we make a similar module for building checkbox UI, which is able to wrap multiple lines and scroll. Won't take long.

**Comment by krzychu124** [comment]
Yeah, we have to merge #382 first, that problem with too long descriptions is quite old

**Comment by aubergine10** [comment]
@kvakvs  Yes, would be good to have a helper (I saw how clean your other helper made the code in #382 - great work!), however not sure about wordwrap (at least in options) as it's already getting crowded in there. Ideally we need translations to be kept as short as possible, ensuring they fit on single line.

**Comment by aubergine10** [comment]
IIRC this is fixed now? If so, anyone know what PR fixed it?

**Comment by krzychu124** [comment]
I think I changed translation but I'll check if we can set max width of the label so it could wrap text automatically when too long
