### ISSUE TITLE
Further enhancement to speed palette

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#406]
We still have the issue that the speed palette is too big in terms of amount of screen space it occupies (see earlier case of this: #162).

Some ideas to shrink it a little:

* Repurpose the "Compact menu" option in General mod options tab to also apply to speed palette?
* UI should ideally factor in screen size and scale accordingly to some extent
* See: #299 and #573

Future ideas (needs more ponder time):

* For mph, have option to hide the *5 speeds (eg. 5, 15, 25, etc) which effectively halves the number of speeds shown
    * If doing island maps, users might want the opposite, eg. hide the *0 speeds (eg. 10, 20, 30, etc)?
* Maybe an option like [Network Skins 2 mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1758376843), where users can mark speeds as favorite (show at start of list) or unwanted (don't show at all) - this way users can customise the list of speeds to just the ones they use most (maybe with some way to 'expand' to full list for rare occasions where they need access to a speed the have hidden)

If #51 goes ahead, we could transition to what is described in #84

**Comment by aubergine10** [comment]
Tagging @SubaruSVX

**Comment by SubaruSVX** [comment]
Well, I play on 1152x720, and I think emphasis should be placed on the last point.

**Comment by aubergine10** [comment]
This has been resolved by #1152, #1157, #1168

Issue #1221 is tracking discussion of additional enhancements which may be made in future.
