### ISSUE TITLE
GameSettings: 'TMPE_Keybinds' is not found or cannot be loaded

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#407]
Only very minor issue that doesn't break anything, but just flagging it up:

```
GameSettings: 'TMPE_Keybinds' is not found or cannot be loaded. Make sure to call GameSettings.AddSettingsFile() to register a settings file before using SavedValue().  [Settings - Internal]
```

The game auto-creates it anyway, but seems to nag if you haven't used `GameSettings.AddSettingsFile()`. I see this with several other mods too. While only minor, would be nice if we could play ball as I assume CO added that log trace for a reason.

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3355261/output_log.txt)

**Comment by krzychu124** [comment]
Warning from CO implementation, can be ignored. Closing.
