### ISSUE TITLE
On-screen display mod

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#410]
I've been pondering this for over a year, but a comment from @kvakvs just prompted me to post the idea...

> **kvakvs:** One problem. I need some GUI space (a tooltip or a floating window?) to display hints, keyboard shortcuts and current help. A tooltip would be great, maybe.

Have you ever played [Railway Empire](https://store.steampowered.com/app/503940/Railway_Empire/)? It's an ok game if you like trains, it's trying to be like [Sid Myers Railroads](https://store.steampowered.com/app/7600/Sid_Meiers_Railroads/) but lacks the gamification. Anyway, one thing that it does excel at is it's small on-screen overlay at bottom of screen that shows context-sensitive info such as keyboard shortcuts and mouse clicks:

![image](https://user-images.githubusercontent.com/1386719/60732225-67857180-9f41-11e9-9d13-acf850b5f925.png)

(That was screen-grabbed from youtube video, so apologies for low quality. If you look close at the mouse buttons you will notice the applicable button is highlighted yellow; it's much clearer in game).

Anyway, I think we need something like that for TM:PE. Considering the keybind stuff and new UI rendering stuff, I think we can easily achieve that now.

What I would suggest, however, is that it's implemented as separate mod if that's possible, as I believe this sort of thing would benefit LOTS of other mods. They could communicate with the OSD mod via a game object or something.

The OSD could be used to display context-sensitive help, keyboard / mice interactions, progress bars, all sorts of stuff. As a separate mod it could just grow over time to facilitate extra features.

It should be optional though; some users will not want OSD.

Another game to check out for its exemplary UI is [Rise of Industry](https://store.steampowered.com/app/671440/Rise_of_Industry/) - I think this is some of the best - clearest, crispest - UI I've seen in any video game I've played.

**Comment by aubergine10** [comment]
Tagging #391

**Comment by kvakvs** [comment]
This (together with generic keybinds render) will become a great assist to users having no idea about TM:PE features for months and years. When work on this begins it'll need a checklist of all tools to visit and report their keybinds to it for display. Might as well be rendered by the `Subtool`/`MainTool` class.

**Comment by aubergine10** [comment]
Yes, and if other modders use it too, it become standard way to let users discover interaction options (keyboard, mouse, maybe even [joysticks/controllers](https://steamcommunity.com/sharedfiles/filedetails/?id=1721824249) at some point)

**Comment by kvakvs** [comment]
Wait is there some ready to use code?

**Comment by aubergine10** [comment]
For what? The OSD? No, not that I know of.

**Comment by kvakvs** [comment]
I suggest having a floating box, positioned around the TM:PE main menu.
The position will be dynamic (top or bottom) to stay towards the screen center.

![image](https://user-images.githubusercontent.com/288724/60821074-1d032f80-a1a3-11e9-8a0d-ff399495e094.png)

A cheap prototype without graphics can be done in an evening, i'll have a look.

**Comment by kvakvs** [comment]
![image](https://user-images.githubusercontent.com/288724/60839664-fd353100-a1cd-11e9-9e88-ca2410ade803.png)

![image](https://user-images.githubusercontent.com/288724/60839694-10e09780-a1ce-11e9-8113-51ad75de6f67.png)

**Comment by aubergine10** [comment]
Would be easier to read if the keybind was put before the description of what the keybind does, and tutorial text was on separate line, eg:

```
Link the lanes
Delete | Backspace Clear       Shift+S Stay in lane       Escape Exit tool
```

**Comment by kvakvs** [comment]
@aubergine10 
![image](https://user-images.githubusercontent.com/288724/60842037-7d11ca00-a1d3-11e9-992b-456db0247627.png)

**Comment by aubergine10** [comment]
Yup, lots better! Text looks really crisp and clear too - how do you get it such high quality? On my rig all the UI looks really blurred.

**Comment by kvakvs** [comment]
@a
![image](https://user-images.githubusercontent.com/288724/60843421-dfb89500-a1d6-11e9-8946-83acc6d45ebb.png)

**Comment by aubergine10** [comment]
Not sure about the backgrounds, think it looked better with just yellow text.

**Comment by kvakvs** [comment]
Are you running the game in native display resolution? I.e. i have 1920x1080 display and the game runs in the exact same resolution.

The backgrounds can be made light with darker text to look more like a keyboard button. But i want at least some color distinction.

**Comment by aubergine10** [comment]
I run at QHD resolution (2560x1440), but for some reason the UI in game seems limited to 1920x1080 regardless of what I set in the Options > Graphics game settings.

**Comment by krzychu124** [comment]
I think we can later add a little question mark to the main tool to toggle that

**Comment by aubergine10** [comment]
Or just customise the existing `?` advisor help button so that it shows our panel instead of the usual tutorial panel.

**Comment by kvakvs** [comment]
![image](https://user-images.githubusercontent.com/288724/60844003-6d48b480-a1d8-11e9-93e3-f635e4e440cc.png)

**Comment by kvakvs** [comment]
![image](https://user-images.githubusercontent.com/288724/60844419-7f772280-a1d9-11e9-840a-91b711b4ad0d.png)

**Comment by aubergine10** [comment]
Another OSD example from game "Cliff Empire":

![image](https://user-images.githubusercontent.com/1386719/61238555-c82c5f80-a734-11e9-8e38-144b3eb2f9d5.png)
