### ISSUE TITLE
Possible parking issue with "Parking Roads" assets

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#423]
### Details

Using ~~LABS 10.21.1~~ STABLE 10.20 <-- that's the problem

> **leaderofthemonkeys** (Paradox):  
> i've been having problems recently w parking, cars just won't park in parking spaces, no matter what i do they won't use them
> on street-parking is a-ok
> but my parking lots remaiuin empty (yes, parking ai is on)
> it's super late, about to go to sleep, so not sure what you want to analyze this

Later:

> i investigated a bit more, seems like it's only badi_dea's parking spaces  
> https://steamcommunity.com/sharedfiles/filedetails/?id=1293869603

### Logs

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3375209/output_log.20.txt) 239,000+ lines!!! by far biggest log file I've ever seen

[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3375212/TMPE.1.log)

### Save game

[QuickSave20190709233553843.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3375240/QuickSave20190709233553843.zip)

Note: Looking at the log file, lotm has 64GB RAM, so I suspect you'll need massive page file to load that savegame. There are truly insane numbers of workshop assets.

### Mods

Bold lines are potentially broken / outdated mods (unlikely to be cause of the issue above, but flagging them up anyway).

Note: Roads United Core+ breaks toll booths; there are some mods that require it (highlighted bold) which should be disabled or removed.

* UnlimitedMoney
* UnlimitedOilAndOre
* UnlimitedSoil
* UnlockAll
* **DaylightClassic (locally installed for some reason)**
* **MoveIt (locally installed for some reason)**
* **PropUnlimitor (locally installed for some reason; also I suspect this is a broken mod)**
* 812125426 - NExt2
* 724382534 - One way train tracks
* 1530376523 - Railway replacer
* 1552053911 - TrailerVariation Loader
* 1546357276 - Industries Vehicle Converter
* 1386697922 - Garbage Bin Controller
* 814498849 - Improved Content Manager
* 1637106958 - Lock Forestry
* 1603398633 - Flag Params
* 820157360 - Spawn Points Fix
* 633547552 - Roads United Core 2.0
* **1586027591 - TinySegments 2.0 (can break traffic lights etc)**
* 1585691173 - HDRI Haven Cubemap Pack
* 1536223783 - Hide Selectors
* 1540147921 - Grid be Gone
* **837112310 - Roads United: Europe (requires Road United Core+ mod)**
* 685719710 - More Shortcuts
* 954067599 - PropRotating Params
* 1369729955 - Customize It!
* 769744928 - Pollution, Death, Garbage and Crime Remover Mod
* **1147015481 - No Crosswalks - Remove Crosswalks/Crossings - Including Road Assets (issues reported with Industries DLC)**
* 1117087491 - Remove Road Props
* 1412844620 - Realistic Walking Speed
* 1394468624 - Advanced Stop Selection (ex MTSE)
* 1388613752 - Tree Movement Control
* 780720853 - Vehicle Effects 1.8.1
* 1349895184 - Tree LOD Fix
* 1324539315 - Land Ships
* 531738447 - CSL Show More Limits
* **553501635 - Sub-Buildings Enabler (DEPRECATED)**
* 734025380 - Configure Outside Connections' Limits
* 785528371 - Cinematic Camera Extended
* 952542692 - Airport Road Light Remover
* 949504539 - SingleTrainTrackAI
* 932490392 - Track My Time
* 595017353 - More Flags ( + flags replacer )
* **932192868 - Road Options (Road Colors Changer ++) (possible conflict with No Crosswalks mod)**
* 775021554 - Theme Mixer
* 922939393 - Transparency LODs Fix
* 911295408 - Prop Scaling 0.3 \[Experimental ALPHA]
* 917543381 - No Problem Notifications
* 910440715 - Plant Scaling
* 903347963 - Transparent Selectors
* 883332136 - Any Road Outside Connections
* 881291183 - Ploppable Asphalt +
* 895061550 - Theme Decals
* 794268416 - Steamy - More Steam controls
* 427258853 - Crossings
* 497033453 - Unlimited Outside Connections (Beta)
* 445589127 - Precision Engineering
* 572888650 - Remove Need For Power Lines
* 576997275 - Remove Need For Pipes
* **821539759 - Disable Zone Check (unmaintained)**
* 406102887 - Super Demand
* 552324460 - No Fires
* 621002682 - No Questions Asked
* 515489008 - Extra Train Station Tracks ( ETST )
* **541673195 - Resident Travel Rebalance v1.1 (not compatible with WG Citizen Lifecycle Rebalance mod below...)**
* 654707599 - Citizen Lifecycle Rebalance v2.6
* 512314255 - More Network Stuff
* 426163185 - Realistic Population and Consumption Mod v8.4.0
* 409069482 - Fill The Houses
* 781767563 - Extended InfoPanel
* 793346248 - Decal Hover Area
* 438449058 - Building Eyedropper Tool
* 768213484 - Subtle Bulldozing, Dragging and More
* **442167376 - Advanced Vehicle Options (AVO) (old version, doesn't properly categorise Industries vehicles)**
* **472128528 - Larger Footprints (Snowfall) (marked as game breaking in workshop)**
* 611254368 - Environment Changer (+ Improved Theme Selection )
* 707497031 - Tram Station Track
* 465127441 - Airport Roads
* 774449380 - Catenary Replacer
* 1094334744 - Procedural Objects
* 1591584836 - HDRI 2K Cubemap Pack
* 1721492498 - Cargo Hold Fix
* 1747800340 - Building Theme: University City Districts
* 928128676 - Improved Public Transport 2
* 934994075 - Service Vehicle Selector 2
* 576327847 - 81 Tiles (Fixed for 1.2+)
* 412149127 - Font Selector
* 1591417160 - Hide It!
* **583429740 - Traffic Manager: President Edition \[STABLE]**
    * v10.20 doesn't include any of the parking fixes
* 1789133988 - Route Shields for PO
* 586012417 - Ploppable RICO
* 815103125 - Extra Vehicle Effects (Plugin for Vehicle Effects Mod)
* 455403039 - Unlimited Trees Mod v1.12
* 912484109 - Flood Damage Control \[BETA]
* **763684437 - Roads United: North America PLUS (requires Roads United Core+ mod)**
* **848896702 - Roads United: US Edition - Reworked (requires Roads United Core+ mod)**
* 973512634 - Sort Mod Settings
* 1776052533 - Stops & Stations
* 1758376843 - Network Skins 2 (Beta)
* **1565201461 - Roads United: US Reworked 2018 (requires Roads United Core+ mod)**
* 1771841274 - HDRI Haven Cubemap Pack 2
* 812713438 - Dynamic Resolution (Fixed for 1.9!)
* 552309905 - No Abandonment
* 412146081 - PostProcessFX v1.9.0
* 1680642819 - Ultimate Level Of Detail (ULOD)
* 1372431101 - Painter
* 1183931915 - Cubemap Replacer
* 458519223 - Unlock All + Wonders & Landmarks
* 924884948 - Plop the Growables
* 878991312 - Prop it Up! 1.4.4
* 793176674 - Sharp Textures
* 791221322 - Prop Precision
* 787611845 - Prop Snapping
* 694512541 - Prop Line Tool [PLT] (vAlpha)
* 650436109 - Quay Anarchy
* 465318661 - Toggleable Whiteness
* 689937287 - Surface Painter
* 1562650024 - Rebalanced Industries
* 1274199764 - Network Tiling
* 1209581656 - Relight
* 812107110 - Less Steam
* 762520291 - Shadow Strength Adjuster
* 672248733 - Ultimate Eyecandy v1.5.2
* 593588108 - Prop & Tree Anarchy
* 564141599 - No Seagulls
* 530771650 - Prefab Hook (Mod Dependency)
* 406354745 - Speed Slider \[v2]
* 1658679290 - Forest Brush v1.2.5
* 1645781000 - Elektrix's Road Tools 2.0
* 898480258 - Camera Positions Utility
* 837734529 - Find It!
* 802066100 - Fine Road Anarchy
* 767233815 - Decal Prop Fix
* 651322972 - Fine Road Tool
* 523824395 - Clouds & Fog Toggler
* 502750307 - Extra Landscaping Tools
* 833779378 - Loading Screen Mod \[Test]
* **1597852915 - More Advanced Toolbar (bit buggy & laggy)**
    * Suggest: Resize It! mod by Keallu instead
* 845665815 - CSL Map View
* 450877484 - Mod Tools

Will update lotm about issue then close ticket.

**Comment by aubergine10** [comment]
Needs to switch to LABS version which has the parking fixes.

**Comment by aubergine10** [comment]
She was apparently using LABS when the issue occurred, but had switched to STABLE in hopes it would fix issue. Suggested to 'Clear Traffic' after switching back LABS as workshop users have stated that solves any remaining parking issues they had.

**Comment by aubergine10** [comment]
Reopening - the issue still persists with LABS 10.21.1

It's specifically the badi_dea assets, which , apparently use a custom AI (and thus likely not picked up by TM:PE parking AI):

> 100% sure i'm using labs, cleared traffic, still no dice  
> but since it doesn't effect any other parking i'm guessing more and more that it is just those parking lots.  
> badi_dea said "mine are using dummy AI, maybe a mod is altering the behavior of that AI?"  
> it worked before, but when i switched to labs for the first time it's been broken ever since  
> even if i move back to stable

**Comment by aubergine10** [comment]
> aubergine18Yesterday at 12:47
> Badi_Dea Which AI does your parking lot road parking assets use?
> Badi_DeaYesterday at 16:11
> I believe it was dummy AI - have you been talking to LOTM?

**Comment by aubergine10** [comment]
Tagging #280 , @479

**Comment by aubergine10** [comment]
Found an older issue relating to Parking Lot Roads - apparently the problem started after Campus update: #352

**Comment by aubergine10** [comment]
Another report, this time re: LABS:

> **t1a2l**:
> I have tmpe labs, i build a big parking near my zoo but no one use it...
> parking roads

Also, the problem is also present on v11 ALPHA too. Maybe not as bad, but cars certainly avoid the parking lot roads.

**Comment by aubergine10** [comment]
Roads United Core has been flagged as potential cause of this issue (unconfirmed).

![image](https://user-images.githubusercontent.com/1386719/72222658-3c6a8300-355f-11ea-8226-60e4c9e188e9.png)

**Comment by krzychu124** [comment]
@aubergine10 still valid issue?

**Comment by aubergine10** [comment]
I'm not noticing any issues in-game with this, although I never really encountered the problem even when users were reporting it.
