### ISSUE TITLE
Spawn and Unspawn patches

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#462]
Two patches not currently possible with Harmony:

* TLM/TLM/Patch/_Vehicle/SpawnPatch.cs 
* TLM/TLM/Patch/_Vehicle/UnspawnPatch.cs

**Comment by aubergine10** [comment]
Tagging #864 , PR #921

**Comment by kianzarrin** [comment]
Fixed by #921
