### ISSUE TITLE
Max vehicle count with very few vehicles on the map

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#469]
Easily fixed with "Clear Traffic" button, but posting link to save in case anyone has chance to investigate.

From [this Steam discussion](https://steamcommunity.com/app/255710/discussions/0/2944710017713477425/):

[Save game in workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1818400557)

Past instances of this issue: #267, #317 

Note: There are some known [vehicle assets that break spawning](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Broken-Vehicle-Assets#breaks-vehicle-spawning). I've asked user who shared save game above to check that list and will report back.

> I wonder if there's a way to detect this issue when a map is loaded and, if detected, automatically clear traffic?

**Comment by aubergine10** [comment]
User confirmed issue resolved after clearing traffic.

Would be great if we could somehow automate this (maybe with confirm dialog so users know what's going on).

**Comment by kvakvs** [comment]
In parking code there is a loophole which can (not confirmed but has the potential to) park the vehicles at `Vector3(0, 0, 0)`. There might be more of these.

**Comment by krzychu124** [comment]
According to linked Steam forum thread comments, issue has been resolved and not related to **TM:PE**. Closing
