### ISSUE TITLE
Check patches for rocket launches

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#496]
Issue detected while testing a save from #494 

```csharp
Simulation error: Object reference not set to an instance of an object
at (wrapper dynamic-method) VehicleManager.CreateVehicle_Patch2 (object,uint16&,ColossalFramework.Math.Randomizer&,VehicleInfo,UnityEngine.Vector3,TransferManager/TransferReason,bool,bool) <0x00ae3>
at RocketLaunchAI.SimulationStep (uint16,EventData&) <0x0083d>
at EventManager.SimulationStepImpl (int) <0x00149>
at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at EventManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.SimulationStep () <0x00693>
at SimulationManager.SimulationThread () <0x0018a>
  [Core]
```

VehicleManager.CreateVehicle_Patch2 

I don't recall seeing space rockets listed in the vehicle types - maybe that is the issue?

![image](https://user-images.githubusercontent.com/1386719/63277883-14237480-c29e-11e9-9a44-9e64c1442c0a.png)

**Comment by kvakvs** [comment]
OK i have launched ChirpX under the debugger and no Null Pointer exception occured.
How do I reproduce?

**Comment by aubergine10** [comment]
@kvakvs I was testing the save game that's in the .zip in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/494

**Comment by kvakvs** [comment]
Does not even load for me. Debugger shows the loading is getting stuck in the infinite loop in `DeleteBuildingImpl` on calling `CheckBulldozing` on a building whose `building.Info` is null. Might be missing assets?

**Comment by aubergine10** [comment]
I was also missing assets (listed in a comment in #494) but it did load - use Loading Screen Mod asset report and it will list what's missing. Although still odd that it would fail to load at all.

**Comment by aubergine10** [comment]
Try `SafeNets` mod - it will avoid some common problems due to loading saves with missing network assets. https://steamcommunity.com/sharedfiles/filedetails/?id=1620588636

**Comment by kvakvs** [comment]
Game loaded with SafeNets, auto-deleted all the missing roads so i've played "fix my city" restoring the roads and waiting for ChirpX to charge. It launched no problem, so my guess would be one of the user's assets causing this.

**Comment by aubergine10** [comment]
I'll see if I can spot any custom rocket assets in the log...

**Comment by aubergine10** [comment]
No custom rockets found. :/

**Comment by krzychu124** [comment]
Old issue, there was game update in the meantime, personally I haven't heard about similar issue since then. 
Closing, reopen if issue persist.
