### ISSUE TITLE
(Not TM:PE) 81 Tiles issue

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#501]
This issue seems to be getting more frequent of late. I suspect it is a mod conflict with some as-yet unknown mod and 81 Tiles.

```diff
// ...

- ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF6BE5A4207)
  0x00007FF6BE5A4207 (Cities) 
  0x0000000006C2FAEC (Mono JIT Code) (wrapper managed-to-native) 
  UnityEngine.Object:FindObjectsOfType (System.Type)
  0x0000000006C2FA0A (Mono JIT Code) UnityEngine.Object:FindObjectOfType (System.Type)
  0x000000022F0DE759 (Mono JIT Code) UnityEngine.Object:FindObjectOfType<object> ()
+ 0x0000000047A0A37F (Mono JIT Code) EightyOne.LoadingExtension/<>c:<OnLevelLoaded>b__1_2 ()
  0x000000022F09562A (Mono JIT Code) AsyncAction:Execute ()
  0x000000002297DD8B (Mono JIT Code) SimulationManager:SimulationStep ()
  0x0000000022938A3B (Mono JIT Code) SimulationManager:SimulationThread ()
  0x0000000006BF08CB (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
  0x00007FFBD3CC5CDF (mono) mono_set_defaults
  0x00007FFBD3C18499 (mono) mono_runtime_invoke
  0x00007FFBD3C438D7 (mono) mono_thread_interruption_request_flag
  0x00007FFBD3CF8955 (mono) unity_mono_reflection_method_get_method
  0x00007FFC00F54034 (KERNEL32) BaseThreadInitThunk
  0x00007FFC039F3691 (ntdll) RtlUserThreadStart
```

Disabling 81 Tiles mod removes the error. I personally get the error only when starting new maps, it doesn't occur when loading existing saves. However everyone else I've seen this error encountered it when loading existing saves.

I'm going to use this issue ticket to collate lists of mods to see if there's some common mods from crashes on different computers.

**Comment by aubergine10** [comment]
User `mrinaldy` on reddit discord

[output_log (23).txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3538246/output_log.23.txt)

Mods:

* 650436109 - Quay Anarchy
* ~~639486063 - Automatic Bulldoze V2~~
* ~~666425898 - No Radioactive Desert And More!~~
* 530871278 - Daylight Classic
* ~~814698320 - Time Warp 2~~
* 593588108 - Prop Anarchy
* ~~505480567 - More Beautification~~
* 502750307 - Natural Resources Brush
* 689937287 - SurfacePainter
* ~~406102887 - Super Demand~~
* 465127441 - Airport Roads
* 625608461 - Adaptive Prop Visibility Distance
* 837734529 - Find It
* 802066100 - Fine Road Anarchy
* 651322972 - Fine Road Tool
* ~~564141599 - No Seagulls~~
* 426163185 - Realistic Population and Consumption Mod
* 586012417 - Ploppable RICO
* 515489008 - Elevated Train Station Track
* 1562650024 - Rebalanced Industries
    * loads 0Harmony v1.2.0.2
* ~~412146081 - Post Process FX~~
* ~~1410003347 - Additive Shader~~
* ~~1209581656 - Relight~~
* ~~762520291 - Shadow Strength Adjuster~~
* 1548831935 - Advanced Vehicle Options (Industries)
* 552309905 - No Abandonment
* 924884948 - Plop The Growables
    * loads 0Harmony v1.2.0.1
* ~~928128676 - Improved Public Transport 2~~
* ~~650805785 - First Person Camera (Updated)~~
* 1619685021 - Move It
* 1394468624 - Advanced Stop Selection
* 667342976 Loading Screen Mod

~~Strikethrough~~ means not common with other crashes.

**Comment by kvakvs** [comment]
On a contrary note, i have 81 tiles activated and do not remember this happening to me.

**Comment by aubergine10** [comment]
My mods:

* ~~(local) - TM:PE DEBUG 11.0-alpha6~~
* 1562650024 - Rebalanced Industries
* ~~1658679290 - Forest Brush~~
* ~~591137516 - Redcomet's Municipal Sound Pack~~
* ~~618536610 - AST: KRA Sound Pack~~
* ~~498386331 - CrossTheLine~~
* ~~533958715 - Real London Sound Pack~~
* 625608461 - Adaptive Prop Visibility Distance
* ~~793176674 - Sharp Textures~~
* ~~818641631 - Ambient Sounds Tuner~~
* ~~833784103 - British Rail Class 43 Effect Definitions Pack~~
* ~~815103125 - Extra Vehicle Effects~~
* ~~898480258 - Camera Positions Utility~~
* ~~870291141 - Random Train Trailers 2.1.0~~
* ~~954067599 - PropRotating Params~~
* ~~940299505 - AnimUV Params~~
* ~~569879360 - WG Realistic Solar v1.3~~
* ~~1192250578 - Emergency Lights Manager~~
* ~~1349895184 - Tree LOD Fix~~
* ~~1388613752 - Tree Movement Control~~
* ~~1412844620 - Realistic Walking Speed~~
* ~~1546357276 - Industries Vehicle Converter~~
* 1548831935 - Advanced Vehicle Options 1.8.5
* ~~1552053911 - Trailer Variation Loader~~
* 689937287 - Surface Painter
* ~~502750307 - Extra Landscaping Tools~~
* ~~1568910950 - ZONE Radio~~
* ~~1348627392 - Tides~~
* ~~949504539 - Single Train Track AI~~
* ~~883332136 - Any Road Outside Connections~~
* ~~793346248 - Decal Hover Area~~
* ~~791221322 - Prop Precision 1.0.1~~
* ~~787611845 - Prop Snapping~~
* ~~780720853 - Vehicle Effects 1.8.1a~~
* ~~654707599  - WG Citizen Lifecycle Rebalance v2.6~~
* 651322972 - Fine Road Tool 1.3.7
* ~~593588108 - Prop & Tree Anarchy~~
* 586012417 - Ploppable RICO
* ~~538019888 - Spawn/Unspawn Positions Swapper~~
* 530871278 - Daylight Classic
* 515489008 - Extra Train Station Tracks
* ~~497033453 - Unlimited Outside Connections~~
* 426163185 - Realistic Population & Consumption Mod
* ~~1433003062 - Rotors FlipXZ~~
* ~~1393820309 - Ticket Price Customizer~~
* ~~1393452031 - Parkify r1.0.3~~
* ~~1372431101 - Painter~~
* ~~1274199764 - Network Tiling~~
* ~~928103306 - Ship Converter~~
* ~~922939393 - Transparency LOD Fix + Cloud Assets Enabler~~
* ~~903347963 - Transparent Selectors~~
* ~~899063611 - UK Sound Pack~~
* 837734529 - Find It! 1.5.4
* ~~820157360 - Spawn Points Fix~~
* 802066100 - Fine Road Anarchy 1.3.5
* ~~767233815 - Decal Prop Fix~~
* 650436109 - Quay Anarchy
* ~~608517757 - Sub-Buildings Tabs~~
* ~~530771650 - Prefab Hook~~
* ~~512314255 - More Network Stuff~~
* ~~510677558 - The Metropolitan Sound Pack~~
* 465127441 - Airport Roads 1.3.7
* ~~881291183 - Ploppable Asphalt~~
* ~~1386697922 - Garbage Bin Controller~~
* ~~476141470 - Craft_Inc's Synthwave & 80s-Retro-Music pack~~
* ~~1289991722 - Music pack: Vault Archives Music Pack~~
* ~~422934383 - CSL Music Mod~~
* ~~611254368 - Environment Changer~~
* ~~629850626 - Workshop RICO Settings~~
* ~~1567569285 - Achieve It!~~
* ~~1661072176 - Empty It!~~
* ~~1721492498 - Cargo Hold Fix~~
* ~~707497031 - Tram Station Track~~
* ~~812107110 - Less Steam~~
* ~~1591584836 - HDRI 2K Cubempap Pack~~
* ~~1585691173 - HDRI Haven Cubemap Pack~~
* ~~1183931915 - Cubemap Replacer~~
* ~~1680642819 - Ultimate Level Of Detail~~
* ~~1556715327 - Show It!~~
* 552309905 - No Abandonment
* ~~1577882296 - Resize It!~~
* ~~1591417160 - Hide It!~~
* ~~1643902284 - Watch It!~~
* ~~1435741602 - Snooper~~
* ~~924884948 - Plop The Growables~~
* ~~1420955187 - Real Time~~
* 1619685021 - Move It 2.5.0
* 1394468624 - Advanced Stop Selection
* ~~1656549865 - Rebuild It!~~
* ~~795514116 - Train Converter~~
* ~~1794015399 - Render It!~~
* ~~724382534 - One-Way Train Tracks~~
* ~~812125426 - Network Extensions 2~~
* ~~775021554 - Theme Mixer~~
* ~~659877005 - First-person Auto-walking 1.3.1~~
* ~~1541897355 - Total Autobudget~~
* ~~1620588636 - Safenets~~
* ~~1530376523 - Railway Replacer~~
* 667342976 - Loading Screen Mod
* ~~1764637396 - Toggle It!~~
* ~~1768810491 - Measure It!~~
* ~~1801953480 - Natural Disasters Overhaul~~
* ~~1776052533 - Stops and Stations~~

**Comment by aubergine10** [comment]
> On a contrary note, i have 81 tiles activated and do not remember this happening to me.

Yup, it doesn't happen for everyone which is why I suspect it to be a conflict with another mod (guessing).

Could you post a list of your active mods (if running TM:PE alpha release 6 or above there will be a full list in `TMPE.log`)?

**Comment by kvakvs** [comment]
```
  * (local)      TM:PE DEBUG 11.0-alpha4
  * 445589127    Precision Engineering
  * 651322972    Fine Road Tool 1.3.7
  * 802066100    Fine Road Anarchy 1.3.5
  * 812125426    Network Extensions 2
    555375742    KeepMoneyMod
    633547552    Roads United Core 2.0
  * 530771650    Prefab Hook
  * 639486063    Automatic Bulldoze v2
  * 502750307    Extra Landscaping Tools
  * 1556715327   Show It!
  * 576327847    81 Tiles (Fixed for C:S 1.2+)
    1420955187   Real Time
  * 1619685021   Move It 2.5.0
    1804882663   Monitor It!
    497033453    UnlimitedOutsideConnections
  * 1620588636   Safenets
  * 1625704117   Roundabout Builder
  * 667342976    Loading Screen Mod
  * 458519223    Unlock All + Wonders & Landmarks
```

**Comment by aubergine10** [comment]
So it looks like these mods can be ruled out:

```
  * 651322972    Fine Road Tool 1.3.7
  * 802066100    Fine Road Anarchy 1.3.5
  * 1619685021   Move It 2.5.0
  * 667342976    Loading Screen Mod
```

That leaves these as possible contenders:

* 650436109 - Quay Anarchy
* 530871278 - Daylight Classic
* 593588108 - Prop Anarchy
* 502750307 - Natural Resources Brush
* 689937287 - SurfacePainter
* 465127441 - Airport Roads
* 625608461 - Adaptive Prop Visibility Distance
* 837734529 - Find It
* 426163185 - Realistic Population and Consumption Mod
* 586012417 - Ploppable RICO
* 515489008 - Extra Train Station Tracks
* 1562650024 - Rebalanced Industries
* 1548831935 - Advanced Vehicle Options (Industries)
* 552309905 - No Abandonment
* 924884948 - Plop The Growables
* 1394468624 - Advanced Stop Selection

**Comment by Tom-Evers** [comment]
For me, it's an incompatibility with TM:PE 10.20

Enable either, and everything is fine. Enable both 81T and TM:PE and it doesn't load.

**Comment by clind922** [comment]
Hi.

I suddenly started getting almost verbatim the same error and a crash, when either 81 tiles or TMPE (Stable or Labs makes no difference) is loaded.

Ruled out a few of the recent additions:

My mods:
- 407871375 - ChirpFilter
- 405999555 - AutoSave
- 406781251 - SnapHotkey
- 1556715327 - Show It!
- 593588108 - Prop & Tree Anarchy
- 563229150 - Advanced Toolbar
- 1938493221 - Mini FPS Booster 1.0
- 498386331 - CrossTheLine
- 446764406 - No Border Limit Camera
- 667342976 - Loading Screen Mod
- **576327847 - 81 Tiles (Fixed for C:S 1.2+)**
- 1627986403 - Bulldoze It!
- 1844442251 - Klyte's Fine Road Tool 2.0.4
- 672248733 - Ultimate Eyecandy 1.5.2
- 465318661 - ToggleableWhiteness
- 1844440354 - Klyte's Fine Road Anarchy 2.0.2
- 531738447 - CSL Show More Limits
- 410151616 - City Vitals Watch
- 1658679290 - Forest Brush
- 1890830956 - Undo It!
- 666425898 - No Radioactive Desert And More!
- 762520291 - ShadowStrengthAdjuster
- 412149127 - Font Selector
- 793176674 - Sharp Textures
- 643364914 - Softer Shadows
- 812713438 - Dynamic Resolution
- 812125426 - Network Extensions 2
- 1393452031 - Parkify r1.0.3
- 515489008 - Extra Train Station Tracks
- 1567569285 - Achieve It!
- 1643902284 - Watch It!
- 689937287 - Surface Painter
- 1415090282 - AutoLineColor Redux
- 1661072176 - Empty It!
- 650805785 - First Person Camera
- 814498849 - Improved Content Manager
- 694512541 - Prop Line Tool
- 530771650 - Prefab Hook
- 512314255 - More Network Stuff
- 502750307 - Extra Landscaping Tools
- 837734529 - Find It! 1.5.4
- 1934023593 - RM Crossings 3.0 
- 1393797695 - Touch This! Tool 4
- 1548831935 - Advanced Vehicle Options 1.9.4
- 2034713132 - Auto Repair
- 1440928803 - Parallel Road Tool 2.0.3
- 1625704117 - Roundabout Builder
- 1274199764 - Network Tiling
- 2030755273 - Automatic Pedestrian Bridge2.0
- 2040656402 - Harmony 2.0.1
- 1562650024 - Rebalanced Industries
- 1619685021 - Move It 2.8.1
- 1677913611 - Smart Intersection Builder
- 427258853 - Pedestrian Crossings
- 2027161563 - Lifecycle Rebalance Revisited 1.4.3
- ~~973512634 - Sort Mod Settings~~
- ~~1394468624 - Advanced Stop Selection~~
- ~~1665106193 - Skip Intro~~
- ~~530871278 - Daylight Classic~~
- ~~1349895184 - Tree LOD Fix~~
- ~~2037888659 - Instant Return To Desktop~~
- ~~2019097300 - RM Unconnected Tracks ~~
- ~~650436109 - Quay Anarchy~~
- 406828238 - Additional Key Bindings
- 1577882296 - Resize It!
- 2172488844 - Picker 1.5
- 2140418403 - Intersection Marking Tool 1.3
- 1680840913 - More Effective Transfer Manager
- 2083188521 - Precision Engineering 2.0
- 1806963141 - TM:PE 11.5.0 LABS

> ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF607EAA471)
0x00007FF607EAA471 (Cities) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF607EB48F1)
0x00007FF607EB48F1 (Cities) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF607EAB33A)
0x00007FF607EAB33A (Cities) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF607EAFAE8)
0x00007FF607EAFAE8 (Cities) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF608084207)
0x00007FF608084207 (Cities) 
0x00000000067224DC (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Object:FindObjectsOfType (System.Type)
0x00000000067223FA (Mono JIT Code) UnityEngine.Object:FindObjectOfType (System.Type)
0x00000000CD9DB699 (Mono JIT Code) UnityEngine.Object:FindObjectOfType<object> ()
0x00000002C17BA2D3 (Mono JIT Code) EightyOne.LoadingExtension/<>c:<OnLevelLoaded>b__1_2 ()
0x00000002785F9A1A (Mono JIT Code) AsyncAction:Execute ()
0x0000000023090B9B (Mono JIT Code) SimulationManager:SimulationStep ()
0x0000000022E54BEB (Mono JIT Code) SimulationManager:SimulationThread ()
0x00000000066E050B (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFE06615CDF (mono) mono_set_defaults
0x00007FFE06568499 (mono) mono_runtime_invoke
0x00007FFE065938D7 (mono) mono_thread_interruption_request_flag
0x00007FFE06648955 (mono) unity_mono_reflection_method_get_method
0x00007FFE67157BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFE674CCE51 (ntdll) RtlUserThreadStart

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/5207986/output_log.txt)

**Comment by krzychu124** [comment]
Problem is here:
```cs
0x00000000CD9DB699 (Mono JIT Code) UnityEngine.Object:FindObjectOfType ()
0x00000002C17BA2D3 (Mono JIT Code) EightyOne.LoadingExtension/<>c:b__1_2 ()
0x00000002785F9A1A (Mono JIT Code) AsyncAction:Execute ()
0x0000000023090B9B (Mono JIT Code) SimulationManager:SimulationStep ()
0x0000000022E54BEB (Mono JIT Code) SimulationManager:SimulationThread ()
```
` UnityEngine.Object:FindObjectOfType ()` should not be ever called from `SimulationManager:SimulationThread()` because weird issues may happen.

**Comment by krzychu124** [comment]
_Out of scope_
