### ISSUE TITLE
Low land value

### ISSUE THREAD

**Issue by t1a2l** [CitiesSkylinesMods/TMPE#512]
### Describe the problem
While at night time and using real time and the LABS version i get low land value.
Everything is ok when using the STABLE version

### Steps to reproduce

1. Open your save with TM:PE LABS and ReaalTime
2.  Wait for night time
3.  See all the map full of low land value icons

### Log files and Savegame
https://drive.google.com/file/d/1W-PaPaH5aimgUP0rn5OLJOtFgLW_BdSL/view?usp=sharing

### Screenshots?
https://imgur.com/a/8RxHGQn

**Comment by aubergine10** [comment]
Are the two screen shots both using LABS?

Could you take some screenshots using STABLE version for comparison?

**Comment by t1a2l** [comment]
Yes they are both using LABS

**Comment by t1a2l** [comment]
Ok you can close the issue i see it happening also on stable.. at only happens on this save although i updated two mods latly the fine road tool and road anarchy to the second version..

**Comment by aubergine10** [comment]
Ah, try reverting those to mods to original versions.

The Klyte mods tend to be... unreliable.

**Comment by t1a2l** [comment]
Just Reverted to the original.. maybe the issue already breaked the save? the problem wont go away

**Comment by aubergine10** [comment]
I think first thing to determine is how land value is actually calculated. I'll see if I can find out then we can start assessing what might be affecting the inputs to that calculation.

**Comment by krzychu124** [comment]
_Out of scope_ - **TM:PE** code does not affect land value in any way
