### ISSUE TITLE
TM:PE Service/Industry Vehicles Don't spawn

### ISSUE THREAD

**Issue by SomeBadVoodoo** [CitiesSkylinesMods/TMPE#514]
While using TM:PE Stable, often times after I load the game service vehicles or industry vehicles do not spawn. If TM:PE is disabled, the problem doesnt exist. 

Sometimes, if there are already vehicles spawned, no more vehicles will spawn but the existing vehicles will continue normally until they return to their home building. Then they will no longer spawn. 

Mostly, however, buildings simply do not spawn vehicles. When clicking on the building it will show 0/7 vehicles spawn. It will try to spawn one (and if its an industry vehicle, the amount of cargo in the building will go down) but the vehicle will not come out of the building and the cargo is returned to the building. 

This has been an issue in the past and it seemed to go away on its on but recently, its become an issue again. It doesnt seem to matter if its a new city or an existing city, sooner or later, the issue will arise and there doesnt seem to be an rhyme or reason. 

### Steps to reproduce

As far as I'm aware, with this particular city, simply loading the game will activate the problem. 

### Log files

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3562095/output_log.txt)

TM:PE Log

[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3562097/TMPE.log)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=1849938183

### Screenshots?

![255710_screenshots_20190831012353_1](https://user-images.githubusercontent.com/54733664/64059639-7f1e5680-cb8e-11e9-96bd-8c1b472e5b92.jpg)
![255710_screenshots_20190831012353_2](https://user-images.githubusercontent.com/54733664/64059640-7f1e5680-cb8e-11e9-99af-aeacaca21a2e.jpg)

### Notes or questions?

 I would appreciate any help as I love the TM:PE mod and at this point, I find the game simply unplayable without it. 

Thanks

**Comment by aubergine10** [comment]
Hi,

Thanks for the detailed error report.

Can you take a screenshot of the limits report from Watch It mod (the 🚫 button at bottom of the watch it sidebar) and post in a comment here.

**Comment by SomeBadVoodoo** [comment]
![255710_screenshots_20190831170919_1](https://user-images.githubusercontent.com/54733664/64069165-390ad680-cc12-11e9-8e64-83e106763d2d.jpg)

**Comment by krzychu124** [comment]
We haven't got any other report in the past year about similar issue. Closing.
