### ISSUE TITLE
"not enough buyers" - trucks not spawning - problem wiht pathfinding?

### ISSUE THREAD

**Issue by kmeldner** [CitiesSkylinesMods/TMPE#522]
### Describe the problem
I have a industry area and in general all traffic is fine through the city.
But for some unknown reason most of the fields report "not enough buyers" problem.
There is no obvious reason why this should happen as there is plenty available storage just  down the road. Also fields that connect to the same road do not have similar problems.

### Steps to reproduce

1. 
2. 
3. 

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=1859516308

**Comment by aubergine10** [comment]
Do you have "Old Town" policy active? If so, try disabling it and see if that helps?

**Comment by krzychu124** [comment]
No other reports about this problem. More info about the game [supply chain](https://skylines.paradoxwikis.com/Supply_chain)
Closing. Reopen or create issue if problem persist.
