### ISSUE TITLE
Top-level "Roads" feature?

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#557]
In #542, @kianzarrin is augmenting the vanilla "Adjust Roads" UI to facilitate bulk application of TM:PE customisations along a named road.

As this will likely be a widely used feature, would it be worth adding a new "Roads" button to the TM:PE menu (see #523 for updated menu style) to make the "Adjust Roads" info view more prominent and easier to access?

It could become the de-facto "point and click" way to bulk apply TM:PE customisations to routes.

For example, users could apply things such as:

* Junction setup - priority signs, junction restrictions, separate turning lanes, etc
* Roundabout rules (if road is a closed loop)
* Speed limits (a visual alternative to Shift key modifier in speed limit tool)

User would select (and optionally modify) the road, then click buttons to bulk apply common setups. Tweaks to the common setups could be set in mod options (see https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/539#issuecomment-551866591 as an example).

Alternatively we could create our own UI panel to have complete control over the "look and feel". This could allow editing roads (that green dragable line thing) like vanilla, but in normal map mode perhaps? TM:PE overlays could be visible so user can see what's happening.

In addition, we could display info about the road such as:

* Maintenance level
* Traffic density/congestion/flow
* Length of road (units depending on kmh vs. mph setting in mod options)
* Anything else that's useful to know about "a named series of segments" (a road)

**Comment by kianzarrin** [comment]
This is so cool. As for
>Anything else that's useful to know about "a named series of segments" (a road)

I am not so sure about the logic that the game uses to have a named road. I think its better if we allow the user to select the road using the vanilla road adjust tool #542 which funny enough does not change what is "a named series of segments".

**Comment by aubergine10** [comment]
From what you mentioned in other issue, it sounds like the game concept of "named road" is literally just "road = find adjacent segments with the same name as the selected segment". 

If so, it's such a shame that CO implemented it that way. For example, if they'd added "road" objects that list segments of the road, and it had the priority flag, that could then be used to make services (road maint, snow plough, water pumping, disaster response) prioritise those roads and adjacent buildings to keep them in full working order.

Regardless, there must be some way - even if determined on an as-needed basis - to get list of segments for "a named road", so hopefully we could still do some of that other stuff?

**Comment by aubergine10** [comment]
The ability to just click a road while toolbar is open (but no tool selected) replaces the need for a top-level Roads button (the road is the button hehe).

**Comment by kianzarrin** [comment]
I still think the fact the priority tool setups up almost all other rules is a bit weird (new features = speed limits of roundabout, ban parking on roundabouts). I kind of shoved this functionally over there because I did not know where to put it. 

Road selection Panel is heavy and slow interface and I much prefer to have a one click setup option as we have in priority tool but maybe a new tool for that leaving the road selection panel to do the more advanced stuff.
