### ISSUE TITLE
Crazy route due to not crossing road

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#558]
I have a farm, shown in image below, which has some cow pastures and a grain barn.

![image](https://user-images.githubusercontent.com/1386719/69376973-3cf34580-0ca3-11ea-8840-6bc108e0493e.png)

The barn is bottom right building, and it needs to deliver grain to the pastures. Should be a really short trip, right?

However, it's facing the entrance road to the farm, and I'm using left hand traffic = lane next to barn travels towards a long rural highway, not the pastures.

Instead of crossing that lane on to the other lane (that leads to pastures), the pathfinder is sending trucks on a massive detour to find a turning point:

![image](https://user-images.githubusercontent.com/1386719/69376918-1f25e080-0ca3-11ea-9904-a83f02995ff0.png)

So they drive all the way to a nearby radio mast, that's half way up a hill, and then all the way back again.

![image](https://user-images.githubusercontent.com/1386719/69377286-dd496a00-0ca3-11ea-817f-669cfd22ac0f.png)

I suspect the small 2-lane roads being used have incorrectly set m_canCrossLanes, but even then I feel that on small roads (UI category), with only 2 lanes the pathfinder should probably just assume vehicle can cross the road. (Not always the case, however, as there are some 2 lane roads with medians in workshop).

Related issues: #505, #506 

If there's some way we could slightly increase lane crossing ability it would greatly reduce the prevalence of such crazy routes.

**Comment by kianzarrin** [comment]
When I face this problem I use this mod to create pedestrian crossings:
https://steamcommunity.com/sharedfiles/filedetails/?id=427258853
Then I allow U turns on the pedestrian crossings.
Alternatively you can allow U Turn at some/every junction.
That said its much better if the cars would cross the road by difficult without the need for us to spell it out for them!

**Comment by aubergine10** [comment]
Yup, there are plenty of ways I could manually fix the issue, such as just turning the building to face the road that the main farm building is on, but like you say it would be good if the pathfinder was more intelligent.

I'll check with the author of those road assets to see if they have the 'can cross lanes' flag enabled. If not, that might be the cause of the issue, although considering how often this issue occurs I suspect it's more likely a pathfinder issue, for example: If spawn road has `m_canCrossLanes == true`, and target is within X range (some value depicting close proximity) then determine which lane direction is closest to direction of target and path from that first, and if that fails path from other lane.

**Comment by aubergine10** [comment]
Closing this as it's now tracked in #1223
