### ISSUE TITLE
Speed limits window too constrained on QHD resolution

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#573]
On this resolution:

![image](https://user-images.githubusercontent.com/1386719/69711681-6116b280-10f9-11ea-9cea-6172b19cf879.png)

The speed limits panel is too constrained and can't be dragged further towards the bottom-right than shown:

![image](https://user-images.githubusercontent.com/1386719/69711588-3af11280-10f9-11ea-948a-9a6d71d50ea3.png)

**Comment by kianzarrin** [comment]
Ant it is too big on low resolution.

**Comment by aubergine10** [comment]
In relation to too big, see issues: #299 and #406.

I think if we could sort its size on small monitors, and it's drag constraints on big monitors, we could close the three issues.

@kianzarrin Is this something you could have a go at fixing?

_Note: Other stuff mentioned in #406, such as choosing what speeds to show or using a vanilla style build bar, was just some random ponderance that's now largely obsolete. Since using the new set of speeds, I've actually found myself taking advantage of all of them (I initially thought I'd only use multiples of 10 on mph mode, but was wrong)._

**Comment by aubergine10** [comment]
@MacSergey has similar problems - reported in duplicate issue #935
