### ISSUE TITLE
More advance roundabout quick-setup.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#578]
In issue #539 I implemented the first phase of roundabout quick-setup This issue is the next phase to handle stations like this:
![Cities_HdgHjyccJG](https://user-images.githubusercontent.com/26344691/69844571-892b2080-1275-11ea-88a1-52c7b1e4e8ed.jpg)
![Cities_PtXixifMAF](https://user-images.githubusercontent.com/26344691/69844572-892b2080-1275-11ea-911e-fa8cf517d170.jpg)
![rabout image0](https://user-images.githubusercontent.com/26344691/68214745-ad813d80-ffe6-11e9-909d-6394d3941497.png)

Tasks:
- [x] option to setup enter blocked junction for roads joining the roundabout.
- [ ] ~~More clever path detection: Instead of following a preferred direction (forward) follow all possible paths in all directions. if the path is not a roundabout then discard it. among the paths that are roundabout I choose the one that has the list amount of left/right turns within the roundabout. if the number of turns are equal then choose the shortest paths~~ With the introduction of road selection panel, this is no longer important.
- [x] short term undo #860
- [x] ban parking on roundabout
- [x] Speed Limit #793

related : #541 #542

**Comment by kianzarrin** [comment]
I want to add option to setup entering blocked junctions for roads joining the roundabout. but our options are already a mess (#853) (sorry that's on me!) and I am worried I might make them worse.

So here is what I think:
- in a highway roundabout we want to allow cars to enter blocked junctions
- in an urban roundabout we want cars to yield.


This is what the game does by default. so in theory I don't need to add an option for this. But in practice, when Biffa is fixing cities he has to turn off `enter blocked junctions` manually because 
- sometimes highway roads join urban roundabouts. 
- sometimes user has modified `enter blocked junction` manually before hand.

So I think I need to add option like this:
```
O modify enter blocked junctions for in-coming cars
   O allow(on)/ ban(off)
```

**Comment by aubergine10** [comment]
There's also case where users build their urban roundabouts out of highway roads so they can watch cars driving round them at warp speed.

I suspect road size in terms of lane counts will be a factor, but haven't thought that through yet.

**Comment by kianzarrin** [comment]
Default settings for entering blocked junctions:

- joining highway : yes
- joining and leaving highway at the same node: No
- urban: No
![Screenshot (859)](https://user-images.githubusercontent.com/26344691/79684422-eed67400-8239-11ea-896b-1c0d23fd0b63.png)
![Screenshot (864)](https://user-images.githubusercontent.com/26344691/79684424-f007a100-8239-11ea-8d5e-1eecb0c2e422.png)
![Screenshot (860)](https://user-images.githubusercontent.com/26344691/79684427-f1d16480-8239-11ea-88f3-b817ea502636.png)

**Comment by aubergine10** [comment]
My focus was drawn to the pedestrian crossing icons - on highway roads... Is that a bug?

**Comment by kianzarrin** [comment]
> I suspect road size in terms of lane counts will be a factor, but haven't thought that through yet.

entering blocked junction is good if you are joining the outer lane but not good when you are joining the inner lane (because you can block cars trying to exit the roundabout. so for one lane roundabout is good but for 2+ lane roundabout is bad. 

hmmm ... maybe we can have an option in policies to enter blocked junction only for the first lane when pedestrian crossing does not exists.

**Comment by aubergine10** [comment]
Regardading lane-wise enter-blocked junction, see also: #565

Actually, for enter blocked junction in general, I keep thinking it maybe needs a complete rethink: #424

**Comment by kianzarrin** [comment]
> My focus was drawn to the pedestrian crossing icons - on highway roads... Is that a bug?

I did brought this up int he pull request https://github.com/CitiesSkylinesMods/TMPE/pull/845#issuecomment-615114683.

Fixing it would be as easy as setting `IsPedestrianCrossingAllowedConfigurable()` to false
```
if the road does has 2+ pedestrian lanes:
    IsPedestrianCrossingAllowedConfigurable = true
    GetDefaultPedestrianCrossingAllowed = true
else if the road to the right has pedestrian lanes AND the road to the left has pedestrian lanes
    // maybe this logic should be more sophisticated to check that the pedestrian lanes is on innder/outter side of the road
    IsPedestrianCrossingAllowedConfigurable = true
    GetDefaultPedestrianCrossingAllowed = true
else
    IsPedestrianCrossingAllowedConfigurable =  false
    GetDefaultPedestrianCrossingAllowed =  false
```

The GUI automatically does not show pedestrian crossing overlays if they are disabled. Actually in my mod I have patched TMPE to hide pedestrian crossing overlays when appropriate.

**Comment by aubergine10** [comment]
I split the ped crossing stuff to new ticket ^^

**Comment by kianzarrin** [comment]
The ticket started with focus on better roundabout detection but now I have abandoned that because road selection panel does the deed.

better roundabout detection should move to another ticket:
- detection and setup of roads that split when joining roundabout.
   - the code for split road setup already exists.
   - my Pedestrian bridge builder already is capable of detecting split roads.
- detection of magic roundabout
   - at every intersection try to see if we can find a mini roundabout. then try to continue on the main roundabout without going through the mini roundabouts.
- graph
  - prefer straight roundabouts.
  - prefer short roundabouts
  - prefer roundabouts without sharp turns

**Comment by aubergine10** [comment]
Ok, create new ticket.

Should this #578 be closed (treat it as completed by the road selection panel)?

**Comment by kianzarrin** [comment]
Its working! 
[TrafficManager.zip](https://github.com/CitiesSkylinesMods/TMPE/files/4521721/TrafficManager.zip)
