### ISSUE TITLE
Proposal for new default menu position

### ISSUE THREAD

**Issue by FireController1847** [CitiesSkylinesMods/TMPE#58]
When it is right here, it feels more natural to me, and looks a lot better too. We might need to work with the first person camera mod creators to see if they're willing to move their icon down a little by default, but maybe we could start a new trend of making a sidebar of buttons on the right? We'd also have to move the developer panel position, and I propose that goes on the left (as every other dev panel shows on the left as well)

![image](https://user-images.githubusercontent.com/16494272/52538259-cb5a9400-2d2d-11e9-86c3-b830a0d71396.png)

**Comment by krzychu124** [comment]
We are thinking about moving all functions from menu to 'build panel' and maybe add keyboard shortcuts to open some tools if I manage how to do it

BTW you can move it there, its position should be saved in configuration

**Comment by FireController1847** [comment]
That idea of a build panel sounds really cool. I still feel like, for now though, wouldn't this be a better position? I know I can move it there and that's always the first thing I do when I install it, but it just feels odd to me when it's in the position that is is for default.

**Comment by krzychu124** [comment]
I think you can play with it in code if you find some time :wink: 
Search for method which is responsible for resetting position of that menu button and saving it to global config. 
I think it's not so hard if we are ignoring possibility of reserved space by other mod icon button.

**Comment by FireController1847** [comment]
If you don't like the idea, let me know. It's only a suggestion, after all, and no hard feelings will come out of it :)

**Comment by aubergine10** [comment]
We've had issues with main menu and button going off the screen so it really needs to stay top-left for defaults.

**Comment by FireController1847** [comment]
Alright, that's fine
