### ISSUE TITLE
[EPIC] UI: Junctions Tool

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#6]
Currently TM:PE has some duplication of UI when it comes to setting priority / give-way for segments at a junction. I always found this confusing, as it's not clear what takes preference; the vanilla 'stop' sign (via info views > traffic routes > junctions tab) or the TM:PE custom UI that has stop/give-way/priority? The current implementation feels cumbersome and not tightly integrated with existing vanilla features.

Would it be possible to integrate with the vanilla UI (info views > traffic routes > junctions tab) so that when there are no traffic lights, the toggleable 'Stop' icon can be set to on of the [three states](https://tmpe.viathinksoft.com/wiki/index.php?title=Priority_signs):

* Stop (red hexagon as per vanilla)
* Give-way/Yield (red upside down triangle)
* Priority (yellow diamond)

Essentially, merge the currently-separate TM:PE UI in to the vanilla UI. The button on the TM:PE menu would then just redirect to: Info views > traffic routes > junctions tab

**Comment by aubergine10** [comment]
It seems TM:PE also has optional feature to allow traffic lights to factor in give-way / priority signs at the junction. In that case, the traffic light icon in center of junction (info views > traffic routes > junctions tab) could have three modes:

1. Signs only
2. Traffic lights only
3. Signs + Lights

Clicking the traffic light icon in center of junction cycles between the three modes, thus allowing config on a junction by junction basis (might cause issues with data size in savegame file; there's a limit to how much each mod can store IIRC).

Alternatively, use the existing option in mod settings, in which case:

* If disabled, user can choose mode 1 or 2
* If enabled, user can choose mode 1 or 3

**Comment by brunoais** [comment]
tbh, I don't really like the native UI for traffic lights.
IIRC, traffic lights and stop signs control are only available if one buys the "mass transit" DLC. Otherwise, the menu `info views > traffic routes > junctions tab` does not exist.
However, I would like if the stop signs of TMPE could integrate with cities skylines own stop signs for people who own the mass transit DLC.

**Comment by aubergine10** [comment]
Yes, this is planned.

**Comment by kianzarrin** [comment]
this is related to #542

**Comment by aubergine10** [comment]
Closing this as we are retaining the TMPE UI.

The stuff about linking TMPE stop sign with vanilla stop sign (ie. adding TMPE stop sign also adds vanilla sign) is handed in separate issue.
