### ISSUE TITLE
Lane connector tool connects lanes even if there is only one lane.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#617]
see https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/586#issuecomment-575894178
In the picture bellow lane connector's `stay in lane` tool connects lanes even if there is only one lane . this is redundant.
![Screenshot (312)](https://user-images.githubusercontent.com/26344691/72672521-09932400-3a64-11ea-83c4-d206dfdf7e9c.png)

if there is only one lane, lane connector tool should ignore situations where there is only one lane in that directions.

**Comment by aubergine10** [comment]
Was this fixed in #586 or are futher changes required?

**Comment by kianzarrin** [comment]
@aubergine10 further changes required. Should be easy. But its low priority.
