### ISSUE TITLE
Monorail node circles are projected on the road under

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#654]
As you can see in the screenshot Monorail node circles are projected on the road under presumably covering up the road nodes.
 ![Cities_blwJHaWHhb](https://user-images.githubusercontent.com/26344691/73859592-f396a900-4842-11ea-9e76-56601792a8ff.jpg)

#635 makes it easier to select the lane as you can see below. but its better to not to render the monorail node circles on the ground at all.
![Cities_QGnevZlhTj](https://user-images.githubusercontent.com/26344691/73859600-f5606c80-4842-11ea-80ef-d8b7d49b485c.jpg)

![Cities_LEEG8ii1r8](https://user-images.githubusercontent.com/26344691/73859606-f5f90300-4842-11ea-9b5d-9a8d811094fa.jpg)

**Comment by aubergine10** [comment]
Variants of this issue affects almost every tool that can interact with lanes:

* Lane arrows
* Lane connectors
* Timed traffic lights
* Speed limits
* Vehicle restrictions

Essentially, those tools (with some exception of timed traffic lights) don't really differntiate between road vs. track. This is particularly a problem with roads that contain one or more tracks (and there are some freaking crazy roads in the workshop as you've probably seen), but more commonly it's issue with tram and monorail roads.

One idea we had a while ago was to use different shapes for tracks: #354 - that would suffice for several tools, but not speed limits and vehicle restricitons which would need additional thought.

Also related: #585

**Comment by kianzarrin** [comment]
In this particular case if we could stop the bleeding it would work. The overlay should not bleed too far up or down. maybe +-3? 
The problem is limiting the minY/maxY does not stop the bleeding it just makes it weird. I don't know how to stop the bleeding. kvakvs mentioned RenderGeometry() which is worth considering.

I mentioned using the ALT key to solve #354. but here we can simply hide monorail markers and show road markers when the mouse is hovering over road rather than monorail.

**Comment by kianzarrin** [comment]
![image](https://user-images.githubusercontent.com/26344691/163764960-65b63b17-fe29-4bdc-b7b2-09b252a72bef.png)
Since when @krzychu124 has reduced vertical render limit, this is not an issue anymore. see https://github.com/CitiesSkylinesMods/TMPE/issues/654#issuecomment-582778841

**Comment by aubergine10** [comment]
Any idea which PR fixed this?
