### ISSUE TITLE
Ditch uglu vehicle restrictions popup

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#657]
When editing vehicle restrictions, this thing appears:

![image](https://user-images.githubusercontent.com/1386719/73905482-56b22b00-4897-11ea-8cec-ef7d83274f47.png)
whhyyyyyyy?

It's grim, and it's somewhat confusing to new users (especially if they've just come from using speed limits tool - they're like "Where's the icons on the popup?").

IMO we could probably get rid of it.

* Invert - we could add keyboard shortcut for this (does anyone even use it?)
* Allow/Ban all vehicles - again, keyboard shortcut could do this (does anyone even use it?!)
* Apply to entire road - we already have `Shift+Click` shortcut for that

Ditching the popup would reduce clutter and confusion, and be one less UI+translations for us to maintain.

**Comment by kvakvs** [comment]
Should replace this with information panel with keybinds/tool buttons for the restrictions tool. It is kind of related with what i am plotting around MainMenu, i or someone else will continue doing the same to every existing tool.

**Comment by rogermartensson** [comment]
Maybe Shift-S for Ban/Allow? If it is possible?

**Comment by aubergine10** [comment]
We're treating `Shift` as "propagate down the road" modifier, so maybe `Ctrl` instead?

* `Ctrl+I` = Invert
* `Ctrl+A` = Allow all
* `Ctrl+B` = Ban all

We could do vehicle shortcuts for common combos?

* `Ctrl+P` = Toggle cars and trucks
* `Ctrl+E` = Toggle service & emergency

So I could do `Ctrl+B` + `Ctrl+E` to set road to "service + emergency" only. Hod down `Shift` with that to propagate down the road.
