### ISSUE TITLE
v11 - Game stuck on pause? Caused by Pause on Load mods, not TM:PE.

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#665]
> # Solution
> Unsubscribe the Pause On Load mod (or any mod that pauses on load). Seems the recent "Paradox Launcher" update broke mods that pause on load.
> ----

Had following two reports via v11 STABLE page:

> **JP DFW**:  
> I am also using Steam on Mac. I unsubscribed from v10.2 today. Quit the application. Rebooted, and started the Steam App. I subscribed to 11.0 then after download, quit the steam application. I restarted launched Skylines and said Play, not resume. I then went to content manager and enabled v11. I then loaded my saved game from last night. First I noticed that while I used 81 tiles to unlock all last night, half the map was locked. When I went to add roads, while to tool would select I could not place any roads. I am about to unsubscribe now and go back a version. The only change in my game was the adoption of TMPE V11.

> **pallamf**:  
> I'm using Steam on a Mac, and switched to V11 yesterday. I removed 10.4, installed 11. When I load games, the bottom menu strip loads about 5 seconds later. The key commands work, I can zoom around, click on things, etc. The only thing that doesn't work is when I take the game off pause, the time and traffic doesn't do anything. It seams like it hangs, but again, I can still scroll around, click on other menus, etc. It just doesn't "run". Then, when I try to quit, it'll hang. I removed v11, reinstalled 10.4, and it all worked normally again. I do have pause on start mod loaded. Curious if anyone else has see this behavior?

I've asked both for logs and any other details.

**Comment by aubergine10** [comment]
Linking #669

**Comment by aubergine10** [comment]
Linking #679

**Comment by aubergine10** [comment]
Possibly related #677

**Comment by aubergine10** [comment]
Linking #695

**Comment by SomeoneElse58** [comment]
I'm also having this strange halted simulation issue. Unlike the other two reports, I am on a W10 machine. Going from v10.2 to v11 will result in the exact situation both the others described; Neither the Stable nor the Labs version work. Going back to v10.2 from v11 works without issue. I also had the Pause on Load mod, but have since unsubbed from it; that did not have any effect.

I do get this error on map load when using v11 and 81 Tiles at the same time: https://i.imgur.com/v8WBJ1Z.jpg
```
Array index is out of range.
[System.IndexOutOfRangeException]

Details:
No details
```
If I unsub from 81 Tiles the array error does not appear, but the main halted simulation issue remains.

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4355478/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4355479/TMPE.log)

**Comment by krzychu124** [comment]
@SomeoneElse58 disable `Electric Roads Mod` and report back if helped or not.

**Comment by SomeoneElse58** [comment]
@krzychu124 No change after unsubbing Electric Roads Mod
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4356054/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4356055/TMPE.log)

**Comment by aubergine10** [comment]
@SomeoneElse58 I suspect it will be the `Proper Hardness Mod - KHFork` mod causing most of the issues as it is quite brutal in the way it changes the game (I'm currently working on a mod compatibility checker and Proper Hardness has almost as many mod conflicts as Shicho mod).

Also, you seem to have two versions of Proper Hardness mod subscribed, one in the offline folder and one in the workshop folder - that will cause problems because the game can't differentiate between mod assemblies (dll files) with same name.

The `Real Time Offline` mod hasn't been updated for latest game version (author states he won't be maintaining it any more). You also have the normal version of `Real Time` subscribed - even though it's disabled, it can still load stuff in to RAM and the game engine has problems when two mods with same assembly name are subscribed (it can't tell the difference between them).

The `Parallel Road Tool` mod also has some serious bugs and incompatibilities, it looks like it's no longer being maintianed by the authors.

`Control Building Level Up` might be obsolete as the game now has a "Historic building" feature built in.

`AssetIconsV2` is known to be game breaking; completely unsubscribe.

If memory serves, `Immersive Water` is not compatible with either of the `Real Time` mods.

The `Building Anarchy` mod is known to be game breaking - it will work for a while but eventually can corrupt the save game beyond repair. I suggest unsubscribing it.

The `Traffic Report Tool` mod has severe conflict with TM:PE, especially if you use lane connector tool (it doesn't process lane connections properly).

`Extended Info Panel` causes problems with `Real Time` mod (as Real Time tries to update the yellow "day progression" bar but can't find it).

`Speed Slider` can sometimes cause problems with `Real Time` mod as it confuses the daily schedule for cims.

You have outdated `Ploppable RICO` mod subscribed, unsub it and try the newer `Ploppable RICO Revisited` mod which fixes dozens of bugs and other issues that the old one had.

You have multiple camera mods subscribed which could potentially cause some issues (some are known to be compatible but I've never seen a log showing so many camera mods subscribed at same time).

`Flight Cimulator` is known to be game breaking; completely unsubscribe.

`More Beautification` causes severe lag, unsubscribe and instead use `Find It` mod.

You have two versions of `Loading Screen Mod` subscribed which will cause lots of errors.

You have two versions of Network Skins subscribed; completely unsubscribe one of them.

You have two versions of `Realistic Population` - keep the `Revisted` version (it is the official update) and remove the older `WG` version.

The `Proper Hardness` mods have severe conflicts with game balance altering mods such as `Realistic Population` and `Lifecycle Rebalance`.

The `81 Tiles` mod is not compatible with `More Vehicles` mod, according to More Vehicles workshop page description.

In general, never have two versions of same mod subscribed (it confuses game engine) and completely unsubscribe any mods you don't use (otherwise there is still risk of them being loaded in RAM _even if they are disabled_).

**Comment by SomeoneElse58** [comment]
@aubergine10 Thank you for the through rundown. I kept `Extended Info Panel` and `Speed Slider` over `Real Time`, as well as `Control Building Level Up`. My game is back to working order with `TMPE v11.1`.

Can you expand upon how a disabled mod can still affect things? Most of the mods you've mentioned were already disabled because they didn't work with `TMPE v10.2` while enabled, yet the game _seemed_ to run fine with them simply disabled.

**Comment by aubergine10** [comment]
@SomeoneElse58 There are a few ways a disabled mod can still affect things:

1. When disabled, some mods don't properly "detatch" their code from the game (eg. remove patches or redirects, etc). This issue is suprisingly common, and it's the primary reason why the game tends to break if there's a second city load in the same Cities.exe session. It's partly due to the game events being somewhat incoherent and also due to modders not having sufficient time to work around those game engine issues. Exit to desktop will usually resolve that issue.

2. Some mods run code even when they're not supposed to (eg. when classes are instantiated, rather than the usual game events). Sometimes this is a necessity (eg. "Skip Intro" mod), other times it's just bad coding. Only way to solve that is complete unsubscribe the mod, then exit to desktop to flush it from RAM.

3. The game will sometimes load referenced assemblies form disabled mods, most commonly the `0Harmony.dll`, even if the mods were disabled when the game was launched. My [Duplicate Assembly Scanner](https://github.com/CitiesSkylinesMods/DuplicateAssemblyScanner) mod can detect that in certain cases.

**Comment by krzychu124** [comment]
All mentioned issues are already closed, so I'm closing this too. I have nothing to add, no new reports since then.
