### ISSUE TITLE
Setup github org - generic CSL mods?

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#673]
Regarding github org, I think we should consider setting up a generic one for CSL mods, not just something specific to TM:PE.

The possibility is that other mods could join under the banner, allowing other modders to more easily take over (or at least bugfix) if original author leaves the community. It would also aid discoverability of mods for any developer wanting to contribute.

Main potential issue I can currently think of is can each repo have it's own github pages, or is there only one pages per org? Also, I have no idea what other mod devs would think about the proposal.

Also, it would be nice if we could shrink the repo name from what it currently is `Cities-Skylines-Traffic-Manager-President-Edition` to just `TMPE`. Would make sharing links to the repo so much nicer: `https://github.com/CSLMOD/TMPE` for example, although not sure what would happen to existing forks, etc.

**Comment by kvakvs** [comment]
Makes little sense unless you have more candidate mods waiting.
`CitiesSkylinesMods`
`CSMods`
Some unrelated mod belonging to a TMPE brand is not bad either :)

**Comment by krzychu124** [comment]
> Also, it would be nice if we could shrink the repo name from what it currently is Cities-Skylines-Traffic-Manager-President-Edition to just TMPE. Would make sharing links to the repo so much nicer: https://github.com/CSLMOD/TMPE for example, although not sure what would happen to existing forks,

According to github docs: 
> When you rename a repository, all existing information, with the exception of project site URLs, is automatically redirected to the new name

> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. 

and also
> Warning: If you create a new repository under your account in the future, do not reuse the original name of the renamed repository. If you do, redirects to the renamed repository will break.

About Github Pages:
> There are three types of GitHub Pages sites: project, user, and organization

> User and organization sites are always published from a repository named `<user>.github.io` or `<organization>.github.io`. Unless you're using a custom domain, user and organization sites are available at `http(s)://<username>.github.io` or `http(s)://<organization>.github.io`.

> The source files for a project site are stored in the same repository as their project. Unless you're using a custom domain, project sites are available at `http(s)://<user>.github.io/<repository>` or `http(s)://<organization>.github.io/<repository>`.

**Comment by aubergine10** [comment]
looks good! let's try and get this setup for v11.2 (month or two from now?) allowing us to also do #659.

**Comment by aubergine10** [comment]
BTW, I like @kvakvs ideas for the org name in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/673#issuecomment-583826595

**Comment by kvakvs** [comment]
Setting up an Organisation takes approx 5 minutes and old links and refs to the old address continue working. Ping @krzychu124 let's do this :)

**Comment by krzychu124** [comment]
OK, so org name `CitiesSkylinesMods` and repo `TMPE`, right? @aubergine10

**Comment by aubergine10** [comment]
@krzychu124 Yes :)

**Comment by krzychu124** [comment]
Do we need separate e-mail for org?
![image](https://user-images.githubusercontent.com/19638970/74765677-4da45f00-5284-11ea-9a4e-73858b985ccf.png)

**Comment by kvakvs** [comment]
No, keep your own, i guess.

**Comment by krzychu124** [comment]
Repository transferred to organization, looks good 😃
