### ISSUE TITLE
Add lane highlight to Vehicle Restrictions tool

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#681]
When user is hovering a vehicle restriction icon, it is sometimes unclear which lane it corresponds to.

![image](https://user-images.githubusercontent.com/1386719/74113255-f4a93c80-4b9a-11ea-9277-ebd861c1c810.png)
> That was just an example from my current city; the more common scenario is huge roads with like 24 lanes where you have to start counting rows and lanes to work out what's being changed.

Could we pimp the relevant lane with a highlight to make it completely clear which lane is being altered?

The lane highlight would only be visible while the vehicle restriction icon is hovered.

Suggestion: White highlight (like outgoing lanes on Lane Connector tool) but without the border -a subtle highlight might be sufficient. Alternatively (might be overkill, try white first) the highlight could be coloured similar to the icon border (green or red) showing current state; that way if user hovers green icon the lane is green, they click to apply restriction = icon and lane turn red.

**Comment by aubergine10** [comment]
Refs: #33

**Comment by kianzarrin** [comment]
@aubergine10 what is the difference between this and #33 ?

Also suggesting Shift modifier do the same thing as apply to all road toggle.

**Comment by aubergine10** [comment]
memory loss heh, totally forgot about the earlier issue until after I'd made this one but noticed it later on routine issue trawl and linked it in.

**Comment by kianzarrin** [comment]
- I manged to put the lane highlight on the top of segment highlight and stop them from blending with each other:
![Cities_Oko0fAG3eG](https://user-images.githubusercontent.com/26344691/74665731-e82f7000-51a8-11ea-8c5d-0379ffc9a86e.jpg)
- holding shift will turn the lane highlight to yellow. 
- Notice the yellow buttons: pressing those buttons while holding shift will apply changes to the whole lane.
- I am planning to do the same with invert
- pressing delete will activate the allow all button and show the 'button is pressed' sprite.
![Cities_mVL1lbkHJd](https://user-images.githubusercontent.com/26344691/74666080-89b6c180-51a9-11ea-9145-15230ebeafa8.jpg)
- pressing shift+delete will allow all cars on the whole segment. the related GUI button will display yellow color and pressed sprite.

**Comment by kianzarrin** [comment]
Observation: 
Suppose you ban several vehicles on a single segment:
![Screenshot (529)](https://user-images.githubusercontent.com/26344691/74668564-24b19a80-51ae-11ea-9eb8-678231fa5c4d.png)

Then you shift click to ban another call on the whole lane:
![Cities_Otk8dYamp1](https://user-images.githubusercontent.com/26344691/74668766-925dc680-51ae-11ea-8602-1db97d76badd.jpg)

You notice that all the other restrictions on the same lane have applied to the rest of the segments but restrictions from other lanes have not applied to the rest of the segments. strange ha?
I consider this to be a bug and I shall fix it :)

**Comment by aubergine10** [comment]
Yeah, the UI of this tool is a bit weird.

Suggestions: 

1. Completely ditch the floating panel - it's confusing and largely obsolete I think?
2. Shift click an icon should only apply the changed state of that icon along the route; other vehicles should be unaffected
    * Example: If I shift+click car to restrict it (red icon state) then the car should be restricted along the route; other vehicle categories on the route would be unchanged.
3. Maybe have a `Ctrl` key shortcut that works a bit like speed tool - ie. toggles between lane-mode and direction-mode

**Comment by kianzarrin** [comment]
@aubergine10 
> Completely ditch the floating panel - it's confusing and largely obsolete I think?

No I worked so hard to make it useful! I think we need to improve on it. 
I think Priority road should also have a panel. in my opinion too many modifier keys with no proper visual feedback is confusing for users. Its better to have a panel that associates each button with a modifier key. if the button is pressed the particular mod is activated (until the button is pressed again). if the modifier key is pressed button texture changes to pressed and the particular mode is activated (until modifier key is released).

**Comment by aubergine10** [comment]
If we keep the floating panel, could we at least make it look a bit nicer?

* Ditch invert button, seems pointless
* Replace Ban/Allow all buttons with graphic buttons (similar to speed palette), rough mockup (still not found any remotely decent graphics apps for Windows):

![image](https://user-images.githubusercontent.com/1386719/74673684-9c2ffb80-51a7-11ea-81dd-25f54b8820c1.png)

Red with bar version of that icon to 'ban all'. Could be shortcuts for allow/ban (Ctrl+A, Ctrl+B) shown in tooltip of those buttons.

And maybe some button to toggle 'entire route' mode (tooltip would mention Shift key).

**Comment by kianzarrin** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/26344691/74682226-1b382a80-51ce-11ea-9c8d-c9809d48953e.gif)
Yeah invert is pointless. 
if shift (or road mode button) is pressed, lane highlights will become yellow and apply to road's length. the road mode button displays pressed sprite. related buttons show yellow color indicating they influence the whole road.

**Comment by kianzarrin** [comment]
@aubergine10  I am thinking maybe we do not need this shift modifier at all. I don't think anyone will use it. "apply restriction to entire road" is good enough. we just need to get rid of the invert button.

**Comment by aubergine10** [comment]
I'd still keep `Shift` for 'apply to route' as that's consistent with all other tools and to me seems more intuitive than clicking a button on a panel. We can keep the button panel tool (it's looking a lot cleaner now and taking up less space) as some users will prefer that. But personally I'd prefer using `shift` just like in all other tools.

**Comment by kianzarrin** [comment]
OK so I will remove the shift GUI button that I just added but the modifier remains.
