### ISSUE TITLE
Timed traffic lights default wrong way

### ISSUE THREAD

**Issue by dynamiik** [CitiesSkylinesMods/TMPE#690]
### Describe the problem
For example on a T-Junkion: When road 2 (which is turn left or turn right) has green light, the right turning lane on the street to the left should be green but insteed it is the straight lane from the street to the right.

### Steps to reproduce

1. Place default timed traffic light

### Log files

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4185614/output_log.txt)
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4185616/TMPE.log)

### Savegame?

[Savegame](https://steamcommunity.com/sharedfiles/filedetails/?id=1994710641)

### Screenshots?

[Screenshots](https://imgur.com/a/n716Wkj)

**Comment by krzychu124** [comment]
Don't forget about pedestrians, if each step would have at least one green, automatic pedestrian traffic light would be always red

**Comment by dynamiik** [comment]
I don't know exactly what you mean krzychu124. The traffic light looks like it is for left hand traffic instead of right hand traffic. The extra single green light should be at an other position so cars won't cross each other

**Comment by kianzarrin** [comment]
#769

**Comment by kianzarrin** [comment]
duplicates #769

**Comment by aubergine10** [comment]
This will be fixed in LABS 11.1.1-hotfix2.
