### ISSUE TITLE
The `--continuelastsave` launch option skips mod checker panel

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#697]
Since new launcher, the `--continuelastsave` launch option (what happens when user clicks "Resume" on the launcher app) makes game automatically reload last save.

If TM:PE finds mod incompatibility, it shows the purple warning dialog expecting main menu to remain in background. However, `--continuelastsave` just closes all that down and dives in to game. From user perspective, a purple panel flickers up for less than a second then disspaears again as their last save starts to load.

So we need some way to disable `--continuelastsave` if mod incompatibility is found.

I'm not entirely sure how to do that. I suspect by the time we get round to displaying the "incompatibel mods found" panel, the game has already kicked in loading of last savegame.

**Comment by aubergine10** [comment]
`LauncherLoginData.instance.m_continue`

**Comment by aubergine10** [comment]
```cs
if (LauncherLoginData.instance.m_continue)
	{
		LauncherLoginData.instance.m_continue = false;
		Invoke("AutoContinue", 2.5f);
		m_BackgroundImage.zOrder = int.MaxValue;
	}
	else
	{
		m_BackgroundImage.zOrder = 0;
	}
```

**Comment by aubergine10** [comment]
At the end of compatibility checking, if no problems found (ie. no need to exit to desktop), I need to invoke a method on the main menu but not sure how to get hold of the main menu instance...

This is the method I want to invoke:

```
MainMenu.Invoke("AutoContinue", 2.5f);
```

Any ideas? @krzychu124

**Comment by krzychu124** [comment]
Isn't main menu instance accessible from UIView library?
