### ISSUE TITLE
Auto junction give-way/priority (on priority routes)

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#7]
On a priority route (as defined via road info view panel), any junctions without traffic lights could be given automatic give-way and priority settings.

The calculations would be performed whenever user:

* Marks or unmarks a road as 'priority route' (via road info panel)
* Connects or disconnects a road to an existing priority route
* Removes traffic lights at a junction that has at least one priority route attached

In cases where a junction has two or more priority routes, the primary route can be determined via metrics such as:

* Number of lanes (more = higher priority)
* Speed of road and/or lane (faster = higher priority)
* Width of road and/or lane (wider = higher priority)

**Comment by aubergine10** [comment]
In game, yes, I believe marking a route as priority will cause connecting roads to be given stop signs.

However, what I'm seeking is tighter integration between TMPE and vanilla.

So TMPE should apply it's priority/yeild signs as applicable along a priority route.

There is already TMPE option of **Shift+Click** when adding priority signs to apply them to all junctions for the given road (not tested this myself yet, but see docs here: https://tmpe.viathinksoft.com/wiki/index.php?title=Priority_signs#Priority_roads ).

So in theory the heavy lifting code is already done, it just needs a little extra wiring so that when user first marks a route as 'priority' (using vanilla functionality) TMPE at that point sets up the priority/yield signs. Users can subsequently go in and change any junctions as desired.

**Comment by FireController1847** [comment]
That's an interesting way to look at it. Awesome idea +1

**Comment by aubergine10** [comment]
This was implemented by #631 - vanilla 'Priority road' checkbox replaced with TMPE priority toolbar.
