### ISSUE TITLE
quick fix for lane connector

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#703]
pressing CTRL+S activates stay in lane feature. we can expand it to support the following situations:

![Screenshot (505)](https://user-images.githubusercontent.com/26344691/74601037-f6df2f80-50a1-11ea-89a3-be7da846ef4f.png)
![Screenshot (502)](https://user-images.githubusercontent.com/26344691/74601041-fa72b680-50a1-11ea-8bde-9b98ebed1b58.png)
![Screenshot (500)](https://user-images.githubusercontent.com/26344691/74601042-fcd51080-50a1-11ea-8aa5-2ba3bbb1797e.png)

Sometimes people use lane connector to handle split road like this:
![Screenshot (497)](https://user-images.githubusercontent.com/26344691/74601058-30b03600-50a2-11ea-9220-17e37826e496.png)
But i think that is unnecessary because changing lane arrows would be sufficient(already possible by priority tool -> CTRL+ckick):
![Screenshot (504)](https://user-images.githubusercontent.com/26344691/74601065-4b82aa80-50a2-11ea-9558-616f758ffa52.png)
Cars are not going to change lanes if `switch lane while going straight in junctions` is turned off.
maybe its worth supporting this too because customer is always right?

We need to limit the scope of this review so that it does not get into an all or nothing scenario. The following junction does not support quick fix:
![Screenshot (503)](https://user-images.githubusercontent.com/26344691/74601114-dd8ab300-50a2-11ea-9689-3caa0d396799.png)
I cannot think of other junctions right now. but its worth discussing them for the second phase of this issue.

**Comment by aubergine10** [comment]
I assume existing `Shift+S` is getting changed to `Ctrl+S` as part of this (to tie in with how all the other tools work)? And then `Shift+Ctrl+S` would apply `Ctrl+S` to the route?

I think these two, defintely should be part of `Ctrl+S` shortcut as they are both clearly "straight on":

![image](https://user-images.githubusercontent.com/1386719/74601182-3c483080-5093-11ea-9051-f6236bcc2071.png) ![image](https://user-images.githubusercontent.com/1386719/74601185-4407d500-5093-11ea-953b-233ebb0a0da8.png)

Remember also that `Ctrl+S` (currently `Shift+S`) can be applied multiple times to toggle between:

* Both directions
* One direction
* Other direction

The other two examples you posted are not "straight on" from the perspective of the main road:

![image](https://user-images.githubusercontent.com/1386719/74601197-639efd80-5093-11ea-99ec-b6b108538a7e.png) ![image](https://user-images.githubusercontent.com/1386719/74601200-6994de80-5093-11ea-90e3-ea2be44bbb61.png)

Maybe those could be `Ctrl+J` or something?

**Comment by kianzarrin** [comment]
The shift+S hotkey will be repurposed to be quick fix.

Also we don't need a 4-state stay in lane state-machines for one way roads.

**Comment by kianzarrin** [comment]
@aubergine10 we put comments at the same time. I prefer to use the same hotkey and not introduced a new one. the state machine would be variable depending on the connection.
Also we don't need a 4-state stay in lane state-machines for one way roads so that is kind of a bug.

**Comment by kianzarrin** [comment]
@aubergine10 The other two examples you posted are not "straight on" from the perspective of the main road

so ctrl+s is no longer straight on but rather quick setup.

**Comment by aubergine10** [comment]
ok

**Comment by kianzarrin** [comment]
Some intermediate results:
![Screenshot (511)](https://user-images.githubusercontent.com/26344691/74608797-d7212900-50ec-11ea-8fba-e1c9342cd083.png)
![Screenshot (512)](https://user-images.githubusercontent.com/26344691/74608799-dc7e7380-50ec-11ea-968d-dfd3b08467bd.png)
![Screenshot (509)](https://user-images.githubusercontent.com/26344691/74608772-aa6d1180-50ec-11ea-9469-5c17beb5c6d2.png)

It gets confused when the road is connected from left side of the highway. I should compare inner lanes in that case instead of outer case.

All of these scenarios is handled with one inclusive formula.

**Comment by kianzarrin** [comment]
OK this is done. but it depends on #701

**Comment by kianzarrin** [comment]
In this issue I do not intend to handle tracks. That should be handled as part of #705

**Comment by kianzarrin** [comment]
This works with asym roads too:
![Screenshot (517)](https://user-images.githubusercontent.com/26344691/74610578-0e97d180-50fd-11ea-9825-6dfbacd982a6.png)
![Screenshot (516)](https://user-images.githubusercontent.com/26344691/74610581-13f51c00-50fd-11ea-9448-8295cc761d06.png)

**Comment by kianzarrin** [comment]
The second phase of this issue can connect the lanes from the other side of the T junction as well. Also support for 4 way junctions. 

This way we can have a 4-state quick-setup state machine. StayInLane would be special case of Quick-setup where the connecting road has 0 lanes.

**Comment by pcfantasy** [comment]
Aha, nice to see TMPE team also want to implement this function.

actually, I have implement this function for CSUR road.

https://github.com/citiesskylines-csur/CSURToolBox/blob/master/UI/StayInLaneUI.cs
AddLaneConnectionForCSUR

All outgoing lane will connect to nearest incoming lane, and All incoming lane will connect to nearest outgoing lane.

This is a quick way for Y juction in CSUR road.
