### ISSUE TITLE
VERSION vs. Version

### ISSUE THREAD

**Issue by Strdate** [CitiesSkylinesMods/TMPE#728]
It is too late to do anything about it, but anyway...

I found out that my [Adjust Pathfinding](https://steamcommunity.com/sharedfiles/filedetails/?id=1829496988) mod is not working. Reason for this? Somebody renamed the Version property of TrafficManager.TrafficManagerMod class to VERSION. I cannot emphasize how bad idea is it to rename such a key property of the mod since now there is not even an quick and simple way to check if the user is using pre-v11 tmpe or not. The property is now useless as it is version-dependent, although it should inform you about the version in the first place!

You guys are really not saving my time lately...

This is how I use it in my mod:
```
private static string GetTMPEVersion()
        {
            return TrafficManager.TrafficManagerMod.Version;
        }
```

**Comment by aubergine10** [comment]
```cs
Version TMPE_Version = Assembly.Load("TrafficManager").GetName().Version;

if (TMPE_Version < new Version(11)) {
    // Version 11.0 and earlier all had assembly version 1.0.*.*
} else if (TMPE_Version >= new Version(11, 1, 0)) {
   // Version 11.1.0 and above all have correct assembly version in form M.m.b.* (Major, minor, build, *)
}
```

**Comment by aubergine10** [comment]
We renamed it because there's a system class called `Version`.

From TMPE 11.1.0 onwards, the assembly version for `TrafficManager` assembly correctly reports the mod version number.

So if assembly version is less than 11.1.0 you could use your original method to get version number.

**Comment by Strdate** [comment]
I don't give a heck what is from v11 onwards, I'm just saying that you broke compatibility with pre-v11 although you didn't have to.

I don't think that it is meaningful to continue this discussion.

**Comment by aubergine10** [comment]
v11.0 (what's on the v11 STABLE workshop) should still have the `.Version` member.

So it's likely only the current v11 LABS that's breaking things, where the member was renamed `.ModVersion` to disambiguate from `System.Version` class.
