### ISSUE TITLE
Unnecessary scrollbars in mod options

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#743]
@kianzarrin noticed this during in-game testing:

![image](https://user-images.githubusercontent.com/1386719/75343029-7da8bf00-588f-11ea-9b6f-550c764e5f82.png)

In the image above, there isn't any need for scrollbar.

Likely due to recent scrollbar updates (ref: #722, #742)

**Comment by krzychu124** [comment]
I think I fixed that issue in #742

**Comment by aubergine10** [comment]
No, that was double scrollbar issue fixed in #742 I think?

**Comment by krzychu124** [comment]
I changed `scrollPanel` height too, so it probably soled this issue too. 
I didn't noticed that issue yesterday while testing.

**Comment by aubergine10** [comment]
I'll check next time I'm in-game

**Comment by krzychu124** [comment]
Already fixed in [11.1.1](https://github.com/CitiesSkylinesMods/TMPE/milestone/23)
