### ISSUE TITLE
clicking on vehicle restriction handles throws hidden exception

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#744]
see https://github.com/CitiesSkylinesMods/TMPE/pull/721#pullrequestreview-364408877
we should also check for other tools too.

**Comment by aubergine10** [comment]
I tried with other tools but couldn't get that error. Seems to only affect Vehicle Restricitons.

Note: I was just randomly clicking stuff so not sure what specifically causes the error; as such it's possible error is there in other tools so still do some extra testing on that.

**Comment by krzychu124** [comment]
I think that occurs only with shift click.

**Comment by aubergine10** [comment]
Tried various key modifiers with various tools; only one throwing errors is Vehicle Restrictions.

Log file from current 11.1.0 master branch 
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4257123/TMPE.log)

**Comment by krzychu124** [comment]
@kianzarrin 
> I put some debug logs which suggest it is the foreach( lanes in sortedlanes) that is throwing the exception. but sortedlanes has not changed.

You are searching in a wrong place. Exception is thrown in `ShowSigns()`.
The problem is that signs are rendered while you are refreshing list of `this.currentRestrictedSegmentIds` by applying restrictions to segments. 
It is possible because base.OnToolGUI is called from `Update` **and** from `OnGUI`

I think we should investigate if current implementation of interactions are correctly set up.

**Comment by kianzarrin** [comment]
@krzychu124 when fixing a single segment, the refresh is delayed. but when fixing multiple segments it is not. so that's why way of fixing it. but honestly, i'd just return and try again next loop.

**Comment by krzychu124** [comment]
you could convert hashset to array and use regular `for` (that would fix exception for sure)

**Comment by kianzarrin** [comment]
> you could convert hashset to array and use regular for

too slow. If it was up to me I would throw an exception and then catch it silently.

**Comment by krzychu124** [comment]
> If it was up to me I would throw an exception and then catch it silently.
That's perhaps even slower(if you use logging) 😅

**Comment by kianzarrin** [comment]
@krzychu124 It is slower but its not performance critical part of the code. its as a response to user click. your approach occurs every loop.

in any case I know you guys are not going to agree to the exception approach so I found another way to both make the code simpler and solve the problem. Ill upload PR now
