### ISSUE TITLE
When Updating from TMPE 11.0 Stable to TMPE 11.1 LABS, none of the road setups roll over to the new one. 

### ISSUE THREAD

**Issue by somethingstarted** [CitiesSkylinesMods/TMPE#748]
### Describe the problem

I opened the program, then I disabled (not unsubbed) from 11.0 stable and subbed/enabled 11.1 LABS. when I opened my city, every intersection and road had default, vanilla values. No lane changing lines, no custom arrows, no yield's, no custom stoplights. No intersection restrictions (like right turn on red or whatever) I didn't check speed limits etc, but I would imagine those didn't roll over. 

### Log files
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4263030/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4263031/TMPE.log)

**Comment by krzychu124** [comment]
@somethingstarted Have you read description??
It clearly says:
_Switching TM:PE versions:_ **Exit game to desktop first**, **completely unsubscribe (not disable!)** current version, then subscribe other version. Then **relaunch** the game.

**Comment by aubergine10** [comment]
Yup, two versions of TMPE installed = settings will be lost.
```
! * 1637663252   TM:PE 11.0 STABLE
  * 1806963141   TM:PE 11.1.0 LABS
```

Choose one, completetly unsubscribe the other.

**Comment by aubergine10** [comment]
No response, closing.
