### ISSUE TITLE
Panel backgrounds aren't absorbing mouse interactions

### ISSUE THREAD

**Issue by somethingstarted** [CitiesSkylinesMods/TMPE#749]
### Describe the problem

When you click on an option, like Stoplight manager, or speedlimit, any of them, the new black window pops up over the other buttons, and when you click on something, it also clicks on the menu buttons underneath it. 

### Log files

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4263082/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4263083/output_log.txt)

### Screenshots?

![parking restrictions](https://user-images.githubusercontent.com/19464532/75470379-33d6dc00-5956-11ea-8937-a33a0fb3abd9.JPG)
![nodes](https://user-images.githubusercontent.com/19464532/75470380-346f7280-5956-11ea-843e-d3216b2b7fc2.JPG)

**Comment by aubergine10** [comment]
Thanks for the bug report, we're hoping to tackle this issue in next round of UI updates.

Tagging #683 , #726

**Comment by aubergine10** [comment]
The speed limits UI has been completely rewritten for 11.6 release, fixing the issue in OP.

Still need to test the traffic lights - will report back.

**Comment by aubergine10** [comment]
Tested:

✔️ Speed Limits UI
✔️ Lane Arrows UI
❌ Timed Traffic Lights 

@kvakvs is there a quick way to update existing TTL window panels so they absorb mouse clicks rather than passing them through to whatever is beneath? Would close 2-3 similar issue reports.
