### ISSUE TITLE
Yield signs broken (again?)

### ISSUE THREAD

**Issue by Marquillotuca89** [CitiesSkylinesMods/TMPE#756]
### Describe the problem
Yield signs don't work as expected. Cars inside a roundabout (for example) give way to cars incoming to the roundabout even if there is a priority sign for cars on that roundabout and a yield sign for the incoming traffic. 

### Steps to reproduce

1. Build a roundabout
2. Place the priority signs
3. Wait 

### Log files

[Log_Files.zip](https://github.com/CitiesSkylinesMods/TMPE/files/4270765/Log_Files.zip)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2010509718

### Notes or questions?

The problem came back with 11.1.1 v.

**Comment by krzychu124** [comment]
Please set simulation accuracy to **Very High** and test again :)

**Comment by Marquillotuca89** [comment]
> Please set simulation accuracy to **Very High** and test again :)

OMG, if that's the problem, I would be really ashamed. Will try it again. 
Thanks a lot.

**Comment by krzychu124** [comment]
It is possible because reintroduced Simulation Accuracy option skips additional tests for vehicle priority at lower settings. If not helps, that perhaps I messed up something :)

**Comment by Marquillotuca89** [comment]
Ok, just tried again and let it run for 7 minutes. Cars are definitely giving way. 
 
![Captura4](https://user-images.githubusercontent.com/54244543/75613527-57378d80-5af4-11ea-8ef6-26ee9856a5d2.JPG)

![Uploading Captura3.JPG…]

![Captura1](https://user-images.githubusercontent.com/54244543/75613523-5141ac80-5af4-11ea-8d2e-c534d3dc3b2d.JPG)
![Captura](https://user-images.githubusercontent.com/54244543/75613519-4b4bcb80-5af4-11ea-97d8-27ada440574a.JPG)

**Comment by Marquillotuca89** [comment]
Thanks a lot, I'll see if it works.

**Comment by aubergine10** [comment]
I think in your case it might make the issue worse to slow the speed down.

**Comment by Marquillotuca89** [comment]
Well, It dindn't work actually. 

I think it's better if I share a video for you to watch it and see if the Yield Signs look broken for your or not. 

https://www.youtube.com/watch?v=0fDS24c7AUw&feature=youtu.be

I would be really thankful if you could check if everything is correct. 

What is weird to me is that the previous version worked as expected.

**Comment by krzychu124** [comment]
Looks like `waitTime` problem (or inaccurate priority check), I will investigate it :)

**Comment by Marquillotuca89** [comment]
> Looks like `waitTime` problem (or inaccurate priority check), I will investigate it :)

Thanks a lot!

I didn't make a change from yesterday (that worked well with previous version) to today (with the new version).

**Comment by aubergine10** [comment]
This will be fixed in 11.1.1-hotfix1

**Comment by Marquillotuca89** [comment]
> This will be fixed in 11.1.1-hotfix1

Pretty great to hear that!
