### ISSUE TITLE
Despawn buttons missing from Vehicle and Cim info panels

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#759]
In v11.1.1 the `(x)` despawn buttons are no longer appearing on the info panels of vehicles and cims.

**Comment by aubergine10** [comment]
![image](https://user-images.githubusercontent.com/1386719/75616411-6c3e0c00-5b48-11ea-90a6-19f5dec7d6c9.png)

![image](https://user-images.githubusercontent.com/1386719/75616420-77913780-5b48-11ea-8f2c-72876213ae80.png)

**Comment by krzychu124** [comment]
Interesting

**Comment by aubergine10** [comment]
Seems to be side-effect of #656

Looking at the buttons on the TM:PE toolbar (eg. [LaneArrowsButton.cs](https://github.com/CitiesSkylinesMods/TMPE/blob/master/TLM/TLM/UI/MainMenu/LaneArrowsButton.cs)), they include definitions for `.skin` and some stuff about `atlasKeys`. That's missing from the despawn buttons on the info panels.

The info panel classes are:

* https://github.com/CitiesSkylinesMods/TMPE/blob/master/TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
* https://github.com/CitiesSkylinesMods/TMPE/blob/master/TLM/TLM/UI/RemoveVehicleButtonExtender.cs

I don't yet know enough about how the new UI system handles textures or button sizes. Maybe @kvakvs or @kianzarrin could take a look?

**Comment by krzychu124** [comment]
OK, I figured it out and generated new textures. I will create PR and we will see.

**Comment by aubergine10** [comment]
This will be fixed in 11.1.1-hotfix1
