### ISSUE TITLE
No remove the vehicles in the information box

### ISSUE THREAD

**Issue by wxf26054** [CitiesSkylinesMods/TMPE#763]
There is no remove the vehicle in the information box.
I cannot remove the bug vehicles when vehicles in the crowd.

**Comment by krzychu124** [comment]
That issue was already reported yesterday, we are working on fix. Tagging https://github.com/CitiesSkylinesMods/TMPE/issues/759

**Comment by wxf26054** [comment]
well....Thank you for your hard-working!

**Comment by aubergine10** [comment]
Duplicate of #759

Hi wxf26054, I'm closing this issue as it's duplicate. If you want to track updates on the bugfix, please subscribe to notifications on issue #759

**Comment by aubergine10** [comment]
This will be fixed in 11.1.1-hotfix1
