### ISSUE TITLE
auto-TTL rotates the wrong way and murders pedestrians!

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#769]
### Describe the problem
![Screenshot (638)](https://user-images.githubusercontent.com/26344691/75662928-9f7fb880-5c78-11ea-94f7-4b1673cc4a96.png)
I created the timed traffic above using CTRL+CLICK.
In each step the green traffic light is lit on the same segment for pedestrian's and cars. Pedestrian timed traffic light should be set to default mode to turn on green traffic light for pedestrians to the right.

**Comment by kianzarrin** [comment]
The pedestrian lights ARE automatic, the problem is that the direction TTL is rotating is wrong. 
I think i might have messed it up when I tried to add Left Hand traffic support.

**Comment by kianzarrin** [comment]
The fact that the rotation of TTL is wrong is pretty serious and severely reduces the effectiveness.
can we push this to stable?

**Comment by aubergine10** [comment]
I think rather than push to stable, we push to LABS 11.1.1-hotfix2, and then that will get pushed to stable in, say, a week if no major issues reported?

**Comment by aubergine10** [comment]
Does associated PR also fix either #690 and/or #622?

**Comment by kianzarrin** [comment]
duplicates #690.
I don't know about #622 . I explain in the issue.

**Comment by kianzarrin** [comment]
@aubergine10 based on the images in #622 its not auto-TTL . so this is unrelated.
