### ISSUE TITLE
lane connector is buggy for bidirectional lanes

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#784]
This code seems to provide support for bidirectional lanes as it adds lanes in both directions:
https://github.com/CitiesSkylinesMods/TMPE/blob/0131e7f9096ddd01b178b96a37b1bdfeb234c6a2/TLM/TLM/State/Flags.cs#L437
First of all do we need reverse connection if the lanes are not bidirectional?
Secondly when I tried to connect bidirectional lanes back and forth I noticed intermittent problems. I did not mange to capture them on screen due to its intermittency but this is what happens:
- Sometimes when I connect one bidirectional lane to another, I can see both the forward and  reverse lane connection curves. and sometimes I do not.
- when I lane1 to lane2 and then I connect lane2 to lane1, The reverse lane connection curves sometimes appears and sometimes it does not. Some other times both the forward and reverse lane connections curves disappear (notice that before hand the reverse connection did not visually exist).

If you play with them long enough you will see.

I tested using this asset: https://steamcommunity.com/sharedfiles/filedetails/?id=1308307531
![Screenshot (685)](https://user-images.githubusercontent.com/26344691/76344319-0997fd80-630a-11ea-99ff-dba34a136cb6.png)

**Comment by aubergine10** [comment]
> First of all do we need reverse connection if the lanes are not bidirectional?

Very good quesiton. Personally, I'd say no. Whole purpose of lane connector is to allow user to specifically decide which incoming lanes link to which outgoing lanes.

I suspect it was implemented the current way to avoid UI issues once a lane is connected in one direction (the circle for the return direction would be obscured by the existing connection).

Bidirectional lanes are a freaking nightmare lol.

**Comment by aubergine10** [comment]
Single-lane train tracks are bi-directional. Hence the [Single Train Track AI](https://steamcommunity.com/sharedfiles/filedetails/?id=949504539). So there is already a usecase where people have bi-directional lanes that we'll need to deal with somehow.

Also, see https://github.com/CitiesSkylinesMods/TMPE/issues/515#issuecomment-597708372

**Comment by aubergine10** [comment]
Kian wrote:

> I tested using this asset: https://steamcommunity.com/sharedfiles/filedetails/?id=1308307531

REV0 (asset author):
> Funicular tracks made in a way that vehicles dont switch lanes  
> Could be road setting related not sure  
> Aside that i didnt change anything unusual

**Comment by kianzarrin** [comment]
The main obstacle here is not the back-end but rather its the UI. the forward/backward lane curves cover one-another.

One solution is for the lane curves to overlap.

**Comment by kianzarrin** [comment]
in case of bidirectional tracks One question is how to restrict lane transitions based on lane connections
 1- source lanes with any incoming/outgoing connections are restricted to lane connections .
 ![image](https://user-images.githubusercontent.com/26344691/158016520-de00c4fb-11fe-4429-a65e-fa877f0f71ea.png)
2- source lanes with outgoing connections are restricted to lane connections. if the lane has only incoming connections, it wouldn't influence its outgoing transitions.
![image](https://user-images.githubusercontent.com/26344691/158016589-7b26b041-d8b3-4b39-bd0a-db6e8c14fc3b.png)

in the second case its impossible to restrict lane transitions using lane connections (unless if there was a way to say restrict all outgoing transitions). So therefore I think we should apply the first approach.
Note: these restrictions only apply to source lanes. target lanes can accept lane transitions from multiple lanes even if they have incoming lane connection.

**Comment by kianzarrin** [comment]
AN assets to that I used for the tests
[train-tracks2x2.zip](https://github.com/CitiesSkylinesMods/TMPE/files/8237607/train-tracks2x2.zip)
