### ISSUE TITLE
Cities skylines CRASH

### ISSUE THREAD

**Issue by garabadz** [CitiesSkylinesMods/TMPE#785]
hi there i tried lot , but stil keep crashing, got this log out, and error log

please help
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4323774/output_log.txt)
[error.log](https://github.com/CitiesSkylinesMods/TMPE/files/4323776/error.log)

**Comment by garabadz** [comment]
my PC stats:

GeForce GTX 1050

Procesor | QuadCore , 3200 MHz (32 x 100)
RAM16263 MB  (DDR4 SDRAM)

**Comment by krzychu124** [comment]
Hi, update your game to latest version first :)

**Comment by garabadz** [comment]
there is no option to update anything at steam.. only validating which is done

**Comment by krzychu124** [comment]
it's weird because your version is `1.12.1-f2`, released 04/06/2019. Check if you have automatic updates turned on. 
Anyways [OSM Import](https://steamcommunity.com/sharedfiles/filedetails/?id=771161159) is probably causing those errors

**Comment by aubergine10** [comment]
Steam keeps games updated by default. You could try reinstalling the game.

As our support policy strates, we don't support old versions of the game:
https://github.com/CitiesSkylinesMods/TMPE#support-policy

If, after updating game to latest version you still have problems please create new ticket and upload new log files.
