### ISSUE TITLE
Lane arrows guide popup malfunction

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#791]
Note: Images are from v11 STABLE release, not sure if it also affects LABS.

Popup about highway rules on non-highway roads:

![image](https://user-images.githubusercontent.com/1386719/77254719-cb300600-6c5a-11ea-9259-ab0b61a0b277.png)

Popup about lane connectors which aren't there:

![image](https://user-images.githubusercontent.com/1386719/77254794-13e7bf00-6c5b-11ea-950c-de2629eac385.png)

**Comment by kianzarrin** [comment]
@aubergine10  the TMPE version you are testing with ... does it include this fix #729 ?

**Comment by aubergine10** [comment]
It wasn't me, it was egi - I just copied here so it was tracked.

He was using the v11 STABLE which is v11.1.0

The PR #729 went in to 11.1.1, so LABS will not have that issue as it's on v11.1.2.

**Comment by DaEgi01** [comment]
yeah, i can verify today evening if v11.1.2 fixed it.

**Comment by kianzarrin** [comment]
So I think we should close this issue

**Comment by DaEgi01** [comment]
yo, wait for test results maybe? ;p

**Comment by DaEgi01** [comment]
looks all good in labs, you can close it.

**Comment by aubergine10** [comment]
We'll be updating STABLE in a few hours so will close once we get all clear there.
