### ISSUE TITLE
Issue on cars stoping at green traffic lights and running red lights with timers set

### ISSUE THREAD

**Issue by Gyomfgy** [CitiesSkylinesMods/TMPE#796]
### Describe the problem

Hello, as discussed on Steam, I share you here what you asked for.

My first message on Steam : "Hi, very good mod, but I just have one little problem: when I set timers for different states on my traffic lights, some cars stops suddenly while it's still green for them and then start again, even running red lights. Any idea how to solve it? Thx :)"

### Steps to reproduce

1. 
2. 
3. 

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4396943/output_log.txt)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2038271141

### Notes or questions?

Thank you in advance :)

**Comment by Gyomfgy** [comment]
Hi again, maybe I'm wrong but I think my problem is quite simple in fact: I had not activated the option allowing vehicles to enter blocked junctions, that could explain.

**Comment by krzychu124** [comment]
Yes, `Allow vehicles to enter blocked junctions` is the right option to solve that issue. You can also apply it for particular junction using `Junction restriction tool`
