### ISSUE TITLE
Yield Hesitation - Back After SH Update

### ISSUE THREAD

**Issue by LemonsterOG** [CitiesSkylinesMods/TMPE#798]
### Describe the problem
It appears that pesky yield hesitation has returned since the Sunset Harbor update.

Poster Per @krzychu124

### Steps to reproduce

1. In a roundabout, set all inner road and entry road restrictions to to allow moving continuously.
2. Set inner road priorities to right of way and entry road restrictions to yield.

### Notes or questions?
Please contact me here on either Steam or Discord with any questions you may have.
Thank you for your continued support of the Cities Skylines community.

**Comment by krzychu124** [comment]
It's weird..., but wait... Do you have `Simulation Accuracy` option set on `Very high`?

**Comment by LemonsterOG** [comment]
Sorry for the delay in response. I don't get notifications from GitHub very often. That's why I asked to be contacted on Steam or Discord.

Simulation Accuracy is on "Medium" -- That's what I always set it at.

Here's screenshots of my settings:

General
https://www.dropbox.com/s/p9ldo5u06fvmzv9/TMPE_Options_General.jpg?dl=0

Gameplay
https://www.dropbox.com/s/e891c1leh0xr4dx/TMPE_Options_Gameplay.jpg?dl=0

Policies
https://www.dropbox.com/s/g0ssk1d6llj8j43/TMPE_Options_Policies.jpg?dl=0

Thanks so much for your continued support.

**Comment by aubergine10** [comment]
Does it improve if you set the Simulation Accuracy to highest level?

**Comment by krzychu124** [comment]
`Simulation Accuracy` was reintroduced to the LABS v.11.1.1. 
It was never available in V11 STABLE. If you used V11 STABLE, Simulation Accuracy setting was internally hardcoded to `Very High`.

**Comment by LemonsterOG** [comment]
Very High seems to work. I wasn't aware of the change. Thanks so much.
