### ISSUE TITLE
Access Denied to TMPE.log

### ISSUE THREAD

**Issue by rodlast** [CitiesSkylinesMods/TMPE#802]
I am running Skylines in Mac Catalina without Steam and currently cannot run the mod due to this issue:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for TrafficManager.State.GlobalConfig ---> System.UnauthorizedAccessException: Access to the path "/private/var/folders/wr/r9rjlbbd0qjdg71y5p6j6bth0000gn/T/AppTranslocation/1581B0BD-2580-4181-83DD-A50DC144E330/d/Cities.app/Contents/TMPE.log"

Seems that since Sierra version there are some problems writing in these temp folders. 

As this seems to be only a log file, I suppose I don't need it. Is there any way I can prevent this file to be written?
Regards

**Comment by krzychu124** [comment]
Hi run game with administrator privileges and should be good. 
There is no option to turn off logging

**Comment by aubergine10** [comment]
Tagging: #379

**Comment by rodlast** [comment]
Sudoing did the trick, thanks
