### ISSUE TITLE
SOLVED PLEASE CLOSE 

### ISSUE THREAD

**Issue by kivanc53** [CitiesSkylinesMods/TMPE#809]
Hello,

I have a problem since the game updated with the new features. I was using old version of the tmpe and I changed it to new version but I can't open my save game. And I think because of the tmpe mod. (But I cannot sure the problem is from tmpe or other mod. This is not a blame I see something in log file. That's the why I am thinking like this.)

PROBLEM: When I opened the game, I cannot pass the the box with Object reference not set to an instance of an object [System.NullReferenceException] Details: No details

This is the TMPE.log file. I see the errors in this file therefore I wanted to write to github.

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4415607/TMPE.log)

If you want to another log file or more details, I can help. 

I want to say again, I haven't experienced this before and I'm opening up a problem record for the first time in github. And I apologize if the problem isn't caused by the mod. I only try to solve my problem. 

Thank You for helps

**Comment by aubergine10** [comment]
Hi, can you run the mod compatibility checker and attach it's log file (AutoRepair.log or, if you're on Mac OSX, Player.log) by drag-dropping it on comment box below - it will upload then click Comment button.

**Comment by krzychu124** [comment]
@aubergine10 it's happening 😭 
tagging #799 
Returning to your problem. Please explain in all details what you do.
How you start the game? Do you use Launcher "Continue" button?

**Comment by aubergine10** [comment]
As @krzychu124 mentions above, it could be issue with the game not performing full load sequence and hopefully the sequence logger will expose issues if that is the case:

https://steamcommunity.com/sharedfiles/filedetails/?id=2018193885

Subscribe and enable the Sequence Logger, then exit to desktop. Then load your city in normal way. 

If it fails to load as before, please attach the `SequenceLogger.log` file (drag on to comment box below, wait for upload, then click comment button).

Both log files (SequenceLogger.log and AutoRepair.log) can usually be found in `C:\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data`.

**Comment by kivanc53** [comment]
Problem solved. Please close the problem. The problem doesn't come from your mode. Sorry to waste your time on this problem.

**Comment by aubergine10** [comment]
What caused the problem?
