### ISSUE TITLE
Customroadai error

### ISSUE THREAD

**Issue by LordPsylex** [CitiesSkylinesMods/TMPE#810]
Could not load type 'TrafficManager.Custom.AI.CustomRoadAI' from assembly 'TrafficManager, Version=1.0.6877.41443, Culture=neutral, PublicKeyToken=null'. [System.TypeLoadException]

Details:
No details

happens on new games and old saves.

**Comment by krzychu124** [comment]
How did you get so old version of TM:PE?
Close game, unsubscribe it and subscribe to newest version [TM:PE v11.2.1](https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252&tscn=1585759824)

**Comment by aubergine10** [comment]
Mod compatibility checker will tell you if you have any other old mods: https://steamcommunity.com/sharedfiles/filedetails/?id=2034713132
