### ISSUE TITLE
Game does not load

### ISSUE THREAD

**Issue by Apple329** [CitiesSkylinesMods/TMPE#815]
### Describe the problem
The game does not load

### Steps to reproduce

I had TM:PE installed in a previous update, after updating the game and installing a new version, the game loads for the first time, but after saving it hangs on an endless download.

### Log files

https://ufile.io/8r2u28af

### Screenshots?

https://ufile.io/usa9xst9

### Notes or questions?
Note: when you turn off the mod, the game loads as usual
Sorry, I do not speak English

**Comment by aubergine10** [comment]
* https://ufile.io/8r2u28af - unable to open file

Please [attach your log files](https://github.com/CitiesSkylinesMods/TMPE/wiki/Share-your-Cities-Skylines-log-file) by dragging them on to comment box below and wait for upload to complete then click green comment button.

**Comment by Apple329** [comment]
sorry i was wrong:
log files: https://ufile.io/xhi6b7vg

**Comment by aubergine10** [comment]
Hi - we updated TM:PE earlier today, see if it works now. If it does, please share the updated TMPE.log as we need to track down which mod was causing the error.

Old log for reference:
```
Info 0.0006358: TM:PE enabled. Version 11.2.1, Build 11.2.1.1854 STABLE for game version 1.13.0-f7
Info 0.0028176: Enabled TM:PE has GUID 2941be02-a327-4537-8d80-cb5f2954cd39
Info 0.0075992: TrafficManager.Resources.incompatible_mods.txt contains 53 entries
Info 0.0092112: Loading global config from file 'TMPE_GlobalConfig.xml'...
Info 0.3070435: Global config loaded.
Info 0.3524741: Loading translations: TrafficManager.Resources.Translations.Menu.csv
Info 0.3546999: Loading translations: TrafficManager.Resources.Translations.Options.csv
Info 0.3571915: Loading translations: TrafficManager.Resources.Translations.JunctionRestrictions.csv
Info 0.3573962: Loading translations: TrafficManager.Resources.Translations.LaneRouting.csv
Info 0.3584789: Loading translations: TrafficManager.Resources.Translations.ModConflicts.csv
Info 0.3587853: Loading translations: TrafficManager.Resources.Translations.ParkingRestrictions.csv
Info 0.3589956: Loading translations: TrafficManager.Resources.Translations.PrioritySigns.csv
Info 0.3591753: Loading translations: TrafficManager.Resources.Translations.SpeedLimits.csv
Info 0.3595432: Loading translations: TrafficManager.Resources.Translations.TrafficLights.csv
Info 0.3605874: Loading translations: TrafficManager.Resources.Translations.VehicleRestrictions.csv
Info 0.3608242: Loading translations: TrafficManager.Resources.Translations.Tutorials.csv
Info 0.3632195: Loading translations: TrafficManager.Resources.Translations.Guide.csv
Info 0.3635245: Loading translations: TrafficManager.Resources.Translations.AI_Citizen.csv
Info 0.3637442: Loading translations: TrafficManager.Resources.Translations.AI_Car.csv
Info 0.3646065: Writing global config to file 'TMPE_GlobalConfig.xml'...
Info 0.3827528: TM:PE Incompatible Mod Checker (True,True):


Info 0.3828832: Scan complete: 0 incompatible mod(s) found
Info 0.3845377: Mono version: 2.0 (Visual Studio built mono)
```

**Comment by Apple329** [comment]
Updated TMPE, but unfortunately the picture has not changed:
Log files: https://ufile.io/l7up2gvm

**Comment by aubergine10** [comment]
can you upload your output_log.txt as well please

**Comment by Apple329** [comment]
https://ufile.io/hkkmuxtc

**Comment by aubergine10** [comment]
Mods are being loaded from offline vanilla folders: `H:\Games\Cities Skylines Sunset Harbor\Files\Mods`

Looks like a pirated copy of the game - what's the URL to  your Steam profile page?

**Comment by Apple329** [comment]
Some technical difficulties forced me to change the move the game
https://steamcommunity.com/profiles/76561198445969489

**Comment by krzychu124** [comment]
Yeah, right,,, And profile privacy settings you've changed also today because of technical difficulties??
Also you have local version of Mini FPS Booster (in local mods folder) which binaries are not available legally outside of steam workshop...
@aubergine10 it's waste of time. Closing
