### ISSUE TITLE
Timed Traffic Lights error in 11.3.0

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#826]
Multiple users on LABS page state that timed traffic lights are not working - the UI won't open for them, one-click lights not working, etc:

> Dwarfbare 4 hours ago   
> Hello together, is there a problem with the timed traffic lights? I can no longer open it.?

> rush05 4 hours ago   
> I'm also seeing issues with timed traffic lights using auto setup

> Supremax67 3 hours ago   
> Timed traffic lights broke, no way to set it manually

> ruiluth 3 hours ago   
> I can confirm timed lights not working. No way to remove them either except to remove the junction entirely. Is it safe to downgrade to the stable version?

> tslcomptech 3 hours ago   
> Yes I have to add that the TTL function got screwed up with this update I guess.. I can't change them OR delete them now...PLEASE FIX!! Thank you!!

**Comment by kvakvs** [comment]
Seems to be caused by the new tool handling code ignoring the TTL UI click. Hopefully a small fix.
