### ISSUE TITLE
1.13.0 lane connector does not highlight nodes correctly on-hover

### ISSUE THREAD

**Issue by Xyrhenix** [CitiesSkylinesMods/TMPE#830]
### Description

Using TM:PE LABS 1.13.0, nodes do not highlight properly on the lane connector.

### Reproduction steps

1. Open lane connector.
2. Hover over any node.

### Screenshots

![screenie](https://user-images.githubusercontent.com/39814064/79049229-43666780-7c1a-11ea-8dc8-7cf165089cfb.png)

In the above screenshot, I am actively hovering the cursor over the left node. The cursor cannot be seen due to screenshot method, however the cursor behaves as-expected. The node lines inside change colour, however the node marker does not. The right node appears normally. It does not change colour when I hover over it either.

**Comment by kvakvs** [comment]
I can confirm the problem exists.
As it is not game-breaking, I can address it when i work on Lane Connectors tool and UI.
