### ISSUE TITLE
Icons not showing up when selecting node after choosing TMPE.

### ISSUE THREAD

**Issue by xenoxaos** [CitiesSkylinesMods/TMPE#838]
### Steps to reproduce

1.  Select   tmpe, choose the option to change junction yields
2.  Icons don't show up. a
3. 

### Log files

https://gist.github.com/xenoxaos/f0435a8f4cc566c063b08086fc58b2bc

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2059435448

**Comment by kvakvs** [comment]
A logfile with exceptions!
Nice!
Thank you this helps to fix it.

**Comment by aubergine10** [comment]
This should hopefully be fixed in the upcoming 11.3.2 release - if the issue persists after that update, please let us know.

**Comment by xenoxaos** [comment]
haha @kvakvs I was wondering about that when I looked into it. It seemed to be kinda random. Sometimes it would do the thing where it didn't show anything, but then there were others where it would show and then crash the game. btw, that city that I made was complete shit and was just for the tough city achievement (and maybe filling 7 cemetaries) so don't judge me on it :P

**Comment by xenoxaos** [comment]
@aubergine10 will this be already fixed in the labs version of the mod. Looking at the PR to fix the issue I'm seeing .cs which means I'd need to compile it and I don't have a windows box set up for this kind of thing. :(

**Comment by aubergine10** [comment]
We'll be releasing update to LABS hopefully in next 24 hours.
