### ISSUE TITLE
Error: Array index is out of range.

### ISSUE THREAD

**Issue by Bobby8888** [CitiesSkylinesMods/TMPE#841]
I've seen this problem before on here but all of the solutions don't seem to work for me. Can someone check what is the problem in my game?

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4475298/output_log.txt)

**Comment by pcfantasy** [comment]
D:\Program Files (x86)\Cities Skylines Sunset Harbor\Cities.exe

where did you get this game?  seems not by steam?

**Comment by krzychu124** [comment]
It's not even updated: `Game Version: 1.13.0-f7-steam-win`
Any of known legal platform for me (steam/origin/whatever) don't use that name for game folder.
```
We will not provide support if:
- You are using a pirated or old version of Cities: Skylines
- You are using an older version of the mod
```
