### ISSUE TITLE
Sliders should update tooltip when dragged

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#857]
> Note: This will be fixed by #849 - this issue is just for clarity in tracking / changelog.

In mod options, sliders don't update their tooltip when dragged, making it difficult to know what current value is without first moving mouse away and then re-hovering.

**Comment by kianzarrin** [comment]
has #849 fixed all the sliders or only some of them?

**Comment by aubergine10** [comment]
They all use the same code IIRC, so it should fix all of them.

**Comment by kianzarrin** [comment]
No they don't use the same code. The code is repeated a million times! And there is one more slider that doesn't get updated. But I asked kvakvs to fix

In my mass edit options I designed my own ui class to avoid code repetition. I should use that class everywhere

**Comment by aubergine10** [comment]
@kvakvs  Could you update the remaining slider mentioned above - it might be worth making a small helper function for adding sliders to avoid duplicate code?

**Comment by kvakvs** [comment]
I would totally recommend having some generic option control builder which will do this automatically. For now I added a checklist item to #849 to update the remaining tooltips.
