### ISSUE TITLE
short-term undo for bulk edit tools.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#860]
see https://github.com/CitiesSkylinesMods/TMPE/issues/568#issuecomment-617970817
>> Can this wait until 11.6 release? That kind of stuff should be centralised, for example have a memo class that remembers state for anything that TM:PE can change regarding a node, segment or lane. And we should have central undo stack, maybe also see if we can integrate with the Undo mod somehow so that user has global undo facility?

> My intention is for user to be able to undo immediately afterwards. I do not intend to remember anything long term. so for example when user clicks CTRL+SHIFT+CLICK on a roundabout he can immediately switch back if he CTRL+SHIFT+CLICK again in a few seconds time.
My objective for now is as I said :" It won't be a proper undo feature but it is good enough for my road selection panel."
Yeah it can wait. I guess my work can be upgraded to central undo stack. or maybe we need a redesign if we want to go that route.

**Comment by kianzarrin** [comment]
I introduced IRecordabe interface with Record() and Restore(). I added several implementations of IRecordable for segments, nodes, segmentEnds, and lanes. All of this is wrapped by a big IRecordable.

Each Mass edit operation automatically creates a record of the instancIDs it touches.
to Undo, record.Restore() is called.

**Comment by aubergine10** [comment]
I assume there will be some structs/classes (for node, segment and lane) that can be used as a 'snapshot' (or 'restore point') for those things?

So before making changes, you take a snapshot of current state (eg. send the segment id to a constructor of a 'SegmentSnapshot' class - or whatever - and it grabs all relevant settings for the segment and stores them in its properties)? And then restore would just be running through a list of those objects calling their "Restore()" method or something like that?

If so that would be hugely useful to have for some of the stuff planned in 11.6 code cleanup.

**Comment by kianzarrin** [comment]
I found a bug in priority tool-> shift-click :
1- shift-click on another road to get yield signs.
2- move mouse to another road without going on grass
3- shift click on the other road and you shall get stop signs. One would expect that the state machine should restart.

**Comment by aubergine10** [comment]
Ah, I was typing my comment before you added your's. Sounds good! Ok, do it :)

We could potentially, at later date, use something similar for persistence in save game

**Comment by aubergine10** [comment]
Regarding bug (https://github.com/CitiesSkylinesMods/TMPE/issues/860#issuecomment-618106375) open new ticket for that pls.

**Comment by kianzarrin** [comment]
@aubergine10  my code is here if you want to take a pick but yeah I take snapshots.
> Regarding bug (#860 (comment)) open new issue for that pls.

I am going  to resolve it as part of this issue. I have to modify the code to add Undo anyway I might as well fix this too :)

**Comment by aubergine10** [comment]
The snapshots could later facilitate some sort of copy/paste features at later date. Maybe even provide an alternate way to persist data to savegame, etc.

> my code is here if you want to take a pick but yeah I take snapshots.

![trav](https://user-images.githubusercontent.com/1386719/80046222-e912b400-8501-11ea-8c6b-40ea11b73ce7.gif)
