### ISSUE TITLE
patch spawn/despawn vehicle using new harmony

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#864]
this code is commented out:
https://github.com/CitiesSkylinesMods/TMPE/blob/37b71da7e6f6793db1f2b579f14d96df02c7debf/TLM/TLM/Patch/_Vehicle/SpawnPatch.cs#L12
https://github.com/CitiesSkylinesMods/TMPE/blob/37b71da7e6f6793db1f2b579f14d96df02c7debf/TLM/TLM/Patch/_Vehicle/UnspawnPatch.cs#L12

Once I moved to harmony 2 should we uncomment this?

`VehicleStateManager` no longer exists but we can call `OnSpawnVehicle();` instead. that method is already being called from `CustomVehicle.CustomSpawn()` so maybe I should delete `Vehicle.Spawn/DespawnPatch`

**Comment by kianzarrin** [comment]
if CustomSpawn is copy of the original method then we we should replace CustomSpawn with  the harmony patch.

**Comment by kianzarrin** [comment]
its a bit hard to compare the code because of the differences in decompiler naming and spacing style.
does anyone know a solution?
![Screenshot (923)](https://user-images.githubusercontent.com/26344691/80288465-d934e300-8740-11ea-8d66-74c7abfe93ed.png)

**Comment by pcfantasy** [comment]
@kianzarrin 

No quick way.

I think we have to read carefully about these codes and find out the difference.

**Comment by kianzarrin** [comment]
But the original code was also copy pasted from decompiler why should it be so hard to compare decompiler code with decompiler code?

There is a shit ton of code out there so any automation we develop could be useful and reduce the risk of human error

**Comment by kianzarrin** [comment]
Maybe we can look at decompiler tmpe code using same decompiler. That should solve almost all problems.

**Comment by aubergine10** [comment]
Seems I spotted that some time ago: https://github.com/CitiesSkylinesMods/TMPE/issues/462

I think it would be very useful for TMPE to know when vehicles spawn/unspawn (no idea which is best approach for that).

For example, if we eventually start reserving parking spaces for vehicles, we will need to know if they despawn unexpectedly so we can un-reserve their parking space.

We could also maybe detect many vehicles despawning at same location = likely broken node bug (or at least we could stack trace to get some idea of the code path that led to despawning).

**Comment by kianzarrin** [comment]
@aubergine10 we already receive notification when vehicle spawn/despawns using redirection. I am saying we are now able to do it with harmony

**Comment by aubergine10** [comment]
Yup, it looks like we can do it harmony, but note there's two lines of custom code there:

![image](https://user-images.githubusercontent.com/1386719/80320462-6d20b080-880e-11ea-8f94-6a42f140c39f.png)

I assume we'd just patch the vanilla .spawn two do both?

![image](https://user-images.githubusercontent.com/1386719/80320480-875a8e80-880e-11ea-96fa-7c20b8c75e7e.png)

**Comment by kianzarrin** [comment]
@aubergine10 There is only one line of custom code (functionally speaking) the method is recursive so where the original code calls Spawn, the redirected method calls custom spawn. so its equivalent.

All we need to do is a  post fix (which is what I suspect from almost every custom AI)

**Comment by aubergine10** [comment]
I don't think we should keep the original tbh, as it will go stale if base game gets updated.

Hopefully if we're just doing postfixes on `.Spawn()` methods we'll never even need to look at that vanilla code again.

**Comment by kianzarrin** [comment]
then why do we keep `stockPathFind.cs` ? is it particularly important?
```
<AdditionalFiles Include="Custom\PathFinding\StockPathFind.cs" />
```

**Comment by aubergine10** [comment]
Re: `StockPathFind.cs`: We keep it so we can do diffs when new game version is released.

BTW, I looking at the code in screenshots above, note that there are two different call contexts:

- `CustomSpawn()` is called for vehicle _and_ each trailer (if applicable)
- `OnSpawnVehicle()` is called only once, regardless of how many trailers

So I think we need two postfixes? One for the vanilla `.Spawn()` and one for whatever the parent method is of the code in the screenshots above.

**Comment by kianzarrin** [comment]
@aubergine10 no. only one change (unless if I am making a mistake)

> CustomSpawn() is called for vehicle and each trailer (if applicable) - ie. it can be called more than once per invocation of parent method

Note that on the left there is an equivalent recursive call  for vehicle and each trailer (if applicable) - ie. it can be called more than once per invocation of parent method. So this line provides no new logic and does not need to be patched. Actually It would have made no difference if this line called `Spawn()` instead of `CustomSpawn()` considering Spawn is redirected to `CustomSpawn()`anyways.

**Comment by aubergine10** [comment]
Based on the current way the code works:

Let say vehicle has 2 trailers. That's **3 times** `CustomSpawn()` that will be called (once for front vehicle, then once for each trailer). After that "spawn loop" completes the `OnSpawnVehicle()` is called **once**.

So I don't see how we can replicate that with only one patch around the vanilla `.Spawn()` method, because that method won't know if trailers need adding.

Unless the plan is to call `OnSpawnVehicle()` multiple times, once for each 'part' of the vehicle, then we will need two postfixes.

The current way it works, `OnSpawnVehicle()` is only called _once_, after all parts of the vehicle (front + trailers, if applicable) have been spawned.

**Comment by aubergine10** [comment]
More clarity: If there is a truck with 2 trailers attached, TMPE will currently see:

```
CustomSpawn() // truck
CustomSpawn() // trailer 1
CustomSpawn() // trailer 2
OnSpawnVehicle() // only called after all parts of the vehicle are spawned
```

**Comment by kianzarrin** [comment]
> More clarity: If there is a truck with 2 trailers attached, TMPE will currently see:
CustomSpawn() // truck
CustomSpawn() // trailer 1
CustomSpawn() // trailer 2
OnSpawnVehicle() // only called after all parts of the vehicle are spawned

I think you are wrong. You are confused about how recursive calls work. in the custom code `OnSpawnVehicle` is being called multiple times. 

```C#
CustomSpawn() // truck
CustomSpawn() // trailer 1
OnSpawnVehicle() // trailer 1
CustomSpawn() // trailer 2
OnSpawnVehicle() // trailer 2
OnSpawnVehicle() // truck
```

**Comment by aubergine10** [comment]
Ah, the parent method is `CustomSpawn()`. Ok, that makes more sense.

Bah, there's actually two loops that contain recursive spawn. The more I look at the vanilla `Spawn()` method, the more crazy it becomes. Specifically, does it actually _need_ to be recursive given how the game actually works?

As far as I know, there's never anything that has side-vehicles or vertical trailers. Assuming it's always a start vehicle followed by zero or more trailers, it should be possible to just to create and configure those vehicles with a few simple iterations without going recursive and thus reduce call stack and gc.

**Comment by aubergine10** [comment]
Ok, so there are some wierd vehicle configs that require that extra code in the vanilla Spawn() methods.

So yeah, there's no need for TMPE to replicate those methods, just postfix the event. Earlier I didn't realise it was recursive method (snippets in images didn't show what the parent method was) hence confusion.

**Comment by aubergine10** [comment]
Considering #921 and #1969 are merged, I think this #864 can be closed?

**Comment by kianzarrin** [comment]
damn I fixed this ages ago!

**Comment by kianzarrin** [comment]
TMPE is not harmony only.
