### ISSUE TITLE
Use Harmony 2 instead of Redirection Framework

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#865]
by doing some quick comparison I suspect much of the custom AI code is a copy of the original code with some pre/post modifications. But we have not yet moved them to harmony because of harmony1 shortcomings. but now that we have harmony 2 we should remove the custom AI redirections. The advantages are:
1- if Cities skylines change their code we will have the most up-to-date code. I am concerned that some of that code is already too old and we have not noticed.
2- easier maintenance.
3- less likely to make mistakes.

EDIT: I am dividing this issue to 3 steps:
1- migrate CustomVehicle to harmony (#864 easy peasy!)
2- migrate CustomVehicleAI to harmony (clever prefixes would do the job)
    * patch `StartPathFind()` #895
    * patch other `CustomVehicleAI` methods 
3- move CustomPathFind to harmony (this issue). This is the hardest part and requires a badass transpiler.

**Comment by kianzarrin** [comment]
see #864

**Comment by kianzarrin** [comment]
its a bit difficult to compare the code because we have renamed compiler variables and we have our own spacing style. Does anyone has a solution?

**Comment by pcfantasy** [comment]
agree

**Comment by kianzarrin** [comment]
Based on my experience with node controller the most flexible way of using transpiler call insert is to do this:
```
load/calculate value
[INSERTED INSTRUCTION] value = MethodName(value,....);
use/store value
```

**Comment by aubergine10** [comment]
Looks like this was completed by #1089
