### ISSUE TITLE
Apply Shift+Click speed limit to entire roundabout

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#869]
> @thebugfixnet I figured out that the Speed-Limit function works within round-abouts in the same way they do on normal roads.
On normal roads with Shift-Klick the speed limit is assigned from one junction to the next. I can understand this as in real world also the speed limits at the next crossing may be different. So this behavior i was ecpexting.
But on roundabouts in my opinion there should be the logic to set the speed limit for the whole roundabout street with Shift-Klick. This is the way ot is in real i think. Additionally the super function of automated lower speed limits on roundabouts do it for the whole roundabout road. To be consistend to this function it would be good to handle it in the same way for the speed-limit function.
![image](https://user-images.githubusercontent.com/37211016/80286843-15ab1380-872e-11ea-85bf-0daee860336f.png)

So if it is a roundabout, I apply to all roundabout segments. Otherwise I apply between to junctions.

**Comment by aubergine10** [comment]
Yes, that would be nice to have.

**Comment by kianzarrin** [comment]
I wrote the code. 
![Screenshot (933)](https://user-images.githubusercontent.com/26344691/80393189-d0ffb380-88b8-11ea-9cbf-77cab682113b.png)
![Screenshot (932)](https://user-images.githubusercontent.com/26344691/80393200-d4933a80-88b8-11ea-8d0f-f19ce0614300.png)
ill do more testing.

**Comment by aubergine10** [comment]
Love it!!
