### ISSUE TITLE
Adding more recommended text editors to the TMPE wiki

### ISSUE THREAD

**Issue by Leo512bit** [CitiesSkylinesMods/TMPE#870]
### Describe your idea
I came across alot of good text editors that maintains plain text UTF-8 format.

These 2 are some that I 

Notepad++
and Jext  https://sourceforge.net/projects/jext/
https://web.archive.org/web/20100113234025/http://www.jext.org/

**Comment by aubergine10** [comment]
Hi, thanks for the suggestions. I've added Notepad++ and a few others.

Jext is obviously abandonware, so I've not added that.
