### ISSUE TITLE
Vacuum trucks ignore TM:PE vehicle restriction and suck the water outside the tunnel

### ISSUE THREAD

**Issue by Viklamvia** [CitiesSkylinesMods/TMPE#886]
### Describe the problem
I built a cross-river tunnel which is fully covered by soiled. Then vacuum trucks always get into the tunnel and suck the water OUTSIDE. (See pictures).Sometimes they even drive out of the road.
 So I tried to use Vehicle Restriction provided by TM: PE, but it works on vacuum trucks.(See pictures)

### Steps to reproduce

see above

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4598970/output_log.txt)

no error message occured

### Savegame?

https://ufile.io/whkfs29c

My Mods collection：https://steamcommunity.com/sharedfiles/filedetails/?id=1697022785

### Screenshots?

![suck the water in tunnel   ignore TMPE](https://user-images.githubusercontent.com/44251392/81406892-00da7100-916d-11ea-875e-0668a3e45198.jpg)
![ingore TMPE](https://user-images.githubusercontent.com/44251392/81406895-020b9e00-916d-11ea-95c1-7b890babc90e.jpg)

**Comment by kianzarrin** [comment]
@Viklamvia You could very easily just drag and drop the pictures in the issue.

I can see you have prohibited city services. what if you also ban trucks as well? 
![ingore-tmpe](https://user-images.githubusercontent.com/26344691/81403677-9c072280-913c-11ea-8eb2-4649af0a3c18.jpg)

I am not sure which color is which but you can tell from the colors what type of vehicle is a vacuum truck.
![suck-the-water-in-tunnel--ignore-tmpe](https://user-images.githubusercontent.com/26344691/81403725-b6410080-913c-11ea-992a-37e95f9e0106.jpg)

**Comment by Viklamvia** [comment]
The first car is vacuum truck. It was assigned into service vehicle by color so I just ban city service. And this road is built in industry area which is designed for trucks so I didnt ban truck but I will try.

**Comment by aubergine10** [comment]
It's possibly a bug in TM:PE; vacuum trucks (`WaterTruckAI`) should certainly be treated as city services, we'll have to check.

Note also, however, that vehicle restrictions aren't outright bansl; they are pathfinding penalties. The pathfinder will try to find "cheapest route" (ie. route with least penalties). The "Vehicle Restriction Agression" setting determines how harsh the penalties are.

**Comment by krzychu124** [comment]
TM:PE doesn't interfere with vacuum truck process or selecting location where they should go. They are also correctly treated as city service. If issue persist, let us know.
