### ISSUE TITLE
Medians

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#89]
Ah, medians.

Behold: https://steamcommunity.com/sharedfiles/filedetails/?id=1563428928
![52349428-71e92100-2a1e-11e9-9469-dc6c383fa2b0](https://user-images.githubusercontent.com/1386719/52900590-a5cb0000-31ef-11e9-9589-e9cfbd55d99a.gif)
Title: "Fuckery" (2019)

There are a plethora of median-related issues, I'll be using this thread to categorise them all.

**Comment by aubergine10** [comment]
### Routing across medians

As discovered in #39, bus routes sometimes cross medians. While it's likely the road above is a broken asset, this does merit further investigations.

Also, in #85, it was discovered that trucks can drive across medians on large roads.

And in #86, lagging vehicle repathing caused vehicles to drive over medians when a recently bulldozed road segment was replaced by an new road segment.

**Comment by aubergine10** [comment]
### ```NetInfo.m_CanCrossLane```

This property of roads, as far as I can tell, is supposed to determine whether vehicles can cross on-coming traffic.

I think it's something that needs further investigation in relation to medians, especially in relation to non-vehicle lanes, as LazarusMan (NeXT2/MOM dev) discusses here: https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/196

Also, [some road assets](https://steamcommunity.com/profiles/76561198157683281/myworkshopfiles/?appid=255710) have implemented solid medians at junctions but the pathfinder (even in vanilla game) ignores them and cars driver over them.

**Comment by andreharv** [comment]
Hey guys just to let you know things are running kinda slow but they are still running.  As I had mentioned on the Discord channel, I am working on a MOM update which will be updated soon (soon hopefully means less than a month).  After I get it out, I will be able to work on the NExt update which will finally port over the New Roads for Network Extensions mod that was abandoned and has/is causing a lot of issues for people right now.  After I get done with that, I am going to pick up another project I had put on the shelf for a year, outlined [HERE](https://community.simtropolis.com/forums/topic/68813-network-extensions-project/?do=findComment&comment=1689619).  I know that since then a lot of people have come up with roads that do this but this addon will allow for the medians to span between networks as well for most two way roads that are in the mod now.  I held off because I did not want to add these if the traffic would not honor the medians.  Now that the workshop is saturated with these median through node roads, I will have to find some way to incorporate their techniques. All that to say, I'm still on the case.

**Comment by andreharv** [comment]
Something else I have been playing with is the idea of an interactive way of determining how a median is drawn through an intersection.  This may be an addon feature that would require NExt and TM:PE as that is all that would use it for now...But just as you have the multi-colored draggable lane routing paths through nodes, with the supporting NExt roads, you could have a draggable median mapper.  It would function similarly to the lane routing mapper, except it would only have one circle in the middle of the network at the beginning of its node.  All supporting roads would have a circle.  Once you drag the line, the median will form in the junction and the pathfinding will change to reflect this.  If you click on the endpoint of the line, you can either reroute to a different road in the junction or cancel (which would remove the median).  Obviously this is a 1 to 1 dragging thing and perhaps the roads would need to be over a certain angle from one another for it to be possible.  Upgrading one of the median roads to another supported road would maintain the junction. Just some initial brainstorming.

**Comment by andreharv** [comment]
> Ah, medians.
> 
> Behold:
> ![52349428-71e92100-2a1e-11e9-9469-dc6c383fa2b0](https://user-images.githubusercontent.com/1386719/52900590-a5cb0000-31ef-11e9-9589-e9cfbd55d99a.gif)
> Title: "Fuckery" (2019)
> 
> There are a plethora of median-related issues, I'll be using this thread to categorise them all.

Can you give me the name of that road?  It looks like a good one to test on.

**Comment by aubergine10** [comment]
The best way I've seen to toggle medians is have them based on traffic lights at the junction. For example, median is there by default but if traffic lights are added it gets removed.

IMO we should go to CO and ask that base game be updated to handle junction-crossing medians better. Requiring users to use TMPE just to control lane changes on roads that use junction-crossing medians is somewhat overkill for many users.

**Comment by aubergine10** [comment]
I'm no longer able to reproduce the issue in OP (although my city is LHT and the image in OP was done on a RHT city).

![image](https://user-images.githubusercontent.com/1386719/145346434-1f0f5a05-54a1-484e-a36e-1b2bcc065f1f.png)

![image](https://user-images.githubusercontent.com/1386719/145347276-d8d96d2b-3cd0-4c0f-a0c6-88206f1e1301.png)

From left to right (on image above):

* Pedestrian (lane 0)
* Parking (lane 2)
* Vehicle (lane 6)
* Vehicle (lane 4)
* Transport (lane 12 - opposite dir to lanes 6 & 4)
* None (lane 8 - median - spans 9 & 10)
* Pedestrian (lane 9 - left side of median)
* Pedestrian (lane 10 - right side of median)
* Transport (lane 12 - opposite dir to lanes 5 & 7)
* Vehicle (lane 5)
* Vehicle (lane 7)
* Pedestrian (lane 1)

**Comment by Elesbaan70** [comment]
@aubergine10 I am trying to wrap my mind around the lane configuration that would make the original screenshot in this issue possible. Is it like this? F=forward, B=backward

BBFF BBFF

If so, then the displaced lanes project will resolve it with the newly added requirements on routing.

**Comment by aubergine10** [comment]
@Elesbaan70 see text under image in https://github.com/CitiesSkylinesMods/TMPE/issues/89#issuecomment-989562534

the asset is here: https://steamcommunity.com/sharedfiles/filedetails/?id=1563428928

I'd suggest using Network Detective to get more specific details. Also note the `None` lane spanning 2 pedestrian lanes in the middle. And yes, your displaced lanes project will almost certainly resolve that issue.

It might be worth collating related issue ids in your main issue so we can reference them in PR and subsequently the release notes / changelogs.

**Comment by aubergine10** [comment]
BTW, here's a list of some obscure roads that might be useful for testing: https://github.com/CitiesSkylinesMods/TMPE/wiki/Roads-to-Test

**Comment by Elesbaan70** [comment]
> the asset is here: https://steamcommunity.com/sharedfiles/filedetails/?id=1563428928

Whoa. That led me to look up Avenida 9 de Julio, and it turns out that is the ultimate test of #1392 and #1528, *together*. 🤯
