### ISSUE TITLE
migrate custom start path find to harmony.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#895]
This issue is to focus on VehicleAI.StartPathFind part of  #865 

EDIT: I shall search for but not fix poteintial bad/stale code in the CustomAI. for those we can create issue[s] to discuss them.

**Comment by kianzarrin** [comment]
I read the custom AI code:

A) All `*AI.StartPathFind()` call different overloads of `Pathfind.CreatePath()`
B) Only `*AI.StartPathFind()` calls different overloads of `Pathfind.CreatePath()`
C) All overloads of `Pathfind.CreatePath()` eventually call the biggest overload of `PathFind.CreatePath()`
D) Its all done in simulation thread.
Therefore each `*AIStartPathfFind()` needs a prefix to store necessary data. The `PathFind.CreatePath()` overload C should be replaced with `CustomPathManager.CustomCreatePath()` using harmony prefix.

For example the picture bellow show the diff bellow:
![image](https://user-images.githubusercontent.com/26344691/82322358-0c386280-99df-11ea-8c36-a627dd31e65c.png)
A: `ExtVehicleManager.Instance.OnStartPathFind` is called in prefix
B: args should be initialized in prefix.
C: call to `PathManager.CreatePath()` is replaced with `CustomPathManager.CustomCreatePath()`

The TMPE redirects do have comments highlighting the non-stack code but they are not highlighting all the changes.

**Comment by kianzarrin** [comment]
stable path for bus AI is changed to true in this commit https://github.com/CitiesSkylinesMods/TMPE/commit/cdb0fbe0b919757c6a0321bf85ad042b3425345e
but I do not understand why. Does anyone know what stable path is for?

> aubergine18Yesterday at 17:16
stable path seems to be don't randomize segments, I assume at junctions
so normal vehicles they'll occasionally take a random road at a junction, but that would be shit for busses - they'd be routing all over the place
hence stable path
i don't know why it's a parameter though, like, why not just check if vehicle is a bus and cache that somewhere
kian.zarrinYesterday at 20:56

from decompiler I can see:
```c#
this.m_ignoreCost = (this.m_stablePath || (this.m_pathUnits.m_buffer[(int)((UIntPtr)unit)].m_simulationFlags & 8) != 0);
// Does that mean with TMPE people are not discouraged by high bus ticket prices?
```
```c#
if (this.m_stablePath) b = 128;
else b = (byte)this.m_pathRandomizer.UInt32(1u, 254u);
this.ProcessItem(item, nodeID, num16, ref instance.m_segments.m_buffer[(int)num16], b, b, laneIndex4, lane6);
// this seems to be lane randomization
```
```c#
    if (!this.m_stablePath)
    {
        Randomizer randomizer = new Randomizer(this.m_pathFindIndex << 16 | (uint)item.m_position.m_segment);
        num8 *= (float)(randomizer.Int32(900, 1000 + (int)(instance.m_segments.m_buffer[(int)item.m_position.m_segment].m_trafficDensity * 10)) + this.m_pathRandomizer.Int32(20u)) * 0.001f;
    }
    float num11 = item.m_comparisonValue + num8 / (num4 * this.m_maxLength);
    if (!this.m_ignoreCost && ticketCost != 0)
    {
        num11 += (float)(ticketCost * this.m_pathRandomizer.Int32(2000u)) * 3.92156863E-07f;
    }
// so this one seems to be more general randomisation.
```
```c#
// don't know what this one does. there is not alternative for when `m_stablePath` is set to false.
if (lane3.m_laneType != NetInfo.LaneType.Pedestrian || item2.m_methodDistance < 1000f || this.m_stablePath){
    [...]
    item2.m_laneID = lane;
    item2.m_lanesUsed = (item.m_lanesUsed | lane3.m_laneType);
    this.AddBufferItem(item2, item.m_position);
}
```
I still do not understand why sable path is false in Vanilla game

**Comment by kianzarrin** [comment]
CarAi.StartPathfind changes lanetype 
```
NetInfo.LaneType.Vehicle -> NetInfo.LaneType.Vehicle | NetInfo.LaneType.TransportVehicle
```
Commit: 87730454e58138f767f32138271f18c2a9851e44
```diff
-				if (CustomPathManager._instance.CreatePath((ExtVehicleType)vehicleType, vehicleID, ExtCitizenInstance.ExtPathType.None, out path, ref Singleton<SimulationManager>.instance.m_randomizer, Singleton<SimulationManager>.instance.m_currentBuildIndex, startPosA, startPosB, endPosA, endPosB, NetInfo.LaneType.Vehicle, info.m_vehicleType, 20000f, this.IsHeavyVehicle(), this.IgnoreBlocked(vehicleID, ref vehicleData), false, (vehicleData.m_flags & Vehicle.Flags.Spawned) != 0)) {
+				PathCreationArgs args;
+				args.extPathType = ExtCitizenInstance.ExtPathType.None;
+				args.extVehicleType = vehicleType;
+				args.vehicleId = vehicleID;
+				args.buildIndex = Singleton<SimulationManager>.instance.m_currentBuildIndex;
+				args.startPosA = startPosA;
+				args.startPosB = startPosB;
+				args.endPosA = endPosA;
+				args.endPosB = endPosB;
+				args.vehiclePosition = default(PathUnit.Position);
+				args.laneTypes = NetInfo.LaneType.Vehicle | NetInfo.LaneType.TransportVehicle;
+				args.vehicleTypes = info.m_vehicleType;
+				args.maxLength = 20000f;
+				args.isHeavyVehicle = this.IsHeavyVehicle();
+				args.hasCombustionEngine = this.CombustionEngine();
+				args.ignoreBlocked = this.IgnoreBlocked(vehicleID, ref vehicleData);
+				args.ignoreFlooded = false;
+				args.randomParking = false;
+				args.stablePath = false;
+				args.skipQueue = (vehicleData.m_flags & Vehicle.Flags.Spawned) != 0;
+
+				if (CustomPathManager._instance.CreatePath(out path, ref Singleton<SimulationManager>.instance.m_randomizer, args))
```
Seems like an accident. Not sure.

**Comment by kianzarrin** [comment]
BusAI does not call `OnStartPathFind()` unlike other AIs. Is this intentional or a mistake?

**Comment by kianzarrin** [comment]
CargoTruckAI sets `args.extVehicleType = ExtVehicleType.CargoVehicle;`
why not `ExtVehicleType.CargoTruck` ?

**Comment by kianzarrin** [comment]
> @aubergine10 Not sure if it's related or relevant, but NetLane also has a ticket cost (maybe for toll lanes?)

seems like it:
![image](https://user-images.githubusercontent.com/26344691/84345757-de49d680-abb6-11ea-8789-87f9cd58e765.png)

**Comment by thebugfixnet** [comment]
Used a Vanilla save with 155k CIMs (growing)
Deleted Metro/Train-Lines, no Taxi
24 Buslines, a lot of busses, 150% budget

Price: 1$ with Ticket Price Customizer
2,810 CIMs a week / 188 Tourists a week after 4 weeks

Price: 10000$ with Ticket Price Customizer
2,851 CIMs a week / 201 Tourists a week after 4 weeks
+250k$ a week :smile:

3rd test:
added toll booths to the 10 most used  Bus routes with max. toll Price
2,859 CIMs a week / 197 Tourists a week after 4 weeks

**Comment by aubergine10** [comment]
Why on earth are cims ingoring ticket cost? That makes a whole bunch of [city/district policies](https://github.com/CitiesSkylinesMods/TMPE/wiki/City-and-District-Policies#transport-preferences) practically useless.

**Comment by thebugfixnet** [comment]
You View it from the CIMs View. but you have to View it as a City Planner: you loose Money with these Rules, Change the amount of private vehicles on the Road and Reduce the noise Pollution. You're Not making CIMs more clever....

**Comment by aubergine10** [comment]
Were any transport-affecting city policies set when you did your tests? Because if not, then the ticket price and, by extension, all policies relating to it, are entirely useless - literally no effect on transport prefs.

Increasing ticket price of a transport line should make it less desireable. But if a change as significant as $0.01 vs. $100.00 has zero effect on transport prefs, then it seems something is probably wrong.

Would be interesting to perform similar test on toll booths - obviously they don't affect public transport (which is correct and logical). However, for private traffic is there any difference between a cheap toll booth and an expensive toll booth. Would need A/B split testing approach on same road to remove any other factors such as distance, speeds, etc.

**Comment by thebugfixnet** [comment]
@aubergine10 No, no city policies set at all. No Mods that change game mechanics except TMPE and Ticket Price Customizer (only optical mods i had still active, all other unsubbed). It is a bare vanilla city.

I agree that it should be as you expect. But in my tests it did not...

Regarding to toll price:

I've tested today in my town and build one other roads as alternative to the road with a toll both... i just checked optical how much traffic was on the roads.... the shorter way got the toll booth... I make the toll free roads longer and longer step by step.... Even with beeing up to ~25% longer: there where a _few cars_ using this longer road than w/o toll booth. I've tested it with lowest toll and highest toll: I would say just a _minimal_ change in the amount of vehicles taking the longer but cheaper route. 

But it was not that at max. standard possible toll all cars where using the alternative route. Only if i just split the road and have nearly the same length (maybe) 80% took the cheaper way.

At toll booth it is working - but in my opinion not strong enough....

**Comment by kianzarrin** [comment]
> @victoriacity
He says that 8000 is to make it compatible with 81 tiles
4800 only works for 25 tiles
I guess he's not logged in to VPN for days
So he wasn't checking any non-Chinese social network

> @krzychu124 yep, that endPos looks like a bug. 

So the conclusion is all I need is a simple transpiler that changes 4800 to 8000 :)

**Comment by pcfantasy** [comment]
@kianzarrin 

I remember that there is a bug related to this 4800 but not sure now.

The bug is , if a industrial building(maybe outside 25tile I am not sure now) is under a air line, then there are no cargo trucks import to this building.

After change this to 8000, everything is fine.

**Comment by kianzarrin** [comment]
@pcfantasy thanks for the info 
Does that mean the 81 tiles mods do not work well without TMPE?

**Comment by pcfantasy** [comment]
> @pcfantasy thanks for the info
> Does that mean the 81 tiles mods do not work well without TMPE?

Yes, I think so.

**Comment by Sipke82** [comment]
> Why on earth are cims ingoring ticket cost? That makes a whole bunch of [city/district policies](https://github.com/CitiesSkylinesMods/TMPE/wiki/City-and-District-Policies#transport-preferences) practically useless.

I guess those policies just fiddle with the probability that the CIM uses Public transport =)

**Comment by aubergine10** [comment]
> but is it TMPE's job to make CS 81 tiles compatible?

Updates to 81 Tiles are extremely unlikely; BP is no longer active.

**Comment by DaEgi01** [comment]
Will it affect players who play with 25 tiles only?

**Comment by aubergine10** [comment]
Could it be made dependent on whether 81 Tiles mod is active?

**Comment by DaEgi01** [comment]
sure, would be a little slower due to method call instead of constant, but maybe worth it. no idea what that value actually affects though.

**Comment by aubergine10** [comment]
Looking at Kian's updated patch code, we only need to know whether 81 Tiles is present at time of transpiling (see `TLM/TLM/Patch/_VehicleAI/_CargoTruckAI/StartPathFindPatch.cs` in the linked PR #943). So it's one-time check per load.

**Comment by krzychu124** [comment]
`PostVanAI` has the same logic, should we change it there also?

**Comment by aubergine10** [comment]
I didn't see the transpiler in the current PR for `PostVanAI`...?

**Comment by krzychu124** [comment]
It's not cargo(small vans), `PostVanAI` derives from `CarAI`, not `CargoTruckAI`

**Comment by kianzarrin** [comment]
CustomShipAI is the only one that does not use skip queue. Is this an oversight?
![image](https://user-images.githubusercontent.com/26344691/84554230-a4481400-ad1f-11ea-8be9-c3c0d4576ae0.png)

**Comment by kianzarrin** [comment]
As for the 81 tiles max start/end pos:
- I guess the code would be slower because startPathFind is called for vehicles beyond 25 tiles.
- TMPE does not currently use max pos of 8000 for Post vans. That means it might not work with 81 tiles. I can easily apply the same transpiler to PostVanAI. I don't even need duplicate code for that I just call the same transpiler :)
- One option is to move the code to 81 tiles mod (or whatever else it is called) .

**Comment by kianzarrin** [comment]
@aubergine10  I am almost certain that this is a mistake https://github.com/CitiesSkylinesMods/TMPE/issues/895#issuecomment-641728942

apart from the fact that lane type all of a suddent was changed ... look at the decompiled vanilla code:

```C
if (PathManager.FindPathPosition( NetInfo.LaneType.Vehicle | NetInfo.LaneType.TransportVehicle, ...);

...
	
if (Singleton<PathManager>.instance.CreatePath(NetInfo.LaneType.Vehicle,  ...);
```

So it seems that the @Victor-Philipp  has confused the arguments passed to `FindPathPosition()` with `CreatePath()`

**Comment by kianzarrin** [comment]
@aubergine10 I an idiot! BusAI StablePath value DOES math the CS vanilla code! Nothing to worry about there!

**Comment by aubergine10** [comment]
The `maxPos` transpiler might be required for garbage service, particularly the garbage transfer trucks added in Subset Harbor which are designed for long-haul transfers.

**Comment by aubergine10** [comment]
@kianzarrin can this issue be closed (IIRC we have fully migrated to harmony now)?

**Comment by aubergine10** [comment]
Looks like this was completed by #1089
