### ISSUE TITLE
Change/expose Harmony ID

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#897]
see https://github.com/CitiesSkylinesMods/TMPE/pull/866#discussion_r427456974
Other mods can use Harmony ID to control priorities using `[HarmonyBefore()]` and `[HarmonyAfter()]` attributes see https://harmony.pardeike.net/articles/priorities.html

Attributes require compile time constants so we cannot evaluate the string runtime.

Argument could be made that the harmony string should be in TMPE.API although I believe tits better that other mods just copy paste the string. 

For the sake of backward compatibility the value of Harmony ID should not change.

The harmony ID currently is `de.viathinksoft.tmpe`.

Since according to this [github search](https://github.com/search?q=%22de.viathinksoft.tmpe%22&type=Code) the only mod that is using harmony id is my node controller.  it should not cause too much trouble to change this one last time. I can modify my code to include both IDs :) .
```
[HarmonyBefore("de.viathinksoft.tmpe")]
[HarmonyBefore("new harmony ID")]
...
```

But what should be the new Harmony ID value? we better give it a good thought so that we don't change it again!

harmony documentation says:
> `var harmony = HarmonyInstance.Create("com.company.project.product");`
The id should be in reverse domain notation and must be unique. In order to understand and react on existing patches of others, all patches in Harmony are bound to that id.

**Comment by krzychu124** [comment]
You can also use:
-  number `[HarmonyPriority(int)]` where `400` is normal
- `Priority` class

**Comment by aubergine10** [comment]
https://tmpe.me is our domain

**Comment by kianzarrin** [comment]
if we are following Harmony author recommendation it should be called:
"me.CitiesSkylinesMods.TMPE"

but i think its just simpler to call it "me.TMPE"
@aubergine10  do you agree?

**Comment by aubergine10** [comment]
If we're going for reverse domain, then `me.tmpe`.

**Comment by kianzarrin** [comment]
@kvakvs @krzychu124 Do you all agree with `me.tmpe` ?

**Comment by kvakvs** [comment]
@kianzarrin i am happy with that, we (me) own the domain and its not going to go anywhere from the project. Sure, use it. Can even use subdomains if you wish reuse that for more assemblies, like `me.tmpe.<something>`

**Comment by aubergine10** [comment]
did the id get updated? if so, pls link the PR and close

**Comment by krzychu124** [comment]
@kianzarrin when we could update it? 
Lookin at github search result I see that only you use this ID so I don't want to break your mods with this tiny change :)

**Comment by aubergine10** [comment]
We should also update https://github.com/CitiesSkylinesMods/TMPE/blob/master/docs/Mod%20Integration.md with details about the API, harmony id, and anything else useful to other modders that want to integrate with TM:PE

**Comment by kianzarrin** [comment]
> @krzychu124 : when we could update it? Lookin at github search result I see that only you use this ID so I don't want to break your mods with this tiny change :)

Good point. First we need a PR. Then I can fix my mods before the PR is merged (I can use both IDs to be compatible with both TMPE versions).

**Comment by aubergine10** [comment]
Is this something we can get in for 11.6.5.1 release or should it be pushed back to 11.6.5.2 or 11.7.0?

**Comment by krzychu124** [comment]
yeah, I'll send PR 😉
