### ISSUE TITLE
Simulation Error: Cannot cast from source type to destination type

### ISSUE THREAD

**Issue by techsupport1235** [CitiesSkylinesMods/TMPE#908]
### Describe the problem
Tried to load this save up today and it kept spitting out this error, I would rather not lose all this work.

This save is the only one not working it seems.

### Steps to reproduce

1. Attempt to Load the Save

### Log files

https://ufile.io/d28x2xqa - Output_log.txt

### Savegame?

Will add when steam's servers start working again.

I have disabled all my mods and all my assets, separately, and still, get this error, google leaves me at a loss on what to do.

Any help would be much appreciated

**Comment by krzychu124** [comment]
Why you even think it's **TM:PE** error?

Disabling mods will not solve your problem, because that save file needs specific mod(s) enabled but at a time you are trying to load that file, mod is disabled or unsubscribed, causing and error.

I suggest subscribing to [Mod Compatibility Checker](https://steamcommunity.com/sharedfiles/filedetails/?id=2034713132) and follow instruction in mod description, but first go to **Content Manager -> Saves**, find that save file and hit _Subscribe All_ and then _Enable All_ to make sure you subscribe all mods and assets that are necessary to load that savegame. Reopen game after subscribing and enabling mods to properly reinitialize mods and assets

**Comment by techsupport1235** [comment]
Evidently I was missing an asset, I subscribed to it and clicked enable all.
Whenever I restart Cities: Skylines, however, all mods are suddenly disabled.

**Comment by krzychu124** [comment]
Game config is probably corrupted, you need to enable all and restart again. It's hard to tell why it corrupts, but sometimes it does. Usually restarting game helps

**Comment by techsupport1235** [comment]
I've restarted, enabled, then restarted several times. All mods keep getting disabled.

I managed to get the mods to stay after clicking Enable All, still get the same error
Output log https://ufile.io/athj0tln

**Comment by krzychu124** [comment]
Subscribe to Mod Compatibility Checker, link above.

Do you have 81 tiles mod enabled when you are trying to load savegame?

**Comment by techsupport1235** [comment]
Okay
Yes I do.

**Comment by krzychu124** [comment]
Also unsubscribe `FineRoadAnarchy` and `FineRoadTool` since you have newer version subscribed

**Comment by techsupport1235** [comment]
Output of the mod compatibility checker
https://ufile.io/0nbwjjun

**Comment by aubergine10** [comment]
> "Proper Hardness Mod - KHFork"

The Proper Hardness mod is incompatible with vast numbers of other mods. Assuming it's similar to the one in the workshop, these are its compatibility vectors:

```cs
{ 2090425593uL, Status.Incompatible }, // Game Speed mod
{ 2039606384uL, Status.Incompatible }, // Easy Mode: Money Mod
{ 2039486691uL, Status.Incompatible }, // 1133108993 Extended Building Information (1
{ 2039205403uL, Status.Incompatible }, // Free Maintenance by Anvilarse
{ 2025147082uL, Status.Incompatible }, // Realistic Population revisited
{ 2016920607uL, Status.Incompatible }, // RICO revisited
{ 1875298330uL, Status.Incompatible }, // Extended Building Info (live627)
{ 1830455071uL, Status.Incompatible }, // EasyMode
{ 1776052533uL, Status.Incompatible }, // Stops & Stations
{ 1766839841uL, Status.Incompatible }, // Anxiety Reducer
{ 1749971558uL, Status.Incompatible }, // Real Time Offline
{ 1744522363uL, Status.Incompatible }, // Money Back (Refund)
{ 1614061108uL, Status.Incompatible }, // Real Construction
{ 1598546349uL, Status.Incompatible }, // Mary's Mod
{ 1587482024uL, Status.Incompatible }, // 真实人口，低密度只有一户人，高密度人口容量变大
{ 1556715327uL, Status.Incompatible }, // Show It!
{ 1551563197uL, Status.Incompatible }, // EnhancedBuildingCapacity - Fixed
{ 1522785644uL, Status.Incompatible }, // Infinite Demand Mod
{ 1420955187uL, Status.Incompatible }, // Real Time
{ 1393820309uL, Status.Incompatible }, // Ticket Price Customizer
{ 1227735337uL, Status.Incompatible }, // Full Refund Cost[Industries Compatible]
{ 1204126182uL, Status.Incompatible }, // Ploppable Rico High Density Fix
{ 1133108993uL, Status.Incompatible }, // Extended Building Information (1.10+)
{ 1108715012uL, Status.Incompatible }, // Adjustable Business Consumption
{ 938049744uL , Status.Incompatible }, // Proper Hardness Fixed
{ 931330091uL , Status.Incompatible }, // 410344523 PopBalanceMod
{ 928988785uL , Status.Incompatible }, // Extended Building Information (billw)
{ 838095079uL , Status.Incompatible }, // Cheaper Hydro Electric Power
{ 819155459uL , Status.Incompatible }, // 超级需求 (super RCI demand)
{ 767788339uL , Status.Incompatible }, // More Demands Configurable
{ 670422128uL , Status.Incompatible }, // Extended Building Information (Hedgehog)
{ 586012417uL , Status.Incompatible }, // Ploppable RICO
{ 426163185uL , Status.Incompatible }, // Realistic Population and Consumption Mod v8.4.0
{ 414469593uL , Status.Incompatible }, // Extended Building Information (emf)
{ 411190402uL , Status.Incompatible }, // Building Simulation Overhaul
{ 410344523uL , Status.Incompatible }, // PopBalanceMod
{ 408706691uL , Status.Incompatible }, // Proper Hardness
```

You have two versions of Advanced Vehicle Options (AVO) subscribed; unsubscribe the old one.

I've had some reports that "Mods Listing" mod is broken since Sunset Harbor update (not had time to test myself yet). Might be worth removing it.

**Comment by techsupport1235** [comment]
I'll remove it.
I think it is just safe to say that this save died, my fault for not routinely saving.

**Comment by krzychu124** [comment]
Closing (external issue, links to log are dead).
