### ISSUE TITLE
Cars driving off of road

### ISSUE THREAD

**Issue by theobjectivesea** [CitiesSkylinesMods/TMPE#913]
### Describe the problem
Cars take shortest path possible, driving off of the road to the road they want to go to

### Steps to reproduce
Happens in any game, nothing needs to be reproduced

1. 
2. 
3. 

### Log files

https://ufile.io/f/1yohc

**Comment by krzychu124** [comment]
Please subscribe to [Mod Compatibility Checker](https://steamcommunity.com/sharedfiles/filedetails/?id=2034713132) and follow mod description. 
I counted at least 5 ancient and broken mods. All of them may impact on game path finder causing issues you've described.

**Comment by krzychu124** [comment]
Since there was no response, I assume that problem was solved. I'm closing the issue. Let us know if problem persist.
