### ISSUE TITLE
Speed limits: Allow lanes/roads to be clicked (not just icons)

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#925]
Currently, when changing speed limits, I have to click the icons to apply the change to a road/lane.

Would be great if I could just click the road side (direction mode) or lane (lanewise mode).

**Comment by Xyrhenix** [comment]
Agreeing with this, as it can make it much easier to set speed limits in a hurry. Perhaps this same feature could be applied to the lane connector in some form?

Example: You've selected a node, but rather than having to click the tiny dot you just have to click the lane that the dot is on.

**Comment by aubergine10** [comment]
Lane connector already has that feature ;)

**Comment by aubergine10** [comment]
Closing this as it's tracked in #1221
