### ISSUE TITLE
Speed limit panel and screen resolution over FullHD

### ISSUE THREAD

**Issue by MacSergey** [CitiesSkylinesMods/TMPE#935]
If screen resolution over FullHD - 2K or 4K, Unable to move speed limit panel beyond FHD resolution

Example 2K: cant move it further to the right or down
![image](https://user-images.githubusercontent.com/20316130/84397913-ed0ca980-ac07-11ea-86cb-3b16599a3f5c.png)

**Comment by aubergine10** [comment]
Confirmed - but duplicate of #573
