### ISSUE TITLE
on a segment to segment transition only the smaller segment needs crossings.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#936]
Problem:
CS has too many redundant crossings and they are ugly. 
![image](https://user-images.githubusercontent.com/26344691/84408707-24358780-ac15-11ea-9e29-6973a74b3f8d.png)

Solution:
A policy to auto-disable crossings on the ~~smaller~~ bigger segment.(or highway segment)
![image](https://user-images.githubusercontent.com/26344691/84409014-89897880-ac15-11ea-8d37-8bb2d4cb45d8.png)

This also would be useful at the ground to elevated/tunnel connections.

**Comment by aubergine10** [comment]
> A policy to auto-disable crossings on the smaller segment.

I assume you mean the bigger segment? (smaller crossing = safer than bigger crossing)

**Comment by kianzarrin** [comment]
![image](https://user-images.githubusercontent.com/26344691/92520143-d0dad180-f223-11ea-83a5-e0cc798ca6be.png)
