### ISSUE TITLE
Locale additions - `ro` and `oc`

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#946]
`ro` Romainian - discord user MarkTrefi123 wants to translate

`oc` Occitan - steam user Perry7484 wants to translate

**Comment by krzychu124** [comment]
Schema updated on `Crowdin`, some translations needs approval and support for new language by the mod also needed

**Comment by aubergine10** [comment]
Awesome, thanks! I'll keep this issue open until new langauges are ready.
