### ISSUE TITLE
Vanilla bug: Intecity busses don't work on two-way outside connections

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#960]
> I think this was initially reported in discord by @MacSergey

If an outside highway connection is two-way, intercity busses don't use it.

In some unrelated work on lane connector rendering, @krzychu124 discovered that vanilla game adds an extra vehicle lane on one-way highway outside connections.

![image](https://user-images.githubusercontent.com/1386719/85475359-e12cca00-b5ad-11ea-8865-9e4de776f688.png)

Here you see intercity bus entering the map via the hard-shoulder:

![image](https://user-images.githubusercontent.com/1386719/85475432-fdc90200-b5ad-11ea-9116-1f1b975a0c25.png)

So this is a bug in vanilla, in that it does not add the extra lane to two-way highways, which in turn breaks intercity buses.

I'm not sure how to fix this, it's not really task for TMPE but could possibly be a small external mod that does it if someone has time?

**Comment by krzychu124** [comment]
_Out of scope_

**Comment by aubergine10** [comment]
Wiki article added: https://github.com/CitiesSkylinesMods/TMPE/wiki/Intercity-buses-not-working
