### ISSUE TITLE
Transport paths break when upgrading roads

### ISSUE THREAD

**Issue by Keyof13** [CitiesSkylinesMods/TMPE#975]
Upgrading roads breaks public transport paths, causing 'Cannot find path' error. Tried with both Network Extensions 2 on and off, the bug happens both times. This save game has NE2 on.

Savegame: https://steamcommunity.com/sharedfiles/filedetails/?id=2161234891

**Comment by krzychu124** [comment]
Hi, have you tried [Broken Nodes Detector](https://steamcommunity.com/sharedfiles/filedetails/?id=1777173984)?

**Comment by krzychu124** [comment]
Just tested your savegame. You have two invalid nodes (green and blue).

![image](https://user-images.githubusercontent.com/19638970/87364783-d2b24c80-c574-11ea-9442-18a5e6d13037.png)

![image](https://user-images.githubusercontent.com/19638970/87365266-15285900-c576-11ea-903f-3b6c1f4baf5e.png)

Move them with Move It to rebuild from scratch
If you are curious what is going on read **Broken Nodes Detector** description and #277

**Comment by Keyof13** [comment]
I think it worked. Thank you for your help!!!
    On Tuesday, July 14, 2020, 08:03:49 AM GMT+8, Krzysztof <notifications@github.com> wrote:  
 
 


Just tested your savegame. You have two invalid nodes (green and blue).





Move them with Move It to rebuild from scratch
If you are curious what is going on read Broken Nodes Detector description and #277

**Comment by Keyof13** [comment]
I think it worked. Thank you for your help!!!
