### ISSUE TITLE
1.13.1

### ISSUE THREAD

**Issue by ReflexShow** [CitiesSkylinesMods/TMPE#977]
Hello there (:
I have a little question please, recently i updated my game in accident to 1.13.1
and i saw your mod not complitble with it, so i wanted to ask how can i downgrade the game
or ask when you gonna update it? 
Thanks (:

**Comment by krzychu124** [comment]
You probably use ancient version of TrafficManager (v10.20). 
Close game, unsubscribe it and subscribe to [TM:PE v11 Stable](https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252) or [TMPE v11 Labs](https://steamcommunity.com/sharedfiles/filedetails/?id=1806963141)
