### ISSUE TITLE
Speed Limit interface km/h to MPH unit conversion is wrong

### ISSUE THREAD

**Issue by Glenwing** [CitiesSkylinesMods/TMPE#988]
The speed limit conversions to MPH are incorrect. For example the speed limit interface gives:

- 120 km/h = 77 MPH (should be 75)
- 130 km/h = 83 MPH (should be 81)
- 140 km/h = 90 MPH (should be 87)

and so forth.

I believe the problem is in [Constants.cs](https://github.com/CitiesSkylinesMods/TMPE/blob/master/TLM/TLM/Constants.cs) Line 27:
`public const float SPEED_TO_MPH = 32.06f; // 50 km/h converted to mph`
50 km/h is **31.06** mph, not 32.06 (actually would be 31.07 if rounding; the exact conversion is 31.06856).

https://www.google.com/search?q=50+km%2Fh+to+mph

**Comment by kvakvs** [comment]
I will include this constant change into the new speed limits UI merge request.

**Comment by aubergine10** [comment]
oops, lol, didn't notice your commit
