### ISSUE TITLE
Lane connector not working properly anymore.

### ISSUE THREAD

**Issue by DaEgi01** [CitiesSkylinesMods/TMPE#99]
![lane connector not respected anymore](https://user-images.githubusercontent.com/11689162/53131927-752bf300-356e-11e9-8cc8-a1e151fc4fc5.png)
this is the intersection. the cars do not respect the lane connector anymore.
customizations come into effect immediately is on.
still i waited quite a while to check if the issue still appears.

**Comment by krzychu124** [comment]
Could you upload that save? I would like to check if this particular intersection has some invalid data or it other problem

**Comment by DaEgi01** [comment]
you were right, this intersection or something else seems seriously broken. i demolished it and rebuild every segment .. and now cars don't even want to use it at all xD
gonna send you the save after some more testing.

**Comment by DaEgi01** [comment]
ok forget it ... were some broken segments or something ... rebuild an even larger part and now it works fine. sry for the hastle.

**Comment by krzychu124** [comment]
No problem, I suspect some sort of desynchronization between vanilla segments collection and our used for pathfinding. 

Would be nice to figure out what could cause that issue. 
I've noticed that type of desynchronization in one of my test saves but in my case there was a problem with switching enter at blocked junction restriction option. 
I couldn't disable it at one  particular junction. I fixed that with removing that node completely. 
We are not syncronizing nodes currently so there might be the problem sometimes.

**Comment by DaEgi01** [comment]
happened again.
here is the save: https://steamcommunity.com/sharedfiles/filedetails/?id=1662300561
the affected intersection is marked red
![tmpe_laneconnector_brokenintersection](https://user-images.githubusercontent.com/11689162/53168106-2fa50f80-35da-11e9-833e-35d4d22942dd.jpg)

**Comment by krzychu124** [comment]
Thanks, I can't check it out now but I will do it today for sure.
Check out if you don't have any mods which could override updateSegment or finalizeSegment methods, iIrc

**Comment by krzychu124** [comment]
I can't load your save 😕 I'm getting null pointer exception in simulation. Looks like missing prefabs...
```
Simulation error: Object reference not set to an instance of an object
  at RoadBaseAI.CanEnableTrafficLights (UInt16 nodeID, .NetNode& data) [0x00000] in <filename unknown>:0 
```

**Comment by DaEgi01** [comment]
send you a friend request via steam ... not sure if its you .. but its a krzychu124 from poland ;D

**Comment by krzychu124** [comment]
Nope 😉 That's my second account. I don't use it. Try krzychu1245 😄

**Comment by aubergine10** [comment]
@krzychu124 You can try the [**Safenets**](https://steamcommunity.com/sharedfiles/filedetails/?id=1620588636) mod to get rid of that `RoadBaseAI` error.

**Comment by krzychu124** [comment]
@aubergine10 thx, 
IIRC I finally managed to load that save but I couldn't reproduce that issue 😕

**Comment by aubergine10** [comment]
Will the recently improved segment validation (and handling if not) stuff solve this? (ie. can this issue be closed?)
