### ISSUE TITLE
Layout Algorithm partially failing in MainMenu panel

### ISSUE THREAD

**Issue by kvakvs** [CitiesSkylinesMods/TMPE#992]
### Main Menu sometimes shows with all buttons far apart

The possible reason is there is an error happening while running the layout logic in the MainMenu panel, and the placement logic works, while the autosize logic doesn't work due to that unknown exception.

Investigate possible cause, which part of layout code was not run (fit children in button panel?).

### Steps to reproduce

Hard to reproduce, but it happened on Biffa's stream https://www.youtube.com/watch?v=N15U3ZsZjoI 
soon after he had a savegame error at 25:14

![bild](https://user-images.githubusercontent.com/288724/90156091-5d60b400-dd8c-11ea-80aa-ca18c19afb00.png)

Advanced Vehicle AI was enabled prior to that at 23:22 (possibly unrelated?) and then a floating RV was found from there a flying pedestrian went across the motorway to the other side at 24:35 (possibly related to Advanced AI?)

### Screenshots?

28:53
![bild](https://user-images.githubusercontent.com/288724/90156387-aadd2100-dd8c-11ea-81c5-39ebfe84623f.png)

29:33 in white map mode
![bild](https://user-images.githubusercontent.com/288724/90156455-c21c0e80-dd8c-11ea-9ec2-7b178c0a4921.png)

**Comment by aubergine10** [comment]
Does this still happen? Maybe it was due to issue with that UI Scaling mod?

**Comment by kvakvs** [comment]
I did not observe it for some time neither in my games nor on C:S streams.
It happened due to a possible exception in the layout code.

**Comment by krzychu124** [comment]
Yup, currently there are no exceptions, everything works. In the past when you left TMPE menu open and enter into free camera mode then on exit the game usually thrown an exception to the log (probably because of incorrectly removed panel so it failed to update).

**Comment by aubergine10** [comment]
ok, closing

**Comment by kvakvs** [comment]
Still here in 11.6.1 TEST, in this Biffa's recent stream https://youtu.be/mNDGvAUMgG4?t=157
There's an exception to catch, that's not caught, and interrupts the layout

**Comment by aubergine10** [comment]
can we get log file from Biffa?

**Comment by kvakvs** [comment]
![bild](https://user-images.githubusercontent.com/288724/146111770-c5ba2783-c3f2-4d0a-959e-53a6a07a2746.png)
Some camera addon, probably cinematic camera. Can get it and try reproduce myself, or maybe you already have it.

**Comment by aubergine10** [comment]
I'm currently using [First Person Camera: Updated](https://steamcommunity.com/sharedfiles/filedetails/?id=650805785) and haven't noticed any issues. I also have [Camera Positions Utility](https://steamcommunity.com/sharedfiles/filedetails/?id=898480258) and haven't had any issues with that.

I was previously using [First Person Auto Walking](https://steamcommunity.com/sharedfiles/filedetails/?id=659877005) and have vague recollections of encountering the problem with that but that was like 1+ year ago.

I found 2 cinematic camera mods (never used either): [Cinematic Camera](https://steamcommunity.com/sharedfiles/filedetails/?id=409073879) looks like old one, and newer one: [Cinematic Camera: Extended](https://steamcommunity.com/sharedfiles/filedetails/?id=785528371). There's a few other camera mods in workshop such as [Totally Free Camera](https://steamcommunity.com/sharedfiles/filedetails/?id=602077938) and [Smooth Camera](https://steamcommunity.com/sharedfiles/filedetails/?id=2519929628) which I've also never used.

**Comment by kvakvs** [comment]
Tried Cinematic Camera: Extended. No crash, but if i opened speed limit window at least once, it keeps reappearing when i exit cinematic camera.

**Comment by krzychu124** [comment]
> Still here in 11.6.1 TEST, in this Biffa's recent stream https://youtu.be/mNDGvAUMgG4?t=157 There's an exception to catch, that's not caught, and interrupts the layout

Also, bear in mind that workshop 11.6.1 he use is way older than current `master` (it's pre speed limit UI merge).
I didn't update it because of bug that is in-progress #1233 and since setting up default speed limits is way easier to access would be good to release fully working version instead of bugged (issues are too easy to reproduce/spot) 😉

**Comment by krzychu124** [comment]
@kvakvs between 11.5.1 to 11.6.6.3 we've fixed few memory leaks, probably the issues is no longer reproducible with the latest version. Also no new reports about this in the past few months. Close it?

**Comment by kvakvs** [comment]
Seen it pop for a fraction of a second on Biffa's stream somewhere May-June.
Can close for now
