### ISSUE TITLE
Timed Traffic Light Enhancement - Vehicle Tripped Traffic Lights

### ISSUE THREAD

**Issue by LemonsterOG** [CitiesSkylinesMods/TMPE#995]
### Describe your idea
As an example, let's use a T intersection (3-way). On the main road, leave the traffic light green (with minimum time allowed and maximum not needed) unless a vehicle "trips the sensor" on the side road. Then change the main road lights to red and the side road to green based on specified time limits (like you can with the existing feature). Then switch back to green lights for the main road and red for the side road, until it's tripped again.

### Screenshots?
Not necessary.

**Comment by krzychu124** [comment]
I think you can already achieve similar thing in TTL settings, just need to play with settings a bit 🙃

**Comment by LemonsterOG** [comment]
It doesn't as far as I can tell, because you have to set a maximum time for the "main" road lights. I guess I could just set the max to 999.

**Comment by LemonsterOG** [comment]
Oh...by using the after minimum time options. I always use them, but never played around with them for this purpose. I'll do so now. Thanks for replying.

**Comment by krzychu124** [comment]
I think we will reopen that issue when we start refactoring TTL code. ♾️ option would be nice addition.

**Comment by LemonsterOG** [comment]
Then I'm glad I mentioned it. :-)
